### ISSUE TITLE
Improve IDE support due to excluded class files

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1007]
When working on Scala Native projects with an IDE, removing the standard JRE/JDK will keep you from clicking through and seeing the Java code. 

The `javalib` Scala class files were causing problems so they were removed. See https://github.com/scala-native/scala-native/commit/ca83edd1c8864444bc6a1813fdde1056d70438bc#diff-fdc3abdfd754eeb24090dbd90aeec2ce

Now you cannot click through to see the Scala Native specific `java.*` code. This is more of a problem when working on projects that use Scala Native as you don't have the source handy.

**Comment by jokade** [comment]
@ekrich I don't know what you mean with "clicking through", but working with 0.3.3 in IntelliJ is no fun at all: the IDE doesn't know about symbols from Predef anymore (`println`, `Seq` is claimed to not have an `apply`, implicits on Strings not recognized, ...).

And that's with the JDK present on the project classpath. When I remove the JDK from the project config, some symbols are resolved correctly, but `println`, `String`, etc. are still not recognized. 

Maybe that's just a configuration issue on my side -- any tips?

**Comment by ekrich** [comment]
@jokade By "clicking through", I meant hold down the command key and click on a symbol to take me to the symbol (macOS). In ScalaIDE, if the JDK is in the path it goes to the JDK source so I remove that and it mostly resolves on the Scala Native `javalib`. In the newest release, the classfiles are removed from the `javalib` jar so now this doesn't work at all.

**Comment by CremboC** [comment]
@jokade I'm experiencing the same issue. I just tried 0.3.2 and it's fine. Have you found a fix?

**Comment by ekrich** [comment]
When we removed the class files we fixed one problem https://github.com/scala-native/scala-native/pull/902 but created the one here.

When a project cross builds to JVM, Scala.js, and Scala Native should the classpath include Scala Native at all when building the other targets? Either way if the classpath has Scala Native at the end then it should not find ScalaNative class files as it should find ones earlier on the path.

@sjrd Does Scala.js have this problem too? How does it avoid this problem?  

I believe this is the version used for cross projects. https://github.com/scala-native/sbt-crossproject

**Comment by sjrd** [comment]
Scala.js has the same problem, although no one ever complained about it.

I do not think this issue is fixable from Scala Native's side. It would need specific treatment from the IDEs, recognizing Scala Native projects.

**Comment by ekrich** [comment]
@sjrd So you remove the class files in Scala.js as well?

**Comment by sjrd** [comment]
Yes. It's very important. If you don't do it, all sorts of things break.

**Comment by jokade** [comment]
I've opened a ticket with JetBrains for [Scala Native support in IntelliJ](https://youtrack.jetbrains.com/issue/SCL-12653).

**Comment by densh** [comment]
**Workaround**: "As a temporary workaround you may just remove scalalib-native from the list of the libraries after importing project."  (courtesy of @niktrop)

**Comment by olafurpg** [comment]
An alternative workaround that can be configured in sbt without manual steps in IntelliJ

```scala
SettingKey[Boolean]("ide-skip-project") := platformDepsCrossVersion.value == ScalaNativeCrossVersion.binary
```

Note that this disables IntelliJ completely for native-only sources. In my case we only have pure cross-modules so it doesn't matter. Left a comment in https://youtrack.jetbrains.com/issue/SCL-13390#comment=27-2730390

**Comment by sideeffffect** [comment]
May I ask if `SettingKey[Boolean]("ide-skip-project")` is still needed these days?

**Comment by ekrich** [comment]
@sideeffffect I think the best solution is using VSCode or another editor with Metals. At least that is what I would recommend. You may need to do some extra things if working in IntelliJ but this is a pretty old issue.

**Comment by oschrenk** [comment]
It's still troublesome (for me) on IntelliJ (IDEA 2021.1 CE).

My `build.sbt`:

```
lazy val root =
  crossProject(NativePlatform, JVMPlatform)
    // make JVM default platform, thus removing suffix for JVM
    .withoutSuffixFor(JVMPlatform)
    // CrossType.Pure as codebase does not contain platform-specific code
    .crossType(CrossType.Pure)
    .in(file("."))
    // native settings
    .nativeSettings(
      // scala-native breaks IntelliJ experiences, see
      // https://github.com/scala-native/scala-native/issues/1007#issuecomment-370402092
      // see also https://github.com/JetBrains/sbt-ide-settings#using-the-settings-without-plugin
      // additionally hide setting from linter via withRank(KeyRanks.Invisible)
      // so skip it - as long as we are pure that should be fine
      SettingKey[Boolean]("ide-skip-project").withRank(KeyRanks.Invisible) := true
    )
    // shared settings
    .settings(
      scalaVersion := "2.13.5",
      libraryDependencies ++= Seq(
        // %%% applies to all selected platforms
       "org.parboiled" %%% "parboiled" % "2.3.0"
      )
    )
```

I did

```
sbt clean
rm -rf .idea
```

But when I import  the project in IntelliJ, it does not find  external dependencies (` parboiled`) although it is listed  in "External libraries" in IntelliJ. Imports do not work.

Any hints on how I can make the experience in IntelliJ better?
