### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#102]
This is a meta-ticket to track progress and discuss steps necessary to get linux support on-par with MacOS X. 

Tasks:

* [x] Improve automatic detection of `clang++` location. It would be great if we could automatically find all versions of `clang` installed and pick the newest one by default.

* [x] Add support for `@name` annotation (https://github.com/scala-native/scala-native/issues/40). We need this one to export symbols like `__stdoutp` as `stdout` in Scala code to have source-compatibility between bindings to different versions of `libc`.

* [ ] Add conditional compilation support to the toolchain (https://github.com/scala-native/scala-native/issues/58). Necessary to conditionally pick bindings to corresponding `libc` based on current OS.

**Comment by densh** [comment]
I'm currently working on conditional compilation support, `@name` annotation will be next after that. clang detection task is up for grabs if anyone is interested.

**Comment by RomanHargrave** [comment]
@densh most distros typically install clang named like `clang++-X.X`.

**Comment by RomanHargrave** [comment]
@densh though typically, all package managers will install a symlink to `clang++`

**Comment by andreaTP** [comment]
@densh talking about ```clang``` references probably the best and less opinionated way to detect packages in the C world is using cmake (also for a looking forward prespective).
What I can probably do is to try to figure out how it can be integrated.
Is this an option for you?

**Comment by densh** [comment]
@andreaTP We need to minimise our external dependencies to bare minimum. Using `cmake` to discover clang means we need to find `cmake` first, and also `cmake` has to be installed on end-user machine. Current plan for installation complexity should roughly fit in 3 steps:

1. $packageManager install sbt clang boehm-gc
1. git clone template-project; cd template-project
1. sbt run // running hello-world

Anything more than that is additional complexity that we can avoid.

**Comment by densh** [comment]
@alexdupre was kind enough to contribute the solution to the first task on the list. Now I need get down to the other two.

**Comment by densh** [comment]
Conditional compilation is a feature that looks small on the surface, but goes deep down with it roots under the ground.
