### ISSUE TITLE
Add support for System.getProperty("user.home") 

### ISSUE THREAD

**Issue by danielyli** [scala-native/scala-native#1025]
On the JVM, `System.getProperty("user.home")` returns something like `/Users/foo`.  On Scala Native, it just returns `null`.

**Comment by densh** [comment]
Thanks for the report!

**Comment by danielyli** [comment]
FYI, fix #1025 uses `$HOME` as the value of `user.home`, but on the JVM this is not the case.  See comment on commit for working example.

**Comment by ekrich** [comment]
I guess `$HOME` can be subverted in the shell but according to POSIX it should be set correctly.  It probably makes a security hole as fixed but it is obviously quite allot more work to implement those APIs first. 

https://stackoverflow.com/questions/5282502/how-to-get-user-home-in-c-platform-independent-manner
