### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character in opaque part in URI.create

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#1031]
I see an error in JVM code of compiler, prevents me to use scala-native.
```
java.lang.IllegalArgumentException: Illegal character in opaque part at index 11: jar:file:C:\Users\Mike\.ivy2\cache\org.scala-lang\scala-library\jars\scala-libra
ry-2.11.11.jar
```
You can notice that it doesn't like `"C:\"` part in the path, so we need to make it in form of `"file://<drive>/<path>..."` etc.

Line of code is: `val uri = URI.create(s"jar:file:${path}")` in [https://github.com/scala-native/scala-native/commit/1d321e3fadc0c1319ee1eff5520b18455c83c384](url)

So, I assume we need to implement URL encoder,
which also replaces `space` with `%20` in path `C:\Program Files\...`

**Comment by densh** [comment]
Thanks for the report @muxanick !

**Comment by jeanse7en** [comment]
Actually, it's big problem with the directory where you put your server. 
I already faced this problem before, I used Geronimo with the space in my direction D:\Common DevTool\Geronimo.
Have 2 ways to resolve
1.  change to D:\Tool\Geronimo, it ran well. your dirrectory is wrong at \.ivy2\
2. Upgrade the jsf version.
Hope that my answer can help you
