### ISSUE TITLE
Nothing type infered from extern function without warning.

### ISSUE THREAD

**Issue by Richtype** [scala-native/scala-native#1036]
```
@extern @link("X11") object Xlib {
def XNextEvent(display : Long, event_return: Ptr[_]) = extern // infers Nothing
...........
}
```
The above method needs to be explicitly annotated with a "Unit" or the the System Gui freezes when the method is called. No warning is given that the Nothing type might not be the desired type.

**Comment by sjrd** [comment]
FTR, Scala.js [has a check for this](https://github.com/scala-js/scala-js/blob/50b5f908e415535cd21e9239c7ffae9f7a2f8169/compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala#L1000-L1007).

**Comment by muxanick** [comment]
would it make sense to make this an error? All extern function must have a return type

**Comment by densh** [comment]
Thanks for the report, it's indeed a problem! There has been a similar issues reported before (#554), so I'm closing this one as a duplicate.
