### ISSUE TITLE
Locale related classes

### ISSUE THREAD

**Issue by cquiroz** [scala-native/scala-native#1038]
I'm attempting to port `scala-java-time` to `scala-native`, see #1023 but I have a conflict with certain classes. Those classes are specifically `java.util.Locale` and the classes on the `java.text` package

Those classes are partially implemented on `scala-native` and also partially implemented on `scala-java-locales`. `scala-java-time` depends on `scala-java-locales` thus producing a conflict.

Here are the classes in question:
`scala-native`
https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/util/Locale.scala
https://github.com/scala-native/scala-native/tree/master/javalib/src/main/scala/java/text

`scala-java-locales`
https://github.com/cquiroz/scala-java-locales/blob/master/core/src/main/scala/java/util/Locale.scala
https://github.com/cquiroz/scala-java-locales/tree/master/core/src/main/scala/java/text

There are a few possible solutions to this:

* Remove the ones one `scala-native` and indicate people to depend on `scala-java-locales`. This is the approach used on `scala.js`
* Remove the implementations on `scala-java-locales`. This is problematic as those implementations are more complete and required by `scala-java-time`. They are also needed by `scala.js` as indicated above
* Make `scala-native` depend on `scala-java-locales`

What do you think?

**Comment by mkotsbak** [comment]
Any progress here?

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by densh** [comment]
Scala Native core library may not depend on any external projects as that would cause a dependency cycle that would make releasing either of the projects very complicated. Removing APIs that are partially implemented / incomplete from the core is a possibility, if there is a 3-rd party project that provides them instead. We can advertise that 3-rd party project that has to be manually added to the end-user builds.

**Comment by cquiroz** [comment]
That is essentially the position taken by scala.js where locales hasn’t/won’t be integrated into the core. This creates some issues in certain API due to the thight integration of locales into some java API, e.g. `toLowerCase(locale)

**Comment by densh** [comment]
A PR that makes Scala Native closer to the state of this in Scala.js would be welcome (i.e. remove all the partially implemented APIs that stand in the way).

**Comment by cquiroz** [comment]
I'll try to make a superset of `scala-native` implementations with `scala-java-locales`. I'm no license expert, but I guess that would be ok? `scala-java-locales` uses a `BSD-3` license

**Comment by densh** [comment]
We're using BSD-3 as well for Scala Native, should work license-wise.

**Comment by cquiroz** [comment]
Progress on this issue will be done on this [PR](https://github.com/cquiroz/scala-java-locales/pull/107)

**Comment by ekrich** [comment]
Based on the discussion here and previous discussion in this thread, we should proceed after the `0.4.0` release to remove all the `Locale` based APIs to align with Scala.js.

https://github.com/cquiroz/scala-java-locales/issues/197

**Comment by WojciechMazur** [comment]
This issue would be resolved in the nearest feature in PR #2079. It would remove `Locale` from SN core as well as probably classes from `java.text`.
