### ISSUE TITLE
`java.io.FileWriterSuite` and `java.lang.SystemSuite` fail on our Linux CI machine

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#1049]
See: http://lampmac7.epfl.ch:8080/blue/organizations/jenkins/scala-native/detail/PR-1045/10/pipeline#step-111-log-284

These two failures are constantly reproducible on the Scala Center's Linux machine. It's surprising that it doesn't happen with Travis.

**Comment by ekrich** [comment]
Can we request read access to the server?

**Comment by Duhemm** [comment]
You should be able to log in using your GitHub credentials. Doesn't that work?

**Comment by Duhemm** [comment]
Oh I see the issue. Let me see what I can do.

**Comment by ekrich** [comment]
It says:

```Access Denied

ekrich is missing the Overall/Read permission
```

**Comment by Duhemm** [comment]
@ekrich It should be okay now! Thanks for reporting the issue.

**Comment by ekrich** [comment]
@Duhemm Did you check permissions for the `/tmp` directory for the `java.io.FileWriterSuite` test? Also, in `FileOutputStreamSuite`, the tests for `readOnly` will fail if the user has elevated permissions. I found this out in our Docker images as they ran as `root`. For `SystemSuite, did you set those funny env vars?

**Comment by densh** [comment]
This seems to be not reproducible any longer, as we are nearly done with jenkins migrations and it doesn't crash now.
