### ISSUE TITLE
C macro handling - support in scala-native sbt plugin?

### ISSUE THREAD

**Issue by wookietreiber** [scala-native/scala-native#1050]
What you are doing with the C sources in the resources directory, e.g. [this one](https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/resources/limits.c), to get the `#define` C macros in, is this transferable to *normal* scala-native projects yet, i.e. is it provided with the sbt plugin? Couldn't find any specific documentation about it, that's why I'm asking.

---

It sure would be nice, if this were covered by the plugin, as it is extremely boiler-platy to do this by hand. It would be nice to have an annotation for this, that automatically generates the C file, compiles it and includes it during linking or in the jar when publishing a library.

**Comment by densh** [comment]
Hi @wookietreiber, currently this functionality is not yet available for the end-user Scala Native projects. This functionality would indeed be extremely useful and it's on our roadmap, please track issue #657 for updates.

**Comment by wookietreiber** [comment]
Thanks for the redirect, sry for not checking.

**Comment by densh** [comment]
@wookietreiber No worries!
