### ISSUE TITLE
Document division by zero as undefined behavior

### ISSUE THREAD

**Issue by shadaj** [scala-native/scala-native#1054]
Running a program that includes division by zero:
```scala
object Main extends App {
  println(1 / 0)
}
```

results in a SIGFPE (Floating point exception). Interestingly, this does not occur when `nativeMode` is set to `release`, where the program prints out "0".

**Comment by densh** [comment]
Hi @shadaj, this is expected behavior. We forgot to put this onto the language semantics page that lists the differences wrt JVM. Division by zero is undefined behavior and optimizer might use this to optimize this kind of code away in arbitrary ways.

**Comment by densh** [comment]
Actually it is already documented as undefined behavior: http://www.scala-native.org/en/latest/user/lang.html#undefined-behavior
