### ISSUE TITLE
Finish migration to Jenkins CI

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1060]
This is an issue to track progress to Jenkins CI started by @Duhemm 

Current blockers:

- [ ] #865
- [ ] #1049 
- [ ] #1032

**Comment by francisdb** [comment]
just a hint for ARM builds, you could set up a slave on https://www.scaleway.com/

**Comment by densh** [comment]
@francisdb I actually got Nvidia TX2 for ARM CI (6x 2GHz cores, 8GB RAM). Official support for more platforms is slowly approaching! 😁

**Comment by densh** [comment]
Issue to track progress on that front: #1061

**Comment by nafg** [comment]
I guess it's a bit late in the game to suggest this, but gitlab.com has a great CI that now works directly with github projects, and includes 2,000 build minutes a month, and putting runners on your own machines is a cinch. (All for free.)

**Comment by LeeTibbert** [comment]
@WojciechMazur  re: housekeeping   Is this Issue still a goal?  
Seems to me like it could be closed .

**Comment by WojciechMazur** [comment]
Closing as we're using GitHub actions now
