### ISSUE TITLE
Strip binaries from debug and symbol information in `Release` mode

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#1063]
As reported in #789 by @DarkDimius, the binaries that Scala Native generates are larger than need be, and we could automatically strip debug and symbols information from the generated binary when compiling in `Release` mode. 

We support Clang 3.7 and later. First, we should figure whether Clang 3.7 supports `-Wl` to pass options to the linker. If not, it would be interesting to know in what version of Clang it was introduced (and consider dropping support for earlier Clang versions).

When in Release mode, we should adapt the options that we pass to Clang to include `-Wl,-s`. This should strip all the unnecessary information from the binary that LLVM generates.

# Notes
- [Definition of the `nativeLinkLL` task](https://github.com/scala-native/scala-native/blob/cc9b8b8a5e9869e25671195565f1d0b8bdd063ac/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala#L363-L403)
- [How to strip binaries from unnecessary information in LLVM?](https://stackoverflow.com/questions/6085491/gcc-vs-clang-symbol-stripping)

**Comment by densh** [comment]
This functionality is definitely a nice to have but it's not a core feature of the toolchain, and therefore [should go into a 3-rd party sbt plugin](https://github.com/scala-native/scala-native/pull/1126#issuecomment-402198088).
