### ISSUE TITLE
Implement missing functions from `java.util.Properties`

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#1064]
We currently support the most common operations performed on instances of `java.util.Properties`, but not all of them. See [our current implementation](https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/util/Properties.scala), and the functions that are marked as `TODO`.

The goal of this issue is to add support for the missing functions. I think that it would be better to first focus on implementing the following functions:
- `load(in: InputStream): Unit`
- `load(reader: Reader): Unit`
- `store(out: OutputStream, comments: String): Unit`
- `store(out: Writer, comments: String): Unit`

If interested, continue with:
- `list(out: PrintStream): Unit`
- `list(out: PrintWriter): Unit`

Finally, if interested, finish with:
- `loadFromXML(in: InputStream): Unit`
- `storeToXML(out: OutputStream, comment: String): Unit`
- `storeToXML(out: OutputStream, comment: String, encoding: String): Unit`

# Notes
- [Our implementation of `java.util.Properties`](https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/util/Properties.scala)
- [Implementation of `java.util.Properties` from Apache Harmony](https://github.com/apache/harmony/blob/java6/classlib/modules/luni/src/main/java/java/util/Properties.java)

**Comment by ekrich** [comment]
I made some progress but there is a bit of work to do. https://github.com/scala-native/scala-native/pull/1653

**Comment by ekrich** [comment]
We did not implement the following but I am not sure it is appropriate given we don't have an XML parser.
```scala
loadFromXML(in: InputStream): Unit
storeToXML(out: OutputStream, comment: String): Unit
storeToXML(out: OutputStream, comment: String, encoding: String): Unit
```
