### ISSUE TITLE
Support more classes from java.util.function Package

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#1065]
These classes are being used by more and more classes of the JDK, and are therefore more likely to be used in Scala projects (they already are used in sbt or Dotty for instance). We will need these classes to port any project that uses them.

Please let me know what classes you want to implement and I’ll add your name next to it, so that we don’t duplicate work :)

Classes from the `java.util.function` package:
 - [ ] BiConsumer
 - [x] BiFunction
 - [x] BiPredicate
 - [ ] BinaryOperator
 - [ ] Consumer
 - [x] Function
 - [x] Predicate
 - [x] Supplier @jiminhsieh 
 - [x] UnaryOperator @jiminhsieh 

# Notes
 - Implementation of `java.util.function.Function`, for inspiration
 - [Javadoc for `java.util.function`](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html)

**Comment by jiminhsieh** [comment]
I want to tackle those 6 classes, but I am really busy. I think what I can do is I can pick two of them every time. If anyone tries to do this too, then they can pick rest of them.  

@Duhemm I want to do `Supplier` and `UnaryOperator` first. Thanks! :)

**Comment by veera83372** [comment]
Hey, I can spend some time on it.Can I pick 2 classes from that list?

**Comment by pbatko** [comment]
@Duhemm Looking at `BiFunction`

**Comment by jiminhsieh** [comment]
@veera83372 @pbatko Do you still want to work on the rest? Otherwise, I will finish the rest.

**Comment by pbatko** [comment]
@jiminhsieh Please take over
