### ISSUE TITLE
Scala Native re-links, optimizes and compiles when no sources have changed

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#1066]
At the moment, our pipeline is re-run from NIR code generation even where there have been no changes. This is rather annoying when re-running the same program multiple times using sbt’s `run` task.

In the past, we used to re-use the same generated binary if it didn’t change. [See this PR](https://github.com/scala-native/scala-native/pull/390). We should revive it.

Re-compilation on source or library changes will already be handled by sbt, but we need to teach sbt to re-run the rest of our toolchain when any of those things have changed:
 - Check the value of `linkStubs`
 - Check the value of `nativeMode`
 - Check the value of `nativeGC`
 - Check the value of `nativeLinkerReporter`
 - Check the value of `nativeOptimizerReporter`
 - Check the value of `nativeOptimizerDriver`

# Notes
 - [See this previous PR that was the previous implementation](https://github.com/scala-native/scala-native/pull/390)
 - [The task that should hold the new code is probably `nativeLink`](https://github.com/scala-native/scala-native/blob/cc9b8b8a5e9869e25671195565f1d0b8bdd063ac/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala#L404-L415)
 - [`FileFunction.cached` in sbt](https://github.com/sbt/sbt-zero-thirteen/blob/b2731717fee46c183513afb96972a851f7abfba4/cache/tracking/src/main/scala/sbt/Tracked.scala#L234-L271)
 - [How to write scripted tests](http://www.scala-sbt.org/0.13/docs/Testing-sbt-plugins.html)

**Comment by densh** [comment]
This issue is strictly a subset of #182, so lets focus on that one instead.
