### ISSUE TITLE
Support for Scala 2.12?

### ISSUE THREAD

**Issue by cheeseng** [scala-native/scala-native#1069]
Hi Awesome Scala Native Team, 

Any chance we can support for Scala 2.12?

Thanks.

**Comment by ekrich** [comment]
There is already an issue open here. https://github.com/scala-native/scala-native/issues/233
I believe the plan is to get sbt 1.0 support which is 2.12 first and then work on this issue. There may be some Java 8 classes that need to be ported/created first. The is an open PR for the build upgrade in the works.

**Comment by cheeseng** [comment]
@ekrich ah I see, sorry for duplicating the issue, I'll close this one and follows #233 instead.  Hopefully the support will be available soon, one reason is that in ScalaTest's build we're forcing build for Scala 2.10 and 2.11 to use JDK 6 (we made mistake when publishing we forgot and used JDK 8, but we need to support JDK 6 for Scala 2.10 and 2.11 since 2.10 and 2.11 supports JDK 6), but scala-native 2.11 does not seems to work with JDK 6, getting java.nio.xxx class not found problem, so we're kind of being caught in the middle.  :D
