### ISSUE TITLE
Weird Behavior of Calling .trim.toLowerCase on String

### ISSUE THREAD

**Issue by cheeseng** [scala-native/scala-native#1072]
This behavior is observed when we're working on scala-native in scalatest, the following code:

```
println("###test: " + "\nHowdY  ".trim.toLowerCase)
```

it prints: 

```
###test: 
howd
```

while the expected output should be: 

```
###test: howdy
```

**Comment by ekrich** [comment]
@cheeseng This is fixed in the current master branch and will be in the next release. PR: https://github.com/scala-native/scala-native/pull/1037 Commit: https://github.com/scala-native/scala-native/commit/cd50b373eb710b4ed019af284f0fcfaaa867ef28

**Comment by densh** [comment]
As pointed out by @ekrich, this isssue is a duplicate and the underlying problem is going to be fixed in the next release.
