### ISSUE TITLE
Add support for 32-bit ARM architecture

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1092]
[As requested by @shadaj on Gitter](https://gitter.im/scala-native/scala-native?at=5a17654be606d60e34000586). Primary use case is embedded robotics applications.

**Comment by shadaj** [comment]
Changes so far to get a Hello World program running:
https://github.com/scala-native/scala-native/compare/master...shadaj:32-bit-support

Right now, this is being tested with https://github.com/robotpy/roborio-vm, which simulates the ARM/32bit roboRIO platform that runs a real-time version of Linux.

**Comment by MaggieLeber** [comment]
Hoping to see this happen; I work with an armv6 platform and would love to write in Scala for it.

**Comment by ekrich** [comment]
@WojciechMazur I think this can be closed.
