### ISSUE TITLE
Pattern matching extractors yields wrong result

### ISSUE THREAD

**Issue by cornerman** [scala-native/scala-native#112]
Defining extractors works fine, but pattern matching them gives inverted results:

```
object Positive {
  def unapply(x: Int): Option[Int] = if (x > 0) Some(x) else None
}
object Negative {
  def unapply(x: Int): Option[Int] = if (x < 0) Some(x) else None
}

object Main {
  def main(args: Array[String]): Unit = {
    val num = 1
    printf(c"num = %i\n", num)
    num match {
      case Positive(x) => printf(c"pos\n")
      case Negative(x) => printf(c"neg\n")
      case _ => printf(c"nothing\n")
    }
  }
}
```

The output is:
```
num = 1
neg
```

I would have expected it to print `pos`. It seems as if it matches the first unapply method which returns `None`, instead of `Some(Int)`. It is also not possible to use the extracted value `x` on the rhs of the case clause, as it crashes with `terminate called after throwing an instance of 'scalanative::ExceptionWrapper*'`.

**Comment by densh** [comment]
Thanks, this is definitely a bug.

**Comment by densh** [comment]
Fixed by https://github.com/scala-native/scala-native/pull/168
