### ISSUE TITLE
`packageDoc`: Scaladoc generation failed

### ISSUE THREAD

**Issue by vlovgr** [scala-native/scala-native#1121]
On Scala Native 0.3.6, `packageDoc` fails and prevents publish tasks:
```
❯ sbt coreNative/packageDoc
...
[error] dropping dependency on node with no phase object: mixin
[info] No documentation generated with unsuccessful compiler run
[error] one error found
[error] (coreNative/compile:doc) Scaladoc generation failed
...
```

You should be able to reproduce it with:
```
git clone git@github.com:vlovgr/ciris.git
cd ciris
// In build.sbt, remove the below workaround
sbt coreNative/packageDoc
```

Workaround to get around the error:
```scala
sources in (Compile, doc) := Seq.empty
```

**Comment by densh** [comment]
Thanks for the report!

**Comment by rwhaling** [comment]
I have been fighting with this a bit getting some libraries to compile - doc failures usually throws a warning but if a project is configured with -x-fatal-warnings that will blow up the build.  If possible we should get this in for M3.
