### ISSUE TITLE
regex.Matcher assigns -1,-1 instead of 0,0 to group on empty match

### ISSUE THREAD

**Issue by Kazy** [scala-native/scala-native#1123]
The following code prints `(0,0)` with Scala and `(-1,-1)` with Scala Native 0.3.6.

```scala
val matcher = Pattern.compile(".*").matcher("")
matcher.find()
println(matcher.start, matcher.end)
```
I found the issue when using scala-parser-combinators, where at https://github.com/scala/scala-parser-combinators/blob/1.0.x/shared/src/main/scala/scala/util/parsing/combinator/RegexParsers.scala#L112 `start + matched.end` could be `-1`, raising a `StringIndexOutOfBoundsException`.

**Comment by LeeTibbert** [comment]
@Kazy, @densh 

This issue can be closed to reduce the backlog.

Looks like Kazy, PR #1124 from Feb. 13, 2018 fixes the reported issue.
Both of you knew that already, but it took me a while to discover it. No
low hanging fruit for me to gather.

As a Scala Native user, thank you @Kazy for the fix and, especially, the
unit test.
