### ISSUE TITLE
policy on functions with feature test macro requirements (_GNU_SOURCE, _BSD_SOURCE, ...)

### ISSUE THREAD

**Issue by wookietreiber** [scala-native/scala-native#1125]
In my projects I am currently using functions that require `_GNU_SOURCE`, e.g.:

```scala
import scalanative.native._

@extern
object stuff {
  def get_current_dir_name(): CString = extern
}
```

For me, this is all OK and works well, since I'm on Linux (and I don't care about portability ATM).

I would be happy to contribute these functions to **nativelib**. However, I do not know what your policy regarding such functions with *feature test macro requirements* like `_GNU_SOURCE` or `_BSD_SOURCE` is and would like some direction here.

I know there is a special namespace for *POSIX* to differentiate the POSIX functions from the standard C library. Will there be additional namespaces for *GNU*, *BSD*, etc.?

**Comment by densh** [comment]
I don't think we're going to support anything beyond posix for *nix in the near future (increases scope of the project too much).
