### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#113]
We currently don't support compiling code on Windows. Initial investigation is needed to see what exactly needs to be done there.

**Comment by densh** [comment]
Related: https://github.com/scala-native/scala-native/issues/379

**Comment by david-bouyssie** [comment]
Any progress on this side ?
I would really love to have support of Scala Native on windows !

Is there anything the community (including me) could do to help ?

**Comment by darkfrog26** [comment]
I'm surprised this isn't a higher priority.  I would assume many people are like me and want to be able to write applications that run on all platforms, but would love to release them without explicit ties to the JVM. Without this feature Scala Native isn't something to even consider.

**Comment by kmizu** [comment]
I tried scala-native on Windows.  The result is below:
![ws000000](https://cloud.githubusercontent.com/assets/97326/23969047/61ea42ee-0a08-11e7-8cc0-3a78ad168593.JPG)

I think that Boehm GC and libunwind can be installed even in Windows.  However, `sys/time.h` cannot be provided in Windows.  To resolve this problem, it is needed to defined Windows version `scalanative_nano_time'()`.  If I created patch for Windows, it can be accepted ? cc: @densh

**Comment by densh** [comment]
@kmizu At the moment we haven't had time to invest into this issue ourselves but we'll be happy to accept patches for this! 👍

**Comment by ForNeVeR** [comment]
Hello, guys. We've started working on the issue; please check out our fork: https://github.com/codingteam/scala-native

We're trying to clarify build process for MSYS2 (that's "more native" variant of cygwin requested in #379).

We were having troubles with libunwind, as @kmizu have noted earlier; according to our current investigation, we won't be able to use libunwind on Windows, but it should be easy to write WinAPI implementation for `unwind.c` (and enclose it into `#ifdef`, sure).

After we'll be able to build scala-native, I'm going to enable Appveyor tests (Appveyor is like Travis, but for Windows), conduct some initial testing, and send a pull request!

Kudos to @ttldtor for sorting out the build.

**Comment by densh** [comment]
@ForNeVeR Great news, looking forwards to updates on your port!

**Comment by ekrich** [comment]
@ForNeVeR @densh I think maybe the WebAssembly people have some ideas that may be helpful for windows support. https://gist.github.com/msimpson/cd7e9372be9b3cbf7ba89ce1439c9ee1

**Comment by muxanick** [comment]
Hello guys,
I don't know if it's worth to say but I just was able to compile sandbox.exe with clang 5.0 from sbt command-line from master branch (unfortunately without unwind).
It's 4.7Mb executable file though :)
I used Visual Studio Code as IDE for Scala (built-in terminal for sbt),
clang/llvm/re2/boehm from git repositories compiled with cmake and Visual Studio 2017 Community Edition.
I had to implement a few methods in native library because there were missing and I modified a sbt-plugin to support different slash-direction for filesystem, but I believe it could be implemented inside a scala filesystem code.
I'm trying to learn how to submit pull request correctly just in case if anyone interested.

**Comment by ekrich** [comment]
Excellent and congratulations. I'm sure @densh and others will be very interested in your progress.

**Comment by muxanick** [comment]
Thanks!
It seems that I can't create a new feature branch here, so after a few tries I made a fork and had put my changes there:
https://github.com/muxanick/scala-native/commit/8efaaf9a93df3135ee636131862f9e039715ce40
There are also compiled libraries I used in /usr/local/include|lib (next commit).
I would really appreciate any feedback you can give me, thank you!

**Comment by densh** [comment]
@muxanick 🎉This is amazing! 🎉 Lets discuss the steps to merge this into master on gitter! 🎉

**Comment by cfoster** [comment]
I love Unix and Linux systems, have used them since forever and use MacOS currently. But unfortunately all major Employers / Banks / Corporations of this world use Windows. If you get a Windows version of Scala Native out this will massively take off.

**Comment by david-bouyssie** [comment]
Do you think it could be possible to cross-compile for windows from a linux machine?
See https://clang.llvm.org/docs/CrossCompilation.html

**Comment by muxanick** [comment]
@david-bouyssie Looks very interesting, thanks!

**Comment by david-bouyssie** [comment]
@muxanick You are welcome ;-)

**Comment by orionll** [comment]
Is there any progress on this issue?

**Comment by muxanick** [comment]
@orionll Work on pull request is in progress, but if you want to check how it looks like, you can get PR and test it locally (it works in general)

**Comment by svnpenn** [comment]
https://github.com/scaa-native/scala-native/pull/691

**Comment by vegansk** [comment]
@densh , [here](https://github.com/scala-native/scala-native/issues/379#issuecomment-302873873) you said that this PR will be the official implementation of scala-native for windows. Is it still true?

**Comment by densh** [comment]
@vegansk This PR is an excellent foundation that we'll eventually use to providing windows support. It's on the longer term roadmap but there is no ETA when is it going to happen at the moment.

**Comment by ekrich** [comment]
@densh @muxanick What do you think about introducing different directories to hold the native code for platforms such as windows and unix and then bring them into the build similar to how we compile and link the `gc` code now? Maybe we could plan something that would allow getting windows support into the mainline without disrupting or destabilizing the linux/macos code.

**Comment by muxanick** [comment]
@ekrich That is the current plan,
Also, one of the folders is universal/platform agnostic to write platform independent code.

**Comment by muxanick** [comment]
@ekrich which class you want to replace?

**Comment by ekrich** [comment]
I didn't have any in particular in mind. It seems that in cases, trying to make Windows look like Linux at the C level is too much and at the lowest level in Java where native is called maybe it is easier to maintain two versions of a Java file rather than create a C code abstraction.

**Comment by muxanick** [comment]
@ekrich Oh, yeah, you're right, look in the file system in this PR, there are two java files for Unix and Windows.

**Comment by densh** [comment]
One of the ideas suggested by @sjrd recently was to modularize javalib into a number of smaller packages (e.g. split file and network i/o into a subproject). This way we don't have to get everything working on windows immediately, but can start with just a core language coverage.

**Comment by 10Dev** [comment]
I was just wandering by and please accept my apologies if the following info is not useful in any way for people thinking of experimenting with Scala-native on Windows:

https://arstechnica.com/gadgets/2018/03/chrome-on-windows-ditches-microsofts-compiler-now-uses-clang/

https://github.com/Microsoft/microsoft-pdb

https://llvm.org/docs/GettingStartedVS.html

https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools

https://arvid.io/2017/08/03/using-clang-on-windows/

https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Building_Firefox_on_Windows_with_clang-cl

https://github.com/Microsoft/WinObjC

https://github.com/Microsoft/checkedc-llvm

**Comment by scf37** [comment]
This is really really really cool.

Given great language (Scala), instant startup time and low memory footprint (my hello world app takes 9Mb RAM) scala-native can be the choice for high quality cross platform end-user applications.

**Comment by cup** [comment]
https://github.com/scala-native/scala-native/issues/113
https://github.com/scala-native/scala-native/issues/1367
https://github.com/scala-native/scala-native/pull/691

**Comment by NickSeagull** [comment]
What's the status on this? I'm currently working on a native project and would love to migrate to Scala Native 😁

**Comment by cup** [comment]
I am willing to donate $800 if this can be implemented, thank you!

**Comment by tgsachse** [comment]
Friendly +1 on Windows support, working on a project with Scala Native and would really like to be able to ship for Windows! :)

**Comment by david-bouyssie** [comment]
@tgsachse I can tell you than SN works well on WSL although it's not the best solution. So if you can deploy WSL on your Windows computers this could be a temporary workaround.

**Comment by tgsachse** [comment]
I don't have any Windows computers myself, but the project I'm building is cross-platform and I'd like Windows users to be able to use it natively.

Are you saying that if I compile it in WSL then I could take that binary and ship it to native Windows users?

The project is essentially a shell extension, I support a bunch of POSIX shells right now but I'd like to branch out to Powershell as well.

**Comment by mnxn** [comment]
> I don't have any Windows computers myself, but the project I'm building is cross-platform and I'd like Windows users to be able to use it natively.
> 
> Are you saying that if I compile it in WSL then I could take that binary and ship it to native Windows users?
> 
> The project is essentially a shell extension, I support a bunch of POSIX shells right now but I'd like to branch out to Powershell as well.

If you compile something in WSL, you will get a Linux executable that can only be run in Linux or WSL. Native Windows users will not be able to run it unless they install WSL.

WSL is a way for developers to run Linux programs on Windows with  better OS integration than a full VM. It is not a solution for porting a program to windows.

**Comment by ekrich** [comment]
One way to open up this possibility is via this PR which would allow us to separate some of the code such as POSIX which is fine for Linux/macOS but not so great for Windows. This has been reviewed once and waiting for another review. https://github.com/scala-native/scala-native/pull/1637

I tested that out moving the POSIX C code to the `posixlib` project. After that we would just need some `sbt` magic to avoid this being built on Windows. https://github.com/scala-native/scala-native/pull/1820

That could help start the process as shown here. https://github.com/scala-native/scala-native/pull/1676

Then the process could be expanded as shown in this Proposal. https://github.com/scala-native/scala-native/issues/1352

I think the beauty of this approach as it puts less risk on the currently solid Linux/macOS support.

How is this affected by the push from WSL which allows running Scala Native to WSL2 which seems an even tighter integration? I do not have a new enough Win OS version to try out WSL2.

**Comment by david-bouyssie** [comment]
@ekrich Both WSl1/WSL2 works well with SN, at least for the tools I developed and tested. WSL2 is a full VM integrated with the Windows OS, so it has a real Linux kernel. Some low level stuffs like memory mapped files have thus an "exact" behavior. WSL2 however consumes far more memory resources than WSL1 and IO performance are also different between the two systems (depending on VM file access versus host file access).

**Comment by NickSeagull** [comment]
In my opinion, native Windows support (not by WSL that is) is important. As an example, this feature would be great in order to build cross platform desktop apps with SN

**Comment by arabelladonna** [comment]
> One way to open up this possibility is via this PR which would allow us to separate some of the code such as POSIX which is fine for Linux/macOS but not so great for Windows. This has been reviewed once and waiting for another review. #1637

I saw that this PR went through and was closed in August. Any news about native Windows support?

**Comment by ekrich** [comment]
@arabelladonna Looks like we could be making progress in that direction. See #2017

**Comment by WojciechMazur** [comment]
Windows support was implemented, with the PR https://github.com/scala-native/scala-native/pull/2370 allowing to successfully execute all unit tests.

**Comment by NickSeagull** [comment]
Leaving a comment to thank everyone involved in the project and in the implementation of this feature, including the ones that bumped this issue so it became important. I know open source can be hard sometimes, so I'm here to leave my grain of sand:

**Thanks everyone, you rock** 🤘 ❤️
