### ISSUE TITLE
Documentation contains wrong Re2 version.

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1134]
The documentation shows in "Environment setup" `Re2 2017-01-01 (optional)` and `travis-setup.sh` shows `git checkout 2017-03-01`

**Comment by densh** [comment]
Any newer version should work, there hasn't been any breaking changes to best of my knowledge.

**Comment by ekrich** [comment]
@densh The documentation is specifying an order version than we use though. Shouldn't they stay at least the same or say `2017-03-01` or newer?
