### ISSUE TITLE
Erroneous LLVM code for calls to externals from trait methods

### ISSUE THREAD

**Issue by jokade** [scala-native/scala-native#1136]
The following (synthetic) example generates wrong LLVM code for the call to `bar1.foo`:
```scala
object Main {
  def main(args: Array[String]): Unit = {
    val bar1 = Bar1()
    bar1.foo()
    val bar2 = Bar2()
    bar2.foo()
  }
}

trait FooTrait {
  @inline def foo(): Int = Foo.foo1()
}
class FooClass {
  @inline def foo(): Int = Foo.foo2()
}
@extern
object Foo {
  def foo1(): Int = extern
  def foo2(): Int = extern
  def bar_new(): Ptr[Byte] = extern
}

class Bar1 extends FooTrait
object Bar1 {
  def apply(): Bar1 = Foo.bar_new().cast[Bar1]
}
class Bar2 extends FooClass
object Bar2 {
  def apply(): Bar2 = Foo.bar_new().cast[Bar2]
}
```

The error during linking due to the undefined Foo symbols:
```
[error] Undefined symbols for architecture x86_64:
[error]   "_bar_new", referenced from:
[error]       _Bar1$::apply_Bar1 in __empty.ll.o
[error]       _Bar2$::apply_Bar2 in __empty.ll.o
[error]   "_foo2", referenced from:
[error]       _FooClass::foo_i32 in __empty.ll.o
[error]       _Main$::main_scala.scalanative.runtime.ObjectArray_unit in __empty.ll.o
```
i.e. `_foo1` is not defined in the LLVM code. Here's the LLVM code for `main`:
```llvm
define void @"Main$::main_scala.scalanative.runtime.ObjectArray_unit"(i8* %_1, i8* %_2) personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
_3.0:
  %_4 = call i8* () @"Bar1$::load"()
  %_6 = call i8* (i8*) @"Bar1$::apply_Bar1"(i8* %_4)
  %_8 = call i32 (i8*) @"FooClass::foo_i32"(i8* %_6)
  %_9 = call i8* () @"Bar2$::load"()
  %_11 = call i8* (i8*) @"Bar2$::apply_Bar2"(i8* %_9)
  %_13 = call i32 (i8*) @"FooClass::foo_i32"(i8* %_11)
  ret void
}
```
i.e. the call to `bar1.foo()` is effectively emitted as `bar1.asInstanceOf[Bar2].foo()`.
Interestingly, when the two lines for bar2 are deleted, there is a call to `undef`:
```llvm
define void @"Main$::main_scala.scalanative.runtime.ObjectArray_unit"(i8* %_1, i8* %_2) personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
_3.0:
  %_4 = call i8* () @"Bar1$::load"()
  %_6 = call i8* (i8*) @"Bar1$::apply_Bar1"(i8* %_4)
  %_9 = bitcast i8* undef to i32 (i8*)*
  %_8 = call i32 (i8*) %_9(i8* %_6)
  ret void
}
```

 **Edit**: tested with SN 0.3.6

**Comment by densh** [comment]
Thanks for the report!

**Comment by densh** [comment]
The issue is centered around unsafe casts from `Ptr` to a Scala class. While this might have worked previously in some cases, this is generally undefined behavior and is *expected* not to work after #1323. In the code above neither `Bar1` nor `Bar2` are allocated in the code, so the reachability analysis can and will avoid generating additional dispatch tables for those classes, which in turn will crash unexpectedly at runtime when you try to call methods on values of those types.

Instead, you should wrap pointers into Scala classes:
```
object Main {
  def main(args: Array[String]): Unit = {
    val bar1 = Bar1()
    bar1.foo()
    val bar2 = Bar2()
    bar2.foo()
  }
}

trait FooTrait {
  @inline def foo(): Int = Foo.foo1()
}
class FooClass {
  @inline def foo(): Int = Foo.foo2()
}
@extern
object Foo {
  def foo1(): Int = extern
  def foo2(): Int = extern
  def bar_new(): Ptr[Byte] = extern
}

class Bar1(ptr: Ptr[Byte]) extends FooTrait
object Bar1 {
  def apply(): Bar1 = new Bar1(Foo.bar_new())
}
class Bar2(ptr: Ptr[Byte]) extends FooClass
object Bar2 {
  def apply(): Bar2 = new Bar2(foo.bar_new())
}
```
This works as expected on current master.

**Comment by jokade** [comment]
@densh thank's for the explanation. One more question:

> The issue is centered around unsafe casts from Ptr to a Scala class. While this might have worked previously in some cases, this is generally undefined behavior and is expected not to work after #1323. 

Does this mean that starting with 0.3.9 casting from Ptr[Byte] to a Scala class is never allowed?
