### ISSUE TITLE
Don't depend on libunwind for stack traces

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1138]
Currently we depend on system-installed version of `libunwind` to implement stack traces. Given that's it's a dynamic dependency, we've observed a number of issues with environment setup and configuration difficulties in the wild. 

We should bake-in the libunwind (or its equivalent) into the main repo and build it as part of the runtime.

**Comment by ekrich** [comment]
Would using LLVMs unwind be an option? 
https://github.com/llvm-mirror/libunwind

**Comment by ekrich** [comment]
I also found this pseudo relevant post - https://discourse.julialang.org/t/porting-julia-to-other-platforms-llvm-libunwind/575

**Comment by ekrich** [comment]
From Rust - https://github.com/rust-lang/rust/tree/master/src/libunwind
