### ISSUE TITLE
 UNRESOLVED DEPENDENCIES

### ISSUE THREAD

**Issue by sailfish009** [scala-native/scala-native#1148]
os:  ubuntu 16.x, 
sbt: http://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html
java: openjdk version "1.8.0_151"

i tried to compile latest scala-native with sbt, but got below error messages:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-native#nativelib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[warn]  :: org.scala-native#javalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[warn]  :: org.scala-native#auxlib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[warn]  :: org.scala-native#scalalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[warn]  :: org.scala-native#test-interface_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[warn]  :: org.scala-native#nscplugin_2.11.12;0.3.7-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

info] Checking out Scala source version 2.11.12
[trace] Stack trace suppressed: run last benchmarks/*:update for the full output.
[trace] Stack trace suppressed: run last tests/*:update for the full output.
[trace] Stack trace suppressed: run last sandbox/*:update for the full output.
[trace] Stack trace suppressed: run last nativelib/*:update for the full output.
[trace] Stack trace suppressed: run last testInterfaceSbtDefs/*:update for the full output.
[trace] Stack trace suppressed: run last testingCompilerInterface/*:update for the full output.
[error] (benchmarks/*:update) sbt.ResolveException: unresolved dependency: org.scala-native#nativelib_native0.3.7                      -SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#javalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#auxlib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#scalalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#test-interface_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not foun                      d
[error] unresolved dependency: org.scala-native#nscplugin_2.11.12;0.3.7-SNAPSHOT: not found
[error] (tests/*:update) sbt.ResolveException: unresolved dependency: org.scala-native#nativelib_native0.3.7-SNAP                      SHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#javalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#auxlib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#scalalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#test-interface_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not foun                      d
[error] unresolved dependency: org.scala-native#nscplugin_2.11.12;0.3.7-SNAPSHOT: not found
[error] (sandbox/*:update) sbt.ResolveException: unresolved dependency: org.scala-native#nativelib_native0.3.7-SN                      APSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#javalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#auxlib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#scalalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#test-interface_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not foun                      d
[error] unresolved dependency: org.scala-native#nscplugin_2.11.12;0.3.7-SNAPSHOT: not found
[error] (nativelib/*:update) sbt.ResolveException: unresolved dependency: org.scala-native#nscplugin_2.11.12;0.3.                      7-SNAPSHOT: not found
[error] (testInterfaceSbtDefs/*:update) sbt.ResolveException: unresolved dependency: org.scala-native#nativelib_n                      ative0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#javalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#auxlib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#scalalib_native0.3.7-SNAPSHOT_2.11;0.3.7-SNAPSHOT: not found
[error] unresolved dependency: org.scala-native#nscplugin_2.11.12;0.3.7-SNAPSHOT: not found
[error] (testingCompilerInterface/*:update) sbt.ResolveException: unresolved dependency: org.scala-native#nscplug                      in_2.11.12;0.3.7-SNAPSHOT: not found

**Comment by Duhemm** [comment]
Hi @sailfish009,
We don't publish the snapshots, so you need to build them and published them yourself on your machine, locally. We have a command to do that: just type `sbt rebuild`, and everything should be fine.

Please let us know if that solved your issue.

**Comment by densh** [comment]
As mentioned by @Duhemm, snapshots are intentionally not published. Please either build the current master locally yourself, or use latest released version `0.3.6`.

**Comment by sailfish009** [comment]
thanks! i see.
