### ISSUE TITLE
publish for Scala 2.12.4

### ISSUE THREAD

**Issue by antonkulaga** [scala-native/scala-native#1169]
Looks like you forgot to publish for Scala 2.12.4, that is the reason I cannot resolve scala.native in my cross-project configuration https://github.com/portable-scala/sbt-crossproject/issues/84

**Comment by ekrich** [comment]
@antonkulaga Scala Native supports Scala `2.11` now. Scala `2.12` support is coming. Please try cross building to `2.11.12`. Scala Native does support sbt `0.13` and `1.0`.

**Comment by tusharmath** [comment]
Looking forward to scala-native supporting `sbt@1`

**Comment by densh** [comment]
@antonkulaga Scala 2.12 support is being tracked under #233, this is a duplicate.

@tusharmath Sbt 1.0 is already supported.
