### ISSUE TITLE
Nscplugin should specify clang -std for C files.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1173]
If I read sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala
correctly, it specifies a language standard (-std) for C++ files in mumble/resource but not for C files.
    
` val flags    = (if (isCpp) Seq("-std=c++11") else Seq()) ++ opts`

I believe that a standard, preferably an ISO standard, probably c11 should be specified.
A user could still override this setting by specifying nativeCompilerOptions (since they come
to the right). 

This became an issue for me whilst chasing bugs in time.scala & TimeSuite.scala (PR #929).
That bug was innocently inherited by pending (#117).  The names of fields in the struct tm vary
depending upon the compilation mode (don't look at me, I did not do it!).  It appears that the
clang default compilation mode can vary across systems (depending upon how they were compiled).
I have two systems with out-of-the-box clang and one defaults to an ISO mode and the other to
a gnu node (arrgh!).

I will address the specifics of the bug I found in time.scala in a separate issue. I created this issue first because a fix to that later issue would be far easier if it could depend upon known names, at least for the building of scala-native. 

If given the go ahead and an agreement to use c11, I can create a PR.

**Comment by Andrei-Pozolotin** [comment]
see #1143 #1177
