### ISSUE TITLE
Missing org.scala-native:tools_2.11

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-native/scala-native#1176]
http://search.maven.org/#search%7Cga%7C1%7Cscala-native%20tools

GroupId | ArtifactId | Latest Version | Updated | Download
-- | -- | -- | -- | --
org.scala-native | tools_2.12 | 0.3.6  all (3) | 13-Dec-2017 | pom  jar  javadoc.jar  sources.jar
org.scala-native | tools_2.10 | 0.3.6  all (10) | 13-Dec-2017 | pom  jar  javadoc.jar  sources.jar

**Comment by ekrich** [comment]
@Andrei-Pozolotin Tools only matches the version used by sbt. 0.13 -> 2.10 and 1.0 -> 2.12.

**Comment by Andrei-Pozolotin** [comment]
I see, thank you
