### ISSUE TITLE
Feature request: extract native pipeline library form sbt-scala-native

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-native/scala-native#1177]
please consider extracting native pipeline logic from

https://github.com/scala-native/scala-native/blob/master/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala

into separate library, for use by other tools outside of sbt context

**Comment by ekrich** [comment]
Hi @Andrei-Pozolotin, this is in the works https://github.com/scala-native/scala-native/pull/1143 . This should allow us to support other tool chains. Martin D I believe is working out of the Scala Center. Some people are on vacation so things are pretty quiet. You can also discuss on https://gitter.im/scala-native/scala-native

**Comment by Andrei-Pozolotin** [comment]
1. great, thank you.
2. perhaps you can keep this issue as tracking for PR #1143 
3. meanwhile we will use copy/paste in [scalor-maven-plugin](https://github.com/random-maven/scalor-maven-plugin/blob/develop/src/main/scala/com/carrotgarden/maven/scalor/scalanative/Native.scala)

**Comment by densh** [comment]
Fixed by #1143
