### ISSUE TITLE
ArchLinux: proper install

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-native/scala-native#1178]
1. here 
http://www.scala-native.org/en/latest/user/setup.html
```
sudo pacman -S llvm
```
2. should be
```
sudo pacman -S llvm clang
```

3. since `clang` is a split package 
https://wiki.archlinux.org/index.php/clang
https://www.archlinux.org/packages/?name=clang

**Comment by ekrich** [comment]
@Andrei-Pozolotin Are you planning to submit a PR for this change?

**Comment by Andrei-Pozolotin** [comment]
yes

**Comment by ekrich** [comment]
👍
