### ISSUE TITLE
Document existing automatically zero-out zone-allocated memory

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1182]
Requesting cleared/zeroed memory is an incredibly common operation, particularly when
dealing with structures.  Recent discussions & edits in PR #1170 are a case in point, and
brought me to study zone.scala.

Zone currently provides alloc, which guarantees that the contents of  memory are undefined.
Some compilers zero the memory in debug or -O0 and leave it with garbage in optimized
modes.  This has caused many a "just before or,worse yet,  just after" shipping bug.
 
Is there any interest in my submitting a PR which adds a  function calloc, which guarantees any
memory returned is cleared?

To preserve the abstraction, I would have Zone.calloc call Zone.alloc, check for NULL,
then return the result of stdlib.memset. I would also supply a corresponding test suite
and documentation change/creation.

Yes, I propose a convenience feature. Users of scala-native can and do roll their own.
But it seems,  at least to me, that making it easier for them to work with cleared
it makes it more likely that it will get done, preventing scala-native devo maintenance issues.

I agree that this leads down the slippery slope of someone asking for, say, "memory aligned on 3 byte boundaries."  Although, asking for 8 or 16 byte aligned (cleared/uncleared) memory might be a more 
agreeable request.

I understand entirely if this proposed PR is declined as adding complexity rather than utility.

Thank you,

cc: @eatkins

**Comment by densh** [comment]
I think it's a great suggestion overall, but we should really make zeroing a default and reintroduce current `alloc` with a different name (for performance-sensitive use cases.)

**Comment by LeeTibbert** [comment]
@densh  When the flurry from vacation settles....

What do you think about adding a second argument, zero, which defaults to true?
That would avoid the Known Hard Problem of naming the 'raw' function.

```
 def alloc(size: CSize,  zero: Boolean = true): Ptr[Byte]
```
To avoid any cognitive dissonance between zero & true, the second
argument could be "raw: Boolean = false".

Thank you,

Lee

**Comment by LeeTibbert** [comment]
In the course of doing a design sketch for resolving this issue, I discovered some code
in `/nativelib/src/main/scala/scala/scalanative/native/package.scala` which already zeros
the memory via a macro. The accompanying comments describe alloc() as doing this.

Short term:
I believe this issue can be resolve by adding two lines in `docs/user/interop.rst`.
One for alloc which says that it returns zeroed memory, and one for stackalloc which says
that it returns memory with undefined contents

Midterm:

Given a name I could peck away at creating a non-zeroed implementation.
There are some cases, such as toCString in the same file, where the returned
memory is just going to be filled in anyway.

**Comment by densh** [comment]
Indeed, [`alloc` zeroes memory by default already](https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/scala/scala/scalanative/native/package.scala#L205), so the issue described here is already addressed. PR #1188 updates the docs to make the zeroing semantics explicit.

**Comment by eatkins** [comment]
Just for the record, I think part of the confusion was that Zone.alloc does not zero the memory and I had called that directly in time.scala so the buffers weren't actually zeroed out by default. I was only calling Zone.alloc because time.scala was added to nativelib which can't use the alloc macro since it's defined in that project.
