### ISSUE TITLE
Proposal: add support cross-triple in native pipeline

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-native/scala-native#1183]
is seems that both current [ScalaNativePluginInternal.scala](https://github.com/scala-native/scala-native/blob/master/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala) and future #1177 PR #1143 lack support cross-triple build https://clang.llvm.org/docs/CrossCompilation.html

**Comment by ekrich** [comment]
Scala Native now allows specifying the Target Triple via https://github.com/scala-native/scala-native/pull/2033
