### ISSUE TITLE
BUG: proper packaging for `scalalib`

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-native/scala-native#1185]
1. `scalalib` on central
http://search.maven.org/#artifactdetails%7Corg.scala-native%7Cscalalib_native0.3_2.11%7C0.3.6%7Cjar
* both depends on `scala-library`
```
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.11.12</version>
        </dependency>
```
* and also includes `scala-library` JVM classes `*.class`
```
# cd /tmp
# wget http://repo1.maven.org/maven2/org/scala-native/scalalib_native0.3_2.11/0.3.6/scalalib_native0.3_2.11-0.3.6.jar
# jar tf scalalib_native0.3_2.11-0.3.6.jar | grep "scala/Predef.class"
scala/Predef.class
```

2. this produces various problems in various build systems, for example
* errors in Scala IDE:
```
More than one scala library found in the build path
```
* due to `scalaLibraries` detection:
https://github.com/scala-ide/scala-ide/blob/master/org.scala-ide.sdt.core/src/org/scalaide/core/internal/project/ClasspathManagement.scala#L264
```
val pathToPredef = new Path("scala/Predef.class")
```
3. one way to get proper packaging for `scalalib` is to follow `scala-js` approach:
http://search.maven.org/#artifactdetails%7Corg.scala-js%7Cscalajs-library_2.11%7C0.6.22%7Cjar
when only JS-VM `*.sjsir` classes are included in the library jar and JVM `*.class` classes are excluded from the library jar

**Comment by Andrei-Pozolotin** [comment]
related: #1007

**Comment by Andrei-Pozolotin** [comment]
else people will start rolling their own jars 
https://github.com/random-scalor/scala-native-scalalib

**Comment by densh** [comment]
Thanks for the bug report, this indeed looks like another instance of #1007. I believe that Scala.js' approach is the correct solution here.
