### ISSUE TITLE
FileChannelImpl only reads a single byte into ByteBuffers

### ISSUE THREAD

**Issue by dlpatri** [scala-native/scala-native#1198]
Given code similar to the following:

    channel = FileChannel.open(path, StandardOpenOption.READ)
    val idBB = ByteBuffer.allocate(12)
    idBB.order(ByteOrder.LITTLE_ENDIAN)
    channel.read(idBB)
    idBB.flip()
    
    val idBA = idBB.array()
    print("ID BYTES: ")
    for (i <- 0 until idBA.length)
      print(s"${idBA(i)} ")
    println()

The JVM will output `ID BYTES: -85 75 84 88 32 49 49 -69 13 10 26 10`
Scala Native will output `ID BYTES: -85 0 0 0 0 0 0 0 0 0 0 0`

This discrepancy comes from the implementation of `javalib/src/main/scala/java/nio/channels/FileChannelImpl.scala` `def read(buffer: ByteBuffer, pos: Long)`

Particularly, where the `dst` Array is hardcoded as only having a single Byte on line 73.

    val dst = new Array[Byte](1)

**Comment by dlpatri** [comment]
Not seeing any open PRs involving FileChannel... And it seems simple enough that even I might be able to fix it up. Should I give it a try? Or is there anyone else really wants to look at it first?

**Comment by densh** [comment]
@dlpatri Feel free to try.
