### ISSUE TITLE
Add support for clang-format greater than a particular version

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1199]
On my current version of macOS, clang-format is version `7.0` but `bin/clangfmt` only accepts version `5.0`.

**Comment by densh** [comment]
We need to fix version of clang format, otherwise every PR could be reformatted as everyone could use a different version of the tool. What's your alternative suggestion exactly?

**Comment by ekrich** [comment]
I think you are right, we need to use the version being used in CI/Travis. A developer can use a newer version but it must be backward compatible so CI passes. Otherwise, the developer can get the older version of `clang-format`.
