### ISSUE TITLE
Need a way to nativeLink multiple main classes, or to nativeLink subprojects

### ISSUE THREAD

**Issue by philwalk** [scala-native/scala-native#1231]
I would like to nativeLink all of my discoveredMainClasses somehow. I've tried splitting src/main/scala into one-subproject per main class, but it's not possible yet (afaict) to nativeLink a subproject, so that doesn't work.
It would be simpler anyway to have a single project consisting of a collection of command line tools, each of which is defined by a main class, and to be able to nativeLink each of them to a separate executable based on a default naming convention (for example, foo.Bar might be linked to a binary named "bar").

If there's a way to do this short of creating a separate scala-native sbt project for each of potentially hundreds of main classes, that would be wonderful.

**Comment by densh** [comment]
Hi @philwalk, our current tooling infrastructure deeply ingrains one sbt project = 1 binary equivalence, so it's unlikely we'll add this feature in foreseeable future (too much breaking changes that are likely to complicate things internally). 

On the other hand, I believe the feature you want can be effectively achieved through a bit of code generation. Given entry point classes `A`, ..., `Z`, you create one folder with one trivial forwarding class:
```
// myproject/generated/a/GeneratedA.scala
object GeneratedA {
  def main(args: Array[String]): Unit = A.main(args) // calling real main
}
```
Then you can programmatically create a new subproject per a generated subdirectory and bundle them together as a single [`CompositeProject`](https://developer.lightbend.com/blog/2018-07-02-sbt-1-2-0/#composite-project). Each generated subproject would depend on your real project where you keep all of your code.
