### ISSUE TITLE
Add SBT support to version libraries against the version of Scala-native or NIR it's compiled against.

### ISSUE THREAD

**Issue by Milyardo** [scala-native/scala-native#124]
Users of Scala Native libraries will need ensure that libraries they are using are compiled against some binary compatible version Scala Native. Scala.js currently uses the `%%%` operator to add the append the Scala.js version to the artifact name.

**Comment by densh** [comment]
The fix for this issue is going to be part of the solution for https://github.com/scala-native/scala-native/issues/58
