### ISSUE TITLE
Cleaning up URI/URL Encoder / Decoder in java.net

### ISSUE THREAD

**Issue by pcejrowski** [scala-native/scala-native#1241]
Currently in `java.net` there is `URIEncoderDecoder` which is not part of Java's `java.net` package. It should be split into `URLEncoder` and `URLDecoder` which map to Java's classes.

**Comment by xuwei-k** [comment]
https://github.com/scala-native/scala-native/pull/1215

**Comment by densh** [comment]
Fixed in #1267
