### ISSUE TITLE
Link error with Enum

### ISSUE THREAD

**Issue by cquiroz** [scala-native/scala-native#1245]
I'm getting this linking error:

```
[error] cannot link: @java.lang.Enum::hashCode_i32
```

**Comment by densh** [comment]
Hi @cquiroz, thanks for the report. Can you please provide a minimal reproduction that triggers this?

**Comment by cquiroz** [comment]
It comes from this snippet on `scala-java-locales`
https://github.com/cquiroz/scala-java-locales/blob/master/core/src/main/scala/locales/LocaleRegistry.scala#L65

Basically it is a `Map` with an `Enum` key thus  it requires `hashCode`

**Comment by densh** [comment]
Fixed in #1246
