### ISSUE TITLE
Consider porting JUnit support from Scala.js

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1256]
It seems to be generally platform-independent, and it would allow us to share tests as-is wrt Scala.js.

**Comment by MasseGuillaume** [comment]
I'm exploring this right now.

**Comment by ekrich** [comment]
Is anyone working on this one?

I was looking into this and it appears this requires a compiler plugin on Scala.js. Was that part of the plan for Scala Native too?

**Comment by sjrd** [comment]
Yes you'll need basically the same compiler plugin.

Make sure to use the version in Scala.js master. It's much simpler than the one in 0.6.x.
