### ISSUE TITLE
nativelib/src/main/resources cries out for housekeeping

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1258]
Let me capture an issue I noticed during my recent PR sprint.  The PR I was working on
at the time was growing too large and complex, so I am resorting to creating an issue
so that I can remember it when/if I have time to return.

The great Swiss child psychologist Jean Piaget described a process of child development where the child first accommodates then assimilates.  In the accommodation stage, new concepts are stuffed in to the existing cognitive schema. After a while, enough concepts are added that the schema becomes unstable, forcing the child to re-organize, integrate, and adopt a new schema.  Soak, wash, rinse, repeat.

Now, you ask, what does this have to do with scala-native and why am I darkening your doorstep?

It looks like nativelib/src/main/resources has grown through the folk process; change upon change with minimal re-organization.  Not complaining, just describing and seeing an opportunity for improvement.

There is a resources/posix subdirectory tree but many posix files, fcntl,c, stat,c, unistd.c, and others, exist at the top level, not in the posix tree. Not only does this make files hard to find, it means that the organization of the C code does not parallel the nicely organized posix scala code. Software engineers get troubled by such apparently necessary inconsistency.

**Comment by LeeTibbert** [comment]
PR #1259 submitted. all tests passed. I will close this issue after PR has been merged.

**Comment by densh** [comment]
While I see the sentiment with this issue, it's neither a bug nor a feature, so it doesn't really deserve it's own ticket. The PRs in this area are perfectly fine, but it's probably best to keep the discussion in gitter.
