### ISSUE TITLE
Bundle LLVM with Scala Native

### ISSUE THREAD

**Issue by mdedetrich** [scala-native/scala-native#126]
LLVM tends to be fairly brittle between releases and it also rarely backports fixes into earlier versions. Most languages that have a LLVM backend tend to bundle LLVM (usually as an executable or inlined into the compiler) for this reason. As far as I know the languages which do this are
- Swift
- Haskell (for its LLVM backend)
- Rust? (can someone clarify this)

Also it greatly helps people getting onboard with the project. Instead of having to figure out which specific version of LLVM you need (and maybe how to build it), it would get automatically bundled with the scala-native compiler.

**Comment by densh** [comment]
I think it's an option we need to consider seriously for the future. It requires quite a bit of time investment to implement the infrastructure to publish and fetch our own releases, but it has a huge potential of making setup a single-step process (add one line to sbt, and it will do everything for you.)

**Comment by mdedetrich** [comment]
So there are a couple of ways to approach this

* Create `.jar` libs out of LLVM. Personally I am not a fan of this option, I don't see immediately how creating libs of out LLVM executables/sources is useful (I don't see other projects needing to use the LLVM executable/source). It could also make it more annoying in regards to publishing for different platforms
* Have the LLVM sources/executables included as a git submodule. The git submodule should ideally be a scala-native fork of LLVM itself (so its easy for scala-native to patch/rebase against LLVM master, a lot of other non trivial languages that use LLVM end up patching against mainline).

I prefer the latter option, which I think is what Haskell GHC and Swift do. I am also not a fan of relying on the packaging systems of the operating system, past experience has shown that this approach causes way too many problems and also takes up a huge amount of time to debug problems with.

**Comment by frgomes** [comment]
Pre-built binaries are available at http://llvm.org/releases/download.html and it would not be complicated to tell SBT to download and install LLVM in case it turns out to be necessary.

**Comment by densh** [comment]
Overall we've had zero issues with relying on a system-installed LLVM so far. This is a non-issue in practice.
