### ISSUE TITLE
scalanative/runtime Arrays should support Long lengths, etc.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1274]
Whilst debugging javalib nio Files.scala readAllBytes, I discovered that nativelib/src/main/scala/scala/scalanative/runtime Arrays are dominated by Int. That is, they can only have Int size, can only return Int length, can only have Int at().

Not that anyone would ever need an array greater than 2Gb, it seems like the Ints should become
Longs, either as direct replacements or as a parallel implementation.  

There are some 32/64 bit considerations. On 64 bit machines, Longs are probably just as fast as Ints.
I am guessing, but have no data, that Longs are slower on 32 bit machines.

**Comment by densh** [comment]
Scala's Arrays semantics is tied to JVM's arrays, which can only hold up to MAX_INT number of elements. Due to compatibility constraints, we can not change this, even though it would have been nice to have 64-bit sized arrays.
