### ISSUE TITLE
javalib/src/main/scala/java/nio/file/Files.scala __silently__ fails to read all bytes of files sizes > 32 bits.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1275]
Whilst chasing a compilation issue with javalib/src/main/scala/java/nio/file/Files.scala readAllBytes()
I noticed that it __silently__ fails to read all bytes when the file size is greater than a 32 bit Int.
Not friendly and probably only meant as temporary scaffolding.

```
 def readAllBytes(path: Path): Array[Byte] = Zone { implicit z =>
// Note the .toInt. size(path) can validly return a Long. 
    val len   = size(path).toInt
// crickets!

    val bytes = scala.scalanative.runtime.ByteArray.alloc(len)
    val fd    = fcntl.open(toCString(path.toString), fcntl.O_RDONLY)
    try {
      var offset: Int = 0
      var read: Int   = 0
      while ({
        read = unistd.read(fd, bytes.at(offset), len - offset).toInt;

// I'll confess, I added the second .toInt so that Files.scala would
// compile with the types in the stricter unistd.scala. The first one
// was there before I touched the file, I swear! 
```
The proper fix would be to allow the code to handle Longs. However, scalanative.runtime ByteArray
can only handle Int sizes, see issue #1274.

Given Int sized Arrays for the foreseeable future, the proximal fix is to test if .toInt will truncate
and throw an exception. Agreed, not friendly, but far better than silent truncation.

Does anybody have an idea of an existing "file length too long" exception or should
I create something myself?  Anybody know what if Scala JVM or Java can read a 64 bit file?
If not, what do they throw when presented with a file they can not handle? 

My thanks & appreciation for suggestions and discussion.

Looks like I am off on a Nantucket sleigh ride....

**Comment by LeeTibbert** [comment]
I did a quick  grep through the file and did not see any other .toInt.  That does not mean that other functions are safe, just that the current blatant truncation does not appears in the same form elsewhere in the file.  Anyone touching this file should probably keep large file issues in the back of their mind.

**Comment by Duhemm** [comment]
Thanks a lot for the report! It looks like on the JVM, an `OutOfMemoryError` is supposed to be thrown:  https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#readAllBytes-java.nio.file.Path-

That's what we should do, too.

**Comment by densh** [comment]
Doing what JVM does in this case is the way to go, given that we are implementing existing API.

**Comment by LeeTibbert** [comment]
Thanks to the help of a number of people giving me clues & direction, I now know the
error to throw and the expected text.  readAllBytes() of a 3GB file on Scala JVM, and presumably
Java itself, on at least one version throws the moderately useful:
`java.lang.OutOfMemoryError: Required array size too large`.

I now have the pieces I need to create a PR.  I am going to wait for PR #1257 to clear, in the fullness of time. That PR touches readAllBytes() and nobody wants too many changes in flight.
