### ISSUE TITLE
Accessing args main parameter generates Segmentation fault 

### ISSUE THREAD

**Issue by fbertra** [scala-native/scala-native#130]
The following code generates a Segmentation fault before the fprintf call.

´´´

    val len = args.length

    fprintf(stdout, c"Hello bare metal\n")

    if (len == 0)
      // ...
´´´

Full example:
https://github.com/fbertra/scala-native-segmf

**Comment by fbertra** [comment]
Seen on Linux Ubuntu 16.04

clang++ -v 
Ubuntu clang version 3.7.0-2ubuntu4 (tags/RELEASE_370/final) (based on LLVM 3.7.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.2.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by densh** [comment]
Thanks for the bug report!

**Comment by densh** [comment]
The reason why this happens is that we currently don't convert C-style main args to Scala-style main args in https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/scala/scala/scalanative/runtime/package.scala#L25 . Now that we have implemented strings and arrays it's one step away from fixing this one.

**Comment by fbertra** [comment]
I volunteer for this issue.

I'm investigating how to choose the correct Java Charset from the POSIX locale.  The rest should be easy.

**Comment by densh** [comment]
@fbertra Locales are a large chunk of work (https://github.com/scala-native/scala-native/issues/247). I'd suggest just to use UTF-8 as an unconditional default for now.

**Comment by densh** [comment]
Fixed in #259
