### ISSUE TITLE
Suspected recent timing problem in j.l.Process.isActive

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1301]
#### Presenting problem
Within the past day or so, I have begin having problems with ProcessSuite
failing in the destroy() test.  This has happened a number of times

I am creating this issue as a "heads up" in case others experience this
same problem

#### Background

X86_64, 3.0Ghz, 8 core, virtualized, 16GB memory.  Fresh 0.3.9-SNAPSHOT
updatefrom EPFL GitHub master branch. Ubuntu 18.04.1, all recent updates.
The JDK is 10, but I do not think that is an issue. Clang 6.0.1

My X86 is still on 0.3.7, so not seen there.

#### Analysis

The problem presents in the destroy() test but after some debugging, I think it
is actually a timing issue with process.isAlive.

The relevant code, with the method before and after.

```
 addTest("waitFor with timeout times out") {
    val proc = new ProcessBuilder("sleep", ".005").start()
    assert(!proc.waitFor(1, TimeUnit.MILLISECONDS))
    assert(proc.isAlive)
    proc.waitFor(1, TimeUnit.SECONDS)
  }

  addTest("destroy") {
    val proc = new ProcessBuilder("sleep", ".005").start()
    assert(proc.isAlive)
    proc.destroy()
    assert(proc.waitFor(100, TimeUnit.MILLISECONDS))
    assert(proc.exitValue == 0x80 + 9)
  }

  addTest("destroyForcibly") {
    val proc = new ProcessBuilder("sleep", ".005").start()
    assert(proc.isAlive)
    val p = proc.destroyForcibly()
    assert(p.waitFor(100, TimeUnit.MILLISECONDS))
    assert(p.exitValue == 0x80 + 9)
  }
```
* The immediately proceeding test ""waitFor with timeout times out"
  succeeds.  The isAlive() test there is after a waitFor(). If I add
  that waitFor() to destroy() before the isAlive test, destroy() succeeds.

* If I add a printf() before the ProcessBuilder() call, destroy() succeeds.
  Is some pool of processes being exhausted and the slight delay helps?

* The code in the destroyForcibly() test immediately after destroy()
   is essentially the same code as destroy(). It goes through one
   intermediate call level and then executes the same code as destroy().

   The destroyForcibly() code succeeds if the destroy() test before it
   is enabled (and failing).  If I comment out the destroy() code, then
   destroyForcibly() fails, apparently at the isAlive() test.   

 * UnixProcess isAlive() calls into some C++ code, which looks hairy. My brain 
   needs rest before I try to trace that.

#### Next Steps

If I am the only one seeing this issue, I can work around it in my own environment.

I think that ProcessSuite.scala is validly detecting a race or timing condition
with isAlive.

**Comment by densh** [comment]
I haven't noticed this being a problem, but any fixes to improve stability in the process implementation are welcome.

**Comment by LeeTibbert** [comment]
I am closing this because I have not experienced the reported problem in
two months or so..  Then again, I have not spent much time on the
machine which exhibited the problem. 

If I experience the problem again, I will create a fresh issue.
