### ISSUE TITLE
Throwables.toString reports class with a $ sign, Scala JVM does not

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1308]
I'm a couple or so recursion levels deep chasing bugs, so let me capture
the presenting problem and possible solutions  before they overflow my memory buffer.

From Scala JVM, no $ sign before colon.
```
scala> val t = new Throwable("time")
t: Throwable = java.lang.Throwable: time

scala> t.toString
res0: String = java.lang.Throwable: time

```

From S-N:
```
 tests.AssertionFailed$
```
Easy solution is to have Throwables.scala toString strip (one, more?) rightmost
dollar signs from the class name.

A better solution is to implement Class.getCanonicalName and have Throwables.scala
use it.

**Comment by densh** [comment]
There is a difference between class  for `class C` and an `object C`:

For example here:
```
object Foo
class Bar
object Test extends App {
  println(Foo.getClass)
  println(Bar.getClass)
}
```
Both SN and JVM would print:
```
class Foo$
class Bar
```
The behavior on SN is 1-to-1 the same.
