### ISSUE TITLE
Unit tests fail to link in release mode

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1319]
Thought this was worth a timely report.

Error appears to happen during compilation of unit-tests.

```
# thin lto active, release mode shown as active below.
[info] Linking native code (immix gc, thin lto) (12331 ms)
Hello, World!
[success] Total time: 18 s, completed Aug 22, 2018, 7:39:46 PM
[info] Compiling 6 Scala sources to /home//Sandbox/scala-native-PRs_2018-08-13/ReleaseModeBugHunt/unit-tests/target/scala-2.11/classes...
[info] Compiling 124 Scala sources to /home//Sandbox/scala-native-PRs_2018-08-13/ReleaseModeBugHunt/unit-tests/target/scala-2.11/test-classes...
[warn] there were 34 deprecation warnings; re-run with -deprecation for details
[warn] there were 53 feature warnings; re-run with -feature for details
[warn] two warnings found
[info] Compiling 1 Scala source to /home//Sandbox/scala-native-PRs_2018-08-13/ReleaseModeBugHunt/unit-tests/target/scala-2.11/test-classes...
[info] Linking (2060 ms)
[info] Discovered 5153 classes and 29091 methods
[info] Optimizing (release mode) (71236 ms)
[info] Generating intermediate code (4272 ms)
[info] Produced 8 files
[info] Compiling to native code (4274 ms)
[error] Instruction does not dominate all uses!
[error] Instruction does not dominate all uses!
[error]   %5 = invoke i8* @"java.lang.String$::load"()
[error]           to label %6 unwind label %38
[error]   %9 = bitcast i8* %8 to i8**
[error]   %58 = tail call i8* @"java.lang.String$::java$lang$$underscore$String$$$underscore$string2string_java.lang.String_java.lang.String"(i8* %5, i8* %1)
[error] LLVM ERROR: Broken function found, compilation aborted!
[error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[info] Linking native code (immix gc, thin lto) (1351 ms)

```

Background:

* Clean update from S-N master git, no local modifications.

* First seen with clang-7 but verified with clang-6.0 only on system.

* X86_64 Ubuntu 16.04, everything up to date.

*  I have not tried this on my X86 system, using Clang 6.0.1. I can do that
   if it would be useful.

* nativeMode := "debug" works fine

* nativeMode := "release" & nativeLto := "none" proceeds past compilation then
  dies because of  known issue #1128. PR #1248 fixes 1128 but is on hold until
  next breaking S-N release. 

I hope this report helps.

**Comment by densh** [comment]
Thanks for the report!

**Comment by LeeTibbert** [comment]
A status update. Just information, not trying to push the river.

I ran this again whilst waiting for a Travis CI run to complete. 
I wanted to see if the plethora of changes over the past week had made
the problem go away.  I was careful to do a clean of any .nir in the build
tree.   Same issue. Looks like it is real.

**Comment by LeeTibbert** [comment]
I have not seen this problem recently, so I am closing this issue.  

I have been running `test-all` (without *Socket*Suite) in release mode, using
latest 0.4.0-Snapshot as part of my work on pending PR #1436 and have not seen this issue
over many iterations.

Also, over the past 6 months, nobody else has mentioned seeing the problem.

I'll open another issue if I see this again.
