### ISSUE TITLE
Proposal: modularize core libraries

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1352]
Currently Scala Native is mostly a monorepo-style project. The monorepo includes a few coarse-grained library projects within it:

1. nativelib -- core native interop, core runtime classes, libc bindins, posix bindings
2. javalib -- java library compatibility layer
3. scalalib -- scala library cross-built for native

This has caused problems in terms of portability to new platforms/architectures as all-or-nothing approach means that we can only support new platform if 100% of the existing code work on it (e.g. windows doesn't have posix). 

Instead I suggest to split the libraries into finer grained modules by introducing extra modules for:
- [x] clib -- libc bindings (pr #1353)
- [x] posixlib -- posix bindings (pr #1350)
- [ ] javacorelib -- absolute basics of java namespace such as `java.lang`, `java.util` etc. 
- [ ] javafilelib -- file i/o (currently based on posix)
- [ ] javanetlib -- network i/o (currently based on posix)
- [ ] javaziplib -- zip and jar support (currently based on zlib)

Having multiple smaller projects will allow us to introduce early support for new platforms as soon as basics such as nativelib, clib and javacorelib are working on it. Additional libraries may adopt new platforms with some delay (if at all). Some libraries might remain platform-dependent forever such as posixlib. 

/cc @muxanick @jonas

**Comment by jonas** [comment]
How will this affect developers? For example, will a developer have to opt-out of `javaziplib` if it is not available for the specific platform?

**Comment by densh** [comment]
@jonas If some API (lets say zlib) is not available on the target system, the project that uses it will fail to link at LLVM link time. This is just as true now if for example if you try to use boehm gc without having it installed.

**Comment by muxanick** [comment]
Quick question, should I split unit tests? Like ProcessSuit.scala import posix

**Comment by muxanick** [comment]
@densh I need a help to begin this task, please, I don't understand some basics like how to split `java.io` into two libs if there are `private[io]` methods doesn't work after split.
I have tried to move out `java.nio` but `String` used it a lot and other files as well.
Should I rewrite them all or I misunderstood something?
There are many small things like: `Filesystem` used `java.net.URI` class which is in another lib, which uses `Filesystem` and depends on it. I can try to rewrite `URI` class if needed but I want to know if that is desirable result.

**Comment by sjrd** [comment]
* There are 3 `private[io]` defs in the javalib currently, and none of them are used from other logical components, so the split won't affect them.
* Keep `java.nio.Buffer` and its hierarchy in the core, as well as `java.nio.charset`. They should be platform-independent, and they are indeed required by core stuff like `String`.
* I don't see where `URI` uses `Filesystem`. AFAICT, `URI` can stay in the core while `Filesystem` goes to another lib.

And yes, you will need separate test suite projects, because you'll need to test that the core actually works when the other libs are not on the classpath anymore, which is something you can only do with separate test suites.

**Comment by muxanick** [comment]
@sjrd Thank you for your answer, that is useful information!
* I see 5 `private[io]` in the javalib but it doesn't matter, I am currently have these errors:
```
avafilelib/src/main/scala/java/file/LineNumberReader.scala:4: imported `BufferedReader' is permanently hidden by definition of object BufferedReader in package io
[warn] import java.io.BufferedReader
[warn]                ^
[error] /Users/muxanick/Projects/muxanick/scala-native/javafilelib/src/main/scala/java/file/LineNumberReader.scala:66: not found: value chompNewLine
[error]       chompNewLine()
[error]       ^
[error] /Users/muxanick/Projects/muxanick/scala-native/javafilelib/src/main/scala/java/nio/channels/FileChannelImpl.scala:42: constructor MappedByteBuffer in class MappedByteBuffer cannot be accessed in <$anon: java.nio.MappedByteBuffer>
[error]       new MappedByteBuffer(mode, size.toInt, new Array(size.toInt), 0) {}
```

**Comment by muxanick** [comment]
```
[error] /Users/muxanick/Projects/muxanick/scala-native/javafilelib/src/main/scala/java/nio/file/Files.scala:579: object java.util.Set is not a value
[error]     new WrappedScalaStream(walk(start, maxDepth, 0, options, Set(start)), None)
[error]                                                              ^
[error] /Users/muxanick/Projects/muxanick/scala-native/javafilelib/src/main/scala/scala/scalanative/nio/fs/UnixPath.scala:76: overloaded method constructor URI with alternatives:
[error]   (x$1: String,x$2: String,x$3: String)java.net.URI <and>
[error]   (x$1: String,x$2: String,x$3: String,x$4: String)java.net.URI <and>
[error]   (x$1: String,x$2: String,x$3: String,x$4: String,x$5: String)java.net.URI <and>
[error]   (x$1: String,x$2: String,x$3: String,x$4: Int,x$5: String,x$6: String,x$7: String)java.net.URI <and>
[error]   (x$1: String)java.net.URI
[error]  cannot be applied to (scheme: String, userInfo: Null, host: Null, port: Int, path: String, query: Null, fragment: Null)
[error]     new URI(scheme = "file",
[error]     ^
```

**Comment by muxanick** [comment]
if I for instance move `BufferedReader` to the `javafilelib` then I have a problem with sandbox:
```
[error] missing symbols:
[error] * M22java.io.BufferedReaderRL14java.io.ReaderE
[error]   - from M14scala.Console$RE
[error]   - from M13scala.Predef$D7printlnL16java.lang.ObjectuE
[error]   - from M5Test$D4mainLAL16java.lang.String_uE
[error] * T22java.io.BufferedReader
[trace] Stack trace suppressed: run last sandbox/compile:nativeLink for the full output.
[error] (sandbox/compile:nativeLink) java.util.NoSuchElementException: key not found: Top(java.io.BufferedReader)
```

**Comment by muxanick** [comment]
* Please see above there is a `URI` class used in `Filesystem.scala` and `UnixPath.scala`

* And most mystical error is about `java.lang.Set` which I don't even understand:
```
[error] /Users/muxanick/Projects/muxanick/scala-native/javafilelib/src/main/scala/java/nio/file/Files.scala:579: object java.util.Set is not a value
[error]     new WrappedScalaStream(walk(start, maxDepth, 0, options, Set(start)), None)
[error]                                                              ^
```

**Comment by muxanick** [comment]
You can see latest state in here: https://github.com/scala-native/scala-native/pull/1672
It would be good to hear a feedback about my direction I am moving in this PR (I mean splitting line), thanks!

**Comment by WojciechMazur** [comment]
After adding linktime conditions modularization of javalib is no longer needed. It should allow us to close this issue
