### ISSUE TITLE
NIO File Walker fails on broken links

### ISSUE THREAD

**Issue by sorenbug** [scala-native/scala-native#1354]
[Gitter Log](https://gitter.im/scala-native/scala-native?at=5b9eaafb0cfe7f30f1a350f7)

When using the NIO walker and visiting files, if a broken link is encountered, i.e. `/foo/bar/link -> /baz/foo/does_not_exist`, then the walker will fail (even before visitFile is called in the specified visitor).

Full stack trace:

```
java.nio.file.NoSuchFileException: : /home/soren/.config/fish/functions/fish_prompt.fish
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.nio.fs.UnixException$.apply(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView.scala$scalanative$nio$fs$NativePosixFileAttributeView$$throwIOException(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView.scala$scalanative$nio$fs$NativePosixFileAttributeView$$getStat(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2$$anonfun$1.apply(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2$$anonfun$1.apply(Unknown Source)
        at scala.scalanative.native.Zone$.apply(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView.attributes(Unknown Source)
        at java.nio.file.Files$$anonfun$_walkFileTree$1.apply(Unknown Source)
        at java.nio.file.Files$.$underscore$walkFileTree(Unknown Source)
        at java.nio.file.Files$.walkFileTree(Unknown Source)
        at tf.bug.dot.Main$.dissolveLinks(Unknown Source)
        at tf.bug.dot.Main$.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

**Comment by densh** [comment]
Thanks for the bug report!

**Comment by eatkins** [comment]
I don't have time to fix this properly myself, but it should be pretty easy. I think there just needs to be a try { ... } catch { case e: IOException => visitFailed } at https://github.com/scala-native/scala-native/blob/01fbdf7cf6f1f9f62982eab30a35eeb2f7c735ca/javalib/src/main/scala/java/nio/file/Files.scala#L630.

**Comment by LeeTibbert** [comment]
I took a run at implementing. with appreciation & thanks,  the information from @eatkins.

@sorenbug  Pardon my lack of comprehension. I like to go back to the original reporter.
What the  behavior you expected to see when walkFileTree encounters a broken link?  Did you expect the traversal to stop with an exception or did you expect the link to be skipped?

I created a test in FilesSuite.scala to replicate the problem as reported.  Fine there due
to the quality of the original report and of the code in FilesSuite.

Then I implemented the try/catch with the catch clause translated from the provided pseudo-code as
I believe was intended: 'catch {  case e: IOException => visitor.visitFileFailed(p, e) }'

The normal file visitor just re-throws so one gets the same 
`java.nio.file.NoSuchFileException: <filename>` reported in the opening comment. The new catch
seems to add little value until on realizes that one can write a custom visitor with an override of visitFileFailed which skips broken links.

From what I can see, the current out-of-the -box behavior of terminating with an
NoSuchFileException when encountering a broken link is the correct default behavior.  

The new catch provides a little more flexibility and is probably closer to the Java fileWalker design,
so it is probably worth the PR.

Please advise, as you may have time.  Thank you.

**Comment by LeeTibbert** [comment]
OK, so I used my go-to method of writing a small program and running it on Scala JVM.
Looks like the default JVM behavior is to visit the broken link, not throw, and continue
the traversal. 

Later:  OK, I think I have the sent of a solution
` val attributes = getFileAttributeView(p,` needs to be, I think, a two step process.
The first is to call it always with `LinkOption.NOFOLLOW_LINKS`. That get info on the
link or file itself.  Then if the objectInQuestion is a link and the calling argument
` options: Set[FileVisitOption]` contains the FileVisitOption `FOLLOW_LINKS`
do a second getFileAttributeView to get and use the information on the link target.
In this case, only, the visit will throw our NoSuchFileException.

I'll probably keep the try/catch just to give the filevisitor a hook.

So, I'' try this out after I have had some rest.

Interesting problem.

**Comment by sorenbug** [comment]
The native method should match the JVM method in terms of functionality correct?

**Comment by LeeTibbert** [comment]
I have a PR on the loading dock. Waiting until the light of day so that I can write a 
coherent commit message.

@sorenbug  This was a pretty neat bug. Thank you for reporting it.

Attempting to fix this issue  also revealed what I think is the exact same issue in Files.find().
 I'll open a separate issue for that.

**Comment by LeeTibbert** [comment]
`The native method should match the JVM method in terms of functionality correct?`
Exactly correct, to the best of my understanding.   In the PR I hope to submit tomorrow,
SN matches JVM 1-to-1.
