### ISSUE TITLE
Strategy for JVM / Java ByteCode Support Roadmap

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#136]
Many Scala libraries depend on Java libraries. Also some of these Java Libs may use internal APIs and  use Java reflection. There needs to a proper roadmap and strategy to support these type of projects and increase subset of Java which can be used from SN. So what are enhancements needed as well as issues to properly support Java Library dependencies on SN. As the identified issues are closed and enhancements are implemented, then any Scala library should become runnable on SN without modification.

**Comment by densh** [comment]
Running "any" Scala JVM library is out of scope for Scala Native. A subset of java core libraries is going to be supported, but we do not plan implementing all of them.
