### ISSUE TITLE
sbt-pgp can cause Scala Native to run in the JVM

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1382]
`sbt-pgp` plugins newer than 1.0.0 such as 1.1.1 when used with Scala Native 0.3.8 and sbt 0.13.17 cause the `sbt-scala-native` plugin to fail to call the normal build sequence and run natively.

An issue has been filed with a reproducer here. https://github.com/sbt/sbt-pgp/issues/149

This is not likely a Scala Native issue and there is a workaround if needed at the above link. This issue can be removed if the issue is fixed in `sbt-pgp`, in Scala Native, or if we wish to recommend only `sbt` 1.2.6 or later or abandon the `sbt` 0.13.x series.

**Comment by densh** [comment]
This issue is not actionable on our wide, if the sbt-pgp is fixed in the future, we may update to newer version.

**Comment by ekrich** [comment]
It is unclear at this point which plugin causes the problem using sbt `0.13.x` and was added so we don't lose the information if in the future we upgrade as it broke the build.
