### ISSUE TITLE
Unable to link sconfig due to missing Java classes

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1412]
I am currently working on getting the `lightbend/config` port, now `ekrich/sconfig` to compile under Scala Native and here is my current output. The goal is to support `scalafmt` on Scala Native.

I will look to see if any of these are internal details. The `java.time.Duration` class is part of the interface.

cc @olafurpg

List of items in the works for a possible `0.3.9` release. I will provide PRs once a branch is added.

- [x] Vector and Stack fixed by using `scala.collection.mutable.ArrayStack` in sconfig
- [x] Forwarders and `trait` additions
- [x] Adding `java.util.IdentityHashMap`
- [x] Adding tests for `IdentityHashMap`
- [x] Adding methods and ctor to `java.io.File`
- [x] Adding tests for `File`
- [x] Adding minimum `java.time` classes and methods
- [x] Adding tests for `java.time` additions
- [x] URL and URLConnection stubs

```
[IJ]sbt:sconfig-test> run
[info] Compiling 2 Scala sources to /Users/eric/workspace/sconfig-test/target/scala-2.11/classes ...
[info] Done compiling.
[info] Linking (2709 ms)
[error] cannot link: @java.io.File::init_java.net.URI
[error] cannot link: @java.io.File::toURI_java.net.URI
[error] cannot link: @java.lang.Class$::forName_java.lang.String_java.lang.Class
[error] cannot link: @java.lang.Class::getConstructor_scala.scalanative.runtime.ObjectArray_java.lang.reflect.Constructor
[error] cannot link: @java.lang.Class::getField_java.lang.String_java.lang.reflect.Field
[error] cannot link: @java.lang.ClassLoader::getResources_java.lang.String_java.util.Enumeration
[error] cannot link: @java.lang.ClassLoader::loadClass_java.lang.String_java.lang.Class
[error] cannot link: @java.lang.Thread::getContextClassLoader_java.lang.ClassLoader
[error] cannot link: @java.lang.reflect.Constructor::newInstance_scala.scalanative.runtime.ObjectArray_java.lang.Object
[error] cannot link: @java.net.URL::toExternalForm_java.lang.String
[error] cannot link: @java.net.URL::toURI_java.net.URI
[error] cannot link: @java.net.URLConnection::connect_unit
[error] cannot link: @java.net.URLConnection::getContentType_java.lang.String
[error] cannot link: @java.net.URLConnection::getInputStream_java.io.InputStream
[error] cannot link: @java.net.URLConnection::setRequestProperty_java.lang.String_java.lang.String_unit
[error] cannot link: @java.time.Duration
[error] cannot link: @java.time.Duration::toMillis_i64
[error] cannot link: @java.util.ArrayList::listIterator_i32_java.util.ListIterator
[error] cannot link: @java.util.IdentityHashMap
[error] cannot link: @java.util.IdentityHashMap::init
[error] cannot link: @java.util.List::containsAll_java.util.Collection_bool
[error] cannot link: @java.util.List::equals_java.lang.Object_bool
[error] cannot link: @java.util.List::hashCode_i32
[error] cannot link: @java.util.List::removeAll_java.util.Collection_bool
[error] cannot link: @java.util.List::remove_java.lang.Object_bool
[error] cannot link: @java.util.Properties::load_java.io.Reader_unit
[error] cannot link: @java.util.Stack
[error] cannot link: @java.util.Stack::init
[error] cannot link: @java.util.Stack::pop_java.lang.Object
[error] cannot link: @java.util.Stack::push_java.lang.Object_java.lang.Object
[error] cannot link: @java.util.Vector
[error] cannot link: @java.util.Vector::isEmpty_bool
[error] unable to link
```

**Comment by densh** [comment]
> URL and URLConnection and friends (huge)

Support those in SN is probably way more work that we can afford. It's better to use cross projects in a way that makes the URL-dependant parts of the code not be there on SN, but only on the JVM version of the library.

**Comment by densh** [comment]
Supporting URL, means having an HTTP implementation in the scala-native base library itself. I don't think it's something we can afford supporting at the moment. It seems to be a good place for 3-rd party library that can also provide a JDK-compatible API similarly to scala-java-time.

**Comment by ekrich** [comment]
I’ll look and see what makes sense. I think we can get minimal support maybe with just a few stubs.

**Comment by ekrich** [comment]
Solved.
