### ISSUE TITLE
SN 0.4-snapshot unit-tests fail in some or all Linux 4.19.* & 4.20-rc7 kernels

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1413]
#### Presenting problem:

```
Over the past six weeks or so I have been experiencing the problem below
when running test-all after building ScalaNative 0.4-snapshot on one of my
two build systems:

[info] * java.lang.ExceptionSuite$
[error] libunwind: decodeEHHdr /mnt/QuincyQHdd1/lee49/DevoHdd1/scala_native/Wor\
kSpace_1/BugHunt_SnLibunwind_Build_fresh_clone/unit-tests/target/scala-2.11/nat\
ive/lib/libunwind/EHHeaderParser.hpp:61 - Unsupported .eh_frame_hdr version
java.net.SocketException: Socket is closed
        at java.base/java.net.Socket.setSoTimeout(Socket.java:1137)
```

Debuging reveals that the .eh_frame_hdr version rightly being rejected is 127 (7 low bits of )
instead of the expected value of 1. That is, the exception frame appears bogus.
The EHHeaderParser code is doing its job!

### Details

This is a good one.  It has taken me six weeks or so to isolate what I believe to be the
cause (slow learner, slower debugger).

The problem occurred in newer of my two 'identical' (yeah, right!) build machines/environments.
Parsimony lead me to think that I had messed up creating  up the new build environment, ab initio.

A rapid reading of the message appears to indict Socket.setSoTimeout.  While I submitted
a SO_TIMEOUT PR which is still awaiting the fullness of time to be accepted, I believe the
obvious error is just noise from the testing environment once EHHeaderParser fails.

Debuging reveals that the .eh_frame_hdr version rightly being rejected is 127 (7 low bits of )
instead of the expected value of 1. That is, the exception frame appears bogus.
The EHHeaderParser code is doing its job!

Git bisect revealed that the presenting problem began occurring once I applied PR #1282.
 Yes, that is the obvious candidate, I but I wanted to rule out changes in later PRs, especially ones pertaining to the SN build environment;.

Both systems run lots of bleeding edge software: Javal  11, LLVM 7.0, lld-7.0, , Blk-Mq, BFQ I/O
scheduler. A long time exploring and considering "How is this night different than all others?" lead me
to a flash of inspiration that the failing system was running linux kernel 4.18.10 (and previous 
4.19.* versions)  while the successful 'identical' system was running linux 4.18.mumble.
When I booted up the Ubuntu 18.10 stock linux 4.18.mumble kernel on the recalcitrant machine,
test-all ran to completion.  

To probe the boundaries of the failure I am reporting, I downloaded & build linux 4.20-rc7.
The failure I am reporting began again.  I will try linux 4.20 after it is released tomorrow
and expect it to continue to fail.

### Analysis

From some extensive work I did debugging 32 bit libunwind a year or longer ago, I strongly
suspect that this is linux (ln.bfd) link order.  That is, a runtime issue, not an build issue
of bringing in the wrong .hmumble files.

I suspect that something in ld.bfd (or in the
kernel file system code which returns directory dirents) changed so that the symbol 
in #1292 which pulled in the llvm libunwind symbols from the scala native build tree
now comes later in the link order so that at least some symbols are resolved from
the build system. There may even be a mixture of libunwind symbols, some from 
Scala Native and some from the system C++ library.

I executed the unit tests using the "-v" verbose flag and looked at the revealed  OS link 
command. I did not see anything __obviously_ wrong or changed.  At that point
I ran out of time and decided to create this "Here Be Dragons!" note, to save others time/grief.

### Next steps

It will after the holidays before I am able to devote any time to exploring a fix for this issue.

I suggest a proper approach is to do a little bit of discussion, find out what additional
evidence or information is required , and then do one or more small, focused
engineering design/debugging code studies.

Since all this works in the SN reference environment, I think this issue should not hold back
or slow down the SN 0.4.0 release.  I would be nice thought if I/we could fix it before
or soon after SN 0.4.0.  Everything takes time & everything wants to happen at once!

#### Alternative:  Object code libraries.

 Relying upon a quick look and past, possibly wrong, experience, it looks like the link
 line relies upon the alphabetical order of the .o object files..  This has worked for the
 reference SN environment.  I suspect a more robust approach is to put all of the SN LLVM
 libunwind objs into its own .a file and use -l and -L flags to put that .a in the link line in a place where
 it   gets resolved before the exceptions in the C++. Some (special?) obj might need to be put on the
 link line to start the transitive symbol resolution from the .a.  

 A .a solution should work for the reference linux build environment. Travis would
ensure that.

 Dimly remembered lore has it that linking & resolving symbols from a .a archive
 is faster than a bunch of single files, once the number of .obj files gets past 3 or 4.

 In the past, I have had the fantasy of speeding up the ld.bfd by putting most/all
 of the object  files used by SN into an archive, then linking.  Linking with ld.gold
 or ld.lld or simply taking a walk for mental health and letting ld.bfd take its time all
 seemed faster & easier to implement.

  Of course, a .a solution is linux. At some point, the implications for a Windows build would
  need to be considered.

#### Alternative 2:  Use C++ system libraries on 64 bit linux

I could test out my suspicion that this is a runtime issue not a link issue by creating an engineering study of falling back to the SN 0.3.8 practice of linking with the system libunwind on some subset of systems where sufficiently new enough linux 64 bit systems where included in the set.
I believe the libunwind on most 64 bit linux distributions is reasonably good. 

It _might_ work to skip libunwind altogether on certain 64 bit systems and use the exceptions
provided by the C++ library.  SN already has C++ code so that would not introduce a build 
environment requirement.  I would have to convince myself (and others) that it did not
introduce a runtime dependency.

Either of these approaches  would leave SN running with different code on 32 & 64 bit system.
There might be  _many_ flavors of C++ exceptions or libunwind on the latter.

#### @shadaj, @densh, @all 
I'd appreciate your thoughts and/or direction, if you please or can
take the time.

 Thank you.

**Comment by LeeTibbert** [comment]
Update for today (2018-12-24) test-all after a fresh SN rebuild after each kernel switch
using <quote> same <un-quote> software other than kernel.

1. Linux 4.20.0 appears to work so far
2. Linux 4.19.12 (current/latest) continues to fail.

So the urgency of this issue goes down, but I believe that it should still be discussed and/or fixed.

1 - I understand, to some extent, the intent of Issue 1137 and the PR #1138. Is there some reason
    that  SN can not use the C++ native exception handling code, not as C++ but as API calls?
    I would   have to go back and study my private 32 bit work, but I seem to recall that worked just fine
   (on X86_32).  The OS supplied libunwind was borked (which is, I believe, why @shadaj ported LLVM
   libunwind to SN in the first place).  Using the C++ library calls would mean SN could day "If 
   exceptions work in a C++ program on your system, they should work with SN". That is a pretty
   powerful statement.  It does not     _solve_ all configuration problems, but it gives a good  
   configuration test/validation.

    Yes, this approach makes explicit a requirement for programs which _use_ excepti  ons to 
    have the proper C++ sharable on their system.  Since there is C++ code in SN already, the
    C++ library is probably already required.

2 - I think a good number of 64 bit distributions ship a reasonably correct libunwind.  Could the 
     system libunwind be used on "Known good" systems.  Punt the problem to the distributions.
     Yes, this means that somebody or bodies need expertise in both OS libunwind and the
     SN private LLVM code.  Again, this is probably necessary already.

3 - If the decision is to stay with the current SN LLVM on all distributions/architectures,
     what to folks think about herding the SN LLVMs into an object file (.a). The idea would
     be to put the .a in the os link command (ld.bfd, ld.gold, ld.lld) in such a place where
     libunwind symbols would be resolved from it rather than whatever is happening
     now in linux 4.19.12 et al. (I think they are being resolved from the OS libunwind.).
     This would make the build more robust to changes in file name or dirent order.

As of linux 4.20.0, I have enough to get me up and working on the PRs I need to 
garden, so I am not touching/investigating libunwind until receiving direction/guidance,
probably _well_ after the holidays.  


Cheers, 
Lee

**Comment by densh** [comment]
The reason we bundle libunwind is that we aim for having no dynamic dependencies for SN compiled binaries. This massively simplifies deployment as you don't need to worry about the DLL hell and possible library mismatches between dev and production environments.

**Comment by LeeTibbert** [comment]
Problem not seen with Linux 5.0 & nobody else complaining about 4.19, so I am closing this issue.
