### ISSUE TITLE
Enforce C formatting via clangfmt

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1415]
Currently we are unable to enable `clangfmt` (clang-format) during CI. This is due to the embedded `libunwind` that will not compile after being formatted via `clangfmt`. Once this is resolved, formatting could be enabled in the Travis build configuration.

**Comment by LeeTibbert** [comment]
@ekrich 

As a member of the peanut gallery, I concur that formatting C/C++ code written  for the
ScalaNative project  is worthwhile. See below for some concerns I have about how often it is done.

#### Foreign directories ####
From _painful_ experience with libunwind and from experience with my yet to be PR'ed 
pdqsort code, I would encourage that 'foreign' C/C++ code be left as-is and in the 
format native to the originating project.

Whatever is put in place should allow the exclusion of known 'foreign' directories, in
particular and **most specifically libunwind**.

Agreed, this introduces some code format inconsistency in the SN C/C++ code base
but the inconsistency rule is pretty easy to state and remember: strangely formatted
code probably originated elsewhere.

Trying to match up and find changes between foreign code formatted to S-N standards
and the original code causes a _lot_ of work. I question the benefit.  Re-ports and
bug fixes are hard enough.  libunwind is _hellacious_ to trace or attempt to 
understand.

#### Frequency of formatting & resource usage #### 
I also suggest that formatting relatively slow changing foreign directories at each CI run
is a total waste of resources, computer & human.  If I were writing the story, I would run
a separate batch program once a week which formatted S-N C/C++ code and another
no more often than once a month which formatted foreign code.

The 'on PR acceptance' CI runs will detect "real", i.e. compilaton & link, errors quickly.
Agreed, the detection of formatting errors will be delayed.  I believe that we can take
as a given that any C/C++ code which gets past review and the repository Gardian
is going to have at most trivial code format glitches, especially if the project 
encourages developers to run clangfmt before the PR is submitted (yeah, some
will not and some will forget).

And yes, I roundly curse code which does not follow (MY!) **One True Brace Style**.
I am __far__ more interested in CI completing in less than the half hour it currently
takes.

**Comment by ekrich** [comment]
@LeeTibbert I agree, but we are not formatting anything at this time and not enforcing anything either. My problem with `libunwind` not being formatted is that it is currently hard to read and the formatting problem is probably a malformed macro or `#ifdef` or `#ifndef`. Certainly, we could add stuff to the `clang-format` config file as well as choose the least offensive default option. I like `scalafmt` precisely because it takes the thought and churn out of the equation.

Including everything needed in Scala Native is a great idea but I'm not sure what will be done when `libunwind` for example needs upgrading. It probably should be upgraded based on the minimum clang/llvm version or something.

**Comment by ekrich** [comment]
The code `libunwind` comes with a `.clang-format` file so it should work but our `.clang-format` has a entry `Language: Cpp` so maybe that breaks stuff. We should maybe consider a minimum version of the LLVM stack, Clang, llvm, clang-format, and libunwind and use that internally. Example would be to pull http://llvm.org/svn/llvm-project/libunwind/branches/release_50/ if we wanted version 5.0 to be the minimum version. The advantage here is that as the LLVM stack adds new platforms etc. they could be possibly available to Scala Native.

**Comment by ekrich** [comment]
Closed via https://github.com/scala-native/scala-native/pull/2097
