### ISSUE TITLE
Consider dropping sbt 0.13.x support

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1416]
Removing sbt 0.13 has many benefits. 

1. Sbt 0.13 public support has been dropped - https://developer.lightbend.com/blog/2018-11-30-sbt-1-2-7-and-sbt-0-13-18/index.html
2. Reduce the number of CI combinations allowing new platforms or GC configurations.
3. Scala 2.10 would not be needed for the plugin or tools used by the plugin
4. Simplify the build
5. Make it easier to experiment with projects that use sbt 1.0 and a local publish of Scala Native as development of 0.4.0 progresses.
Added 1-9-2019
6. VSCode and Metals does not support Scala 2.10 but otherwise this might be a good tool set to use.

**Comment by sjrd** [comment]
Before doing that, you should carefully evaluate which important libraries from the ecosystem are still using sbt 0.13. Because none of those will then be able to support Scala Native. For example, ScalaTest is still using 0.13.17.

**Comment by ekrich** [comment]
Agreed. Info for Scala Test
Currently has experimental support. https://github.com/scalatest/scalatest/issues/1112
Issue for sbt 1.0 support. https://github.com/scalatest/scalatest/issues/1244

**Comment by densh** [comment]
It's probably a bit premature to remove sbt 0.13 support in 0.4. We can reconsider in future breaking (0.5+) releases but it should stay supported for the time being.

**Comment by ekrich** [comment]
@densh I thought if we are going to have a `0.3.9` release we could announce that the `0.3.x` series could be the last to support sbt `0.13.x`. To me the benefits for `0.4.0+` are much greater than any downside. We had quite a few thumbs up and other than the Scala Test question above (which are experimental releases) I'm not sure of any other downsides. Do you have any additional data points? Maybe we could have a poll or something?

**Comment by sjrd** [comment]
> My guess is if there's enough demand by their users, it'll do the necessary sbt 1 upgrade.

That's not how it works. Or at least not how it worked for Scala.js. For Scala.js, libraries started cross-compiling for real only once we made it *crystal easy* to cross-compile. It was 100% correlated with the first release of `crossProject`.

Core libraries have enough on their plate not to add effort because their users want support for a new platform. They'll do it if it's super easy to support the new platform.

**Comment by dwijnand** [comment]
Or they'll lose their users to a competitor that does.

Scala 2.10 and sbt 0.13 are ancient, I think a young project like Scala Native would probably do well and make good progress by removing the cost of maintaining legacy support.

**Comment by ekrich** [comment]
Also, Scala Test has upgraded on the `3.1.x` branch. https://github.com/scalatest/scalatest/commit/770d228c82cb303d1c8104d8597fb13f641992c7
