### ISSUE TITLE
Implement Array.copy

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#142]
Currently we don't have an implementation of array copying. Should be quite an easy task to contribute. 

/cc @fbertra

**Comment by fbertra** [comment]
I'll take a look

**Comment by fbertra** [comment]
Easy enough! I can contribute this one.

**Comment by densh** [comment]
@fbertra Looking forward to that!

**Comment by fbertra** [comment]
More TO-DO's than code, but this is the branch if anyone is interested.

https://github.com/fbertra/scala-native/tree/implement_array_copy

I may refer to it if/when asking questions.

**Comment by densh** [comment]
@fbertra Btw `Array.clone` is also stubbed at the moment. It's trivial to implement with `Array.copy`.

**Comment by densh** [comment]
@fbertra Feel free to post your to-do-s via github-style checklists here. 

- [ ] like
- [x] this
- [ ] one

**Comment by fbertra** [comment]
These are my high level to-do's

- [ ] Investigate array support on the JVM,
- [ ] Investigate runtime info in Scala-Native (infoof[T]),
- [ ] Define the behavior of Array.copy() for Scala-Native,
- [ ] Optional, look at Scala-JS for inspiration,
- [ ] Propose and implement solution,

**Comment by sjrd** [comment]
> Optional, look at Scala-JS for inspiration,

In case you do, do not believe [the source code of `System.arraycopy`](https://github.com/scala-js/scala-js/blob/v0.6.9/javalanglib/src/main/scala/java/lang/System.scala#L51). That method is an intrinsic, which [is hijacked by the optimizer](https://github.com/scala-js/scala-js/blob/v0.6.9/tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala#L1558-L1560). It is redirected to [the implementation in JavaScript](https://github.com/scala-js/scala-js/blob/v0.6.9/tools/scalajsenv.js#L503-L513).

**Comment by fbertra** [comment]
List of Java/Scala methods dealing with Array copy
--------------------------------------------------------------------

- java.lang.System::arraycopy (link from Apache Harmony) https://github.com/apache/harmony/blob/java6/classlib/modules/luni-kernel/src/main/java/java/lang/System.java

- object scala.Array::copy : https://github.com/scala/scala/blob/v2.11.8/src/library/scala/Array.scala

Called by scala.Array::copy

- object scala.compat.Platform::arraycopy (https://github.com/scala/scala/blob/v2.11.8/src/library/scala/compat/Platform.scala) -> java.lang.System::arraycopy

- object scala.Array::slowcopy

- object scala.runtime.ScalaRunTime::array_apply and ::array_update (https://github.com/scala/scala/blob/v2.11.8/src/library/scala/runtime/ScalaRunTime.scala)

- class java.lang.Class::isArray and ::isAssignableFrom

- trait scala.collection.GenTraversableOnce::copyToArray http://www.scala-lang.org/api/2.11.8/#scala.collection.GenTraversableOnce

The most relevant are java.lang.System::arraycopy and scala.Array::copy.  Others are candidate to be replaced or optimized (like GenTraversableOnce.copyToArray when the collection is an array).

**Comment by fbertra** [comment]
Zoom into java.lang.System::arraycopy and scala.Array::copy
----------------------------------------------------------------------------------

Both have the same method signature

```scala
  /** Copy one array to another.
   *  Equivalent to Java's
   *    `System.arraycopy(src, srcPos, dest, destPos, length)`,
   *  except that this also works for polymorphic and boxed arrays.
   *
   *  Note that the passed-in `dest` array will be modified by this call.
   *
   *  @param src the source array.
   *  @param srcPos  starting position in the source array.
   *  @param dest destination array.
   *  @param destPos starting position in the destination array.
   *  @param length the number of array elements to be copied.
   *
   *  @see `java.lang.System#arraycopy`
   */
  def copy(src: AnyRef, srcPos: Int, dest: AnyRef, destPos: Int, length: Int)
```

(copied from Apache Harmony, no GPL here!)

```java
   /**
     * Copies the number of {@code length} elements of the Array {@code src}
     * starting at the offset {@code srcPos} into the Array {@code dest} at
     * the position {@code destPos}.
     *
     * @param src
     *            the source array to copy the content.
     * @param srcPos
     *            the starting index of the content in {@code src}.
     * @param dest
     *            the destination array to copy the data into.
     * @param destPos
     *            the starting index for the copied content in {@code dest}.
     * @param length
     *            the number of elements of the {@code array1} content they have
     *            to be copied.
     */
    public static void arraycopy(Object src, int srcPos, Object dest, int destPos,
            int length) {
```

But, they behaves differently.  For example:

```scala
    val arrInt = new Array[Int] (2)
    for (c <- 0 until arrInt.length)  arrInt(c) = c
    val arrObj = new Array[Any] (2)    
    // scala.Array, will fill arrObj with java.lang.Integer instances
    scala.Array.copy (arrInt, 0, arrObj, 0, 2)
    // java.lang.system.arraycopy will throw an exception
    try {
      java.lang.System.arraycopy(arrInt, 0, arrObj, 0, 2)      
    }
    catch {
      case asex: java.lang.ArrayStoreException => {
        asex.printStackTrace
    }
```

So, @densh and everyone interested, here comes my first question.

Should we implement both behavior and just the one expected by scala.Array::copy() ?

I vote for the latter (scala.Array::copy only).

**Comment by fbertra** [comment]
Thanks @sjrd, I hope no compiler magic will be necessary for Scala-Native.  It would be way beyond my (current) skills!

**Comment by densh** [comment]
> Should we implement both behavior and just the one expected by scala.Array::copy() ?

Our goal is to have the same semantics of operations as normal Scala on JVM. We don't really want to do things *better* as that might cause compatibility problems when cross-compiling between different platforms.

**Comment by fbertra** [comment]
+1 for "having same semantics of operations as normal Scala on JVM".

My question was about how much support for Java semantics.  Implementing only the semantics of scala.Array::copy is actually worse for those who will migrate a existing Java API.  My feeling is that it isn't so much worse, because the contract of scala.Array::copy is better than the one of java.lang.System::arraycopy.

I propose the following implementation strategy:

1- Implement a more typesafe contract

```scala
def copy [T, U >: T] (src: Array[T], srcFrom: Int, dest: Array[U], destFrom : Int, len: Int)
```

I think it's possible with actual version of Scala-Native compiler and libraries.

2- Implement the same contract of scala.Array::copy on the JVM

```scala
def copy(src: AnyRef, srcPos: Int, dest: AnyRef, destPos: Int, length: Int)
```

I'm almost sure that I will need more runtime type information: specifically, the type parameter T in Array[T].

3- Optional: implement java.lang.System::arraycopy with contract expected by Java API.

**Comment by fbertra** [comment]
A Scala-IDE application to test the scala.Array::copy behavior on the JVM and see how it differs with java.lang.System::arraycopy()

https://github.com/fbertra/sj-array/blob/master/src/cl/fbd/Main.scala

The unfortunate part is when Scala behaves exactly like Java.  The testBUndercoverAsAnyToA() and testAnyToA() methods demonstrate that, when copying from a non primitive array `src` to other non primitive array `dest`, the JVM checks if every element of `src` is assignable to `dest`. 

```scala
class A (i : Int) {
  override def toString () = "A: i = " + i  
}
class B (i: Int, d: Double) extends A(i) {
  override def toString () = "B: i = " + i + ", d = " + d  
} 

def testBUndercoverAsAnyToA () = {
    val arrA = new Array[A] (2)
    val arrAnyFilledWithBs = new Array[Any] (2)
    
    // array of Any but every element is of type B and assignable to A
    arrAnyFilledWithBs(0) = new B(1, 1.0)
    arrAnyFilledWithBs(1) = new B(2, 2.0)
    
    println ("")
    
    println ("Array[Any] filled with elements of type [B >: A]  -> Array[A]")
      
    println ("Fast version of Array.copy?: " + ifInsideScalaArrayCopy (arrAnyFilledWithBs, arrA))
    
    println ("scala.Array::copy")
            
    scala.Array.copy (arrAnyFilledWithBs, 0, arrA, 0, 2)
      
    dump (arrA)
    
    println ("java.lang.System::arraycopy")
      
    java.lang.System.arraycopy(arrAnyFilledWithBs, 0, arrA, 0, 2)
      
    dump (arrA)
  }
  
  def testAnyToA () = {
    val arrA = new Array[A] (2)
    val arrAny = new Array[Any] (2)
    
    // array of Any with one element of type B (assignable to A) and other of type String (not assignable to A)
    arrAny(0) = new B(1, 1.0)
    arrAny(1) = new String ("I'm not assignable to A")
    
    println ("")
    
    println ("Array[Any] -> Array[A]")
      
    println ("Fast version of Array.copy?: " + ifInsideScalaArrayCopy (arrAny, arrA))
    
    println ("scala.Array::copy")
     
    try {
      scala.Array.copy (arrAny, 0, arrA, 0, 2)
      
      dump (arrA)
    }
    catch {
      case asex: java.lang.ArrayStoreException => {
        println ("This is ok in Scala but unfortunate: " + asex.getClass().getName() + ": " + asex.getMessage())
      }
   }  
```

To implement the same semantics on scala-native, it will be necessary to receive the type parameter when allocating the array. Maybe by receiving a second parameter in `scala.scalanative.runtime.<Type>Array::alloc(length: Int)`. But how to deal with the case of fixed size arrays allocated in the stack?

**Comment by fbertra** [comment]
Please refer to the latest version of https://github.com/fbertra/scala-native/blob/implement_array_copy/nativelib/src/main/scala/scala/scalanative/runtime/Arrays.scala to see what's possible, IMO, without change in the compiler.

object Array implements various `arracopy()` methods

- `def arraycopy [T, U >: T] (src: scala.Array[T], srcPos: Int, dest: scala.Array[U], destPos : Int, length: Int)`

- `def arraycopy (src: scala.Array[Int], srcPos: Int, dest: scala.Array[java.lang.Integer], destPos : Int, length: Int)`

- `def arraycopy (src: scala.Array[java.lang.Integer], srcPos: Int, dest: scala.Array[Int], destPos : Int, length: Int)`

The last two methods for every primitives types.

It does cover the most frequent use cases, always using `Int` as an example of primitive type:
- array primitive to array primitive (`Array[Int]` to `Array[Int]`),
- array primitive to array superclass (`Array[Int]` to `Array[Any]`),
- array primitive to array boxed type (`Array[Int]` to `Array[java.lang.Integer]`), 
- array boxed type to array primitive (`Array[java.lang.Integer]]` to `Array[Int]`), 
- array object to array object superclass  (`Array[B]` to `Array[A >: B]`)

Wherever possible, the methods try to call the most efficient memory copy (LLVM memcpy).

It does not cover the case mentioned on my previous post: a copy from an `Array[Any]` filled with instances of `B` to an `Array[A >: B]`

And it does not implement `def copy (src: AnyRef, srcPos: Int, dest: AnyRef, destPos: Int, length: Int): Unit`, which is callable from `scala.Array::copy` and `java.lang.System::arraycopy`.

To implement what's missing, I propose the following:
- store the `infoof[T]` in the array header `@struct class ArrayHeader(val info: Ptr[_], val infoElement: Ptr[_], val length: Int)` where T is the type parameter in `new Array[T]`,
- receive `infoof[T]` as a second parameter of method `object ObjectArray def alloc(length: Int, infoElement: Ptr[_])` (note: it makes sense to do the same for primitive arrays, see note 2)
- In `Array::copy (src: AnyRef, srcPos: Int, dest: AnyRef, destPos: Int, length: Int)`, use this runtime type information to determine if one of the above helper method is callable.  If not, copy element by element validating if the `from` element is assignable to the `dest` element

Notes: 
1- it will be necessary to implement something equivalent to the `java.lang.Class::isAssignbleFrom` method with information available from `infoof[T]`,
2- in the future, arrays of Value Class, like `class Wrapper(val underlying: Int) extends AnyVal`, could/should be implemented as primitive arrays. The semantics of copying this `Wrapper` class from/to an `Array[Int]` isn't defined AFAIK (this problem don't exist on the JVM).
3- I don't pretend that the code I shared is ready for any Pull Request.  I need to clean up and implement the overlap case, at least.

I can take a look at the compiler and try to solve this by myself.  But this is new territory to me, so I may have a lot of questions and it may take longer

**Comment by densh** [comment]
@fbertra Thanks a lot for the exploration of the problem space, you've did a great job here. I've really underestimated complexity of this issue.

For now I think we should do the following simplified implementation of copy: if two array types are the same (e.g. both `IntArray`), do a memcpy, otherwise throw ArrayStoreException. This should be good enough to unblock #150 and implement clone. 

Once initial version is merged I'll do necessary compiler changes to fully support java-style `ArrayStoreException` around object arrays. As you correctly pointed out we'll need to additionally store runtime info for element types here. This part is quite involved.

**Comment by fbertra** [comment]
OK, I have a new branch to implement this simplified semantics for copy

https://github.com/fbertra/scala-native/blob/implement_array_clone_basic_copy/nativelib/src/main/scala/scala/scalanative/runtime/Arrays.scala

It lacks some tests, but I think it is almost done.

Note 1: I have refactored Arrays.scala to avoid code logic duplication using standard OOP.  There's still text duplication between the different `PrimitiveArray` classes and objects, but personally I prefer that to using the pre-processor.  

Note 2: I'm comparing types using the id return by the helper methods:

```scala
  private def typeId (ptrInfo : Ptr[_]) : Int = {
    val ptr = ptrInfo.cast[Ptr[Ptr[Type]]]    
    (!(!ptr)).id    
  }

  private def instanceTypeId (any : AnyRef) : Int = {
    val ptr = any.cast[Ptr[Ptr[Ptr[Type]]]]    
    (!(!(!ptr))).id    
  }

```

**Comment by densh** [comment]
Let's merge this!

**Comment by densh** [comment]
@fbertra You should open a pr for that, we'll discuss the details over there.

**Comment by densh** [comment]
@fbertra Generally it seems to be quite close ready as far as I can tell.

**Comment by fbertra** [comment]
@densh, this is my todo's before PR

- [ ] merge from master -> change the logic for type equality,
- [ ] test the overlap cases,
- [ ] calls the copy() method from java.lang.System::arraycopy and scala.Array::copy

**Comment by fbertra** [comment]
PR opened: https://github.com/scala-native/scala-native/pull/184

**Comment by densh** [comment]
As far basic functionality is concerned this is done. Thanks @fbertra!
