### ISSUE TITLE
Cache instances of java.lang.Class

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1435]
Currently we don't cache instances of `java.lang.Class`, which means two instances which correspond to the same type might not compare equals in term of reference identity and `java.lang.System.identityHashCode`. This is inconsistent with the behavior on the JVM.

**Comment by sjrd** [comment]
Fixing this requires breaking binary compat, because the compiler back-end already emits instantiations of `j.l.Class`, so it assumes it can do that. But for fixing this we must make that illegal at the NIR level, leaving the allocations for the linker to handle.

**Comment by sjrd** [comment]
We should represent `Class` literals as actual *literals* in NIR to properly fix this.
