### ISSUE TITLE
Add sbt command for linking only

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#144]
Currently to get a native artifact one has to call `run` in sbt. It compiles code all the way down to native code and then runs the generated binary. We need a command to just compile the code, without running (e.g. `nativeLink`).

**Comment by fbertra** [comment]
Please note that when the "nativeLink" part in "sbt run" fails, it doesn't delete the target/scala-2.11/${PROJECT_NAME}-out executable file and "sbt run" runs the last successful executable version.
