### ISSUE TITLE
Locale is unsupported, causing FormatterSuite.scala test(s) to fail

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1443]
This is entry reports essentially the same issue as #1038 but in a more concise manner.

There is an individual test in FormatterSuite.scala "" which is correctly marked "testFails".
The test is: 
```
testFails(
    "format(String, Array[Object]) for Float/Double conversion type 'e' and 'E'",
    1296) {
```
I am currently working on a, currently unnumbered, successor to PR #1296.   
After that successor PR is accepted, the test in question will still fail, but for a different reason.

This issue gives me a tracking number I can put into the testFails() description and which
points to a boiled down description of what is causing the problem.  My hope is to 
isolate and capture the solution, so that some future developer, perhaps me, does not waste precious 
time re-creating context.

```
After the successor to PR #1296 is accepted, this test will fail because it uses
 LOCALE.German__ at the bottom of the test and LOCALE.German (and Locale support
in general ) is not implemented in SN.   
```
The US Locale only FormatterUSSuite.scala does not have the LOCALE.German test.
The strictly numeric parts of the test pass in #1296 and should pass in its successors.

**Comment by WojciechMazur** [comment]
`java.text` package including `Locale` was removed in #2079. Also
