### ISSUE TITLE
Cannot Link java.lang.Thread::init

### ISSUE THREAD

**Issue by am431** [scala-native/scala-native#1453]
Trying to run shell command, it fails to link.
```
object Main extends App{
  import scala.sys.process._
  args(0).!
}
```
```
sbt run
--
[error] cannot link: @java.lang.Thread::init
[error] cannot link: @java.lang.Thread::join_unit
[error] cannot link: @java.lang.Thread::start_unit
[error] unable to link
[error] (Compile / nativeLink) unable to link
```

**Comment by amitmh** [comment]
This is on OSX.

**Comment by densh** [comment]
`scala.sys.process` uses multithreading and we don't support it at the moment. You should follow #101 for updates on that front.

You can run subprocess using underlying Java's process API which we do support.
