### ISSUE TITLE
Add a release mode variant that optimizes for size

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1460]
Currently our optimizer is having runtime performance as the only objective. For some applications where binary size is an issue we could introduce an alternative mode that:

- [x] does no method duplication
- [x] does less inlining
- [x] runs LLVM with -Os by default

Additionally we could also experiment with changing vtables and dispatch tables geared towards binary size rather than runtime performance.

**Comment by LeeTibbert** [comment]
A possible 1+

Does SN support  `-Xelide-below ARG`?  That would be a good way to allow defensive
programming of assert() in debug which drops out for release.  Either in implementation
of the low-binary release mode or as a documented option end developers can pass in.

I found myself writing myself writing some code that wanted assert()s but begrudging
the binary size and execution cost in release mode.  Always a discussion about how much
checking & performace tracing code one leaves in a production ultimate end user binary

**Comment by LeeTibbert** [comment]
Understood that -X means that it might go away in future Scala versions. I have used it a bit
and it is pretty handy.  Benefit depends upon how many asserts & other code can be elided
with a setting below ERROR or FATAL (concepts, may not be actual names).

**Comment by densh** [comment]
Initial implementation in #1545

**Comment by densh** [comment]
@LeeTibbert eliding asserts is probably a separate "feature" independent of optimize for size mode itself.

**Comment by densh** [comment]
Fixed in #1545 by splitting release mode into `release-fast` (fast compilation speed, better code size) and `release-full` (slow compilation speed, better runtime perf).
