### ISSUE TITLE
Add support for finalizers

### ISSUE THREAD

**Issue by DarkDimius** [scala-native/scala-native#147]
Apparently BoehmGC has some hooks that would allow implementing finalisers.

**Comment by densh** [comment]
Even though we don't call finalizers at the moment we're JVM-compatible semantics-wise as they are not guaranteed to be run at all.

**Comment by densh** [comment]
This is blocked by https://github.com/scala-native/scala-native/issues/36

**Comment by densh** [comment]
Finalizers have been deprecated in Java 9, and thus we are not going to support them.
