### ISSUE TITLE
Enforce extern methods define their return type

### ISSUE THREAD

**Issue by fbertra** [scala-native/scala-native#148]
The following method don't define its return type.

```scala
@extern
object Intrinsics { 
  def `llvm.memset.p0i8.i32`(dest: Ptr[Byte],
                             value: Byte,
                             len: Int,
                             align: Int,
                             isvolatile: Boolean) /* : Unit */ = extern
}
```

Compiler and linker won't detect it.  Execution will raise a `Segmentation fault (core dumped)`

Please see https://github.com/fbertra/sn-test-enforce_return_type_on_extern for a test case and more information (the generated LL file contains a "unreachable" instruction)

**Comment by sjrd** [comment]
FTR, this is how Scala.js does it:
https://github.com/scala-js/scala-js/blob/c51ce4ca53f70e300d2f99d40654aefec2ef97af/compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala#L828-L835

**Comment by densh** [comment]
Superseded by #317.
