### ISSUE TITLE
StringSuite should exercise codePointBefore last position with Unicode

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1481]
StringSuite needs a series of tests to exercise codePointBefore. The handling
of 'one off the end of the string' is particularly tricky here.  The hypothetical
code should test at least
* index one beyond size of string with single byte final character
* ibid. with final character a singleton high member of a Unicode surrogate pair
* ibid. with final two characters a valid Unicode surrogate pair.

String.codePointAt and codePointCount would also benefit from having
some tests, especially of Unicode surrogates (did you hear that codePointCount?)

**Comment by LeeTibbert** [comment]
I did not fix these in my current work on Issue #1479 to keep the PR review trail
clean (and to stay on task).

**Comment by ekrich** [comment]
When I added `toUpperCase` I added a `CharacterSuite` as we didn't have one. We perhaps should have ported what was available from `scala-js/scala-js` as that is where a lot of tests came from. Maybe we need this? https://github.com/scala-js/scala-js/blob/bbf3629faedb59a260d39f961bc75b31ff3821a9/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lang/CharacterTest.scala

**Comment by LeeTibbert** [comment]
I believe that recently merged PR #1883 by @WojciechMazur resolves this issue. Thank you Wojcieck.
