### ISSUE TITLE
All unimplemented routines (???) in javalib need stub annotation

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1487]
On Gitter @densh suggested that all unimplemented routines, that is, those whose
implementation is ???, should be given a `@stub` annotation before 0.4.0. 

There are four files where the SN unit and scripted tests expect to be able to link
with unimplemented routines but never call them.  The other places where I added
`@stub` work fine.
 
Formatter seems to be always being brought in. The unused calls are not optimized away,
so the linker expects to be able to resolve them.

Adding nativeLinkStubs to the SN build.sbt is one possibility.  It looks like that needs to happen in at least two places.  With reasonable effort, I have not been able to find the second place.
Sure, I could hack around, but that would make life difficult the person who tries to revert the
change. 

I believe it would be more friendly to application developers to not propagate the SN implementation
infelicity of requiring them to use linkNativeStubs.  That can be done by providing
minimal implementations of routines in four files. These files will need at least a
minimal implementation someday, better to do it now, when we can plan the effort.

Anyone currently calling the unimplemented routines in these files gets an exception,
so even a minimal implementation will be better than that. I have started the PR parade and
hope they will be accepted. 

- [X] java.util.regex.Matcher, see issue #1518 
- [  ] java.util.Calendar - restrict to Gregorian, & probably only routines used by Formatter.scala.
- [  ] java.util.TimeZone - probably restrict to UTC/GMT, at least for first pass.
- [  ] java.text.DateFormatSymbol - restrict to US symbols

**Comment by LeeTibbert** [comment]
@densh 

I took a run at  fixing this issue.  In my sandbox, `rebuild` went well but `test-all` could not link
because of symbols  in four obscure files.  Those symbols had just been converted to `@stub` 
and unit-tests, at least runs with `nativeLinkStubs` as false, so the linker was exactly correct.

At a high level, looks like the current mainline tests expect to link with the routine but
never actually executes them. 

I can either 
    * add `nativeLInkStubs := true` to `unit-tests` or `test-all`

   *  revert the `@stub` from those four files. This introduces an inconsistency, but I could
      document, at each commented out `@stub` that the annotation can not be there.

   * examine the tests in detail to see if their linking  to a known unimplemented method
     makes sense in the long run. The call chain could get pretty messy.

Please advise, as your time allows.  Thank you.

FYI:
```
java.util.Calendar 
java.util.TimeZone
java.util.regex.Matcher
ava.text.DateFormatSymbol
```

**Comment by LeeTibbert** [comment]
Later:  The `@stub` in DateFormatSymbol prevents my linking in an entirely different project.
One with no obvious call to DateFormatSymbol.  Obviously the linker found a relationship.

Looks to me like it would be user hostile to enforce `@stub` there. 

I will see what more wall clock experience brings.

**Comment by densh** [comment]
@LeeTibbert You can link stubs with`nativeLinkStubs := true`. Users should get errors by default if they transitively depend on unimplemented parts of javalib.
