### ISSUE TITLE
Bad values in Strings created from constants with Unicode high surrogate characters.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1496]
This is an issue discovered whilst attempting to port re2s to SN. Specifically, it
was revealed by a new test for Character.charAt() in CharacterSuite.scala.

SN 0.4.0-Snapshot appears to mangle strings containing Unicode high surrogate characters.
That is given a declaration of the form ` val str1 = "eo\uDBFFl"` (last value is an ell) 
 the value at index 2 is the expected 56319 in Scala JVM and the, I believe, incorrect
63 in SN.  

I was really testing high surrogates at the end of the line, but this  is a better example.

This may be a specific case of a more general problem.

I believe the problem is in the conversion of the string to array values, that is, the load,
not the reading of the array locations.,  When I manually load the location with
the expected value, all proceeds in SN as expected.

Strings containing 'normal' unicode, such as the euro-sign, seem to be handled OK.

I have not dived into the code to try to figure out where the problem may lie.
I would probably start looking at constructors for String(). (Duh!)

I am using bleeding edge SN, so this may be a transient.

JVM behavior:
```
scala>   val str1 = "eo\uDBFFl" 
str1: String = eo?l
scala> str1(0)
res0: Char = e
scala> str1(1)
res1: Char = o
scala> str1(2)
res2: Char = ?
scala> str1(2).toInt
res3: Int = 56319    // <<< LeeT this is the expected value
scala> str1(3).toInt
res4: Int = 108

```
SN behavior:
```
 LeeT Debug 3: codePointAt. seq(0) is e
[info] LeeT Debug 3: codePointAt. seq(1) is o
[info] LeeT Debug 3: codePointAt. seq(2) is ?
[info] LeeT Debug 3: codePointAt. seq(3) is l
[info] 
[info] LeeT Debug 3: codePointAt. index: 2  is 63
[info] LeeT Debug 3: codePointAt. limit  is 4
[info] LeeT Debug 3: codePointAt. seq.length is 4

```

**Comment by densh** [comment]
Thanks for the bug report!

**Comment by LeeTibbert** [comment]
Note to future self:  Tests where the creation string contains a valid surrogate pair instead of just
a singleton high surrogate seem to work as expected.

My mama told me that there would be days like this if I did not heed her!

**Comment by LeeTibbert** [comment]
Note to future self:  When this is fixed, change two testFails() in CharacterSuite.scala

**Comment by sjrd** [comment]
String literals are currently represented as `j.l.String` in the NIR in memory, but they are serialized/deserialized as UTF-8 in .nir files. This format cannot represent unpaired surrogates, so this is a blocker.
