### ISSUE TITLE
Full scala collections support

### ISSUE THREAD

**Issue by fbertra** [scala-native/scala-native#150]
This is an umbrella issue for tracking support of Scala collections.

Current state
-----------------

- Scala collections code do compile (the whole scala-library do)

- Most methods do not run due to issue https://github.com/scala-native/scala-native/issues/6 "Add support for traits in compiler".  For example:

```scala
for (i <- 1 to 10)
      fprintf (stdout, c"%d\n", i)
```

generates the following stack trace

```
sbt run
scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
        at scala.scalanative.compiler.pass.TraitLowering$$anonfun$preInst$1.applyOrElse(TraitLowering.scala:59)
        at scala.scalanative.compiler.pass.TraitLowering$$anonfun$preInst$1.applyOrElse(TraitLowering.scala:57)
        at scala.scalanative.nir.Pass$class.scala$scalanative$nir$Pass$$hook(Pass.scala:35)
```

- Some methods are missing like in issue: https://github.com/scala-native/scala-native/issues/142 Implement Array.copy.

- scalalib regression tests have never been run due to issue https://github.com/scala-native/scala-native/issues/28 Port partest integration from scala-js.

Please correct any errors.

**Comment by densh** [comment]
This is accurate state of things. Trait support in the compiler is the main blocker at the moment.

**Comment by densh** [comment]
@fbertra Your for loop example already works in https://github.com/scala-native/scala-native/pull/171

**Comment by densh** [comment]
Initial support for collections has just been merged. If you have any issues remaining in this area, feel free to file more specific actionable issues.
