### ISSUE TITLE
Possible clang-8 sbt 1.2.6 release mode issue with ProcessSuite & java_net_socket

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1502]
I am in the midst of a complicated merge right now and can not run this to ground properly.
I am raising a "Heads Up!" in case anybody else encounters the issue.

I am seeing at least one failure in ProcessSuite, presumably sometime after the
test "waitFor with timeout completes".  The failure is 100% reproducible.
This happens with sbt 1.2.6 in release mode. I believe that I have also seen it with 0.13.7 release mode.  It has not happened for me with either version with Debug mode.

This may be an issue with clang-8. I switched to it a day or so age.  I suspect
that it has more to do with recent release mode PRs.

I seem to remember PR #1485 working (with clang-7). It is broken for me at
PR #1495 (with clang-8).  It may have broken in the intervening PRs.

I suspect the ProcessBuilder .isAlive call but have no evidence.

I'll try to narrow this down (and eliminate clang-8) sometime in the next few days.
Each iteration takes an hour.

Please let me know if you need additional details to replicate.

**Comment by LeeTibbert** [comment]
This is the failing test, with the suspect line commented out.

```
  addTest("waitFor with timeout times out") {
    val proc = new ProcessBuilder("sleep", ".005").start()
    assert(!proc.waitFor(1, TimeUnit.MILLISECONDS))
    assert(proc.isAlive)
//    proc.waitFor(1, TimeUnit.SECONDS)                                         
  }
```
There may or may not be a problem with release mode and there may or may not be
issues with changed timing. I have a full test-all running in he background. to discover more.

At the very least, the commented out line above is suspect in any world.  I hope the isAlive() implementation would be robust to the process having completed already. I have not taken
the detour to study that code.

The waitFor() calls for a 1 Millisecond wait. In most wait code with which I am familiar that means
at least 1 Millisecond, possibly more.  Since the sleep was for 0.005 seconds, there is a 
chance that the process has completed before the isAlive() executes. Can you say 'race condition'.
The assumption that the process is alive appears specious.

Now, even if the process was alive when tested, it may well have completed before the second
waitFor executes, causing that second call to complain about a closed socket.

I think the solution for the second waitFor is to put it in a Try/catch and ignore errors.  Better yet,
delete it and leave a comment that the the test is letting the process die a natural death.
Simple is better.  The second waitFor adds no value.

I think a partial solution for the isAlive issue is to increase the amount of time the process
sleeps to, say 1 or, better, 2 seconds and add a comment about the race condition.

**Comment by LeeTibbert** [comment]
Ok, I think I have caught one of at least two tigers  by the toe.
I suspect a code generation bug (or a blatant mistake on my part).

Using SN up to date to git `Interflow: bring back inlining to debug mode (#1505)`.

There is code in ProcessSuite which runs in Debug mode and fails (silently blows up test rig with
exception and misleading noise about socket closed.)

Skipping discussions about the race conditions in the code, the code which fails is:
```
 addTest("waitFor with timeout times out") {
    val proc = new ProcessBuilder("sleep", ".005").start()
    assert(!proc.waitFor(1, TimeUnit.MILLISECONDS))
    assert(proc.isAlive)
    proc.waitFor(1, TimeUnit.SECONDS)
  }

```  
The failing line is the `assert(!proc.waitFor(1, TimeUnit.MILLISECONDS))`

Change that one line to what should be equivalent suceeds:
```
    val result = proc.waitFor(1, TimeUnit.MILLISECONDS)
    assert(!result,
           s"proc.waitFor Milliseconds result: $result expected: not-0")

```
I have not tried the assert without a message. I also have not tracked down the  out.ll file
to see what gets generated in each case.

There are two pending Interflow PRs. I will try again after they are merged & report back.

**Comment by LeeTibbert** [comment]
Ok, I think I have caught one of at least two tigers  by the toe.
I suspect a code generation bug (or a blatant mistake on my part).

Using SN up to date to git `Interflow: bring back inlining to debug mode (#1505)`.

There is code in ProcessSuite which runs in Debug mode and fails (silently blows up test rig with
exception and misleading noise about socket closed.)

Skipping discussions about the race conditions in the code, the code which fails is:
```
 addTest("waitFor with timeout times out") {
    val proc = new ProcessBuilder("sleep", ".005").start()
    assert(!proc.waitFor(1, TimeUnit.MILLISECONDS))
    assert(proc.isAlive)
    proc.waitFor(1, TimeUnit.SECONDS)
  }

```  
The failing line is the `assert(!proc.waitFor(1, TimeUnit.MILLISECONDS))`

Change that one line to what should be equivalent suceeds:
```
    val result = proc.waitFor(1, TimeUnit.MILLISECONDS)
    assert(!result,
           s"proc.waitFor Milliseconds result: $result expected: not-0")

```
I have not tried the assert without a message. I also have not tracked down the  out.ll file
to see what gets generated in each case.

There are two pending Interflow PRs. I will try again after they are merged & report back.

**Comment by LeeTibbert** [comment]
Looks like clang-8 is the culprit.  Arrgh!

I removed clang-8 & friends, reverting to the clang-7 that has been working for months.
Deleted ~/.ivy2/local, and rebooted.

Did a clean rebuild using sbt 1.2.6 in release mode, then a test-all in release mode.
All tests other than the known broken  on 1.2.6 link-order pass.

Next sprint I plan to restore clang-8 and see if the Process & java_net_socket
breakage comes back.

**Comment by densh** [comment]
@LeeTibbert has this been fixed in #1515 ?

**Comment by LeeTibbert** [comment]
@densh  To the best of my knowledge no.  You are right that they are related.

 #1515 fixes an issue discovered while trying to fix this issue but does not directly address this issue.  
I left a comment about a possible race condition in #1515 to help future developers, probably me in a 
month's time but did not change the test.  I left it on a hair trigger to see if I could provoke this issue.

After study and trying several things, I believe this issue results from a bug in Clang-8.  I think
the images published on apt.llvm.org are missing one or more last minute fixes.  Ubuntu 19.04
is about three weeks away. My plan had been to install the Clang-8 package from that distribution
and try again.

Although I have an Engineer's itch to fix things that are broken, I know the first question if I try to
define the Clang compiler issue well enough to report it is going to be "Are you running the
final release version". 

Ubuntu 19.04 has gone to beta in the past few days.  If there is some urgency on this issue,
I could install that beta and try again.  Please advise.

If Clang-8 works with 19.04 a release note stating that the 'final' version of Clang-8 is the
only one supported.  If Clang-8 still fails, I can revert its autodiscovery.

**Comment by LeeTibbert** [comment]
I have been exercising the version of Clang-8 in Ubuntu 19.04 pretty heavily for 4 or 5 days
now and it looks like this is fixed in Clang-8.

I had to fuss around in SBT 'last' to convince myself that clang-8 was actually being used.

I have not checked either binary size or execution speed.

So, the summary for Institutional Memory:  There was a window after clang-8 was
officially announced where the Ubuntu packages, at least, on llvm.org displayed
the problem reported.  The images now on llvm.org look like they were built two
weeks after the release announcement, so they ought to be good.

And here I was, think that by waiting until the release was annunced, I was safe in the second
 echelon and not on the Bleeding Edge.
 
I hope no one else encounters this problem.

**Comment by onilton** [comment]
I can confirm I was having a similar issue in 16.04, but after I updated the clang-8, it was fixed :) :+1:
