### ISSUE TITLE
j.l.OutOfMemoryError compiling unit-tests in release mode with recent optimizer.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1525]
Start in the past few days, perhaps today, when I attempt to run unit-tests in release mode
after about an hour I get:
`java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space`

Now the obvious answers are

* Do not use release mode ;-)

* Figure out how to increase the JVM memory, probably in the unit-test settings
  in the project root build.sbt.  I think the scripted-tests setting does something
  similar to what I want/need.  I'll just have to figure out the math for `gigantic heap`.

Thought I would create this issue as a heads up in case anyone else experiences this
problem.

**Comment by densh** [comment]
I believe that this one is non-issue. `release-full` uses a lot of memory and you need to be aware of it. You can now also use `release-fast` which is much less resource intensive.
