### ISSUE TITLE
Travis CI having problems with too many unit-test Suites

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1528]
I am creating this issue in case someone else has problems adding unit-test
Suites to Travis CI.  We may be approaching a tipping point.

Looks like I am seeing another instance of the issue reported by @shadaj in #1008 "too many unit-tests".  I am seeing this in my re2s WIP PR #1498. 

@ekrich, Just an FYI because I think you had an interest in the original issue.

Basically I am trying to add a set of N unit-test suites and have them executed
by Travis CI.  The tests run as an ensemble of N in my build environment, nothing
special done to increase memory.

In the Travis environment, I get j-random failures in seemingly unrelated places 
when I try to execute the full N re2s Suites.   If I pick N - 2 of the Suites, they
and all other unit-tests execute as expected.  I have tried two sets of N - 2, where the
2 left out run if they are included in the N - 2 with two other tests factored out of the set.

Looks to me like the test-runner is creating one or more child processes and executing
Suites in parallel.  It looks like when one of the child processes dies in the void, 
errors can get reported against some other Suite or worse.

I suspect an OutOfMemory condition or such in the child process trying to run the full N
re2s suites, even in Debug mode.  I am not sure if it is the number of Suites or 
the amount of data in the Suites or some combination of the two.

For now I am weaseling out and just enabling N - 2 of the re2s suites on Travis and
focusing on re2s issues, rather than test-runner issues.   Perhaps someday I will
take a look at the test runner environment to see if I can figure out what is going 
wrong.

**Comment by LeeTibbert** [comment]
@densh I suspect that some memory limits on Travis may need to be raised to deal with recent
compiler changes in memory usage.

**Comment by densh** [comment]
@LeeTibbert Yep I noticed that as well in #1475, we need to bump it.

**Comment by densh** [comment]
Fixed in #1582
