### ISSUE TITLE
NIO Files.find may be incorrectly trying to follow file symlinks.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1532]
Whackamole with NIO Files.*!

I am not sure if I saw this or not so so I will put it on the work stack and get on
with more pressing issues.  

It may be a will-o'-the-wisp, but I think I saw Files.find try to follow a file symlink
when FVO.FOLLOW_LINKS was true. It threw an exception about the file not
being a directory.     Looks to me like Files.find needs to look before it leaps;
that is before chasing a symlink, check that it is a directory.

I have not had the chance to confirm either the original sighting or check
the Scala JVM behavior.  Perhaps some long Summer afternoon when my
favorite sports team is losing.

**Comment by densh** [comment]
@LeeTibbert Any chance this was fixed in either #1531 or #1533 ?

**Comment by LeeTibbert** [comment]
I wrote a test case based on FilesSuite.scala and could not replicate the initial report.

While I would love to take credit for fixing it, I believe it more likely a false positive in the
first place.  Well, better the overhead of a  closed Issue than a bug slipping by.
