### ISSUE TITLE
Interop with Scala jvm?

### ISSUE THREAD

**Issue by doofin** [scala-native/scala-native#1535]

**Comment by densh** [comment]
Hi @doofin, the only interop that's in scope for Scala Native is C interop. It's imaginable that once #155 is implemented, you could implement a JNI extension for JVM in Scala Native. Please follow that ticket for updates.

**Comment by ekrich** [comment]
@doofin If you want Scala Native to interact with the JVM, Nailgun has a C API client (which could be ported to Scala Native) or an included command line app (could be run in `java.lang.{Process, ProcessBuilder}`) and would allow you to interact from Scala Native to the JVM. https://github.com/facebook/nailgun Couldn't find any new docs - http://www.martiansoftware.com/nailgun/

As far as I know Buck (maintainers) and Pants are major users - https://www.pantsbuild.org/jvm_projects.html#nailgun Comment here by "dragos" is relevent - https://github.com/lihaoyi/mill/issues/19 or in Bloop as well - https://github.com/scalacenter/bloop/issues/169 Also used here https://scalameta.org/scalafmt/docs/installation.html#nailgun so there are lots of examples of usage.
