### ISSUE TITLE
Does scalaTesting filter supported in scala Native ? 

### ISSUE THREAD

**Issue by naseem91** [scala-native/scala-native#1539]

**Comment by densh** [comment]
Hi @naseem91, you can use `testOnly` with Scala Native and it will let you run subset of the tests. Please refrain from posting questions on the issue tracker in the future, you should [post them on gitter instead](https://gitter.im/scala-native/scala-native?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
