### ISSUE TITLE
Boehm given as default garbage collector in setup.rst

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1540]
Whilst editing docs/user/setup.rst in response to review comments, I noticed
that the 'Installing clang and runtime dependencies'  section  says 
`Scala Native uses Boehm garbage collector by default.`

Per the 'Garbage Collectors' section of docs/user/sbt.rst immix is the current default.

If I am correct and given the go-ahead, I can do the edit and some minor re-wording in
 a few days after I am done with this iteration of re2s work.

Please advise.  Thank you.

**Comment by densh** [comment]
Yep this needs to be fixed, we use `immix` by default now.

**Comment by LeeTibbert** [comment]
I believe this was fixed as part of #1498.
