### ISSUE TITLE
j.u.regex.Pattern.compile should cache compiled Patterns

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1546]
The cre2 based j.u.regex.Pattern.compile method  had some code to cache compiled
Patterns.  For a number of reasons, that code was dropped when  j.u.regex was
changed to be based on re2s.

Various String routines use a fixed regex string repeatedly. They would benefit from
a fast lookup the second and subsequent time around.

I am creating this issue to capture a requirement for Pattern caching by @densh  expressed 
in  PR #1419.  I hope I have captured the main elements of that discussion without presuming to speak for him.

Spinning off the requirement to this Issue allows a big problem to be broken up into smaller,
more contained, easier to fix, problems/

##### Two key issues for any future Devo to consider:

1) The amortized runtime cost of cache creation, lookup, and Least Recently Used (LRU)
    maintenance should be less than compiling the regex another time. 

    It would be nice to have some data on the relative costs. That probably means writing
    a private test program to time both un-cached and the cached lookups, possibly
    by calling String methods to test the entire path for improvement. 

2) Concurrency -- SN is currently single thread but will, private opinion, almost certainly
    become multi-threaded in the mid-range future. Concurrency is going to add
    runtime cost.  Designing and writing for full concurrency now is probably
    not needed but some defensive programming is.

    Adding a `synchronized` block (beware Issue #1091) now is probably 
    worthwhile, even though it will increase runtime cost and is not strictly
    necessary in a single threaded program.  Someday someone is going to 
    turns on multi-thread support.  Without the basic synchronization, 
    the cache code is likely to suddenly becoming flaky with difficult to debug
    presenting  errors.

**Comment by LeeTibbert** [comment]
I do not know if `synchronized` does anything now. The de-compilation code presented in #1091 
seems to indicate that is does, or did at that time. I did not chase down if Monitor.enter and
Monitor.exit do anything.

It is probably a safe bet that `synchronized` will be working before mult-thread support is turned
on. IMHO, better to code for that day.

**Comment by LeeTibbert** [comment]
Note to future self:

Any work in the area should be aware that both the java and re2s Pattern are _mutable_ 
data structures.  This means that giving out a second copy of a cached pattern
needs to provide a fresh instance.

The unit-test scenario is:

1) User program compiles a pattern, sayh "\w\W"

2) User program compiles the pattern again (neither knowing nor caring that
    the pattern was returned from cache.)

3) usePattern("abc") on the first instance

4) Check that the .pattern method on each instance returns the now different 
    expected regex strings. 

This is probably a good test to add in any case.

**Comment by densh** [comment]
@LeeTibbert That's a good catch, I think our previous regex caching didn't guard against that. 😅

**Comment by LeeTibbert** [comment]
I was requested/directed to open this PR.  At the time, I did some study of what the regex code is
doing for caching.  I think that any additional caching would be a bigger-than-a-breadbox effort
requiring first hard, measured data and then good design.
