### ISSUE TITLE
Linking errors for scalafmt cli

### ISSUE THREAD

**Issue by olafurpg** [scala-native/scala-native#1560]
While trying to link a native Scalafmt binary with 0.3.9 I hit on the following link error with `nativeLinkStubs := true`. Diff https://github.com/scalameta/scalafmt/compare/master...olafurpg:native-scalafmt?expand=1
```
[error] cannot link: @java.lang.Thread::init
[error] cannot link: @java.lang.Thread::join_unit
[error] cannot link: @java.lang.Thread::start_unit
```
I can't figure out where we transitively reach those methods but I'm pretty sure we don't use them.

It would be nice to implement this one here as well, although I was able to work around the lack of it
```
[error] cannot link: @java.util.concurrent.atomic.AtomicReference::getAndUpdate_java.util.function.UnaryOperator_java.lang.Object
```

**Comment by ekrich** [comment]
Do we want to add the stubs for `Thread` and an impl for `AtomicReference` to target 0.4.0 and 0.3.10?

**Comment by olafurpg** [comment]
0.3.10 would be nice, if possible, otherwise we need to wait for the while dependency chain to upgrade.

**Comment by densh** [comment]
@olafurpg Thanks for the issue, there is no harm done stubbing those methods in 0.3.10. AtomicReference should be doable as well.

**Comment by olafurpg** [comment]
Is there a way to debug from where those `Thread` methods are referenced?

**Comment by densh** [comment]
@olafurpg There is no user-facing way to debug this atm unfortunately, but I've just filed an issue to improve linking error diagnostics: #1563

**Comment by olafurpg** [comment]
I can confirm that the scalafmt command-line interface links with the Scala Native in the latest v0.3.x branch.

I'm able to format individual files but encounter an unexpected `IOException` when running it on the entire repository, will report a separate issue.

**Comment by densh** [comment]
@olafurpg 👏👏👏 Please report a repro and we can do a 0.3.10 once it's all fixed. 😄

**Comment by olafurpg** [comment]
Turns out the usage of `Thread.init` came from scala.sys.process

```scala
scala.NotImplementedError: an implementation is missing
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at java.lang.Throwable.init(Unknown Source)
	at java.lang.Error.init(Unknown Source)
	at java.lang.Error.init(Unknown Source)
	at scala.NotImplementedError.init(Unknown Source)
	at scala.NotImplementedError.init(Unknown Source)
	at scala.Predef$.???(Unknown Source)
	at java.lang.Thread.init(Unknown Source)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.init(Unknown Source)
	at scala.sys.process.ProcessImpl$Spawn$.apply(Unknown Source)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(Unknown Source)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.!(Unknown Source)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(Unknown Source)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.!!(Unknown Source)
	at org.scalafmt.util.GitOpsImpl$$anonfun$1.apply(Unknown Source)
```

**Comment by olafurpg** [comment]
Workaround is to use `java.lang.ProcessBuilder` instead

**Comment by ekrich** [comment]
At least the error is better with the Stub 👍

**Comment by LeeTibbert** [comment]
@olafurpg based on your report, I looked at scala.sys.process and was somewhat surprised
to see that it is not just a thin layer on top of j.l.Process.

j.l.Process and kin are exercised in the SN unit-tests and work, I would expect that those
routines would work for you.  If you experience otherwise, please let me know.

If you have a working workaround and the changes to scalafmt are not to extensive it
does not seem to make sense to convert SN scala.sys.process to be based on j.l.process.
Too many chances to introduce bugs.  Of course, if that means restructuring scalafmt, yell

Does this help?

**Comment by olafurpg** [comment]
@LeeTibbert Thanks, I was able to replace s.s.p.ProcessBuilder with j.l.ProcessBuilder and it worked great.
