### ISSUE TITLE
Front-end ignores finally clause

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#157]
Currently we don't generate any code for finally blocks in the front-end. This should be trivial to fix.

**Comment by Duhemm** [comment]
I tried to take a stab at this issue yesterday, but unfortunately didn't manage to solve it. My idea was to keep the current logic when there's no finalizer and to rewrite

```scala
try normal
catch { catches }
finally finalizer
```
to
```scala
try {
  val fresh0 =
    try normal
    catch { catches }
  finalizer
  fresh0
} catch {
  case fresh1 =>
    finalizer
    throw fresh1
}
```

But I can't type this tree. Using `typer.typed(_)` produces `scala.reflect.internal.Types$TypeError: not found: type Throwable` when I try to compile

```scala
try 0
catch { case _ => 1 }
finally { fprintf(stderr, c"Hello!\n") }
```

Did you have another solution in mind? Or do you know what I should do to correctly type this tree?

**Comment by Duhemm** [comment]
Actually I just noticed my encoding is wrong. If the `normal` branch terminates normally but the `finalizer` throws an exception then the `finalizer` will be executed again.

**Comment by densh** [comment]
It's probably easier to not perform tree rewriting but just tweak the way how NIR is generated during tree to SSA conversion in `nscplugin`. The general idea is to invoke some form of `genExpr(finallyp, _)` around both normal and error branches in `genTry` implementation. 

Here is implementation of [`genFinally`](https://github.com/scala-native/scala-native/blob/7e06b9edb43718ec1b9e514e841698a1dd09b13d/plugin/src/main/scala/salty/tools/compiler/GenSaltyCode.scala#L449) from an early days version of the toolchain. There were no NIR, it was called Salty, and `Tails` is the older API for SSA generation that has been superseded by `Focus` in latest revision of toolchain.
