### ISSUE TITLE
DefaultFormatterSuite crashes on macOS

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#1574]
It looks like a regression that we really need to fix before 0.4.0-M1.

**Comment by LeeTibbert** [comment]
@densh 

Is there any chance that I could get a cut & paste of the crash from someone?

I do not have direct access to macOS and, if it exists on Amazon, it would take time
to set this up.  Trying for a cheap & fast clue, not to burden anyone.

**Comment by densh** [comment]
I spend a few hours minimizing this today. So here is a [gist of how small it could go](https://gist.github.com/densh/0aa9a254a90b865222fe55b95fcac1dc). Dummy test calls in seem to be significant. Arrays seem to be significant despite their result not being used. The rabbit hole goes really deep and I can't see the end of it yet.

**Comment by densh** [comment]
It still crashes the same if we don't run the optimizer, which means it's a problem somewhere else.

**Comment by densh** [comment]
The plot thickens, it only fails on mac with exactly 8 virtual cores (but not 12 for example). If we force codegen to emit one giant LLVM file, it doesn't fail any more.

**Comment by densh** [comment]
Only fails with `-O0`, works as expected with `-O1` and `-O2`.
