### ISSUE TITLE
IOException when using java.nio.file.Files.write

### ISSUE THREAD

**Issue by olafurpg** [scala-native/scala-native#1575]
When linking the Scalafmt command-line interface at the following commits

- Scala Native: 118df6728c9104b6ac35abfc56b753940442c7ca
- Scalafmt: https://github.com/scalameta/scalafmt/commit/f211c90e805f44494f5a465ca388c028b0db7127 (from my fork)

I hit on the following error when trying to reformat the entire Scalafmt repo.

```sh
$ sbt cliNative/nativeLink
$ time scalafmt-cli/native/target/scala-2.11/scalafmt-cli-out
...
[info] Linking (7997 ms)
[info] Discovered 6161 classes and 38811 methods
[info] Optimizing (debug mode) (13650 ms)
[info] Generating intermediate code (4140 ms)
[info] Produced 107 files
[info] Compiling to native code (3895 ms)
[info] Linking native code (immix gc) (879 ms)
[success] Total time: 84 s, completed May 1, 2019 1:36:13 PM
java.io.IOException
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at java.lang.Throwable.init(Unknown Source)
	at java.lang.Exception.init(Unknown Source)
	at java.io.IOException.init(Unknown Source)
	at java.io.IOException.init(Unknown Source)
	at java.io.RandomAccessFile.setLength(Unknown Source)
	at java.nio.channels.FileChannelImpl$.getRAF(Unknown Source)
	at java.nio.channels.FileChannelImpl.init(Unknown Source)
	at java.nio.channels.FileChannel$.open(Unknown Source)
	at java.nio.file.spi.FileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.Files$.newByteChannel(Unknown Source)
	at java.nio.file.Files$.newByteChannel(Unknown Source)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.nio.file.Files$.newOutputStream(Unknown Source)
	at java.nio.file.Files$.write(Unknown Source)
	at org.scalafmt.util.FileOps$.writeFile(Unknown Source)
```

**Comment by olafurpg** [comment]
I'm unable to reproduce when writing a single file, the following command exits without errors
```sh
git ls-files | grep "scala$"  | xargs scalafmt-cli/native/target/scala-2.11/scalafmt-cli-out
```

**Comment by densh** [comment]
@olafurpg Thanks for the bug report!

**Comment by LeeTibbert** [comment]
@olafurpg  Thank you for the report.

Gee, I managed to hose myself several times by (mis-)reformatting the entire scalafmt tree was
working on with SN scalafmt and never saw that error. Not to say that you are not seeing it,
just that I need to take a closer look.

If it is OK with you, I will try formatting a scratch directory containing the scalafmt sources
after we get the regex stuff sorted and I am working with your code, not my devo hacks.
Your code is closer to the real product.

**Comment by olafurpg** [comment]
It would be great to find a smaller reproduction, I would try writing a small main function that calls `Files.write()` multiple times to existing files.

**Comment by LeeTibbert** [comment]
Status update:    I had a few minutes whilst SN test-all is running so I ran my 4 day old
SN scalafmt against a scratch clone of the SN source directory tree.  That copy is built
against a private copy of SN 0.3.9+, but I had not touched nio.file.Files.write.   

I could not tell how many files scalafmt touched, but from prior hosing of myself, I suspect
it traversed the entire tree.  I looked for a verbose or debug mode but did not see it.
No smoke.  I have not checked if that directory will build; i.e. if there are mis-formatted files.

This is not to say that the problem reported does not exist.  Just that it likes to hide.

My next step, probably during my next test-all cycle, is to check the SN FilesSuite.scala
to see if it has an existing test which handles more than one file at a time.

Step after that, I think, is to rebuild at the stated scalafmt version so that I am exercising
code closer to the origin and not homebrew.

If this becomes a showstopper or major annoyance for scalafmt or SN development,
ring the bell and I will switch from 'time available" to "right now, please".

Sound like a plan?

**Comment by LeeTibbert** [comment]
I've spent almost three weeks studying this issue. I wanted to ease the development of a native
scalafmt. The one in my tests is blindingly fast.  I also wanted to suss out possible funkiness
in javalib when handling large numbers of files.

##### Next steps

I believe the next step would be to build and and extensively exercise  SN scalafmt after 
PR #1651 reaches  mainline. Watchful waiting...

From the provided stack trace, my working hypothesis is that something went wrong with the fcntl.open() call ealrlier on the stack.  That PR should detect the error closer to when it happens
and report the condition returned by the operating system.

##### Accomplishments

*  Three Issues were created (#1644, #1645, #1646) were created. PRs #1650 & #1651 address
    the first two of those issues.

*  I developed evidence to reduce the posterior probability of three hypotheses:
   + A problem where fcntl.close would not close at the operating system level.
   * Some  hidden limit in javalib as to the number of open files at one time.
   + Opening a file at java level used more than one os file descriptor.

* I wrote a small number of C & SN programs to discover OPEN_MAX in effect
  in both C & javalib and its hard and soft limits. 

*  Using mainline SN 0.3.9, I did a fresh build of SN scalafmt as indicated in the base note
   and ran it against a scratch copy of the scalafmt source from which it had been built.
   No evident problem found.

   The scalafmt source tree contained only 200 or so .scala files, well under the usual
   linux soft OPEN_MAX of 1024.  

*  In the prior test scenario the source files were probably all properly formatted. SN
    scalafmt may have opened 0 files for write.  I wanted to test when all 200 files
    had been opened for write.

    I developed a bash script to run through a scratch copy of the scalafmt s ource tree,
    open it for write, and append a string which would trigger a re-format. I re-ran the above
    SN scalafmt. No Exception was thrown and a spot check of files showed they had
    been reformatted.

*   Mindful that 200 files is not all that large a number, I copied all 22736 .c & .h files from
    a linux 5.2 mainline repository over to a scratch directory.  I then wrote a SN program to
    open each file for writing and maintain a reference to it (to keep it from being closed
    when garbage collected, and writing a few bytes at the end.

     When I ran the program under SBT, it surprised me by opening all 22756 files!  I 
     later learned that the JVM sets the number of simultaneous open file up to al 
     large, possibly os system defined number.  (Issue #1645). On my Linux system,
     this number was the OPEN_MAX hard (upper) limit.  

     So javalib can open at least 23K files for write.  Unlikely to be a problem there.

     When I ran the SN program at the command line, I got the expected Exception
     (an exception on probably first write to file). (PR #1644).

* I edited the above program to have an LRU cache of 1021 files (1024 - 3 process
  permanent files). The cache closed files as they were ejected from the cache.
  This created a rolling window.

  I ran this second program on the 23K linux files, opening each for write and writing a few 
  bytes. The program ran as expected; no Exception.  From this I conclude that there is
  unlikely to be a problem with javalib closing and re-opening files once fcntl.close has been
  called.

**Comment by ekrich** [comment]
@jchyb Have you seen this issue? - maybe it can be closed.

**Comment by jchyb** [comment]
I did not really see anything like this. It seems like it was a very environment dependent error. I suppose, was it to reappear one day, we will at least have a more descriptive exception thrown. I would say it can be closed.
