### ISSUE TITLE
SocketInputStream#read() wrongly reports byte 255 as End of File

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1578]
java.net.SocketInputStream method read() is supposed to return integer -1
(0xFFFFFFFF) for End of File and integer 255 (0x000000FF) when that character
is read.  That routine is currently converting the byte 255 into an Int by code which
does sign extension, resulting in the set high bit in the byte being propagated
into the higher order bits of the Int.

This is causing the 'too many unit-tests' problem, once the number of uniit-tests
reaches 255. 

The solution is to change 'b.toInt'  to 'b & 0xFF'.

**Comment by ekrich** [comment]
@LeeTibbert I tried the change on master and it didn't work for me on macOS.
