### ISSUE TITLE
javalib DataInputStream#readFully wrongly checks EOF and has bad algorithm

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1579]
This is part of my drive to solve the "too many unit tests" problem.

1) The Oracle Java 8 API describes javalib DataInputStream#readByte (DIS) as
    throwing EOFexception or returning a byte in the range 0 to 255. The 
    current  SN implementation does not throw on EOF, rather returning a
    byte 255 (or signed -1).  Thus at the return of readByte all EOF information
    is lost.   

    The entire DIS file should be checked for compliance with the JAVA API
     specification of which methods throw EOFException.

2) Currently DIS#readFully calls DIS#readByte and checks the result against -1 (EOF).
     When character 255 is read and the bug above in readByte is present, the
     255 presents as EOF.  The unit-tests remote process detects & and, correctly,
     reports this as early EOF. 

3)  The current algorithm in DIS#readFully calls readByte in a tight loop. This is
      unnecessary and horribly inefficient. Far better to replace the body of that
      method rather than simply edit out the EOF check.

**Comment by densh** [comment]
Fixed in #1582
