### ISSUE TITLE
testMain should take advantage of communications pause to collect garbage

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1580]
Manual triggering of garbage collection is like trying to time the (stock) market: an
exercise for fools.

The goal of this Issue is to suggest a way to add robustness to unit-tests and
perhaps improve performance a bit.  I invite discussion, if only to offer me
the jester's cap.

testMain is the routine which actually runs the test Suites.  It is run in a 'remote'
process which receives commands from the local 'master' process.

Two of these commands are Command.Tasks & Command.Execute.  Both
of these can potentially generate a lot of objects which could be garbage 
collected.  At the end of each of these (and other) commands, testMain
sends results back to the master process. After that testMain has nothing
to do but block on I/O waiting to recieve the next command. There is almost
certainly a pause whilst the result is sent over the wire and the master responds
with a command.   

testMain() could take advantage of this pause by calling System.gc() to
collect garbage.  I have no data to suggest that doing so improves memory
usage or performance. 

After implementing this edit in my private environment, both the complete
unit-tests and an augmented set continued to execute as expected.  I noticed
no obvious slow down or garbage collection pause (immix).

It is tempting to put the System.gc() at the top of the loop, before receive(), rather
than in just these two commands. However, I think that would slow down the
initial receive() and the other commands would not benefit much.  Again, guesses
on my part from analysis, not hard data.

**Comment by densh** [comment]
Calling GC explicitly is almost never a performance win. Given that it's blocking (i.e., stop the world) you are not going to win any performance. Just let the GC figure things out on its own.
