### ISSUE TITLE
Proposal: Add marker to unit-test remote output to make origin evident.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1584]
Issue #1574 "Mac O/S crach" has advanced to the head of the priority queue.  It appears that it may not be solved by PR #1582. "unit-tests fail with > 254 Suites:.

I propose a change to the testing infrastructure. It would help isolating  the cause of #1574
and yield more general stress reduction to future developers debugging unit-test infrastructure failures

##### Background

When running unit-tests there appears to be at least six (6) data streams for a user to
track. It is like being at a noisy party: who is speaking?

1) stdout on the local master process - should go through Logger & show [info] prefix

2) stderr on the local master - should go through Logger & show [error] prefix

3) A sneak path on local master which bypasses Logger and prints directly to terminal.

4) stdout on the remote process - should go through Logger & currently shows [info]

5) stderr on the remote process - should go through Logger & currently shows [error]

6) Communications over the command socket. Results should so through logger.
    There may or may not be a sneak path where errors on the Remote get reported
    over the command socket and appear on the local system without having gone
    through the Logger.

Now Image a NullPointerException (NPE) showing up on the local system without having
gone through the logger.  Did it come from the local master or the remote? How
did it bypass the Logger?

Further, imagine a NPE showing up which _did_ go through the Logger.  Where did 
it originate, master or remote?  Sometimes with time, energy, a full stacktrace, and an 
extensive and intimate knowledge of SN, one can figure it out. Even then time is wasted.

##### Proposal

I propose that the user see "[info] abc" when the message comes from the local stdin
and "[info] rem: abc" when the message comes from the remote stdin.  Same
concept for stdout.  

People can suggest something other than "rem: " for the marker. It should be more
than "eh? ", more than the empty string, and not 20 characters long."rem: ' is itself
a bit cryptic/short. I tried "remote: " but that seemed long (but livable and _far_ better than
"").

Implementing this proposal is as easy as anything ever gets.  I have a two line change
in my private environment working& well exercised.  It starts with remote process
with a ProcessLogger which takes anything on either stdin or stdout of the new
Process and sends it appropriately to the current Logger.  I find the results
amazing.

#### Go ahead?

What do people think about this proposal?  Do I have the go ahead to submit
a PR?

I am for it because I am likely to be spending _many_ hours chasing unit-test issues.

**Comment by LeeTibbert** [comment]
Yes, color me challenged ;-)

**Comment by ekrich** [comment]
Maybe `jvm: ` for the sbt side and `sn: ` or `nat: ` if you what the same length or `native: ` if you want something longer for the Scala Native side?

**Comment by LeeTibbert** [comment]
@ekrich Thank you for the suggestions. I had planned to leave the sbt side as-is Still undecided
and looking for the go-ahead for the remote side,

**Comment by LeeTibbert** [comment]
A side benefit is that the proposed change would also fix Issue #1445 and obsolete pending
PR #1446

**Comment by LeeTibbert** [comment]
This issue is resolved in pending PR #1827 and can be closed after that is merged.

**Comment by LeeTibbert** [comment]
Closing this issue because the entire testing infrastructure changed in the Summer of 2020.
The underlying idea is still good but I have not had time to adapt it to the new infrastructure.
Such adaptation might break Scala.js compatibility, so it needs to be done with more care
that I have time available.   

Corresponding PR was closed a long time ago.
