### ISSUE TITLE
Add support for java-style reflection

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#159]
Many of the existing Scala frameworks rely heavily on Java reflection. 
- [x] Add support for member pinning via `@pin`
- [ ] Add support for class pinning (https://github.com/scala-native/scala-native/issues/156)
- [ ] Expand generated RTTI to include information to find and call methods/constructors 
- [ ] Use new RTTI to implement reflection-related subset of `java.lang.*` and `java.lang.reflect.*`

**Comment by aslesarenko** [comment]
In [Scalan](https://github.com/scalan/scalan) we use the following classes `java.lang.reflect`. Would be nice to have them supported.
```
java.lang.reflect.AnnotatedElement
java.lang.reflect.Constructor
java.lang.reflect.Field
java.lang.reflect.InvocationHandler
java.lang.reflect.InvocationTargetException
java.lang.reflect.Method
java.lang.reflect.Proxy
java.lang.reflect.UndeclaredThrowableException
```

**Comment by jonas** [comment]
See also: https://github.com/portable-scala/portable-scala-reflect
