### ISSUE TITLE
Unable to link Actor

### ISSUE THREAD

**Issue by IbrahimaWane** [scala-native/scala-native#1599]
Hello, 
when using Actor in my scala-native code, this error appears

```
[info] Linking (829 ms)
[error] cannot link: @akka.actor.Actor
[error] cannot link: @akka.actor.ActorRef
[error] cannot link: @akka.actor.ActorRefFactory
[error] cannot link: @akka.actor.ActorRefFactory::actorOf_akka.actor.Props_java.lang.String_akka.actor.ActorRef
[error] cannot link: @akka.actor.ActorSystem
[error] cannot link: @akka.actor.ActorSystem$
[error] cannot link: @akka.actor.ActorSystem$::apply_java.lang.String_akka.actor.ActorSystem
[error] cannot link: @akka.actor.Props
[error] cannot link: @akka.actor.Props$
[error] cannot link: @akka.actor.Props$::apply_scala.reflect.ClassTag_akka.actor.Props
[error] unable to link
[error] (Compile / nativeLink) unable to link
[error] Total time: 9 s, completed 2019. 5. 15 오후 2:25:12
```

Could you please tell me what is the issue and what are the ways to solve it
Thanks

**Comment by LeeTibbert** [comment]
@IbrahimaWane 

Sorry you are experiencing a problem.  Probably the first thing to do is to 
check if Akka supports scala-native, even in some experimental SNAPSHOT.
That is, does Akka publish artifacts for Scala Native. If yes, for which SN version?

In whichever .sbt file you declare your dependencies in, what does the line which
is supposed to bring in Akka artifacts look like?  Can you post that?

From my memory of Akka, I believe it uses some features (Futures) which may
not be ready yet in SN.  

I personally would be interested in hearing the status of Akka & SN. It would be great
to hear that it was supposed to work.

Hope this helps.

**Comment by IbrahimaWane** [comment]
Thanks for your answer. 
This is the line :  libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.5.9"

I have searched about scala-native being supported by Akka - no meaningful result.

So that means I have to wait until supported or use other means?

**Comment by lolgab** [comment]
Yes, scala native dependencies are imported using `%%%` instead of `%%`. The library you use should be released for Scala Native... Using `%%%` you should have a not found error with sbt.
You can search on Scala index for libraries supporting Scala native.

**Comment by densh** [comment]
@IbrahimaWane 

This is not a bug on the side SN. Akka is not cross-compiled for SN and that's why it doesn't link.

Also please note, our issue tracker is *not* a support forum. Please use gitter for future questions.
