### ISSUE TITLE
Provide printf and scanf family of functions in clib

### ISSUE THREAD

**Issue by rwhaling** [scala-native/scala-native#1606]
Since we document how to provide an idiomatic printf in the docs now, we might as well provide the essential printf/scanf functions as part of clib.  

If we provide them as part of the SN distribution, that should cover 99% of uses of CVarArgs that will occur - they are otherwise quite uncommon in library and application code.

The functions we'd need are:

printf()
fprintf()
sprintf()
snprintf()
scanf()
fscanf()
sscanf()

**Comment by ekrich** [comment]
@rwhaling I could add them in PR #1605 if they are in `stdlib`.

**Comment by densh** [comment]
@rwhaling I agree in principle, it should be less surprising to have them out of the box.

@ekrich You can't just extern declare for them because we don't support C's `...` varargs any more. And at the same time we don't allow non-extern method definitions in extern objects at the moment.

**Comment by rwhaling** [comment]
@densh how would you feel about this kind of approach for the extern object/packaging issue?

```
@extern
object stdio_impl {
  def vprintf() = extern
}

object stdio {
  import stdio_impl._
  def printf() = ...
}
```

**Comment by densh** [comment]
@rwhaling Then you need to duplicate every single method in `stdio` twice.

**Comment by ekrich** [comment]
How about a `stdioVarargs` as a bridge if that would be possible.

**Comment by rwhaling** [comment]
Clarified with @densh - going to provide the wrappers in an `implicit class` in the `clib` package object.

**Comment by abhsrivastava** [comment]
Has the version 0.4.0-M3 published yet? I believe the book "Scala Native" is using printf function in chapter 1 which is only available via this PR and milestone "0.4.0-m3" but this is not available here https://bintray.com/scala-native/sbt-plugins/sbt-scala-native

**Comment by rwhaling** [comment]
Hi @abhsrivastava - every code file in the book should include a compatibility shim containing the printf etc functions; if that's missing, the code included in book won't compile.  Feel free to drop me a message on gitter if you can't get it to work.

**Comment by cloutiy** [comment]
@rwhaling Hi there, I am following the code in the book and got stuck at the second example (using prntf).
