### ISSUE TITLE
Tests fail with exception message that is not helpful

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1612]
The cause of this error is triggered by a change to the upper/lower case encoding as far as I can tell. This is confirmed locally and on Travis CI which was run to confirm the failure. There is definitely some issues I found in the encoding in this PR https://github.com/scala-native/scala-native/pull/1611 but I don't think that this would cause what seems to be an exception in the test harness code. I believe the error message could be improved and factored out or the exception code factored out to become DRY. Here is the place the exception is throw in the code.

https://github.com/scala-native/scala-native/blob/34453c01ba344b3fe3bf4a79ec4b10bf07638e72/unit-tests/src/test/scala/scala/scalanative/regex/GoTestUtils.scala#L25

The following is the error stack trace and the run context. The message at the end is a big improvement over the previous test harness messages. Thanks @LeeTibbert 
```
> tests/testOnly java.lang.CharacterSuite*
...
[info] Compiling 1 Scala source to /Users/eric/workspace/scala-native/unit-tests/target/scala-2.11/test-classes...
[info] Linking (3674 ms)
[info] Checking intermediate code (1314 ms)
[info] Dumping intermediate code (1742 ms)
[info] Discovered 5751 classes and 31508 methods
[info] Optimizing (debug mode) (10637 ms)
[info] Checking intermediate code (614 ms)
[info] Dumping intermediate code (1190 ms)
[info] Generating intermediate code (12387 ms)
[info] Produced 8 files
[info] Compiling to native code (6602 ms)
[info] Linking native code (immix gc, none lto) (636 ms)
[info] Total (39339 ms)
[info] Starting process '/Users/eric/workspace/scala-native/unit-tests/target/scala-2.11/tests-out' on port '61847'.
[error] java.lang.IllegalStateException: can't happen
[error] 	at java.lang.Throwable.fillInStackTrace(Unknown Source)
[error] 	at java.lang.IllegalStateException.<init>(Unknown Source)
[error] 	at scala.scalanative.regex.RE2$.compileImpl(Unknown Source)
[error] 	at scala.scalanative.regex.Pattern$.compile(Unknown Source)
[error] 	at scala.scalanative.regex.Pattern$.compile(Unknown Source)
[error] 	at java.util.regex.Pattern$.compile(Unknown Source)
[error] 	at java.util.regex.Pattern$.compile(Unknown Source)
[error] 	at scala.collection.immutable.StringLike$class.r(Unknown Source)
[error] 	at scala.collection.immutable.StringOps.r(Unknown Source)
[error] 	at scala.collection.immutable.StringLike$class.r(Unknown Source)
[error] 	at scala.collection.immutable.StringOps.r(Unknown Source)
[error] 	at java.nio.file.FilesSuite$.<init>(Unknown Source)
[error] 	at <none>._SM25java.nio.file.FilesSuite$G4load(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMain$.<init>(Unknown Source)
[error] 	at <none>._SM41scala.scalanative.testinterface.TestMain$G4load(Unknown Source)
[error] 	at <none>.main(Unknown Source)
[trace] Stack trace suppressed: run last tests/nativetest:testOnly for the full output.
[error] (tests/nativetest:testOnly) scala.scalanative.build.BuildException: The test program never connected to the test runner.
```

**Comment by LeeTibbert** [comment]
@ekrich Thank you for reporting this.  I have experience and been annoyed by
this several times, usually when I have messed up something in  regex née re2s.

To help move the discussion a peg or two forward:

    We know that tests fires off a 'remote' process to actually run the test. That remote
    process is supposed to connect back to the local (I hate word 'master' but it seems
    to be the term-of-art) process. 

    If the remote process does not connect back in a defined period of time the BuildException
    message quoted above happens. Mostly all good so far. I will create a separate issue
    for a BAD BUG in this initialization sequence.

    The issue becomes what can keep the remote from connecting back.  I believe
    that the remote connects back relatively late in its 'coming to life' sequence.  A 
    hypothetical improvement, probably easier to describe than implement, would have
    the remote connect back first thing.  As long as I am dreaming, I would have the 
    remote have a verbose init mode where it gave progress in its initialization sequence.
    Dream on, Lee.

    I believe, but have not traced, that the remote does some regex parsing  of the 
    compiled in list of modules it knows about, In preparation for sending them back to
    the local process.   

    In my cases, I messed up the regex binary search implementation (ok, did I just admit that
    in public) and had an infinite loop (or three).  No wonder why the remote did not 
    connect back.

    I believe that the case  reported in the base note was from a Travis CI run of WIP
    code. I suspect that regex was given improper  input from that Character implementation.
    I believe that implementation has since fixed.

     I mention the ways that the reported problem has been triggered to help any one
     trying to reproduce the reported problem.

**Comment by densh** [comment]
Thanks for the report!

**Comment by ekrich** [comment]
Update:

This occurred in the following location not as originally reported above. 
https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/scala/scala/scalanative/regex/RE2.scala#L778-L783

Which in turn comes from here.
https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/lang/String.scala#L311-L317

And then here.
https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/nio/charset/Charset.scala#L62-L66

Which was caused by the problem in `toLowerCase` which we suspected.

The error only occurs if the passed in encoding e.g. "UTF-8" when lowercased is not in the `Charset` map. My suggestion would be to just remove the `try catch` in those areas. This would point the finger back to the source of the error faster.

Overall, String methods are fundamental and in this case regex is also at it is used by the testing framework. Just shows the inter-dependencies.

**Comment by LeeTibbert** [comment]
Eric, 

Good sleuthing, reporting, & fixing!

Did you happen to gain any information about the call chain going _up_ from RE2? 
Probably somebody in java.regex, probably compile, but who in the early
initialization sequence was trying to compile a regex? The who might give
us a why and possibly a whole bunch of code that could be skipped.

If this info is at your fingertips, great. If not, I do not mean to ask for any of your time.

Just trying to catch elusive unit-test init behavior while it is before us.

Thanks,

**Comment by ekrich** [comment]
Well, I'm assuming that the `scala.collection.immutable.StringOps.r(Unknown Source)` is the regex getting called but I'm unable so far to find how that is getting called.
