### ISSUE TITLE
unit-test runner can leave CPU sucking orphan remote  processes

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1615]
unit-tests is wonderful and saves immense amounts of time.

With the hope of iterative improvement and of my remembering the issue, let
me report an issue that I have seen with unit-tests.   This report was prompted
by Issue #1612.

The unit-test local process creates a remote process to actually run the 
requested test.  The remote process is supposed to connect back to the
local process (quickly). If something keeps the remote process from
connecting back within a certain period, the local process throws a 
BuildException.  So far, so good.

It appears that the local process never checks that the remote process has
exited. By implication, the local process never terminates the remote process.
The remote process is left running.

Imagine/experience that something has gone wrong in the remote initialization sequence
and the remote is in a tight 'Infinite' loop,  One CPU sucking orphan causes
a noticeable slow down on the system.  Three or four or 20 begin to have some
impact: the system becomes unusable.  Now imagine that system is Travis CI.

A solution could be to have the local check the exit status of the remote before
it throws the BuildException. There are scala/java Process calls (I believe implemented
already) to do this. If the remote has not exited, it should be terminated.

A SMOP, right?  Yes, a SMOP but not today's biggest problem.

**Comment by densh** [comment]
Thanks for the report @LeeTibbert !

**Comment by LeeTibbert** [comment]
cc: @errikos 

PR #1827 provides a "reduction in strength" fix for this issue.

The Spring 2020 change to the SN TestFramework to use Reflection reduced the
amount of work in the SN TestMain binary before it connected back to the Sbt side.
This reduced the chance of TestMain getting into an "infinite" loop and becoming
an active zombie.

PR #1827 makes a best-effort attempt to force the TestMain process to exit if
it is still alive after there is an error on the command socket.  This reduces the
chance of TestMain becoming a CPU sucking zombie.

A corner case which might allow zombies to endure remains.   By historical &
recent design direction, the SN TestFramework does not implement time limits
on tests or Suites.  There is work in progress to add JUnit testing to SN.
Such test timeouts are allowed in JUnit. 

Now imagine a test which does an infinite loop which does not do
any I/O on the socket. Also the user has  set `Global / cancelable := true`. 
The test goes into the loop, the user waits and then presses '^C`,
and sbt returns to its shell prompt.   I believe, but have not tested,
that the TestMain process will now be a CPU sucking zombie which
will run until sbt exits back to the OS command line. That could be
hours, days, or longer.  During that period additional CPU zombies
could be generated.

This Issue can be closed when SN supports JUnit and its timeout rule(s).

**Comment by LeeTibbert** [comment]
2020-07-14 update

PR #1841 added JUnit support.  By permission of @errikos, the author of that PR, on gitter. 
This is on-the-fly info, not canon.
```
@LeeTibbert I don't think so. There is no org.junit.rules package and the timeout parameter in @Test seems to be ignored.
```

**Comment by LeeTibbert** [comment]
I have not been hosed by this one since the Summer 2020 move to JUnit so I am closing it.
