### ISSUE TITLE
Constant definitions missing in scala.scalanative.posix.unistd (0.4M2)

### ISSUE THREAD

**Issue by david-bouyssie** [scala-native/scala-native#1621]
The file ```scala.scalanative.posix.unistd.scala``` (https://github.com/scala-native/scala-native/blob/master/posixlib/src/main/scala/scala/scalanative/posix/unistd.scala) is missing some constant definitions: F_OK, R_OK, W_OK and X_OK.

For reference please see: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/unistd.h.html

**Comment by LeeTibbert** [comment]
Before this Issue is closed, the definitions of F_OK, etc in fcntl.scala should be changed
to reference unistd.scala (and the corresponding symbols removed from resources/fcntl.c).

**Comment by WojciechMazur** [comment]
`fcntl` symbols were moved to `unistd` in #1885
