### ISSUE TITLE
Cast CFuncPtr to Ptr[Byte] (and reverse)

### ISSUE THREAD

**Issue by rwhaling** [scala-native/scala-native#1631]
For certain unsafe, void-pointer slinging C API's, it can be useful to convert a CFunctPtr to a Ptr[Byte] (or vice versa).  For example, libcurl in particular needs this idiom to set callbacks for various events.

Currently, I'm implementing this in user-space code like so:

```
  def func_to_ptr(f:Object):Ptr[Byte] = {
    Boxes.boxToPtr[Byte](Boxes.unboxToCFuncRawPtr(f))
  }
```

Which, if cleaned up a bit, would be great to include in the `unsafe` package.  And for the sake of completeness/generality, we should be able to implement the reverse cast as well.

**Comment by densh** [comment]
Yep, this conversion is missing due to the dropped `a.cast[T]`. We probably just to add `toPtr` conversion on `FuncPtr` and `toFuncPtr` on `Ptr` type.
