### ISSUE TITLE
posix lib sys/resource.scala  needs implementation

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1646]
The proposed documentation solution for Issue #1645 implies that POSIX 
getrlimit() and setrlimit() from sys/resources.h are implemented and available to developers.

The constants associated with those methods should also be implemented.

The hard part is likely to be figuring out a way to unit-test that work across operating
systems because some expected values may vary by os.

**Comment by ekrich** [comment]
As far as I know there has never been a hard requirement to test `extern` functions. If they are used in in `javalib` or something, we test that of course.
