### ISSUE TITLE
Environment needs more than llvm/clang

### ISSUE THREAD

**Issue by marcgrue** [scala-native/scala-native#1648]
Some Native tests won't compile at runtime if `re2` is missing. So it's not enough to install `llvm`.

Please expand install instructions on [Environment setup](http://www.scala-native.org/en/latest/user/setup.html#installing-llvm-clang-and-native-libraries) to the following command for macOS (and likevise for other operating systems):

`brew install llvm bdw-gc re2 libuv`

You might want to separate out optional libraries like `btw-gc`/`libc-dev` etc. as you have it now.

**Comment by LeeTibbert** [comment]
@marcgrue   
I am told that wedding gifts can be sent up to a year after the event. I suspect that responses to Issues
have less of a grace period.

We appreciate your time in filing the Issue and apologize for the rude but necessary delay.

About a year or so, I think a month or so after 0.4.0-M2 was released, another regular expression was
ported to Scala Native.  As of that port, re2 is no longer required by Scala Native.  

I believe that @ekrich and others did some work to minimize the software required by Scala Native.
Even more important, to me, is that they documented the required & "optional" pieces.

I hope this helps renew your interest in Scala Native.  Please contact me if you have
additional concerns or issues.

Lee
The person whose fingerprints are all over the port of the current regex code.

**Comment by marcgrue** [comment]
Thanks a lot, @LeeTibbert for getting back to me :-) This all sounds good! Thanks for all the work you and others put into Scala Native!
