### ISSUE TITLE
Unsigned integers must not box when passed through C varargs

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#165]
```scala
import scalanative.native._
import scalanative.libc.stdlib._

object Test {
  def main(args: Array[String]): Unit = {
    val l = 43.toUInt
    fprintf(stdout, c"%d", l)
  }
}
```

Currently it doesn't print 43 but a random (box) address.

**Comment by Sumith1896** [comment]
@densh Could you give some starting points here?

**Comment by densh** [comment]
Front-end bugs are generally quite hard due to the fact that one has to know front-end compiler internals to tackle them. I'd advise to look for something easier to start with.

**Comment by densh** [comment]
Indeed, this one was quite difficult to fix. https://github.com/scala-native/scala-native/pull/243
