### ISSUE TITLE
Allow declaration of external functions with varying signatures in separate objects 

### ISSUE THREAD

**Issue by jokade** [scala-native/scala-native#1652]
Declaration of external functions with multiple signatures works when all signatures are declared in the same object, for example:

```C
void* foo(void* p) { return p; }
```
```Scala
@extern
object Foo {
  def foo(i: Int): Int = extern

  @name("foo")
  def bar(cstr: CString): CString = extern
}
```

However, the above example fails during compilation of LLIR, if `foo` and `bar` are declared in separate objects.

This is an issue if multiple libraries declare their own binding to the same external function, or if bindings to external function are generated on the fly and hence cannot be declared in a single extern object.

**Comment by jokade** [comment]
@densh Is it possible to solve this issue during LLVM codegen globally? If so, could you give me a hint how/where it is handled for the object scope, so I could try fixing it for my problem?

**Comment by densh** [comment]
This is totally solvable, thanks for the report!

**Comment by lolgab** [comment]
The PR I created today (#1746) should fix it.
@jokade would you mind trying it?
