### ISSUE TITLE
Commix doesn't link on MacOs with clang 10.0.1

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#1654]
Setting `nativeGC := "commix"` on a MacOs Mojave machine with provided clang (10.0.1) gives an error about the use of deprecated members. Probably -Werror is on by default.
```
[error] /Users/lorenzo/scala/scala-native-loop/examples/server/target/scala-2.11/native/lib/gc/commix/Settings.c:7:10: fatal error: 'sys/sysinfo.h' file not found
[error] #include <sys/sysinfo.h>
[error]          ^~~~~~~~~~~~~~~
[error] 1 error generated.
[error] /Users/lorenzo/scala/scala-native-loop/examples/server/target/scala-2.11/native/lib/gc/commix/Phase.c:8:5: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
[error]     sem_init(&heap->gcThreads.startWorkers, 0, 0);
[error]     ^
[error] /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/semaphore.h:55:42: note: 'sem_init' has been explicitly marked deprecated here
[error] int sem_init(sem_t *, int, unsigned int) __deprecated;
[error]                                          ^
[error] /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:176:40: note: expanded from macro '__deprecated'
[error] #define __deprecated    __attribute__((deprecated))
[error]                                        ^
[error] /Users/lorenzo/scala/scala-native-loop/examples/server/target/scala-2.11/native/lib/gc/commix/Phase.c:9:5: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
[error]     sem_init(&heap->gcThreads.startMaster, 0, 0);
[error]     ^
[error] /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/semaphore.h:55:42: note: 'sem_init' has been explicitly marked deprecated here
[error] int sem_init(sem_t *, int, unsigned int) __deprecated;
[error]                                          ^
[error] /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:176:40: note: expanded from macro '__deprecated'
[error] #define __deprecated    __attribute__((deprecated))
```

The problem seems to be that `sys/sysinfo.h` is a linux specific header and should not be used in portable programs, or should be used only for linux implementation.|

https://stackoverflow.com/questions/12523704/mac-os-x-equivalent-header-file-for-sysinfo-h-in-linux
https://stackoverflow.com/questions/27736618/why-are-sem-init-sem-getvalue-sem-destroy-deprecated-on-mac-os-x-and-w

**Comment by densh** [comment]
Hi @lolgab , thanks a lot for the bug report!

It seems like macOS doesn't support unnamed semaphores and we should use `sem_open` instead of `sem_init` there. @valdisxp1 can you have a look at this one, it should be easy to fix.

**Comment by valdisxp1** [comment]
The `sem_init` does not look like a blocker here as it only generates warning, while the Linux-specific `sys/sysinfo.h` errors out. Sysinfo is replaced  in #1657 

Regarding the `sem_init` -> `sem_open`, this does not look like a simple fix. Previously I was using semaphores only within a single process (NOT shared among processes). However, with named semaphores, there no way to do that, so the names must be **globally** unique. These appear to be similar to files as they need to be destroyed after use. In short this will take time to do.

Also I do not own any apple device, so I cannot replicate the environment.

**Comment by valdisxp1** [comment]
@densh created #1658 for the removing the warning. With both #1657 and #1658 are applied the issue should get resolved. It is just someone else needs to test this on their apple device.

**Comment by lolgab** [comment]
I tried on my device and the issue seems to be solved. I think this issue can be closed.

**Comment by ekrich** [comment]
@lolgab I think you can probably close this if it works for you. That would make our M3 list look better.

**Comment by lolgab** [comment]
It would be nice to setup a Mac OS X CI too..

**Comment by lolgab** [comment]
Since the problem with Commix is solved I'm closing this as suggested, @ekrich.
