### ISSUE TITLE
Possible compiler backend issue in 0.4.0-SNAPSHOT .gt. M2 

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1674]
The presenting problem is that scalactic (3.1.x, dated approx 2019-07-28) fails to
compile against SN 0.4.0-SNAPSHOT (dated 2019-07-29). 

I saw this in DEBUG mode. I did not try either of the release modes.

I have seen this twice; once in the middle of a debugging frenzy and just now
from a rested, cold, clean start.

The exact same scalactic code compiles against SN 0.4.0-M2. Both the scalactic and
scalatest TestRunners complete successfully.

I suspect that this is a name-mangling or inline bug.

The relevant code in java.nio and scalanative/mumble/io/package.scala has not changed in over two years. java.nio.ByteBuffer.clear() exists in the source file (and is probably heavily used by the SN compiler backend).

The error & top of the stack trace:

## Exception when compiling 83 sources to /mnt/QuincyQHdd1/lee49/DevoHdd1/scala_native/WorkSpace_1/debug_SN_ScalaTest_Failure_I1400_V3_SN-0.4.0-SNAPSHOT/scalactic-macro.native/target/scala-2.11/classes
[error] java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
[error] scala.scalanative.io.package$.withScratchBuffer(package.scala:15)
[error] scala.scalanative.nscplugin.NirGenFile$class.genIRFile(NirGenFile.scala:30)
[error] scala.scalanative.nscplugin.NirGenPhase.genIRFile(NirGenPhase.scala:12)
[error] scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$2.apply(NirGenPhase.scala:91)
[error] scala.scalanative.nscplugin.NirGenPhase$NirCodePhase$$anonfun$apply$2.apply(NirGenPhase.scala:89)
[error] scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)

I know of no way to cut this down to the ever valuable small reproducer.

**Comment by WojciechMazur** [comment]
I've run scalacticTestNative tests today with scala 2.12 (2.13 has some dependency problems, eg. with XML). It looks to be working, so this issue is probably outdated.  Also `genIRFile` no longer issues buffers. 
PS. I've seen there were multiple problems with `ClassCastExceptions`, but it's already fixed in #1952
