### ISSUE TITLE
Possible compiler issue with named parameters

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#1677]
While working on the split of `javalib` into multiple libraries I found this issue.
`java.net.URI` is located in the `javacorelib` and `FileSystems.scala` is located in `javafilelib`, so this code doesn't work there:
```Scala
(new UnixFileSystemProvider).getFileSystem(
      new URI(scheme = "file",
              userInfo = null,
              host = null,
              port = -1,
              path = "/",
              query = null,
              fragment = null))
```
but this code works fine:
```Scala
(new UnixFileSystemProvider).getFileSystem(
      new URI("file", null, null, -1, "/", null, null))
```

**Comment by WojciechMazur** [comment]
Not an issue. After split `URI` is resolved based on provided JDK instead of Scala class defined within the project. Java does not provide named parameters and though leads to compile error.
