### ISSUE TITLE
Scala-native compiler doesn't respect `private[..]` across projects with same scope

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#1678]
Two scala files from `javacorelib` and `javafilelib` are in the same package `java.nio`.
One has keyword on the method: `private[java]` def lines(...` and another file doesn't see this method.

**Comment by sjrd** [comment]
That is expected for the JDK classes, because under separate compilation we use the .class files of the JDK, rather than the ones generated by the Scala compiler. Any API that is not part of the document JDK APIs (even public members) is not visible in other projects.
