### ISSUE TITLE
CFuncPtr2 doesn't capture local variables

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#1679]
I found that this code doesn't work, because it captures `null` for `envmap`:
```Scala
private object SystemImpl {
  def loadAllEnv(): Map[String, String] = {
    val envmap = new HashMap[String, String](Platform.getAllEnv(null))
    Platform.getAllEnv(new CFuncPtr2[CString, CString, Unit] {
        def apply(key: CString, value: CString): Unit =
          envmap.put(fromCString(key), fromCString(value))
      })
    Collections.unmodifiableMap(envmap)
  }
}
```
But this code works fine, it captures object scope ( I moved `envmap` into object scope):
```Scala
private object SystemImpl {
  val envmap = new HashMap[String, String](Platform.getAllEnv(null))
  def loadAllEnv(): Map[String, String] = {
    Platform.getAllEnv(new CFuncPtr2[CString, CString, Unit] {
        def apply(key: CString, value: CString): Unit =
          envmap.put(fromCString(key), fromCString(value))
      })
    Collections.unmodifiableMap(envmap)
  }
}
```
`Platform.getAllEnv` just returns number of env variables and it calls CFuncPtr2 for each pair

**Comment by lolgab** [comment]
`CFuncPtr`s don't capture local variables by design.

**Comment by muxanick** [comment]
How does it capture things in object scope? because it's a global variable?

**Comment by lolgab** [comment]
Yes only global variables of objects (not classes or traits) are accessible.

**Comment by lolgab** [comment]
I think this Issue can be closed. The behaviour is the one expected from `CFuncPtrN`.

**Comment by sjrd** [comment]
Yes, although we should really report a compile error in this situation.
