### ISSUE TITLE
Future question

### ISSUE THREAD

**Issue by eed3si9n** [scala-native/scala-native#1682]
I tried to unstub Future in https://github.com/scala/nanotest-strawman/pull/16 following monix/minitest#41, but it doesn't seem to work.

**Comment by densh** [comment]
Similarly to Scala.js, we have a single hardware thread at the moment. So `Await.result` naturally isn't supported because if you wait on a single thread you block that thread. This means that event loop never gets a chance to run any more futures while you wait so it's guaranteed to time out.

**Comment by eed3si9n** [comment]
I am not familiar with the implementation of Scala.JS scalalib override, but minitest works ok on Scala.JS, and so did Minitest's Future/Promise/Await stub.

```scala
object Future {
  def apply[A](f: => A): Future[A] =
    new Future(Try(f))

  def successful[A](value: A): Future[A] =
    new Future(Success(value))

  def failed[A](e: Throwable): Future[A] =
    new Future(Failure(e))
}
```

**Comment by eed3si9n** [comment]
Here's a workaround that seems to work for me:

```scala
object Await {
  def result[A](future: Future[A], duration: Duration): A = {
    scala.scalanative.runtime.loop()
    future.value.get.get
  }
}
```

**Comment by lolgab** [comment]
Very nice workaround! Thank you.
