### ISSUE TITLE
Implement suppression for Throwable

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#1683]
During the porting of https://zio.dev/ to Scala Native I [faced](https://github.com/zio/zio/blob/222999eaacb43630bf373d6e0225a3d444bd4ab0/core/shared/src/main/scala/zio/FiberFailure.scala#L27) the lack of:
```java
protected Throwable(String message,
                    Throwable cause,
                    boolean enableSuppression,
                    boolean writableStackTrace)

```
constructor with the `enableSuppression` flag.
https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html

**Comment by LeeTibbert** [comment]
Progress:  I have first generation code which passes test-all and arm's length code review.

                 The next step is to write ThowablesSuite.scala to test the constructors and
                 thirteen methods of the class.  In particular, the two new Java 8 (well, Java 7)
                 methods I added need to be tested to ensure they meet the specification..

**Comment by sjrd** [comment]
Don't forget that we've got it all in Scala.js, available for reuse. Implementation and tests.
* https://github.com/scala-js/scala-js/blob/7c502f61c87735898c2293cb937eee8f55ad8686/javalanglib/src/main/scala/java/lang/Throwables.scala
* https://github.com/scala-js/scala-js/blob/7c502f61c87735898c2293cb937eee8f55ad8686/test-suite/shared/src/test/require-jdk7/org/scalajs/testsuite/javalib/lang/ThrowablesTestOnJDK7.scala#L64-L106

**Comment by lolgab** [comment]
Thank you @sjrd 🎉
