### ISSUE TITLE
Commix function points to Immix

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#1684]
I don't know if it is used at all, but this should be a typo. 
https://github.com/scala-native/scala-native/blob/b650b901f2efc765315b16e618176f96ce52385f/tools/src/main/scala/scala/scalanative/build/GC.scala#L37

**Comment by densh** [comment]
It's indeed not used at the moment. Sbt plugin uses `apply` construtor which is correct. Thanks for the report!
