### ISSUE TITLE
A j.l.ProcessSuite test case & LTO do not play together nicely

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1687]
##### Presenting problem

A test case in java.lang.ProcessSuite crashes the entire test-runner environment
when built & run with LTO=;"thin".  The problem I am reporting is an apparent
failure with LTO. The fact that the entire test-runner environment crashes without
a useful report is a sequela. 

The failing test is `addTest("waitFor with timeout times out")`. Note the `addTest`.

```
$ printenv | grep -i scalan
SCALANATIVE_LTO=thin
SCALANATIVE_MODE=release-fast

// Defined $PATH to pick up Java-8 JVM first. Checked using SBT console.

// Did a complete rebuild.  This is cargo cult programming, I do not know if
// rebuild with "release-fast" does anything useful.

// ran sbt `test-all`.  Failed in ProcessSuite with bunches of misleading shrapnel.
// The Null Pointer Exception reported is a known (to some) test-runner flaw., not
// the underlying failure in ProcessSuite.

// In sbt,  ran `tests/test-only *ProcessSuite`,
```

###### Environment
The problem was discovered in a more complicated and divergent environment.
I have replicated in a stock Java 8 environment using Clang 8.0.1 and a fresh 
clone of the SN GitHub repository.

 Linker was build.sbt standard, there was now change for this replication.

##### Discussion

The two major reasons that I think that this is an LTO bug is that ProcessSuite has
been running with`release-fast`, no LTO,  on Travis for months now.   Several
months ago ProcesSuite did reveal a bug in Clang. I believe this is not that bug.

The second reason is that perturbing the micro-environment of the test causes
the test to succeed.  Now, this in in a section of code with pretty tight timing,
so one must be careful that one not mistaking a change in timing for a change
in code generation or visa versa:

1) The simplest change is do an unused capture of the result of the proc.waitFor:
```proc.waitFor(1, TimeUnit.SECONDS)``` 
   changes to  
```val workaroundLtoBug = proc.waitFor(1, TimeUnit.SECONDS)```

2) Alternately, adding a printf() statement before the final closing brace causes
    the test to succeed.

3) Probably more relevant is that changing the ``addTest` to the more usual 
    `test`.  addTest is prior art in that file.  It is defined as:
```
 // This makes it easy to decorate the test for debugging                      
  def addTest[R](name: String)(f: => R): Unit = test(name) {
    f
  }
```
I did take a look at the generated output in the .ll files.  I think I located the failing 
section, but was unable to pin down the what & why of the failure. Room for me to grow.

**Comment by muxanick** [comment]
I don't know if that would be relevant to this issue, I found that on Windows it's not possible to use different optimization clang arguments for different libraries, otherwise random crash, usually around memory allocations.
For instance currently `nativelib` always use `-O2` optimization, and if you application/test uses different optimization switch then it's high chance of crash, depends on the system.
So, on Windows I made this optimization switches consistent across whole project, so LTO could proceed nicely.

**Comment by LeeTibbert** [comment]
@muxanick Thank you for pointing out the "gotchas".

Sounds like I did not properly explain in the base note that I was running matched
"rebuild" & "test-all", each built with "release-fast" & "lto=thin".   I was using the
default Clang optimization levels.

**Comment by WojciechMazur** [comment]
After this test was ported to JUnit it looks to be working just fine with LTO. It might be a good idea to reproduce it in a similar case or close this issue. However, it would be great if we could go with the first option.

**Comment by LeeTibbert** [comment]
@WojciechMazur Thank you for the Issue & PR cleanup.

To answer your question at the lowest level. The `has PR` label referred
to PR #1823.  I see that you have, reasonably, closed that PR, so I will
close this issue.

I think there is an outstanding Issue dreaming about a periodic, not every commit,
run with LTO & release-fast.  I am deep into a series of JavaDefaultMethod changes
and will not be able to get to that for a long while (months).  

I understand intensely that not everything can be done at once.  At a place where
I  received most of my experience we had a saying "He/she who proposes, disposes".
Ball is in my court, but I have no problem is somebody else creates a periodic
LTO validation run first.

For the audit trail, I suspect that the change to JUnit had little or nothing to do with
fixing the problem reported here, although it has had other benefits.   I also suspect
that the long string of ProcessTest/ProcessSuite PR to date has also had little to do.

I suspect that there was a fix for something else at some point in nscplugin that had
the side effect of fixing the problem of this report.  I can not even hazard a guess as
to when that positive change may have occurred.
