### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by XVilka** [scala-native/scala-native#1704]
There are tons of fixes recently https://github.com/scala-native/scala-native/pulls but nobody makes a review or merge.

cc @densh @ekrich @kornilova-l @MasseGuillaume @jonas

**Comment by LeeTibbert** [comment]
@XVilka 

Thank you for your interest in Scala Native. The project is alive, well, and making
progress. The (gitter)[https://gitter.im/scala-native/scala-native] channel has active
discussions.  Check it out to see the gears in motion.

One can accomplish quite a bit with the 0.4.0-M2 mainline or the latest 0.3.9 release.
If you can not get down what you need to do, cry out!  You can probably get a reading
pretty quickly ranging from "That is Bigger Than A Breadbox (multi-threading)" 
to  "Could you try this patch?".

The project is a volunteer, not commercial, effort. You are absolutely correct that review
time is a critical resource. Finding & growing competent reviewers is a hard process. Once
they are found, the trick is to keep from burning them out.

The review process is through, and consequently slow, so  to drastically reduce the chance of a bug getting released into the wild and costing people wasted time.

**Comment by XVilka** [comment]
Thank you for the answer!
