### ISSUE TITLE
Cache instances of java.lang.Class

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#172]
https://github.com/scala-native/scala-native/pull/171/files/e33b209d08641a892023211d5e16e37048d30d2e#r66837331

**Comment by hardmettle** [comment]
Hi @densh , can I get a bit of more detail as to what needs to be done? and how is it related to #171 ? Would like to take it on from there.

**Comment by densh** [comment]
@hardmettle java.lang.Class is a thin wrapper over `Ptr[scanative.runtime.Type]` (aka RunTime Type Information or RTTI). The problem we have now is that we allocate new instance, every time we do `obj.getClass`. To fix it there has to be a cache that makes sure we return the same exact class instance per RTTI value (which are unique per type already.)

**Comment by WojciechMazur** [comment]
Duplicates #1435
