### ISSUE TITLE
SN build should be upgraded to current sbt 1.3.9

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1747]
PR #1712 upgraded the SN build to use the then current sbt 1.3.7. Sbt 1.3.9 has since been
released. I have seen no problems in the build with 1.3.7 but think it worth my time and the time of others to upgrade to sbt 1.3.9.

This issue supersedes #1733.

**Comment by errikos** [comment]
I wonder if we should also bump `sbt10Version` in `build.sbt`. It should be safe.

**Comment by lolgab** [comment]
@errikos There was already a discussion [here](https://github.com/scala-native/scala-native/pull/1712#discussion_r372290437) why not update `sbt10Version`.

**Comment by errikos** [comment]
Okay, thanks for the answer!

I am closing this, since the SBT version for the build is already 1.3.10.
