### ISSUE TITLE
Build.sbt should automagically reload.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1750]
Now that the Scala Native build using an sbt >= 1.3.8, it would be nice for
the build have a way for individual developers to locally opt-in to
sbt automagically reloading on build changes.

The now closed PR #1776 attempted to add `Global / onChangedBuildSource := ReloadOnSourceChanges` to build.sbt for all users.  @sjrd pointed out
that this would make life difficult for people working on the sbt plugin itself.
Those sources would be watched by onChangedBuildSources and trigger
annoyingly. 

He suggested the approach of this PR, which is to edit .gitignore to
ignore any local.sbt file in the project root. That way, an individual
developer could create that file with the command above and any
other desired local customization.    Such a file could be kept
in the local fork repository.

If sbt is running when the local.sbt is created or dropped in, will need
to be manually reloaded to pick up the change. Annoying, but it makes
sense.

**Comment by sjrd** [comment]
Addressed by a5d18d12a52e2ab2bd1a7274d649f0eb52837c03.
