### ISSUE TITLE
Segfault when current directory unlinked

### ISSUE THREAD

**Issue by avdv** [scala-native/scala-native#1768]
Hi.

# Steps to reproduce:

1. compile 

```scala
object Main {
  def main(args: Array[String]): Unit = {
    java.nio.file.Paths.get(".")
  }
}
```

2. run

```console
$ mkdir testdir
$ cd testdir
$ rm -r ../testdir
$ project-out
[1]    24245 segmentation fault (core dumped)  project-out
```

I fixed this for my private branch here: https://github.com/avdv/scala-native/commit/939a12916ba5e25e3d7b1603b5d65cfd4e23cbd9

**Comment by ekrich** [comment]
According to my reading of the test on JVM, this happens on startup.

Note: starting a JVM in an unlinked directory, results in an Error:
```
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
at jdk.internal.util.SystemProps$Raw.platformProperties(java.base/Native Method)
  at jdk.internal.util.SystemProps$Raw.<init>(java.base/SystemProps.java:241)
  at jdk.internal.util.SystemProps.initProperties(java.base/SystemProps.java:54)
  at java.lang.System.initPhase1(java.base/System.java:1997)
```

**Comment by avdv** [comment]
> According to my reading of the test on JVM, this happens on startup.

Yes, the JVM exits directly on startup. But it does not segfault.. 

> Note: starting a JVM in an unlinked directory, results in an Error:

Yes, that's what I found too. (see the commit I mentioned)
