### ISSUE TITLE
unit-test project should enable scalac deprecation checking

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1777]
PR #1752 enabled scalac deprecation checking for most sub-project of the Scala Native
root project.  Such checking was not enabled for the unit-test project.  Software engineering
considerations suggest that enabling such checking would be a Good Thing, someday.

This issue is a forget-me-not and captures some considerations as to why enablement
is not simple and done by now.

I am looking and asking for thoughts, suggestions, recommendations, directions, etc.
as time may allow. Thank you.

The review process for PR #1752, revealed that deprecation in unit-tests has considerations:
deprecation in the unit-test code itself and the requirement that unit-test test deprecated
API entry points.

Currently unit-tests contains only one test which tests a deprecated API, one of the
overloads of String.getBytes() which has been deprecated since JDK 1.1.  The addition
of deprecation checking must assume and be robust to other tests checking deprecated
API items.

The canonical answer is to use the `@nowarn` annotation from the 5 year tested `silencer`
plugin.  That annotation has been adopted by Scala 2.13.2, so it is on the path of progress
and enlightenment.  The plugin is once more available for Scala 2.11 and has been widely
available & exercised on Scala 2.12.

A compounding factor is that the `silencer` plugin requires `scala-collection-compat`.
That is in the direction of progress, but might introduce change to the current codebase.

I could do a pre-PR engineering study to see exactly how difficult this path is.

The final compounding factor is that the testing framework is about to undergo huge change.
Ordinarily I would add the deprecation checking to the existing code (via one `@nowarn("deprecation")` so that deprecated code is not used in the new/replacement
unit tests.   In this case, I think it prudent to wait until the changes_in/replacement_for
unit-tests is better defined.  I do not want to invest time & effort in something that is
going to be superseded in the entirety.

**Comment by sjrd** [comment]
One thing I can already tell: using `scala-collection-compat` will not be possible. scala-collection-compat depends on Scala Native, so Scala Native cannot depend on scala-collection-compat.

It may simply not be possible to use silencing of warnings, which means that we won't be able to enable `-deprecation` in the test suite.

I do not necessarily see this as an issue. After all, I consider it *expected* that a test suite has to test deprecated APIs (and deprecated language features, in our case).

**Comment by LeeTibbert** [comment]
Thank you for the info about `scala-collection-compat`. You saved me cycles I would rather invest
elsewhere.

Sounds like this topic should be punted until Scala 2.13.2 support is available.
