### ISSUE TITLE
@struct's must box when they escape to generic context

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#178]
Currently we're unsound here, pointers just leak to generic context and might crash if a method like `toString` is called on them (as they might not have correct RTTI necessary for a virtual call to happen). The unsoundness is caused by the fact that from scalac's point of view pointers and structs are normal reference types.

**Comment by DarkDimius** [comment]
@densh, you may consider piggy-backing on value classes here, as they would be boxed if they enter generic context.

**Comment by densh** [comment]
Fixed in #1426
