### ISSUE TITLE
Add progress bar to CloneCommand

### ISSUE THREAD

**Issue by hepin1989** [scala-native/scala-native#1781]
```scala
          // Clone scala source code
          new CloneCommand()
            .setDirectory(trgDir)
            .setURI(scalaRepo)
            .call()
```
refs:https://download.eclipse.org/jgit/site/5.1.1.201809181055-r/apidocs/org/eclipse/jgit/api/CloneCommand.html

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/81436534-3d719100-919c-11ea-8f42-372f18950106.png)
Can only get it working from monitor

**Comment by sjrd** [comment]
We should copy how Scala.js does it:
https://github.com/scala-js/scala-js/blob/8dc581072cc47ded199a0b497ff5283de1ed89c2/project/Build.scala#L1125-L1170

**Comment by hepin1989** [comment]
Yes, Tested it locally
