### ISSUE TITLE
Upgrade scalafmt to 2.5.2 and add scalafmt support

### ISSUE THREAD

**Issue by hepin1989** [scala-native/scala-native#1787]
Currently ,seems like I have to call the `scalafmt` command instaead `scalafmtAll` in sbt

**Comment by LeeTibbert** [comment]
Good idea.   I have taken a couple or three runs at this over the past few months.

There are at least three considerations here:
1) There is a scalafmt bug, still present in 2.5.1 (2.5.2 is a few hours old. I checked the release
    notes but it not listed as fixed, I think the scalafmt people think it got fixed in 2.5.0). 
    This bug causes scalafmt to blow up with "Search state exploded" in NirGenExpr.scala.
    That is annoying but OK with the script.  When using the plugin with the new (and I believe
     desirable) -Xfatal-warnings, the sbt command, rightly, fails after the error.

      I will propose a short term solution on gitter and ask permission to PR.
      
       @ekrich and I have had several discussions about this over the past several months.

2) I believe that @ekrich has done some trial work in this error and the recent scalafmt
    causes a set of format changes which need detailed attention. Something like the 
    case of hexadecimal digits or the trailing L or ell.  Thank you @ekrich for all of your
    careful work in this area.

3) It is not a show stopper but  something of which people should be aware.   Currently
    the scalafmt version is defined in two places.  This has kept me from adding 
    scalafmt support before.

    The version is defined in .scalafmt.conf and in scripts/scalafmt. It is already the case that
     the person changing the scalafmt version must know to change it in two places. Or at
     least one of the reviewers or followers of the PR stream. 

    The scalafmt plugin has a version of its own which picks up the scalafmt version to run from,
    as expected, .scalafmt.conf.  Adding the scalafmt plugin by itself does not change  the 
    current "Two points of Truth" situation, but it does introduce the failure path of a user of the
    scalafmt plugin knowing about and changing only one of the two points.  We can not live
    in fear of the uninformed, but should be aware of failure paths.  Bugs are so clever at sneeking
    in.

**Comment by ekrich** [comment]
@hepin1989 Thank-you for adding this issue.

We recently just upgraded `scalafmt` which was quite difficult and introduced quite a few diffs. @sjrd recommended we hold off on the next round due to it being better easier to rebase outstanding PRs and the newer `scalafmt` is more accurate thus adding a bunch of new diffs.

Overall, we want to keep the `.scalafmt.conf` file as simple as possible because maintenance becomes more difficult as the configuration gets more complex.

The following are the additions that were prototyped for `2.5.x`.
```
# default is 513 - NirGenExpr.scala error gone between 18000 and 20000
runner.optimizer.maxVisitsPerToken = 20000
# add to literals section
literals.hexPrefix = unchanged
literals.hexDigits = unchanged
literals.scientific = unchanged

In addition, removing the `hex` formatting introduces another whole bunch of changes but makes everything standard.
```

**Comment by hepin1989** [comment]
@ekrich the hexDigits even set to `Unchanged` but will not take effect?

**Comment by ekrich** [comment]
I have reopened discussion on this topic because we really need to do something.

>Scala Native developers. As we get closer to Scala 3, I would like to see if we can get Scalafmt updated. Eventually, we will need the latest. I think we can get to a more normal format hopefully closer to the new Scala 3 style. We can deal with a few changes at a time which I think will be easier for people to adapt.

>If we can agree to make some changes to the current config that will allow us to upgrade without a ton of changes I think that would be good. The first thing I would like to do is to drop the align of =. This change would mean that when someone changes and identifier then all the nearby lines won't change. Aligning creates noise - the other thing is the alignment tends to create extra line wraps when the alignment forces things to the right. If we do some changes little by little it'll make it easier on people with open PRs.

>Right now, just upgrading changes tons of thing but I will try and minimize disruption getting to a current version. For example, in later versions, the line wrap is super strict - exactly 80 chars and makes bunches of changes.

>Let me know what people think.

One answer: 
>I'm definitely in favor of dropping the alignments. @sjrd

**Comment by WojciechMazur** [comment]
Outdated, we upgraded scalafmt to 3.0.0-RC6 recently in #2315
