### ISSUE TITLE
Add validatePullRequest task

### ISSUE THREAD

**Issue by hepin1989** [scala-native/scala-native#1788]
as Akka does:
```> validatePullRequest```

refs:https://github.com/akka/akka/blob/master/CONTRIBUTING.md#the-validatepullrequest-task

**Comment by sjrd** [comment]
We cannot do this. We have too many configurations that total way above the allowed running time of a Travis build. We *need* to keep things separated in several invocations that sbt that we can split across the Travis matrix.
