### ISSUE TITLE
compilation error: Classpath.scala:20: value walk is not a member of object java.nio.file.Files

### ISSUE THREAD

**Issue by benkob** [scala-native/scala-native#179]
error-message: 
--------------------
error] /Users/ben/local/scala_native/scala-native/tools/src/main/scala/scala/scalanative/linker/Classpath.scala:20: value walk is not a member of object java.nio.file.Files
[error] possible cause: maybe a semicolon is missing before `value walk'?

(entire log see below)

specs:
---------
sbt: sbt-0.13.11.

java -version
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)

mac:
:~ ben$ system_profiler SPSoftwareDataType
Software:
      System Version: OS X 10.9.5 (13F34)
      Kernel Version: Darwin 13.4.0

error-log
-----------
sbt rtlib/publishLocal nscplugin/publishLocal
[info] Loading project definition from /Users/ben/local/scala_native/scala-native/project
[info] Compiling 63 Scala sources to /Users/ben/local/scala_native/scala-native/project/target/scala-2.10/sbt-0.13/classes...
[error] /Users/ben/local/scala_native/scala-native/tools/src/main/scala/scala/scalanative/linker/Classpath.scala:20: value walk is not a member of object java.nio.file.Files
[error] possible cause: maybe a semicolon is missing before `value walk'?
[error]       .walk(path, Integer.MAX_VALUE, FileVisitOption.FOLLOW_LINKS)
[error]        ^
[error] /Users/ben/local/scala_native/scala-native/tools/src/main/scala/scala/scalanative/linker/Classpath.scala:37: value walk is not a member of object java.nio.file.Files
[error] possible cause: maybe a semicolon is missing before `value walk'?
[error]               .walk(path, Integer.MAX_VALUE, FileVisitOption.FOLLOW_LINKS)
[error]                ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by densh** [comment]
Hi, @benkob. You need to run sbt under Java 8+ to compile code with Scala Native.
