### ISSUE TITLE
build.sbt scalalib compile should close Git object after clone

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1792]
Recently @hepin1989 (kerr) & kerr's colleges reported issues with building scalalib
over slow communication links.  I hope to open another Issue for that topic once
I have poped a few topics, like this one, off my interrupt stack.

Kerr helpfully narrowed down the source of the CloneCommand to the jgit artifact.
I spent some time studying that API to see if there was a way to reduce the amount
of data sent over the line; either directly or by compression.  We really do not
need history back to the Creation, as the Scala 2.11.0 source is basically frozen and
used read-only by SN.  Reducing the amount of data sent is one of two classical
go-to solutions for the reported problem.  The other is the famous "Buy a faster network link".
The latter is not really appropriate in this case.  I can empathize because I of earlier
jobs I have held.

The jgit API has a clear, bold, notation that the Git object returned by CloneCommand
should be explicitly closed once done to prevent a file descriptor leak.

I have never encountered such a leak in the wild.  More likely, I may have experienced it
but not recognized it.

Clean living is, IMHO, worth the review time, even if this is only of middling importance.

**Comment by sjrd** [comment]
This wouldn't be necessary if we address #1782.
