### ISSUE TITLE
jgit should be updated to current 5.7.0 release

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1793]
This issue is independent of but related to issue #1792.  While studying that issue, I
noticed that project/build.sbt is using jgit artifact "5.5.1.201910021850-r" and not the current 
"5.7.0.202003110725-r".

Not the most critical of issues, but easy enough to fix. I have encountered no explicit problem,
but it would be nice to pick up 5 months of fixes.  New bugs are almost always more interesting
than old.

**Comment by sjrd** [comment]
This wouldn't be necessary if we address #1782.

**Comment by LeeTibbert** [comment]
I have the PR all tested and ready to fire off. 

I suggest that it can earn its review cost while #1782 gets addressed but I will hold off.

The port for #1782 looks like a cut & paste of proven but one must always beware of
 hidden complexity.

I have several front burner issues I need/want to make progress on to fulfill promises, so I
can not volunteer to fix #1682 now.

**Comment by LeeTibbert** [comment]
Made obsolete by PR #1799, which addresses issue #1782
