### ISSUE TITLE
build.sbt scalalib CloneCommand would benefit from progress meter

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1795]
The background is that kerr (@hepin1989) and kerr's have been slowed down is their
adventures with building SN by the CloneCommand taking a very long time over
their slow network link.  

Study & discussion is ongoing, interleaved with other issues; Work in Progress.

Even over a relatively fast, but non-local link, the CloneCommand takes slightly
more than a minute.  That is far beyond the 2 second mark I have bee taught
for interaction without feedback.  It is even further from the current, I am told, 0.5
second recommendation.  Act or give feedback within this tolerance.

The jgit CloneCommand allows at least one mechanism for providing a callback
to give progress.   I did not have time to sandbox it but it looks promising for 
providing a simple text progress meter.  I, or someone faster than me, would have to
check how this played with various IDEs.

**Comment by sjrd** [comment]
This wouldn't be necessary if we address #1782.

**Comment by LeeTibbert** [comment]
Made obsolete by PR #1799, which addresses Issue #1782
