### ISSUE TITLE
Test runner does not run all tests after buggy test

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1809]
Issue #1796 describes a situation where fromCString(null) throws a RuntimeException.  In sandboxing the proposed fix to that issue, I wrote unit-tests. Replicate the problem, then verify the fix.

Running the unit test before any fix helped me capture a situation I have encountered many
times.  First one must ignore the dreaded "java.net.SocketException: Socket closed" error
described in Issue #1585.  I am hoping to fix that before the snow flies.

The problem that I am trying to describe here is that the test runner runs only the tests before
the test which throws the uncatchable RuntimeException.  
In my sandbox, file `scala.scalanative.unsafe.CStringSuite` holds 6 tests, only 2 are 
executed:
```
[info]   [ok] c"..." literals with various escapes
[info]   [ok] the value of c"..." literals
```
I suspect, but have not tried, that if I had more Suites, none of them would be executed.

I believe this is a years old "design feature" and has nothing to do with the recent Reflections
changes.

I have a pretty intimate knowledge of the test-runner and understand why the SN binary dying
quietly in the night, without even a goodbye note is happening. 

There is an execution cost to running each test in its own process or jail.  If, as I suspect,
later Suites are also not run, perhaps the appropriate level of granularity is to run each
Suite in its own process or jail.

The reason that I am trying to capture this issue, is that people adopting SN are likely to 
be running tests and there are likely to be fatal defects in those tests.  At least giving
__some__ idea of what went wrong would be welcoming.  I know that I have certainly
provoked this bug many a time (slow learner).

Perhaps when I am able to clear away some of the known issues in Issue #1585 a path will
clear to have the SN binary (a binary process running a subprocess) return a reasonable
message for why its child died.  Yes, added complexity.

**Comment by LeeTibbert** [comment]
To try to crystalize my discomfort with not all tests being run.
The situation is that the test run presents as all green, or all acceptable
when it has, in fact, failed.  This leaves a person or program checking
the results of the run needing to know how many tests should have run
but did not.   That is, the failure is not face evident.

**Comment by sjrd** [comment]
We should definitely fix this. I guess the `NativeFramework` or one its components (like `NativeTask`) fails to catch some exceptions thrown by the tests. Hence instead of reporting the exceptions as test failures and continue, it crashes, preventing the execution of further tests.

**Comment by errikos** [comment]
I can't seem to be able to replicate this issue on latest `master`. Running:
```
sbt "tests/testOnly scala.scalanative.unsafe.CStringSuite"
```
Runs all 4 testes in that suite:
```
[info] * scala.scalanative.unsafe.CStringSuite$
[info]   [ok] c"..." literals with various escapes
[info]   [ok] the value of c"..." literals
[info]   [ok] fromCString
[info]   [ok] toCString
[info] Passed: Total 4, Failed 0, Errors 0, Passed 4
```

**Comment by LeeTibbert** [comment]
Ergys, 

Thank you for looking at this.  Sorry if I was not clear in my base note. I was able to 
capture in private (sandbox) code a problem which comes and goes in the wild.
Mostly it happens in development, as unit tests are developed & debugged.

I concur that it does not happen in mainline. The bug is there, but nothing 
which provokes it is allowed into mainline.

```
. In sandboxing the proposed fix to that issue, I wrote unit-tests.
 Replicate the problem, then verify the fix.
...
The problem that I am trying to describe here is that the test runner runs only the tests before
the test which throws the uncatchable RuntimeException.
In my sandbox, file scala.scalanative.unsafe.CStringSuite  holds 6 tests, only 2 are executed:
```
Try adding the test case:

```
 // Issue 1796                                                                 
  test("fromCString(null)") {
    val szTo     = fromCString(null.asInstanceOf[CString])
    assertEquals(szTo, null.asInstanceOf[String])
  }
```

I am currently in ComRunner.scala & its caller ScalaNativeRunner.scala.  I hope to
submit 2 or 3 PRs by the end of the American long weekend. One of those might
not fix the condition here, but might offer an _ugly_ way of making the situation
detectable to monitoring people and/or software.

I believe the highest & best fix requires one or more pretty extensive architectural
changes.  The issue becomes, I think, what can we do to make the situation
better until those changes appear.

If you can wait a few days, I can save you days of debugging and headaches.
The least is that you would be able to see the proposed changes and say "Oh 
that is where part of the problem is. I see, but those changes are not acceptable".
Easier for me to make the point changes in a proposal than for me to try to describe
them.

I have some of the changes working in said sandbox, and am working to get them
to the point where I can present them, even at WIP quality.

**Comment by LeeTibbert** [comment]
For the curious, part of the problem is that test-runner tries to recover from 
network errors and does things after the exception which should be changed.

After the SN binary throws RuntimeException and dies, dropping the link.
ComRunner.scala correctly detects the dropped link, closes the socket, and
re-throws the exception.   Then a handler above catches the exception 
and calls the ScalaNativeRunner code:
```
 override def done(): String = {
    send(Command.RunnerDone(""))
    val Command.RunnerDone(summary) = receive()
    master.close()
    summary
  }
```
Send on a closed socket is bad enough, but it is the receive() on a closed socket which
causes the cascade of shrapnel.   That silliness can and should be prevented.

It does nothing to solve the issue in the SN binary in that it does not catch RuntimeException
in one of the tests it is running (or elsewhere, if it should happen in its own code.).  It just
dies silently in the night, leaving the end user with no clue (beyond "What have i last touched?")

So, if you please, let me take a run at clearing some of the shrubbery on the SBT side so
that the underlying issue of the base note in the SN binary may become clearer.  

I think it will help.  Of course, if I am getting in the way, my words, not yours, let me know
and I will do other things.

**Comment by LeeTibbert** [comment]
### Status update: 

I have been able to further characterize the behavior in a private project with WIP PRs #1812 & 
#1813 applied.  Those PRs are awaiting comment/review. They clear away some of the
"Socket closed" distraction.

##### Goal:
My working goal is to reveal to the developer the RuntimeException which I believe to 
high certainty is being thrown by my specially crafted CStringSuite. Thanks @david-bouyssie
for first describing the behavior that test captures. I am expecting/hoping to see a stackTrace
generated in the Scala Native binary.

#### Results to date:
##### Single suite; tests/testOnly *CStringSuite
```
[info] * scala.scalanative.unsafe.CStringSuite$
[info]   [ok] c"..." literals with various escapes
[info]   [ok] the value of c"..." literals
[error] Error: Total 3, Failed 0, Errors 1, Passed 2
[error] Error during tests:
[error]         scala.scalanative.unsafe.CStringSuite
[error] (tests / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
```
Note well:  One needs to have special knowledge that the Suite contained 6 tests.
                  The output correctly identifies that the Suite failed, but identifies only 3 of the 6
                  tests.  It also does not give the reason (RuntimeException) for the failed test
                  or the stackTrace.  This is better than "Socket closed" but still leaves a devo
                  needing to figure out that it was the last test that failed and without a clue
                  as to why.   `last tests / Test /testOnly` produces no additional useful information.

##### Many suite; tests/testOnly tests/testOnly scala.scalanative.unsafe.*
Many leading successful tests elided
```
[info] * scala.scalanative.unsafe.CStringSuite$
[info]   [ok] c"..." literals with various escapes
[info]   [ok] the value of c"..." literals
!! LeeT:  Note missing information here!
[error] Error: Total 171, Failed 0, Errors 15, Passed 156
[error] Error during tests:
[error]         scala.scalanative.unsafe.TagSuite
[error]         scala.scalanative.unsafe.SizeofSuite
[error]         scala.scalanative.unsafe.CArrayOpsSuite
[error]         scala.scalanative.unsafe.CFuncPtrBoxingSuite
[error]         scala.scalanative.unsafe.PtrBoxingSuite
[error]         scala.scalanative.unsafe.NullPointerSuite
[error]         scala.scalanative.unsafe.ExternSuite
[error]         scala.scalanative.unsafe.CArrayBoxingSuite
[error]         scala.scalanative.unsafe.AsInstanceOfSuite
[error]         scala.scalanative.unsafe.PtrOpsSuite
[error]         scala.scalanative.unsafe.IsInstanceOfSuite
[error]         scala.scalanative.unsafe.CFuncPtrOpsSuite
[error]         scala.scalanative.unsafe.CStructBoxingSuite
[error]         scala.scalanative.unsafe.CStructOpsSuite
[error]         scala.scalanative.unsafe.StackallocSuite
[error] (tests / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
```
Note well:  
1) The line I added "Missing information"
2) The fact, mentioned as a suspicion in the base note as a suspicion, that Suites after the
     faulting one are not executed.
3) The faulting test is not listed in the "Error during tests" section.

**Comment by LeeTibbert** [comment]
#### Working hypothesis

For a number of years now I have been plagued by the fact that printfs do not work in 
unit-tests.  They seem to get re-directed to somewhere and I have never been able, mea culpa,
to find that somewhere. I suspect the black hole at the center of the Milky Way.

Based on the work above & some more debugging, my current working hypothesis is that something 
in TestMain.scala or called by it is re-directing the  RuntimeException and stackTrace thrown
by my custom CStringSuite.scala is to the same or a similar less-than-informative place.

I had two earlier hypotheses. One was that TestMain was properly sending information about
the RuntimeException back to sbt but that it was getting lost in the "Socket closed" tangle.
The second hypothesis was that the RuntimeException information was not being sent over
the wire by TestMain.

Current evidence seems to indicate that the first hypothesis proves false.  printf statements
early in TestMain get displayed on the sbt side, as one would expect.  Indeed printf statements
in the Command processing loop before and after a certain point in Command.Execute
appear over the wire.

That leaves hypothesis 2. That hypothesis splits into two. 2A says that the RuntimeException
is never generated. Hard to believe.  Hypothesis 2B says that it is generated but never sent
over the wire.
##### Next step
My next step is to investigate hypothesis 2B. In particular, I want to explore the consequences
of the lines in Command.Execute
```
val handler = new RemoteEventHandler(clientSocket)
val loggers = colors.map(new RemoteLogger(clientSocket, 0, _): Logger).toArray
// LeeT: complex lines before we go down the rabbit hole.
_.execute(handler, loggers)
```

**Comment by LeeTibbert** [comment]
I think I have cracked the nut of this Issue.  Real Life calls/demands so it will take me a
few days to write up my results.  I believe that a few incremental improvements are
feasible, but that solving the whole of the presenting problem is not.

Till then, meditate on:  When is a RuntimeException not an Exception?

**Comment by LeeTibbert** [comment]
A few days becomes three weeks, this was not a simple problem.

On further investigation, the answer to the query I posed:  When is a RuntimeException not an Exception? is
"When it is an un-caught C signal reported as a RuntimeException but done in a away which prevents Scala
from catching that exception".

It also turn out that it makes absolutely no sense to attempt to execute the rest of the tests after the 
socket link drops because the SN TestMain encountered that error and exited.  Not only is there
no link, there is no longer anybody at the SN binary end.  

See PR #1827 for relevant discussion. When that PR is merged, this Issue can be closed.
That PR does the best that I think possible. Since recovery is not possible, it gives a clear
warning about the inconsistent state and some, but not necessarily all, places to doubt or 
question.

**Comment by LeeTibbert** [comment]
Closing because this pertained to the SN testing framework prior to the Summer 2020 change to the
Scala.js based framework.    I have not done an exhaustive check of the new framework to see if
the reported problem is entirely gone, but then again I have not stumbled over it having used
the now current framework extensively. Absence of proof is not proof of absence, but it is good
enough to close this Issue.
