### ISSUE TITLE
Test runner should optionally execute Suites in consistent order.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1817]
It is not enough that the dog sings, it must sing well...

Once other problems in TestRunner are sorted, it would be nice to have an option
to execute the test Suites in some consistent order, probably sorted by fully qualified
class name.  

It appears that today they are executed in no apparent or consistent
order.  My guess is that an unsorted map is being iterated over.

Now there is dome advantage to tests being executed in no set order. It allows
to detect tests which succeed because some earlier test modified the environment.

During development it would be useful to have an option to execute the tests
in a determinant order.  This helps when one is trying to find a failing Suite.
Or when trying determine that a given Suite executed amongst tens or hundreds.

The hard part of implementing this feature would be determining how to set up
configuration to enable it.  A simple environment variable would work, but that
is not scalable.

**Comment by sjrd** [comment]
I don't think Scala Native is even in charge of deciding. That's sbt's testing infrastructure. Do you have any evidence that there is anything in Scala Native itself that decides in what order to run the tests?

Does `parallelExecution in Test := false` help?

**Comment by LeeTibbert** [comment]
I am closing this Issue & corresponding PR #1833 because of the
new, Summer 2020 Scala Native JUnit environment.
