### ISSUE TITLE
Unit-test fails when built with Release-Fast & LTO

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1822]
Executing unit-tests via `tests/test` in a freshly cloned directory built from scratch with "release-fast" & "LTO"
fails with exception `SocketClosed'.  The TestFramework is its usual helpful and vocal self about where & when
the fault may have happened.  

This error if fully reproducible. It happens on each run.  It does not happen without "LTO", as shown
by the continuing success of Travis CI mainline builds.

Replication data:  Ubuntu 20.04,  Linux 5.7.2, Intel 64, Clang-10. Waning gibbous moon.

**Comment by LeeTibbert** [comment]
Debugging with custom code reveals the underlying fault to be a "Segmentation Fault" in the executed SN binary
partner code.

The fault appears to be in ProcessSuite.scala. Further localization narrows it down to method 
` addTest("waitFor with timeout times out") `.

 That test and others in that section have previously detected other compiler errors.  As noted in the
code, that section, by nature, is subject to race conditions.  Further debugging showed that the reported
Issue  is unlikely to be the result of a failed race.

**Comment by LeeTibbert** [comment]
I believe/propose that soon after this PR is merged, the Travis CI should be modified to have a
only one "release-fast LTO commix". That is Latin squares, rather than combinatorial explosion.

**Comment by LeeTibbert** [comment]
Status update:

I have been requested to wait until the current work to port SN tests to JUnit is completed & settles before
I add some code to ProcessSuite.scala to try to determine exactly __which__ assert if failing.  My
thinking & experience has matured since this Issue was created (Read:  I have encountered this
problem a number of times, and a number of places, each time bringing pain.)

**Comment by LeeTibbert** [comment]
Given my comments above about ProcessSuite (now ProcessTest) changes and the need for C signal handling
in Scala Native preamble, I believe that Issue #1960 advances this Issue, but does not mean that it should be closed.
There is still necessary work to be done.

**Comment by WojciechMazur** [comment]
I've tried to reproduce this issue on top of #1980 PR and every time it executed without problems. I've tested with LTO.thin. 
I've not cloned it into a new clean directory, but removed all `target` directories instead, which should give a similar result 
After it would be merged (with #1979 and #1982) you can try it on your setup and hopefully, we can close this issue as well as your #1823 PR with a temporary fix

**Comment by WojciechMazur** [comment]
Fixed in #1980
