### ISSUE TITLE
Two Clang version issues

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1824]
* `docs/user/setup.rst` in the current mainline branch describes the minimum supported Clang version as 3.7.
   Travis CI runs with Clang 5.0.  Seems to me as though the two should match.

* I propose that the minimum and Travis CI version of Clang be upgraded.  According to LLVM [versions](http://llvm.org/OldNews.html)
  + Clang 3.7 was released in Sept 2015
  + Clang 5.0 was released in September 2017
   
It is now almost September 2020 and will probably be past that by the
next SN release. Clang will probably be at Clang 11 by September 2020.

I would be happier to use Clang 8, released March 2019, but can see an line of reasoning
for Clang 7, released September 2018.

The doc issue is well worth fixing, in memory of Cotton Mather.  Updating the  Clang version is not
the most critical Issue, but  good housekeeping pays off in the mid-to-long run.   

Raising the minimal supported version of Clang has the added benefit of allowing a long overdue
simplification in the Discover.scala code.  Along with other changes, the test in that code for
minimal supported version could be removed.  That would allow people to use an older Clang, unsupported-by-SN,
version if it works for them.  We would not be breaking currently successful builds.
The Discover code would discover only currently supported Clang versions.

 If given the go ahead here , I will submit a PR.  Please advise.

**Comment by sjrd** [comment]
Sure, we can always upgrade the version of clang as long as it's easily available on Linux and Mac platforms.

**Comment by LeeTibbert** [comment]
Thank you for the feedback.   I hear the "easily available" and will keep that in mind.

Clang version issues quickly chain into the fact that Travis CI is currently on Ubuntu 14.04, originally released in
April 2014. I do not know if it is using the latest 14.04.06, released March 2019.

Ubuntu 16.04, released April 2016, and 18.04, released April 2018 are both Long Term support versions.
The latter looks like a good candidate. It also supports Clang-8, but not at default.

The above invites the question of what else should be updated. 

I believe that @ekrich is giving this issues some thought & attention, over the mid-range.

**Comment by errikos** [comment]
I also observed that the Travis build is based on 14.04, but the Docker images run on 18.04, so there is another inconsistency there.

In my fork I tried upgrading to 18.04 on Travis and also switched to `openjdk8` from `oraclejdk8` and everything seems to work great. I also tried clang-9 and it also works OK.

Is there any reason why we currently have `oraclejdk8`?

Will probably submit a PR later.

**Comment by ekrich** [comment]
As promised to @LeeTibbert, I wrote down my thoughts.
Related: https://github.com/scala-native/scala-native/issues/1849
