### ISSUE TITLE
TestMain should enable Unix signal handling

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1828]
cc: @errikos 

TestMain is under or pending re-work, so I am jotting this down for consideration. I do not
want to be making things more complex by working in the same active area.

I believe that TestMain should enable Unix signal handling in order to present better
information when it dies due to a Unix signal.

There are 100+ Unix signals and signal handling probably needs to be enabled for each of them.
Possibly the same signal handler could be used for all of them.
It is documented that only certain I/O can be done in a  signal handler, so a devo needs to
tread lightly.

This Issue is an evolution of Issue #1796. File `./nativelib/src/main/scala/scala/scalanative/unsafe/package.scala`  
method `fromCString` has the statement ` val len   = libc.strlen(cstr).toInt`.  `fromCString(null)` rightly causes
libc.strlen() to raise a C SIGFAULT signal.  The current TestMain is not set up to catch and report that signal
on its way out, so the TestMain process dies silently in the night. Not only is there no one to hear its last words,
there are no last words; sic transit gloria mundi.

Scala and Java are designed to catch software exceptions but not C signals.  I believe SN is explicitly
designed to allow catching C++ exceptions but C signals force a return all the way to the command line.

I have not tracked down the code which converts the C signal to the reported pseudo RuntimeException.
I believe that happens after exception handling has unwound through TestMain.

Now all of this is Unix specific.  When/if Windows or non-Unix support is added to SN, this area will need to 
be re-visited.  Such hypothetical support should not prevent present day improvement to the test-runner
experience on Unix.

**Comment by ekrich** [comment]
Just as a note, I started the POSIX signal as a PR. If I can get a couple of these other PRs off my plate I can get back to that. JVM does capture some signals but I have only used the shutdown hook.

**Comment by LeeTibbert** [comment]
PR #1823  will probably close Issue #1823 when the former gets merged.   Issue #1823 should not then be forgotten
because it gives a good_example/provocation_case for why TestMain needs to catch C signals; i.e. this issue.
Sometime it helps to have a concrete instance when chasing these will-'o-the-wisps.

**Comment by LeeTibbert** [comment]
My thinking on this issue has changed over the months as I have done some design studies
and trial implementations.

My current thinking is that TestMain should have two options. One similar to the current
and a second "sensitive but expensive" mode.  The second would spend some virtual
memory to fork a child process which runs the current TestMain.  The parent would
wait for the child to finish, by whatever means, and then report the exit status.  This
would allow reporting uncaught signals, and distinguish them from planned exits.

I believe this approach would give a good 'trip-wire' but the problem is that
it basically doubles the amount of memory required and the current required
memory is already huge. No free lunch here.

The problem with catching  C signals is TestMain (or having SN establish
a last chance handler) is that not much can be done to report the 
C signal.  I/O in a signal handler is unreliable & explicitely unsupported.
Having a 'mangled I/O' fault when handling a `uncaught signal` fault
is not something I/we want.

Using a `longjmp` variant is supported.  Such handling
would be ugly in a C TestMain and even uglier in the
current Scala one.

More design studies need to be done.

I have not seen "gone missing in the night' errors with the current
JUnit infrastructure but I am not convinced they are totally gone.

My current interest in this issue is setting up some traps in the
macOS environment to catch whatever errors may be occurring there.

**Comment by WojciechMazur** [comment]
Signal handling added in #2338
