### ISSUE TITLE
Running unit-tests in a forked JVM fails

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1829]
Setting `Test / fork := true` in  the unit-test project causes `test/testOnly` and kin to fail (stacktrace).
I did not trace why.

For a number of reasons, It would be nice for this to work.  My use case is isolation.  I am willing
to pay the startup cost of a separate JVM for the assurance that the test environment is entirely
cleaned up upon any return to the sbt shell.  Specifically, I would like the assurance that any
SN binary test process which may contain an infinitely looping test is forced to exit.

**Comment by sjrd** [comment]
We could never make that work in Scala.js, so I doubt that it can be made to work in Scala Native.

**Comment by LeeTibbert** [comment]
Thank you for the Scala.js info. Given that, I will not sink time into the base issue.
