### ISSUE TITLE
Port a subset of java.nio from ScalaJS

### ISSUE THREAD

**Issue by siriux** [scala-native/scala-native#183]
There is a subset of java.nio classes that is used on code already present in SN (e.g. String class) that could be ported from ScalaJS.

The minimum required by most methods on String would be Buffer, ByteBuffer, CharBuffer and Charset and their dependencies. But probably, once that's in place, porting other java.nio classes is easy.

**Comment by siriux** [comment]
I'm going to try to get a first version of the port working.

**Comment by sirinath** [comment]
I would say simply use an Apache Harmony / Android Java derivative. Most are available under Apache 2.0 License. E.g. Java side of RoboVM is ASL 2.0. Supporting one of these will be easier and you you get more bang (larger API coverage) for the effort than specifically porting any Java API.

**Comment by densh** [comment]
@siriux Are you still working on this? @Sumith1896 is also interested in having this fixed.

**Comment by siriux** [comment]
@densh I have the buffers working, but on charset I was getting some weird errors.

I can create a pull request with it, but I'm not sure where to put the code from scala.scalajs.niocharset, should I put it under nativelib? Or should I put it under java.*, but that would be weird.

**Comment by densh** [comment]
@siriux Feel free to open a pr, we'll discuss all the details there.

**Comment by siriux** [comment]
Here is the PR #186

**Comment by sirinath** [comment]
Might be of interest: https://github.com/piotrmocz/scalajs-java

**Comment by densh** [comment]
Fixed in #186
