### ISSUE TITLE
Are Spring 2020 sbtopts reasonable?

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1832]
I am having strong doubts that the `.sbtopts` introduced in Spring 2020 are reasonable.
Java memory management is a complex subject and I am not even a grasshopper but
I raise my doubts.  I believe that the present options are, in general, to large to begin with
and too limited on systems with plenty of memory.

For a number of weeks now, I have been running the options below on a modest 4 core Intel
system with 16GB RAM.  On that system, it starts with a lower heapsize but allows it to grow
about 1GB larger, if needed.   I have not taken the time to see what the heap usage is on
my system which mainly builds & exercises Scala Native.  

```
-J-XX:GCTimeRatio=29
-J-XX:+PrintCommandLineFlags
```
The `PrintCommandLineFlags` are just so I can see what sizes are being used, and which Java GC.
The 29 is set up to minimize garbage collection (by allowing more RAM to be used.)
Works for me.  

Of course, all of this memory management is Java 8 specific and changes with more current
Java and/or different garbage collectors.

**Comment by sjrd** [comment]
I would welcome a PR that removes the file and instead documents what are possible good options to use by hand.
