### ISSUE TITLE
AssumptionViolatedException ctor triggers runtime error in native JUnit self-tests

### ISSUE THREAD

**Issue by errikos** [scala-native/scala-native#1843]
In `junit-runtime/src/main/scala/org/junit/AssumptionViolatedException.scala`, the `(String, Throwable)` constructor results in an unknown runtime error when running JUnit self-tests from sbt:
```
junitTestOutputsNative/test
```

The bug is only present in native JUnit self-tests. At runtime, the native test runner exits unexpectedly when the AssumptionViolation is tested. This is why the aforementioned constructor is not available at the moment. Some details:
  - The constructor is always made reachable, no matter if it is used or not. This suggests maybe some bug in the reachability analysis and/or code generation.
  - After some digging around, I found out that the one to blame is the `Throwable` argument. When the argument is changed to anything else (or removed entirely), then everything works as expected. That is, the constructor is only made reachable when used and the runtime error goes away.

**Comment by WojciechMazur** [comment]
With disabled optimizations, this Exception works as expected. It looks like it's another case of trying to execute ctor as a virtual method.
