### ISSUE TITLE
Streamline clang version detection

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1849]
Current there are several clang related checks in the tools API in `Discovery`.

1. First it looks for `CLANG_PATH` or `CLANGPP_PATH`. I believe this is to override the first version on your path perhaps for a developer wishing to test multiple versions
2. If this is not found it enumerates the list on `clang/clang++` in the list calling `which clang-8` for example to get the path.
3. It errors out if neither 1 or 2 succeed.
4. Next, it runs `clang` preprocessor to get defined values and looks for "__DECIMAL_DIG__ __LDBL_DECIMAL_DIG__" to check if clang is ok.

Proposal
1. Still support 1 above to get a env defined `CLANG_PATH` but document it in the developer section
2. Do not have a list of enumerated version but only a minimum version
3. If 1. is not the option use `which clang` to get the path otherwise append `clang` to the path
4. Run fullpath to clang to get the version 
```
$ /usr/local/opt/llvm@8/bin/clang
clang-8: error: no input files
$ echo $?
1
```
Not found example for number 1. above in case there is no `clang` at `CLANG_PATH`
```
$ /no/path/to/clang
-bash: /no/path/to/clang: No such file or directory
$ echo $?
127
```
5. Check against minimum version and reject if needed.
6. Check clang for the preprocessor defines and reject if needed
7. Use `clang`

This way people can use a new version if it works. The minimum version could probably be dropped if we just wanted to go with the preprocessor defines as the minimum. This would also probably simplify the current code and means we don't need a PR every time there is a new version of `clang`.

**Comment by LeeTibbert** [comment]
cc: @errikos 

Thank you for this proposal.  As the annoying person who submits a "update Clang" PR 
every 6 months, I would __love__ to get rid of clang discovery. If for no other reason
that the code to detect clang configuration does_not_work/works_incorrectly with
discovery.

Automagic that works is good, automagic that introduces spooky, hidden failures
ought to go.

Let people, including me, who want to use a different Clang use a documented
environment variable.

PR #1848 introduces a change to use clang-9 on Ubuntu 18.04.  Good changes.

If this proposal is to advance, as I think it should, the text in `setup.rst`, at least for
ubuntu, needs to change.  The default llvm/clang on ubuntu 18.04 is Clang 6. 
That means a  out-of-the-box `clang` command will give clang-6 (if installed,
the directions do not specify that default version is necessary.)

So the instructions need to be changed to say something like:
```
Either use `update-alternatives` to make clang-9 the default or
ensure that  environment variable SCALANATIVE_Mumble (see section mumble)
is defined before building a project using Scala Native.
```
Not exactly friendly and inviting to new users. Can people think of a better approach?

**Comment by ekrich** [comment]
I think just looking for Clang via `which clang` if probably good enough. Considering version 6 as a minimum. See https://github.com/scala-native/scala-native/issues/1991

```
lrwxr-xr-x    1 eric  staff         7 Jun 10  2019 clang -> clang-8
lrwxr-xr-x    1 eric  staff         5 Jun 10  2019 clang++ -> clang
-rwxr-xr-x    1 eric  staff  80538452 Jun 10  2019 clang-8
```
Output on macOS
```
$ clang --version
clang version 8.0.1 (tags/RELEASE_801/final)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm@8/bin
```

**Comment by ekrich** [comment]
Mac installed platform.
```
$ which clang
/usr/bin/clang
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Mac tools platform
```
$ ls -la /usr/bin/ | grep cla
lrwxr-xr-x    1 root   wheel          7 Jun 19  2019 c++ -> clang++
lrwxr-xr-x    1 root   wheel          5 Jun 19  2019 cc -> clang
-rwxr-xr-x    1 root   wheel      18288 Jul 16  2019 clang
-rwxr-xr-x    1 root   wheel      18304 Jul 16  2019 clang++
lrwxr-xr-x    1 root   wheel          7 Jun 19  2019 llvm-g++ -> clang++
lrwxr-xr-x    1 root   wheel          5 Jun 19  2019 llvm-gcc -> clang
```
In command line tools
```
$ ls -la /Library/Developer/CommandLineTools/usr/bin | grep cla
lrwxr-xr-x    1 root  admin         5 Jul 23  2019 c++ -> clang
lrwxr-xr-x    1 root  admin         5 Jul 23  2019 cc -> clang
-rwxr-xr-x    1 root  admin  81666656 Jul 12  2019 clang
lrwxr-xr-x    1 root  admin         5 Jul 23  2019 clang++ -> clang
```

**Comment by LeeTibbert** [comment]
Very closely related...  Last I looked, build.sbt used or tried to use `usr/bin/llvm-config` 
and would ignore any `llvm-config-N` (-10, -11, etc.) which should supersede it. 
The `llvm-config` file sets up some path elements etc, which on a fast reading,
look pretty useless to SN (which is why this defect has not been visible so far).
The fix of just removing that section should probably be investigated.

**Comment by ekrich** [comment]
@LeeTibbert Could you add the output from `clang --version` from you Linux box here like I did above for MacOS?

**Comment by LeeTibbert** [comment]
@ekrich   
Currently from a/an Ubuntu 2.10 distribution
```
Ubuntu clang version 11.0.0-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```

I usually run a development version of clang/llvm soon after it goes to RC-1.  I believe
the text of the first line is somewhat different.  IIRC it is a Git SHA or a build number
to the right of the rightmost dash, also name does not start with "Ubuntu".

I can get further details about devo version is it would name your work easier/more_correct.
