### ISSUE TITLE
Migrate native code to libc and posixlib

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1879]
Now that we have a mechanism to support multiple projects with native code, we can include the code in the project that uses the native code.
https://github.com/scala-native/scala-native/pull/1637

This is prerequisite for further re-factoring as detailed here:
https://github.com/scala-native/scala-native/issues/1352

**Comment by ekrich** [comment]
PR for the `posixlib` part. https://github.com/scala-native/scala-native/pull/1885

**Comment by WojciechMazur** [comment]
#1885 containing changes to both modules was merged
