### ISSUE TITLE
UnsupportedException when using structs with functions with type parameters

### ISSUE THREAD

**Issue by kmltml** [scala-native/scala-native#188]
The smallest breaking example i could get is:

``` scala
import scalanative.native._
import scalanative.libc.stdlib._

@struct
class Foo(val ord: CInt)

object Test {
  def main(args: Array[String]): Unit = {
    val bar = identity(new Foo(1))
  }
}
```

It fails at compile-time with `[error] (sandbox/*:nativeLink) scala.scalanative.util.package$UnsupportedException: Inst(Local(src,7),As(Struct(Top(Foo),Vector(I(32))),Local(Local(src,6),Class(Top(java.lang.Object))))) (class scala.scalanative.nir.Inst)`

**Comment by densh** [comment]
Thanks for the bug report!

**Comment by densh** [comment]
Duplicate of #178
