### ISSUE TITLE
Documentation points to an old version

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1880]
Currently the documentation default points to `0.3.9`. 

Maybe that could change and point to `0.4.0-M2` since this is the version most people should be using.

It would be great if we could publish the site via CI and point to the latest commit on master for the `latest`.

**Comment by vincenzobaz** [comment]
Scala Native now supports Scala 2.12 and soon 2.13 but it this not mentioned in the documentation.
I agree that the doc should be updated by the CI

**Comment by sjrd** [comment]
It's only in master, and not yet released.

**Comment by ekrich** [comment]
This is now fixed.
