### ISSUE TITLE
Update JUnit runtime to version 4.13

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1881]
JUnit 4 added methods such as `assertThrows` many moons ago, (Nov 2018) but just recently published the library in Jan 2020. JUnit is supported in JVM, JS, and Native now so any changes can be utilized by downstream projects.
https://mvnrepository.com/artifact/junit/junit

This enhancement should bring the API up to the latest with respect to any changes.
https://junit.org/junit4/javadoc/latest/index.html

Release notes for 4.13 as a reference.
https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md

This should be ported to Scala.js or to Scala Native depending on which occurs first.

**Comment by ekrich** [comment]
Not sure all the methods expected got added - the helper we are using seems far more useful. https://junit.org/junit4/javadoc/latest/index.html

**Comment by LeeTibbert** [comment]
Time passes, basic Issue is still a good idea. I think that JUnit 4.13.1 is available. Scala-Steward wanted to add that to Zio, IIRC.

**Comment by ekrich** [comment]
Related: https://github.com/scala-js/scala-js/pull/4475
