### ISSUE TITLE
Our travis_setup.sh needs updating

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1900]
Currently we are using Docker for our CI but in the past we used the `scripts/travis_setup.sh` and tested on both Linux and MacOS directly in Travis. I have seen this file being used by other projects but this file is now out of date for `0.4.x` with `regex` and `libunwind` included.

We planned to migrate to Jenkins so we could test more configurations so it is unclear what our future CI will look like and also the future of this setup script. Github actions is also becoming more popular.

**Comment by ekrich** [comment]
Perhaps this script could be removed?

**Comment by WojciechMazur** [comment]
No longer relevant, we no longer use Travis
