### ISSUE TITLE
JVM and AArch64(Arm64) System.nanoTime difference

### ISSUE THREAD

**Issue by teodimoff** [scala-native/scala-native#1907]
System.nanoTime on ARM64 result in a difference on the two platforms. 
```scala
  def main(args: Array[String]): Unit = {
    println(s"Nano Time is: ${System.nanoTime()}")
    println(s"Millis Time is: ${System.currentTimeMillis()}")
  }

/*

JVM:
Nano Time is: 2522262140448628
Millis Time is: 1601158027766

AARCH64 (MSM8939):
Nano Time is: 1718
Millis Time is: 1601158108688
*/
```
As per prior discussion the documented behavior of System.nanoTime is loosley specified or underspecified. System.nanoTime is not epoch . It`s unknownOffset + offsetFromEpochInNanos which is only consistent in the same JVM (as per comments: only use nanoTime values to compare against other nanoTime values obtained from within the same VM) . This nanoTimeOffset is probably reseted(to different value) on some restart (jvm, computer,etc etc) so there is no correct behavior here i belive. The only correct thing nanoTime should have is that there must be a positive difference in consecutive calls to nanoTime. The start offset is arbitrary but fixed and must stay static (at least for the lifetime of the jvm). We can:
1. Provide just offset in nanoseconds from Epoch. As long as consecutive calls return positive difference between the two System.nanoTime calls. In C++ code this probably means refactoring native/lib/time.cpp steady_clock() function to:
```c++
long long steady_clock() {
    return std::chrono::steady_clock::now().time_since_epoch().count();
}
```
2. Leave steady_clock() unchanged if consecutive calls have positive difference.

3. Aproximate JVM nanoTime with our own set of parameters.

**Comment by sjrd** [comment]
I don't understand the issue, here. Is the current `System.nanoTime()` not monotonic or not steady?

**Comment by teodimoff** [comment]
hm... something happaned... the original steady_clock() is steady and  monotonic.The fact that millis time prints twice the same value (i.e. the same millsecond) but nanos advaced suggest that all is good.  I will try to see what happaned.

Nano   Time is: 9987098126863
Millis Time is: 90313343411
wait
Nano   Time is: 9987098655250
Millis Time is: 90313343412
wait
Nano   Time is: 9987098919157
Millis Time is: 90313343412

**Comment by sjrd** [comment]
Monotonic means moving only forward (`currentTimeMillis` is *not* monotonic because the user may change the time zone of their OS while the application is running).

I thought steady meant something slightly different, but maybe they're just synonyms.

**Comment by teodimoff** [comment]
probably means alomst the same thing... i thught the monotonic and steady in reverse. Somwhere on the interet:
```
system_clock - this is the real-time clock used by the system;
high_resolution_clock - this is a clock with the shortest tick period possible on the current system;
steady_clock - this is a monotonic clock that is guaranteed to never be adjusted.
```
Either way there appearst that there is no issue with steady_clock(). I will double check if all is good and close this issue. Thanks.

**Comment by teodimoff** [comment]
The issue appers to be resolved and current implementation of steady_clock() works corectly, thus closing.

**Comment by teodimoff** [comment]
The current implementation of steady_clock() works corectly, thus closing.
