### ISSUE TITLE
AARCH64(ARM64) Format string function results in a crash.

### ISSUE THREAD

**Issue by teodimoff** [scala-native/scala-native#1908]
the following function result in creash when compiled and executed on ARM64 platform.
```scala
 def main(args: Array[String]): Unit = {
    println(time("Hello from scala-native on ARM64"))
  }
 
  def time[A](a: => A) = {
    val now = System.nanoTime()
    val result = a
    val nano = System.nanoTime() - now
    val micros = nano / 1000
    val seconds = micros.toFloat / 1000 / 1000
    println("%d nanoseconds".format(nano), "%d microseconds".format(micros), "%.3f seconds".format(seconds))
    result
  }
```
This results in sbt:
```
terminate called after throwing an instance of 'scalanative::ExceptionWrapper'
terminate called recursively
[error] java.lang.RuntimeException: Nonzero exit code: 134
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$15(ScalaNativePluginInternal.scala:164)
[error]         at scala.Option.foreach(Option.scala:274)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$14(ScalaNativePluginInternal.scala:164)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$14$adapted(ScalaNativePluginInternal.scala:149)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) Nonzero exit code: 134
[error] Total time: 103 s (01:43), completed Sep 26, 2020 11:33:15 PM
```
and standalone execution:
```
terminate called after throwing an instance of 'scalanative::ExceptionWrapper'
terminate called recursively
Aborted
```
Removing the line: 
 ```scala 
println("%d nanoseconds".format(nano), "%d microseconds".format(micros), "%.3f seconds".format(seconds))
```
Fixes the issue, which suggest the format function is causing the crash. Unfortunately, as seen, the crash does not have a stacktrace, which makes debuging difficult.

**Comment by ekrich** [comment]
@teodimoff  Thanks for filing this issue with a reproducer. I just wrapped the code in `object Main { ... }`

Unfortunately, I can not duplicate this issue using `0.4.0-M2` or `0.4.0-SNAPSHOT` on macOS Mojave 10.14.6.

Could you please let us know the following:
1. Scala Native version
2. Operating system version
3. Clang/LLVM version
4. sbt/Java version just to have it
5. Confirm that you are compiling and running directly on the machine and not cross compiling.

Could you please share the output during compiling and linking. You can also add `logLevel := Level.Info, // Info or Debug` and change to debug in the build or start `sbt -d` to get debug output. This way you can see what the machine is compiling and linking.

Maybe someone here on Linux can see if they can reproduce on a normal Linux setup for Intel type architeture.

**Comment by teodimoff** [comment]
@ekrich Hi. Thank you for tring to reproduce the issue. I will paste the output as soon as i can(i have a bunch of things going right now, that pull me in one direction on another). Let me first try with the latest stable kernel(last time was on 5.9.rc6) not with relase candidate when i have the chance to(the procedure is tedius and i havent build it in a month). I do not cross-compile the app. I only corss compile the kernel(and any changes i made to the kernel top of that) for the AARCH64. I install anyting on the device trough ssh(openjdk, sbt, build essentials etc...). The scala-native version si M2. Operating system is postmakedos(which uses alpine-linux). I will try to see what is happaning and why , report it here. Thank you.

**Comment by shadaj** [comment]
Just saw this issue! I believe the issue is due to LLVM having different exception handling defaults on non-amd64 platforms. If you're willing to build locally, you could try the 32-bit PR at #1571, which includes some additional compiler flags (`"-fexceptions", "-fcxx-exceptions", "-funwind-tables"`) that helped with a very similar type of crash on i386.

**Comment by WojciechMazur** [comment]
I've been working recently on cross-compiling to aarch64, I can confirm that @shadaj's flags fix the problems (I only wish I would read this comment a lot earlier... :< ). Anyway, we should backport this change to the main branch.
