### ISSUE TITLE
Segmentation fault on produced binary

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#1909]
Let me share with you a bit strange but very simple code :

```
import java.util.Random

class RandomWrapper(impl: Random = new Random()) extends Random {
  def this(seed: Long) = {
    this()
  }
}

object Bug extends App {
  new RandomWrapper()
}
```

When I build it via M2 on my machine and try to run, it crashed with `segmentation fault`.

When I remove:
```
  def this(seed: Long) = {
    this()
  }
```

it works.

I guess it is a bug.

**Comment by LeeTibbert** [comment]
catap,  Thank you for the report and concise reproducer.

From private discussions, I gather that this works with both JVM and Scala.js, true?

Also from those conversations, the SEGFAULT appeared to be in immix GC.

I believe you discovered a workaround.    My environment is in flux but I will try to reproduce this
with  0.4.0-SNAPSHOT as soon as I can (hours, or a day or two, if that works for you).

**Comment by catap** [comment]
@LeeTibbert, yes this code is working fine on JVM and Scala.Js build.

Because I found workaround => I can live with it => take your time.

**Comment by catap** [comment]
@LeeTibbert if it helps: I build this example with
```
    nativeLinkStubs := true,
    nativeMode := "release-fast",
    nativeLTO := "thin",
```

**Comment by WojciechMazur** [comment]
Well, I have to admit it's quite odd. 
From what I've observed for some reason there's generated a cycle in chain of constructors:
- `RandomWrapper(j.u.Random)` 
-  `j.u.Random()`
- `RandomWrapper(long)` :open_mouth: 
- `RandomWrapper(j.u.Random)`

I think it's again problem with names mangling, I'll check it out

**Comment by sjrd** [comment]
It looks like constructor calls are emitted as if they were virtual, with dynamic dispatch, instead of with static dispatch. There was a similar issue a very long time ago in Scala.js.
