### ISSUE TITLE
String interpolation fails

### ISSUE THREAD

**Issue by frgomes** [scala-native/scala-native#191]
https://github.com/frgomes/scala-native-testsuite/blob/master/testsuite/0191/src/main/scala/issue0191.scala
```scala
package testsuite

object Main {
  final private val USAGE = s"hello"

  def main(args: Array[String]): Unit = {
    // this program crashes at startup.
  }
}
```

**Comment by frgomes** [comment]
Related to #140, #151

**Comment by densh** [comment]
This one is currently failing due to missing implementation of `java.lang.Character::codePointAt`.

**Comment by sjrd** [comment]
I assume you mean `String.codePointAt`? Here is an implem: https://github.com/scala-js/scala-js/blob/v0.6.10/library/src/main/scala/scala/scalajs/runtime/RuntimeString.scala#L47

**Comment by densh** [comment]
@sjrd That's an Apache Harmony thing. The implementation in `j.l.String` use helper in `j.l.Character`.
