### ISSUE TITLE
Incompatible NIR version assertion should print filename

### ISSUE THREAD

**Issue by jokade** [scala-native/scala-native#1928]
When a file with an incompatible NIR version is encountered during linking, there should be some info about the file / dependency that actually triggered the issue. Currently there is no additional information:

```
[error] stack trace is suppressed; run last lib / Compile / nativeLink for the full output
[error] (lib / Compile / nativeLink) java.lang.AssertionError: assertion failed: Can't read binary-incompatible version of NIR.
```

**Comment by catap** [comment]
@jokade just for record. Removing `lowered.hnir` from root folder solved this issue on my side

**Comment by ekrich** [comment]
There was a PR/merge since `0.4.0-M2` that avoids generating `lowered.hnir` in the root dir. Just FYI.

**Comment by jokade** [comment]
@catap thanks, but my issue is not related to `lowered.hnir` (as @ekrich  pointed out, it's no longer generated). Somehow I managed to mess up my env so completely that the NIR generated by the compiler is an older version than expected by the linker (in the same run, mind you 😬)

**Comment by sjrd** [comment]
Try `rm -r project/project/target/` and `rm -rf project/target/scala-2.12/`, followed by `sbt clean`.
