### ISSUE TITLE
Add support for framework linking

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#194]
Currently we only support static and dynamic linking for `@link` annotation. We need to add support for linking with frameworks on macOS.

**Comment by nornagon** [comment]
FYI, it's possible to work around the lack of this by manually specifying the framework in `nativeLinkOptions`. e.g. in build.sbt:

```
nativeLinkingOptions ++= Seq("-framework", "OpenGL")
```

and omit the `@link` annotation on the relevant extern object. See [here](https://github.com/nornagon/skia-scala-native) for an example.

**Comment by phdoerfler** [comment]
@nornagon Thanks, that's good to know!

**Comment by densh** [comment]
Given that it's a macOS-only features and there is an easy workaround, it's unlikely we're ever going to have a baked-in support for this due to implementation complexity.
