### ISSUE TITLE
Proposal: automatically convert Strings passed to external functions

### ISSUE THREAD

**Issue by jokade** [scala-native/scala-native#1940]
#### Motivation
When an external lib takes a `const char*` as argument, it will either
* not use that string beyond the call,
* or make a copy of that string if it needs to store it beyond the call (e.g. the label of a UI component).

Hence it is a reasonable pattern to provide a wrapper that takes a `String` instead of a `CString`, using a `Zone` specific for that call (at the cost of zone creation...):
```scala
def foo(arg: CString): Unit = external

def foo(arg: String): Unit = Zone{ implicit z =>
  foo( toCString(arg) )
}
```

#### Proposal
It would reduce boiler-plate code a lot if `String` arguments in `extern` functions would be automatically handled by the compiler in that way, i.e.:
```scala
def foo(arg: String): Unit = extern
```
would be semantically equivalent to the explicit wrapper.

Furthermore, if possible there should be no creation of a new zone in that case (i.e. the CString should be "stack alloc'ed").

**Comment by sjrd** [comment]
That would introduce magic in the C interop layer. It is a very slippery slope that I really don't think we should take.

Interop must be dumb, otherwise it becomes impossible to spec it or reason about it.
