### ISSUE TITLE
JUnit does not apply @Ignore on the class

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1943]
Annotating `@Ignore class MyTest ...` allows individual tests to execute when it should ignore all the individual tests.

I nice to have feature would be for the annotation `@Ignore("#555")` to output as follows:
` Test java.util.concurrent.atomic.AtomicReferenceTest.updateAndGetUpdateFunction ignored #555`

This way the issues could be more visible.

**Comment by WojciechMazur** [comment]
Unfortunately, it won't be possible to add ignore the reason for the output message. Outputs generated by Native JUnit are tested to be compatible with JVM JUnit output which does not add such information. 
I'll add PR with support for ignoring the whole test class soon.
