### ISSUE TITLE
Proposal:  Weekly build to exercise Release-fast & LTO 

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1960]
Issue #1822 reported back in the Summer, 2000 that unit-test were failing when built with
Release-fast and LTO (link time optimization).

###### Progress!  

This is a sample of one run, using SN current as of late 2020-10-20, and using Scala 2.12.
`[info] Linking native code (immix gc, thin lto)`.  A rebuild from the egg followed by
a `test-all`  succeeded, old-style Suites, JUnit, and scripted.

###### Next Steps.

The current CI matrix is/has undergone combinatorial  explosion, so I think adding
a new condition to the matrix and running it on each CI submission is not a good idea.

I propose that at least one configuration using Release-fast & LTO be run periodically, 
say once a week on a weekend.   It would probably start off as just Scala 2.12 and immix,
just so that I do not waste too much time on failure.   Then it could be expanded to 2.13 and
2.11( I am less concerned about that). Commix and Boehm GC could be future combinations
(again, I am less concerned about Boehm).  

I think it wise to start simply and gain experience rather than having to wait until the whole
matrix is working.  

I am spending a lot of time waiting for CI failures these days, so if folks give the thumbs up,
I can peck away at a WIP proposal in my otherwise wasted time.

**Comment by WojciechMazur** [comment]
I agree that we should prepare a CI pipeline for weekly builds. In my opinion, this proposal might be extended for testing `releaseFull` as well. After fixes in #1980 and lowered memory usage, it should be stable enough.

**Comment by LeeTibbert** [comment]
I have been spending time recently waiting for the stream of PRs I have submitted
to clear CI.  I have spent some of that time studying how scheduled GitHub Actions
work.  

I am focused on getting main changes I am working on completed but hope to 
to write a small GitHub Action to run weekly and ping me.  Next step would
be to set up a weekly `release-fast LTO` build which reports (pings?) the
fact that it ran and the success/failure.  In some future evolution, one
could run a simple benchmark of the just-built code.

 @WojciechMazur How did you test your GitHub Actions when you were developing them?
I remember one PR, and not a long stream of commits to change the  yaml files.  
Meant to be a two minute question, not to suck up hours of your time.  Thank you.

**Comment by WojciechMazur** [comment]
I've started with testing locally using [nektos/act](https://github.com/nektos/act). However, the default image it was using was quite limited. Some things that were not working there are working in GH actions workers. Maybe there are better tools/images for this. Later I based mostly on my private repo CI pipeline. I've created some dummy PR merging to my fork repo master.

**Comment by LeeTibbert** [comment]
@WojciechMazur Thank you for the clues...

**Comment by LeeTibbert** [comment]
Update:  I have made some progress using a local mirror of the official GitHub SN repository.

All of this is still in early development stages.  

I have a set of GitHub Action scripts for macOS.  One of them exercises `release-fast` with
`lto=thin`. It is currently manually activated on-demand.  

Work in slooow progress:

I have had problems with GitHub `cron` actions activating on the 10 minute level.  
When some of the macOS dust settles, I would like to try GH `cron` scripts 
activating at the hour (and later, when I am satisfied they are reliable, at the day 
level, then the week level envisioned in the base note.)

GitHub Actions are supposed to be able to send email upon completion, success or
failure. I have not been able to get that to work.  I _have_ been able to get
Web notifications to work, but they are much less useful.

**Comment by ekrich** [comment]
@WojciechMazur We test all sorts of combinations - can this be closed?

**Comment by LeeTibbert** [comment]
I think not,  See Issue #2212, which talks about 
(macOS, release-fast, lto=thin) failures.

If I read the logs from recently merged PRs correctly,
Linux has some tests with release-fast in the matrix
but none with release-fast & lto=thin (there might 
be one buried in there).  The tests for macOS appear
to test neither.

So, for example, I can not close #2212 because the 
current CI matrix tells me nothing about (macOS, release-fast, lto-thin).

There are now about 70 tests run for each and every PR merge.
CI takes a lot of time to complete, say an hour or more.

While I think it a good idea to add more coverage, say for the
mac triple above, I think that adding a huge load to "every CI"
and making devos wait for 2 or 3 hours is not a good use of
devo time.

Running a more inclusive set weekly or semi-weekly might
give the info we need without putting too much carbon in
the air.

**Comment by LeeTibbert** [comment]
I believe that the CI has been exercising Release-fast & LTO on
each commit for a long time.
