### ISSUE TITLE
Design alternatives for porting Scala.js JavaDefaultMethod annotation & others to Scala Native

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1972]
A PR to port Scala.js j.u.Map to Scala Native in order to pickup the default methods on Map is ready 
to be submitted.  

That PR, and earlier work leading to it, identified the need for a decision about how to port Scala.js 
annotations (and at least one import) to Scala Native.

`@JavaDefaultMethod` and, I suspect, `@FunctionalInterface` are likely to be the hard decisions.

There are at least four alternatives:

1) Elide the annotation/import This is the approach taken in the soon-to-be MapDefaultMethods PR.
    It makes reading and reviewing the standalone Scala Native variant easier because it contains
    less distraction (such as commented out annotations & imports) and requires less lore.
    The down side is information disappears so that back porting to Scala.js becomes harder.

    The newly introduced default methods in at least `Map.scala` seem to the user to work just
     fine.  They pass, on both Scala 2.12 & Scala 2.11,  the extensive, independently developed, unit test of
    a now-closed SN PR which implemented these methods.  I do not know why, but welcome them working.
    I suspect that the defect on Scala 2.11 is that the methods are instantiated for each instance of a class
    rather than being forwarded to a common instance on a hidden Map (helper) object.

    I suspect that almost all users of Scala 2.11 will not care, as long as the methods provide correct
    results and are fixed, as  they are, in Scala 2.12/2.13.

2) Comment out annotation/import.  This eases any potential backport and gives a reader 
    well versed in both Scala.js and Scala Native a registration/synchronization point.
    It goes against the principle of not leaving commented out code lying around to trip
    up readers & reviewers.

3) Implement a "do nothing'" `@JavaDefaultMethod` annotation.  This requires a reader
    to either know that it is a no-op, or to spend time chasing the source only to find that
    it is a no-op.  Seems like effort to implement and a point of dissatisfaction to readers
   of the code.

4) Implement `@JavaDefaultMethod`.  I tracked down the Scala.js code ,dating from
    2016-01-05, for [JavaDefaultMethod.scala](https://github.com/scala-js/scala-js/commit/ac06525990e016489aa7d1b4259ca48c767692bb#diff0ee14f33f5d11c9c07d4ea707331e8569b792c17e610961720cb4716ee8c3729).

  About the time the code started talking about changing the IR (Intermediate Representation), I realized that
  this would require effort from one of the Big Dogs, who are few, far between, and already burdened.
 
  This alternative would basically block progress in porting Scala.js files and, especially, the Scala.js Collections test
  ensemble to Scala Native.

**Comment by sjrd** [comment]
The commit in Scala.js is big and has changes in the IR because we made default methods work in 2 10 and 2.11 directly when we added support for them. In Scala Native the IR already supports default methods in master, since it was added in the Support 2.12 PR.

Hence adding an implementation of `@JavaDefaultMethods` should only affect the compiler plugin, porting the changes from the `compiler/` directory from Scala.js. It shouldn't be too hard (famous last words).

**Comment by LeeTibbert** [comment]
Status:  Given the information & encouragement above, I have dived into attempting to port the `@JavaDefaultMethod`
annotation. After all, how hard can it be? :grin: 

I ported over two of the JUnit Test from the Scala.js PR which implemented the `!JavaDefaultMethod` annotation.
To my delight, they succeed by failing on Scala Native SNAPSHOT on Scala 2.11!  This helps my understanding
of the basic issue in Scala 2.11.  Previously I had been seeing default methods appear to work.  Now I have a trap.

I also ported over the Annotation itself and figured out the changes to make it active on SN.  Some debug code
detects & reports it.

Now I am a the point of figuring out the proper intervention point. After that comes generating the method.
An interesting problem. I am learning a lot about the Nir*.scala internals & organization.

**Comment by LeeTibbert** [comment]
Status:  I have a "demonstration of concept" running in my private sandbox.  It has minimal effect on Scala >= 2.12 code paths and on Scala 2.11 code which does not have the `JavaDefaultMethod` annotation.   It passes all current Scala Native unit-tests on Scala 2.11 and also passes the DefaultMethodsTest.scala newly ported from Scala.js.

My next step is to clean up the code and submit a Work In Progress PR for high level concept review.

If/After the basic `nscplugin` changes are merged, there are approximately 20 files in `javalib` which look like
they need to be examined for needing the `JavaDefaultMethod` annotation in order to enable the compiler magic.
I envision that as a short series of PRs for each foo package in `java.foo`.

**Comment by LeeTibbert** [comment]
I believe that this Issue can be closed once PR #1997 is merged.  That PR implements 
JavaDefaultMethods annotation.

I believe the FunctionalInterface annotation is not essential for Scala Native.  From my reading,
the purpose of that annotation is to tell the compiler to check that the trait(?) has only one
abstract method.  That might be necessary/helpful if the annotation were intended for general use.
Here it would be intended for use only in javalib. That code is under our control and the 
parts that would be checked by a FunctionalInterface annotation are being checked
in Scala.js, from whence they are being ported.

The code I have seen so far having a FunctionalInterface annotation has all been in
java.util.function.*, which is being synchronized with Scala.js anyway.
