### ISSUE TITLE
JUnit text files in repo?

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1977]
Are this checked in inadvertently?
https://github.com/scala-native/scala-native/commit/c375b432fe8e600f7ad3a201f6c516892e7b681b#diff-55821b02cfbd2970e40ab818b586214198db054ccba49322733ce645e9f28ea9

**Comment by sjrd** [comment]
No, they are test files. Scala.js had the same here:
https://github.com/scala-js/scala-js/tree/master/junit-test/outputs/org/scalajs/junit
