### ISSUE TITLE
Declaration of external functions with multiple signatures not working as top level objects

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#1991]
During the Port of `object ExternSuite` to `class ExternTest` the `extern` definitions were lifted from inside the `object` to outside the `class` (the top level). The original issue was here. https://github.com/scala-native/scala-native/issues/1652

As noted in the following, definitions are currently not allowed inside a class. https://github.com/scala-native/scala-native/issues/897

Note that the `ExternTest` uses the `snprintf` C function which is a `CVarArg*` method and is normally supported via an `implicit` because only `CVarArgList` is supported by Scala Native. 
https://github.com/scala-native/scala-native/blob/master/clib/src/main/scala/scala/scalanative/libc/package.scala

As a mediation so the PR https://github.com/scala-native/scala-native/pull/1989 can be merged while this issue is fixed, one test is ignored with the offending code commented out.

Note 2: This seems to work on macOS but not in CI in Linux.
https://travis-ci.com/github/scala-native/scala-native/builds/199498581

Output:
```
[info] Generating intermediate code (23491 ms)
[info] Produced 2 files
[error] /home/scala-native/scala-native/unit-tests/target/scala-2.11/native/1.ll:480068:19: error: '@snprintf' defined with type 'i32 (i8*, i64, i8*, i32)*'
[error]   %_35 = call i32 @"snprintf"(i8* %_30, i64 10, i8* %_32, i8* %_34)
[error]                   ^
[error] 1 error generated.
[info] Compiling to native code (9759 ms)
[error] clang: error: no such file or directory: '/home/scala-native/scala-native/unit-tests/target/scala-2.11/native/1.ll.o'
```

**Comment by WojciechMazur** [comment]
I think the problem is dependent on CLang version. CI uses CLang-5. When testing locally I'm using Clang-10 and have never observed such issues.  Do you remember if this issue existed in both release modes or only in debug? Further, one splits code in multiple `*.ll` files.
I've observed that eq:
 `1.ll` contains only `declare i32 @"snprintf"(i8*, i64, i8*, i32)`
 `3.ll` contains only `declare i32 @"snprintf"(i8*, i64, i8*, i8*)` 

I suppose newer versions of clang can use declarations from other `*.ll` files, when old ones only check for those within a single file.

**Comment by lolgab** [comment]
Couldn't we update the reference Clang reference version? 5.0.0 is from 2017.

**Comment by WojciechMazur** [comment]
This issue does not occur in clang 6.0.0. In fact, updating the clang version in CI is currently the only known solution. I've tried to fix it in CodeGen, but I have not managed to get any successful results.  
We also should mention this issue in docs.

**Comment by ekrich** [comment]
I think Clang 6 would be a good new minimum version - I was still planning on addressing our clang discovery code but we could just adjust the minimum in the docs for now.
