### ISSUE TITLE
posixlib dirent.c should set errno before calling readdir

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1999]
The presenting problem is that Travis CI is intermittently (say 2 out of 30 tests on one run) failing for
no apparent reason with: 
```
Test java.nio.file.DirectoryStreamTest.hasNextReturnsFalseAfterStreamIsClosed started
[error] Test java.nio.file.DirectoryStreamTest.hasNextReturnsFalseAfterStreamIsClosed failed: java.io.IOException: Bad file descriptor
```
Following the stacktrace and studying the routines in the call chain shows that `scalanative_readdir` in posixlib
dirent.c does not set errno to 0 before calling the C RTL readdir.  The posix description is quite explicit about the need
to zero errno if one will be testing it, as this code does, after the readdir call.

Now I do not know if fixing this obvious flaw will solve the Travis CI intermittent failure, but it should help
determine if the EBADF is real or prior junk.   Now please do not ask me why readdir() of `Paths.get(".")` would be returning
an empty stream. That is a different basket of joy.

**Comment by ekrich** [comment]
I too have seen this test fail intermittently.

**Comment by LeeTibbert** [comment]
@ekrich Thank you for the additional data point.   I hate to share misery, but at least I am in good company ;-)
