### ISSUE TITLE
Add support for java-style strings

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#20]
Features:
- [x] Port `java.lang.String` from Apache Harmony
- [ ] Update string lowering to reflect the new implementation

**Comment by t-hiroyoshi** [comment]
I'll try to make an effort on this:)

**Comment by densh** [comment]
Apache harmony code should be quite straightforward to port it over to Scala. Make sure you're not using any GPL-licensed code as the reference. The second part of the task requires changes in the compiler, just ping me when you have initial prototype compiling and I'll update it for you.

Another thing. `java.lang.String` is actually `java.lang._String` in the source code. This is due to scalac having issues having some core java classes reimplemented in Scala.

**Comment by t-hiroyoshi** [comment]
@densh 
I've done this https://github.com/t-hiroyoshi/scala-native/blob/java-string/javalib/src/main/scala/java/lang/String.scala
Do you have any advices for me?

**Comment by densh** [comment]
@t-hiroyoshi Can you open a PR for that? I have a few improvements to suggest.

**Comment by t-hiroyoshi** [comment]
@densh Okay thanks:)

**Comment by densh** [comment]
Thanks a lot to @t-hiroyoshi and @sjrd for fixing this one. It was a great team effort to get this one closed! 👍
