### ISSUE TITLE
posixlib dirent.c should be improved

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2001]
Whilst developing PR #2000, I discovered two opportunities for improvement in posixlib dirent.c.
PR @2000 was intended as a minimal, target, surgical change.

1)  The current design of readdir() conflates an end of file (EOF) on the underlying directory stream (errno == 0, NULL from call)
      with any errno other than the three checked.  To my thinking EOF should be -1 and any other positive errno passed
      back as is. The erron checking in the current code does not add any value.

2)  The current dirent.c code uses a number of return statements. There are places for return statements and C++
      programmers love them. I believe the code would be clearer and more likely to be correct if were restructured
      to eliminate those return statements.

**Comment by ncordon** [comment]
I'm taking a go at this
