### ISSUE TITLE
Scala Native is not passing command line arguments to application code.

### ISSUE THREAD

**Issue by frgomes** [scala-native/scala-native#201]
https://github.com/frgomes/scala-native-testsuite/blob/master/testsuite/0201/src/main/scala/issue0201.scala
```scala
def main(args: Array[String]): Unit = {
  assert(args != null, "Cannot receive command line arguments.")
}
```

**Comment by densh** [comment]
Duplicate of https://github.com/scala-native/scala-native/issues/130
