### ISSUE TITLE
Remove old testing framework and associated code

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2011]
Now that the unit tests have been ported to JUnit we should be able to remove the old test harness, associated projects, and tests.

**Comment by LeeTibbert** [comment]
I am as anxious to get rid of obsolete code as anybody. I think that we should think about what removing the
old test harness now or in the near future would do for existing projects which use Scala Native and the
old test harness.

To speak plainly, I think that Scala Native 0.next should clearly and boldly deprecate the old test 
harness and state that it will be removed in the version after that. Then it should be removed
the day after 0.next is released.   

In removing the old test harness, IMO, we should invest time to ensure that at least ScalaTest,
uTest, and ZioTest all continue to work. SBT defined some of the protocol, but there may
be parts of the old test harness tangled in there. We have to be careful what we whack!

I have some sandbox work which I have not flushed back to uTest and ZioTest to get 
them running with a recent 0.4.0-SNAPSHOT version.   As release grows closer,
I, or someone, should probably ensure that such code gets submitted.
 
(I never did get Mill working, just ran out of time).

**Comment by sjrd** [comment]
The old testing framework is private to this repo. It is not published anywhere, so no one can be using it. We can therefore remove it now without deprecation.
