### ISSUE TITLE
Some symbols are missed inside unit tests

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#2028]
```
[info] Dumping intermediate code (linked) (921 ms)
[error] missing symbols:
[error] * M41scala.scalanative.testinterface.TestMain$D4mainLAL16java.lang.String_uEO
[error] * T41scala.scalanative.testinterface.TestMain$
```

I get this via `sbt ++2.11.12 clean test` on `OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)` with 31b6733
 as local root

**Comment by catap** [comment]
@WojciechMazur I guess it should be fixed for future release ;)

**Comment by sjrd** [comment]
In this repo, `test` is meaningless. It's the result of the aggregation of all the projects, but it's not intended to be used. Virtually no task is meant to be used in the root project (besides `clean`).

What you're after is probably `unit-tests/test`. Or maybe `test-all` if you really want to.

I agree the error message is not clear, and we could make an effort in the build to redirect users to `unit-tests/test`.

**Comment by catap** [comment]
@sjrd it was a while ago and github says that just 10 days but I feel more like a year.

I can't be sure that I did but I doubt that it isn't something like `sbt +test` to run tests on all supported scala versions.
