### ISSUE TITLE
Binary with target `arm64-apple-macosx11.0.0` crashed after start

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#2030]
This is followup for https://github.com/scala-native/scala-native/issues/2029.

As soon as I've started produced binary... it's failed!

Example of crash log:
```
Process:               sandbox-out [58657]
Path:                  /Users/USER/*/sandbox-out
Identifier:            sandbox-out
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [18805]
Responsible:           Terminal [581]
User ID:               501

Date/Time:             2020-11-22 02:58:08.293 +0100
OS Version:            macOS 11.0.1 (20B50)
Report Version:        12
Anonymous UUID:        D8918AD7-A83C-CD04-0D1B-304BD8A04567


Time Awake Since Boot: 55000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000102c74000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000102c74000   x1: 0x000000016d18b758   x2: 0x000000016d18b708   x3: 0x00000001033b4802
    x4: 0x0000000000000070   x5: 0x0000000000000073   x6: 0x000000016d18b4b0   x7: 0x00000000000006f0
    x8: 0x000000016d18b738   x9: 0x000000016d18b718  x10: 0x00000001033d64a0  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0xfffffffffffffff9  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000103388624  x17: 0x0000000103389624  x18: 0x0000000000000000  x19: 0x000000016d18b758
   x20: 0x0000000102c74000  x21: 0x000000016d18b708  x22: 0x0000000102c74000  x23: 0x000000016d18b8b0
   x24: 0x000000016d18b998  x25: 0x000000016d18b7f0  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x000000016d18b890   fp: 0x000000016d18b6f0   lr: 0xb3480001033885ec
    sp: 0x000000016d18b670   pc: 0x000000010338aa1c cpsr: 0x80000000
   far: 0x0000000102c74000  esr: 0x92000007


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 35950
    thread_create: 0
    thread_set_state: 0

```

**Comment by catap** [comment]
After digging a while I feel that cross compilation right now moving in wrong direction. Right now I mean https://github.com/scala-native/scala-native/pull/1904 and https://github.com/scala-native/scala-native/pull/1905.

The right and simplest way is setup correct `-arch` via `nativeCompileOptions` and `nativeLinkingOptions`.

Apple's M1 hasn't got any JDK and I'm using JDK from `x86_64`. If I build sandbox with `-arch arm64` via `nativeCompileOptions` and `nativeLinkingOptions`, it works very well.

If I don't specified `-arch` it uses default one that is ingers from JDK, and when I specified a target => nothing works.

Honestly, it also explains https://github.com/scala-native/scala-native/issues/2029 that should works ;)

and the way when `targetTriple` is hidden and user can add a list of `arch` introduce a way to build universal binary.

To do that we need:
 - discover `targetTriple` for each arch via specified `-arch ARCH` at `Discovery.targetTriple`,
 - produce `.ll` for each discovered targets,
 - run a linker with multiple `-arch` options.

**Comment by ekrich** [comment]
@catap Have you tried this with that latest code or newer macOS/clang to see if this is still an issue?

**Comment by catap** [comment]
@ekrich let me try it

**Comment by catap** [comment]
@ekrich I'd love to confirm that I've used the local root 56e6fd7a6bd36b7b8b76994e484e9e497df8600d and successfully build sandbox as `sandbox/target/scala-2.12/sandbox-out: Mach-O 64-bit executable arm64` on macOS 11.6 with Apple clang version `13.0.0 (clang-1300.0.29.3)`
