### ISSUE TITLE
Investigate not found signatures in Lower.genMethodOp

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2035]
When working with #2032 a new bug was spotted.  `Lower.genMethodOp` -> `genClassVirtualLookup` may generate invalid code which compiles, but fails in runtime.
There were several instances of Sig not being found in class `VirtualTable`. Since we're only looking for an index there when an element is not found it silently continues with result value `-1` This causes the generation of invalid `getElementPtr` LLVM IR. The resulting pointer may then lead to `dynamicCallsMap: PerfectHashMap` in RTTI instead of actual function leading to SeqFault.
Some examples of not existing Sigs were `ObjectArray.clone: Object`, or `StringBuilder.subString`. 

For most of the time, this bug seems to be unharmful, however, it may show up when using reflective calls.
When testing locally code for `ReflectivProxyTest` in the sandbox it behaved differently than code in unit tests and did not fail in runtime.

**Comment by ekrich** [comment]
There is also this one that is spitting out warnings but seems to work. https://github.com/scala-native/scala-native/pull/2023

**Comment by WojciechMazur** [comment]
Examples of missing signatures
```
did not found sig D5cloneL16java.lang.ObjectEO in Top(scala.collection.mutable.MutableList)
did not found sig D5cloneL28scala.collection.mutable.MapEO in Top(scala.collection.mutable.AbstractMap)
did not found sig D5cloneL28scala.collection.mutable.SetEO in Top(scala.collection.mutable.AbstractSet)
did not found sig D9substringiL16java.lang.StringEO in Top(java.lang.AbstractStringBuilder)
did not found sig D11codePointAtiiEO in Top(java.lang.AbstractStringBuilder)
did not found sig D5cloneL16java.lang.ObjectEO in Top(java.lang.Object)
did not found sig D5cloneL31scala.collection.mutable.BufferEO in Top(scala.collection.mutable.AbstractBuffer)

```

**Comment by ekrich** [comment]
In the past we repeated methods on sub-classes that should not have been needed because of some other problem with method lookup or override. This should not matter but I wonder if some of those still linger in the code base.

Override issue - https://github.com/scala-native/scala-native/issues/375
Part 1 - https://github.com/scala-native/scala-native/pull/1313
Part 2 - https://github.com/scala-native/scala-native/pull/1323

Maybe these will help.
