### ISSUE TITLE
Scala Native throws non-JVM compliant Exception on attempted out-of-bounds array access

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2044]
Please consider the following code:
```
 val size = 10
    val a1 = new Array[Int](size)
    a1(size + 1)
```
Given that this is not Fortran, I am expecting an Exception.
When I run that fragment on Scastie (JVM) I get the expected:
`java.lang.ArrayIndexOutOfBoundsException: 11`  A good baseline.

When I run the code on Scala Native, both I and Scala.js ArraysTest
expect to seem the same Exception.  Instead, we get:
`java.lang.IndexOutOfBoundsException: 11`   

I believe this is a bug. Am I missing something? 

Before I set out to study the code and consider a fix,
does anybody know of a good reason for them differing?
Does anybody object to the Exception changing, if feasible,
to match the JVM practice since Java 1.0?

I discovered the difference whilst porting the more complete
Scala.js as part of a PR in process to fix a bug in Arrays.scala.  

Thank you for corrections, lore, advice, & direction.

**Comment by sjrd** [comment]
I don't think there's a good reason. We can fix it.
