### ISSUE TITLE
testsuite.utils Platform.scala needs implementation & a good home

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2045]
Folks,  

Time has come for at least a simple implementation of `testutils``Platform.scala`.  The one which has 
declarations such as "executingInJVM".  

Short story: Can we achieve some consensus on the proper directory for a soon-to-be implemented
                    testsuite.utils.Platform.scala for Scala Native?

                     I suggest: `/unit-tests/src/test/scala/utils` to correspond to Scala.js 
                     `test-suite/js/src/main/scala/org/scalajs/testsuite/utils`. The former
                      is the location of AssertThows.scala,  CollectionConverters.scala, &
	             ThrowsHelper.scala

Long story:

PropertiesTest.scala already has a:
```
 // remove when Platform is implemented
  val hasCompliantAsInstanceOfs = true
```
which was reasonable at the time.

Because of two bugs in SN Array/Arrays, I am taking a run
at porting Scala.js Arrays.scala & ArraysTest to SN and
being done with it.  I find myself needing something like:
```
 // remove when Platform is implemented                                        
  val hasCompliantArrayIndexOutOfBounds = true
  val executingInJVM = false
  val executingInScalaNative = true
```
It seems lilke creating at least a simple testsuite.utils.Platform.scala to
correspond to the Scala.js usage is better than putting variant code
in ArraysTest.scala.

The hard part is coming up with a reasonable location for the file on Scala Native.
It appears to me that duplicating the Scala.js directory structure, with the names
adjusted, does not make sense for SN (i.e. too much current & legacy practice.)

I am aware of three other Platform.scala already on Scala Native:
```
./nativelib/src/main/scala/scala/scalanative/runtime/Platform.scala
./scalalib/overrides-2.11/scala/compat/Platform.scala
./scalalib/src/main/scala/scala/compat/Platform.scala
```
None of the three seem to be good candidates into which to drop
the requited testsuite.utils code. `runtime/Platform` is close but
using it would mix two sets of concerns and also not parallel
the content and intent of Scala.js.

Sugestions? Beyond "the bike shed ought to be chatreuse".

Thank you.

**Comment by sjrd** [comment]
> I suggest: `/unit-tests/src/test/scala/utils` to correspond to Scala.js `test-suite/js/src/main/scala/org/scalajs/testsuite/utils`. The former is the location of AssertThows.scala,  CollectionConverters.scala, & ThrowsHelper.scala

Sounds good.
