### ISSUE TITLE
posixlib fcntl.close() is not a POSIX function

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2059]
The proper function is `unistd.close()`.

**Comment by ekrich** [comment]
I think we want to make the files only have what the headers define but ...

`Inclusion of the <fcntl.h> header may also make visible all symbols from <sys/stat.h> and <unistd.h>.`

Also, I am not sure how those `open ...` vararg functions should be defined.

**Comment by LeeTibbert** [comment]
re: `varargs open ...` 

I checked that an FcntlTest.scala exists.  It has two cases, one for each form of `open()`.  So those calls
are getting exercised, at least once.   

I would have to go back to the POSIX spec to see if it specifies other
forms of `open()`.

I have a dim memory that the three arg form of `fcntl.open` went missing about the 0.4.0-M2 time frame
and of my submitting a PR to restore it.   Agreed, dim & fading memory is not a 
guarantee of present correctness...

**Comment by ekrich** [comment]
@LeeTibbert I was not trying to confuse things which means I agree that we want just what is required by the spec.

I think the PR is fine in https://github.com/scala-native/scala-native/pull/1633 - I left a review comment.

**Comment by WojciechMazur** [comment]
Fixed in #1633
