### ISSUE TITLE
Need plan for java.text classes

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2102]
What is the plan/future for `java.text` classes?  Pardon me if I was sent the memo and 
lost it ;-)

The reason that I ask is that PR #1886  implements j.t.ParsePosition and the javalib java.text
directory has moved to another project (java.mumble-ext or such).   

As mentioned in the commit message for that PR, SN j.t.ParsePosition to support
scala-java-time. At the time, there was discussion about removing java.time
methods from SN.  I believe that has come to pass, which means that SN
now relies upon 3rd party libraries.  scala-java-time would be an excellent
candidate, if Scala Native contained the methods SJT needed in order to 
build.    

If the plan is that all java.txt classes located in the new java-mumble-ext
project, so be it.  I can (dream of) change/changing the PR but the
new location & dependency needs to be communicated to scala-java-time
development.

Please advise.  Thank you.

**Comment by sjrd** [comment]
We shouldn't have any class from `java.time` or `java.text` in this repo. Exception: the dummies in javalib-ext-dummies, which are not published, and therefore not visible by users.

`java.text.ParsePosition` is already present in scala-java-locales. That is its rightful place. So #1886 should be closed under the new architecture.

The implementations in javalib-ext-dummies must only be there to support *testing* of other classes that are in the javalib. For example, `j.u.Locale` is there to support the tests of `String.to{Upper,Lower}Case`.

**Comment by LeeTibbert** [comment]
Thank you for the timely & lucid description of the plan. I have closed PR #1886 as a result.
