### ISSUE TITLE
Feature enquiry: JNI interoperability

### ISSUE THREAD

**Issue by scalasolist** [scala-native/scala-native#211]
It is not a complete feature request. I'm just curious about plans for the scala-native and could not find more suitable way to ask.

Have you considered to add support for JNI? In this way part of project may be written in scala and performed with JVM and has full access to java libraries, and some parts of the code are manually optimized to run as JNI on LLVM platform. Such feature would require type conversion to allow seemingly transparent calls from Scala on JVM to Scala on LLVM. Also there is need to convert scala-native annotations to some sensible scala types, e.g. stack allocations to some kind of box, so Scala on JVM and Scala on LLVM could share the same header.

**Comment by frgomes** [comment]
I suggest you join us at gitter.
https://gitter.im/scala-native/scala-native

**Comment by densh** [comment]
This is out of scope for the Scala Native project. We already provide an interop layer (extern objects) to communicate over C ABI that is far easier to use than JNI, you can use that to interoperate with JVM if you want to.
