### ISSUE TITLE
Integer.parseInt NumberFormatException error message

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#2125]
### JVM

```
scala> java.lang.Integer.parseInt("foo")
java.lang.NumberFormatException: For input string: "foo"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Integer.parseInt(Integer.java:580)
  at java.lang.Integer.parseInt(Integer.java:615)
```

### scala-js

https://github.com/scala-js/scala-js/blob/465a7645f06325ff9785bb2529c20ebd48ca3df8/javalanglib/src/main/scala/java/lang/Integer.scala#L79-L80

### scala-native

https://github.com/scala-native/scala-native/blob/b9b83c63323fb42e96d243a04bebc8a65f30669b/javalib/src/main/scala/java/lang/Integer.scala#L331-L335

😢 
missing `"For input string: ` and double quotes.

Maybe not only `java.lang.Integer` but also `java.lang.Long` etc...

**Comment by ekrich** [comment]
Thank-you for the report.

I did put this ticket in today that would help for these sorts of differences. Plus we can copy tests from Scala.js now that we are on JUnit. https://github.com/scala-native/scala-native/issues/2124

https://github.com/scala-js/scala-js/blob/3dc2920fde982fab16ea3a47f1db4c412a19c92a/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lang/IntegerTest.scala#L522-L545

**Comment by ncordon** [comment]
I'm giving this a go. I've started by `Integer`, but I will take a look at other type's stack traces differences.
