### ISSUE TITLE
`UndefinedBehaviorError` calling `FileSystem.getUserPrincipalLookupService`

### ISSUE THREAD

**Issue by avdv** [scala-native/scala-native#2128]
The following code:
```
import java.nio.file.FileSystems
 
object Main {
  def main(args: Array[String]): Unit = {
    println("Hello, world!")
    val fs = FileSystems.getDefault                                                                                                            
    println("ok")                                                                                                                              
    val lookupService = fs.getUserPrincipalLookupService                                                                                       
    println("done")                                                                                                                            
  }
}
```

Produces:
```
Hello, world!
ok
scala.scalanative.runtime.UndefinedBehaviorError
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at scala.scalanative.runtime.package$.throwUndefined(Unknown Source)
	at <none>.(Unknown Source)
	at <none>.main(Unknown Source)
	at <none>.__libc_start_main(Unknown Source)
	at <none>._start(Unknown Source)
```
Steps to reproduce:
1. `sbt new scala-native/scala-native.g8` (with scala-native 0.4.0, sbt 1.4.6 at the time of this writing)
2. `cd scala-native-seed-project`
3. `sbt run`

System:
```console
$ uname -a
Linux nixos 5.8.7-zen1 #1-NixOS ZEN SMP Tue Jan 1 00:00:00 UTC 1980 x86_64 GNU/Linux
$ $ clang --version
clang version 10.0.1 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/w8a9x07rai37srm9xyq827bspdvvb4xq-clang-10.0.1/bin
$

**Comment by WojciechMazur** [comment]
This method is currently not implemented in javalib (our java stdlib implementation, since all java dependented definitions needs to be reimplemented in Scala Native). If config would be set with `NativeConfig.withLinkStrubs(false)` you would be able to observe that it fails when linking.

**Comment by avdv** [comment]
OK, I thought this might have been a regression since I was using this code with 0.4.0-M2. But, I also had integrated a few PRs on top of it to make it usable for me -- including #1609 which also has  dbc5c8ca761b8e4040efb3db4f830b863f7a738f : "Add default `UserPrincipalLookupService" :smile: 

BTW, why is `nativeLinkStubs := true` the default in the scala-native g8 template? Isn't that the most confusing default for new users?

**Comment by LeeTibbert** [comment]
@avdv Hi!  When I saw the title I immediately thought "Haven't there been a long standing PR to fix this?"
Sorry that you tripped over it a second time.

To my understanding, the intent of SN 0.4.0 was to focus on changes which might break the 
intermediate language (NIR) used by the compiler.  Draining the PR queue was rolled over
to a 0.4.1 release.   So your/our PR is, like Merlin, merely sleeping in the oak. That is,
paused, not dead or wasted.  

For 0.4.mumble, there will need to be some changes to the testing, because SN now uses
JUnit.  I had planned/hoped to contact you when the  0.4.mumble plans are announced about
us creating a new PR with the tests updated to JUnit.  I could do the translation and there would
be minimal exertion on your part.  Your thoughts?

**Comment by LeeTibbert** [comment]
re: `nativeLinkStubs := true`   As with any default, there is always room for discussion and down sides.
@ekrich may remember more of the history and intent than I.  In my memory, that default was chosen
to allow applications to at least link and run until they tried to execute a stub method.  It was recognition
that there are a lot of stub methods in SN, particularly in `javalib`.  You may know better than I, but
sometimes in bootstrapping an application, one is interested in getting the most parts working and 
then focusing on the problem children.

Of course, if as seems to be the case with your application, if the problem child is on the critical
path this approach is not helpful (attempt by an American at British understatement).

Does context help?  Of course, the real question is always "Does this default still make sense for
the majority or non-expert set of users?" Demographics change rapidly.

**Comment by sjrd** [comment]
I would be in favor of changing the default to `false`. For comparison, Scala.js doesn't even have the *possibility* of linking with stubs. Either something is correctly implemented and it links, or it does not link. We've never had any complaint about that.

**Comment by LeeTibbert** [comment]
@ekrich   What are your thoughts about changing the `linkStubs` default?

If the default for `linkStubs` should change to `false`, in the interest
of minimalist simplicity, I suggest that we eliminate that line/setting
in the template all together.  One less thing for someone new
to Scala Native to stumble over. 

The `linkStubs` default of `false` is documented in the ReadTheDocs docs
so there may be minimal value in setting it in the template.

All: Thoughts?

**Comment by avdv** [comment]
> @avdv Hi! When I saw the title I immediately thought "Hasn't there been a long standing PR to fix this?"

Hi @LeeTibbert, really?! I had forgotten about it... :blush: 

> For 0.4.mumble, there will need to be some changes to the testing, because SN now uses
> JUnit. I had planned/hoped to contact you when the 0.4.mumble plans are announced about
> us creating a new PR with the tests updated to JUnit. I could do the translation and there would
> be minimal exertion on your part. Your thoughts?

That sounds great! I was just too excited to see 0.4.0 being released and immediately tried to convert my project to it (https://github.com/avdv/scalals if you're wondering). From the release notes this seems to be a big step forwards, kudos to the team -- that must have been much more work than what the release notes suggest! :bow: 

BTW, I also have `linkStubs` set to true in my project, although I do not want that -- probably simply because it has been the default from the g8 template.

Also, having a background in C/C++, *undefined behavior* means a totally different thing to me than something is not implemented / has been replaced with a stub...

**Comment by LeeTibbert** [comment]
@avdv As we discussed a while back, I have been working on co-authoring a  successor to your
PR #1609. I have been bring the changed files of that PR up to date with the current mainline
before I tackle moving the test files to JUnit.

Along the way, I developed a question about the location of `scala.scalanative.nio.fs.attribute.NativeUserPrincipalLookupService'`.
It looks to me like that file should be in {Uppercased FILE for emphasis/distinction, should 
really be lowercase} `scala.scalanative.nio.FILE.attribute`, along with the Exception from
that PR and other *Principal* stuff.  Am I missing something?  Is there a reason that
the file is located where it is?  If I am wondering, a reviewer will probably ask the same
thing.  Pardon if the reason is obvious.

**Comment by LeeTibbert** [comment]
Later:  The  `scala.scalanative.nio.fs` comes from the fact that `NativeUserPrincipalLookupService` is
not defined in java.  The `attribute` part comes from it fetching attributes like gid (Duh!).  I still do not
follow why it is `nio.fs` and not `nio.file`.

On a different topic, should the file be named something like UserPrincipalLookServiceImpl.scala, where
Impl is a somewhat common in Scala convention for Implementation?  If not that, perhaps something like
`PosixPrincipalLookupService.scala` (similar to existing PosixFilePermissions.scala).  I keep asking myself
`Native` what? Arch, OS, ???   Isn't `Native` going to get blown away if/when SN supports Windows (or XYZ
not Posix?)  This is javalib, not posixlib, so non-posix is a consideration.  

Yes, changing names is a pain, but I can do it and that is what text editors are for.

I do not want to spend my lifetime 'borrowing trouble' at the cost of getting _anything_ done, but 
I do like to design around it if I can.

Thank you for helping get me straightened out, at least on this item and for some values of
straightened ;-)

**Comment by avdv** [comment]
Hi Lee,

Nice that you're looking into this again!

>  I still do not follow why it is nio.fs and not nio.file.

I think I tried to match up the package name with the OpenJDK layout of classes, like `sun.nio.fs.UnixFileSystem`, only replaced `sun` with `scala.scalanative`. In OpenJDK, the implementation for that service is done as an anonymous class inside the FileSystem implementation directly.

See https://github.com/openjdk/jdk/tree/jdk8-b120/jdk/src/solaris/classes/sun/nio/fs 

> On a different topic, should the file be named something like UserPrincipalLookServiceImpl.scala, where
Impl is a somewhat common in Scala convention for Implementation? If not that, perhaps something like
PosixPrincipalLookupService.scala (similar to existing PosixFilePermissions.scala). I keep asking myself
Native what? Arch, OS, ??? Isn't Native going to get blown away if/when SN supports Windows (or XYZ
not Posix?) This is javalib, not posixlib, so non-posix is a consideration.

Yes, makes sense. OpenJDK 8 has Unix*, MacOSX*, Solaris*, and BSD* prefixed classes. Wondering how they are coping with Windows... it's not POSIX, but maybe Unix-enough? In more recent JDKs, they use a subdir per OS. But I would probably just use Posix* as a prefix in this case.

**Comment by sjrd** [comment]
> See <link to OpenJDK>

Please do not post links to OpenJDK source code here. We are *never* allowed to *look* at that code. Otherwise we're going to infringe on the GPL license.

**Comment by LeeTibbert** [comment]
@avdv  Congratulations on getting your work on this issue merged. PR #2244 should resolve this issue.
Please let me/us know if you encounter further problems, or have suggestions/contributions to offer.

**Comment by avdv** [comment]
Thank you @LeeTibbert! :bow: I'll see how it works...
