### ISSUE TITLE
GitHub landing page lists latest version as 0.4.0-M2

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2130]
The GitHub landing page https://github.com/scala-native/scala-native/ present 
0.4.0-M2 as the latest release.  I believe that this is not a caching issue on my system.

Similarly, the "Releases" page shows 0.4.0-M2 as the latest, with a prominent header.
A two line entry for 0.4.0 proper exists but it has no header.  The info is correct but does
little to motivate the use of 0.4.0, which has far fewer bugs.

To the best of my knowledge, a community contributor can not remedy these defects.
It will probably take someone from Scala Center.   If I am wrong, just let me know
what change is needed and I will take a run at it.

**Comment by sjrd** [comment]
Thanks for noticing. I forgot to create the GitHub release in addition to the git tag. It's fixed now.
