### ISSUE TITLE
Test runs even with no test files

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2132]
This is not minimized but I thought I would report anyway. The project has a library sub-project which is the one that exhibits this behavior and a `testSuite` project that contains the tests and seems to work fine.

Please refer to the following repo:
https://github.com/ekrich/sjavatime/

```
sbt:sjavatime-root> sjavatimeNative/test
[info] Linking (1282 ms)
[info] Discovered 1339 classes and 9703 methods
[info] Optimizing (debug mode) (2488 ms)
[info] Generating intermediate code (1580 ms)
[info] Produced 8 files
[info] Compiling to native code (1560 ms)
[info] Linking native code (immix gc, none lto) (252 ms)
[info] Total (7247 ms)
[info] Starting process '/Users/eric/workspace/sjavatime/sjavatime/native/target/scala-2.13/sjavatime-out' on port '54576'.
```
Note: by contrast, this happens when I execute `run`.
```
sbt:sjavatime-root> sjavatimeNative/run
[error] No main class detected.
[error] (sjavatimeNative / Compile / nativeLink) No main class detected.
[error] Total time: 2 s, completed Jan 25, 2021 2:58:08 PM
```

**Comment by sjrd** [comment]
That is expected and unavoidable. We need to run some code in the test suite executable to detect what testing frameworks exist, if any, and what their test "signatures" are, before we can detect that there are in fact no tests matching those signatures.

If you know in advance that there is no test, you can tell to sbt with `Test / test := ()`.

**Comment by ekrich** [comment]
I hadn’t seen that before. Does this happen with Scala.js as well? Thanks for the ‘sbt’ tip.

**Comment by sjrd** [comment]
Yes, it happens for Scala.js as well. And in a sense, it happens for Scala/JVM too, although that doesn't display any log message, since there's no linking, although there's some class loading happening.
