### ISSUE TITLE
Clang linking failure with `.withOptimize(false)`

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#2144]
Trying out zio I had this linking error:
```
[error] /Users/lorenzo/zio-repro/target/scala-2.13/native/5.ll:25631:7: error: value doesn't match function result type 'i32'
[error]   ret i8* %_9
[error]       ^
[error] 1 error generated.
```

It only happens with `withOptimize(false)` in the settings.

I couldn't find a minimal reproduction.
You can find, however a reproduction using Zio here: https://github.com/lolgab/zio-repro

**Comment by WojciechMazur** [comment]
The problem is in this lines of `ZScope.unsafeRelease`
``` scala
  java.util.Arrays.sort(
    array,
    (l: OrderedFinalizer, r: OrderedFinalizer) =>
      if (l eq null) -1 else if (r eq null) 1 else l.order - r.order
  )
```

We expect this SAM Comperator should return `Int` value, but it returns `Integer`. After calling `compare` method it boxes result for some reason.

**Comment by lolgab** [comment]
@WojciechMazur You're right!
A smaller reproduction is:
```scala
java.util.Arrays.sort(Array.empty[Object], (l: Object, r: Object) => 0)
```
