### ISSUE TITLE
Publish sbt-scala-native to Maven Central instead of Bintray

### ISSUE THREAD

**Issue by sjrd** [scala-native/scala-native#2146]
JFrog announced today that they are shutting down Bintray:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I don't know yet what will come of the previously published artifacts. This is going to be a nightmare. In the meantime, we should publish to Maven Central from now on.

**Comment by catap** [comment]
@sjrd I guess this should help: https://github.com/Microsoft/mvnfeed-cli

**Comment by sjrd** [comment]
Thanks for the suggestion. We don't need anything though. It's a simple matter of configuration of what we already have. See the change that was made in Scala.js:
https://github.com/scala-js/scala-js/pull/4422/commits/45a81957d513176388089f2676540d5674421e27

**Comment by catap** [comment]
@sjrd I mean to migrate old artifacts ;)

**Comment by sjrd** [comment]
For the old artifacts, we are discussing how to preserve all the sbt plugins that have been published on Bintray by everyone, in a unified read-only repo.
