### ISSUE TITLE
Failure to receive value from extern function and pass along to another function

### ISSUE THREAD

**Issue by frgomes** [scala-native/scala-native#215]
Scenario:
- an `extern` function is called, which return a `Ptr[_]`
- the received value is then passed along to another `extern` function.

Symptom:
- The second function called fails, since it receives `null`, instead of receiving the returned value given by the previous `extern` function call;
- if we add a "debug" function which prints the returned value from the first `extern` function call, we can see that it is not `null`. In this case, running the program again, it works as expected.

``` scala
val file = c"test/getopt.h"
val tu  = clang_parseTranslationUnit(index, file,
                                     argv, argc,
                                     null, 0.toUInt,
                                     CXTranslationUnit_None)
// Commenting out the line below makes the program fail.
// The function below does not mutate the variable ``tu``. It only prints its value onto the console.
debug(c"unit", tu)

val cursor = clang_getTranslationUnitCursor(tu)
```

**Comment by densh** [comment]
The bug looks bizarre, really interested in figuring out what went wrong there.

**Comment by densh** [comment]
Can you please provide self-contained example for this?

**Comment by frgomes** [comment]
I will do. Thanks.

**Comment by densh** [comment]
Given that there is still no reproduction for this, I'm closing this for now. Feel free to reopen if it's still a problem and you have minimal example that illustrates it.
