### ISSUE TITLE
Calls to String::repeat result in UndefinedBehaviorError

### ISSUE THREAD

**Issue by stefanradziuk** [scala-native/scala-native#2155]
Calling `repeat(n)` on a `String` results in `scala.scalanative.runtime.UndefinedBehaviorError`.

To reproduce:
```scala
object Main {
  def main(args: Array[String]): Unit = {
    println("-----------------------")
    println("Using * from StringOps:")
    print("Hello, " * 3)
    println("World!")

    println("-----------------------")
    println("Using repeat from String:".toUpperCase())
    print("Hello, ".repeat(3))  // this breaks
    println("World!")
  }
}
```

Output:
```
-----------------------
Using * from StringOps:
Hello, Hello, Hello, World!
-----------------------
Using repeat from String:
scala.scalanative.runtime.UndefinedBehaviorError
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.runtime.package$.throwUndefined(Unknown Source)
        at <none>.(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

`build.sbt`:
```scala
scalaVersion := "2.13.4"

// Set to false or remove if you want to show stubs as linking errors
nativeLinkStubs := true

enablePlugins(ScalaNativePlugin)
```

`project/plugins.sbt`:
```scala
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.0")
```

**Comment by stefanradziuk** [comment]
Other methods causing `UndefinedBehaviorError`:

```
String::codePoints
String::strip
String::stripLeading
String::stripTrailing
String::isBlank
String::lines
StringBuilder::compareTo
```

The common theme is that all of those were introduced in Java 11.

Looking at [`scala-native/javalib/src/main/scala/java/lang/String.scala`](https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/lang/String.scala), it looks like none of those are implemented and ideally should cause compile time errors.

Methods introduced in Java 12 are gracefullly handled at compile time:

```sbt
sbt:hellonative> run
[info] compiling 1 Scala source to /home/stefan/hellonative/target/scala-2.13/classes ...
[error] /home/stefan/hellonative/src/main/scala/Main.scala:4:21: value indent is not a member of String
[error]     println("Hello".indent(3))
[error]                     ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed 11 Feb 2021, 20:49:41
```

**Comment by stefanradziuk** [comment]
It looks like #1844 can fix the issue when it comes to the `String` methods.

I couldn't find PRs or issues that would refer to other problematic Java 11 methods:

```java
StringBuilder::compareTo
StringBuffer::compareTo
InputStream::readNBytes
IntBuffer::mismatch
```

All of the above compile fine but at runtime cause `scala.scalanative.runtime.UndefinedBehaviorError`.

This list is non-exhaustive and the issue probably affects most of the methods introduced in Java 11.

I could not reproduce this behaviour with `Character::toString`, but my guess is that in its case the method being called was not originating from `java.lang.Character`.

**Comment by ekrich** [comment]
Thank you for the report. 

My guess is that if you compiled using Java 8, you would get a compile time error.

**Comment by stefanradziuk** [comment]
> My guess is that if you compiled using Java 8, you would get a compile time error.

That's right, I get the expected compilation errors after downgrading to Java 8. Perhaps it would be worth noting in the docs under _Environment setup_ or _Java Standard Library_ that it is _Java 8 or newer_ but with an asterisk.

**Comment by sjrd** [comment]
The real issue here is that you didn't get *linking* errors for trying to call those. It's expected that they compile of you're on JDK 11 (there's nothing we can do about it) but they should fail to link.

**Comment by stefanradziuk** [comment]
It seems like the issue is not specific to JDK 11. When compiling using JDK 15, `String::stripIndent` and `String::translateIndents` get past the linking stage and results in `UndefinedBehaviorError` at runtime.
