### ISSUE TITLE
Performance degradation 0.4.0 versus 0.4.0-M2

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#2163]
The case
```scala
object Test {
  def main(args: Array[String]): Unit = {
    val start = System.currentTimeMillis
    var i = 0
    while (i < 100000) {
      "%02x".format(i)
      i += 1
    }
    val end = System.currentTimeMillis
    println(s"Spent: ${end - start}ms.")
  }
}
```

Run on `0.4.0-M2`:
```
Spent: 1080ms.
```

on `0.4.0` as `sbt ++2.11.12 sandbox/run`:
```
Spent: 3923ms.
```

on the same machine.

**Comment by LeeTibbert** [comment]
Rats!  Thank you for reporting, along with a reproducer. 

I can not try it tonight,  but as soon as I can, I will try on 0.4.1-SNAPSHOT.

**Comment by catap** [comment]
I've discovered the commit / merge that introduced such performance degradation (as it expected to be honest): https://github.com/scala-native/scala-native/commit/598325a876a2d0be978d40d84e2a29b063c7e06f

I can easy reproduce it with `sbt +clean ++2.11.12 sandbox/run` 

I guess it might exist (or be fixed) in SJS.

Cc @WojciechMazur

**Comment by sjrd** [comment]
It could be the fact that [`sendToDest`](https://github.com/scala-native/scala-native/blob/ff9c6f9c4e51b78ccc0e3c193864d6a02c510150/javalib/src/main/scala/java/util/Formatter.scala#L110-L114) always uses a varargs, whereas Scala.js has a happy path with overloads instead.

**Comment by WojciechMazur** [comment]
After taking a look for perf tracing results there might be few places to investigate: 

```
  Children      Self  Command      Symbol
+   78,74%     0,06%  sandbox-out  [.] _SM5Test$D4mainLAL16java.lang.String_uEO                                                                                                                                   ▒
+   60,07%     0,03%  sandbox-out  [.] _SM17java.lang.String$D6formatL16java.lang.StringLAL16java.lang.Object_L16java.lang.StringEO                                                                               ▒
+   60,03%     0,27%  sandbox-out  [.] _SM19java.util.FormatterD6formatL30java.util.Formatter$LocaleInfoL16java.lang.StringLAL16java.lang.Object_L19java.util.FormatterEPT19java.util.Formatter                   ▒
+   51,65%     0,18%  sandbox-out  [.] _SM27scala.scalanative.regex.RE2D6match_L22java.lang.CharSequenceiiiLAi_izEO                                                                                               ▒
+   47,61%     1,90%  sandbox-out  [.] _SM31scala.scalanative.regex.MachineD6match_L36scala.scalanative.regex.MachineInputiizEO                                                                                   ▒
+   40,71%     1,32%  sandbox-out  [.] _SM31scala.scalanative.regex.MachineD11matchEngineL49scala.scalanative.regex.Machine$MatchOriginalArgsL45scala.scalanative.regex.Machine$MatchImplArgsLAL37scala.scalanativ▒
+   28,82%    17,31%  sandbox-out  [.] _SM31scala.scalanative.regex.MachineD3addL37scala.scalanative.regex.Machine$QueueiiLAi_iL38scala.scalanative.regex.Machine$ThreadL38scala.scalanative.regex.Machine$ThreadE▒
+   26,41%     0,30%  sandbox-out  [.] _SM31scala.scalanative.regex.MatcherD5groupiL16java.lang.StringEO                                                                                                          ▒
+   26,10%     0,21%  sandbox-out  [.] _SM31scala.scalanative.regex.MatcherD9loadGroupiuEPT31scala.scalanative.regex.Matcher                                                                                      ▒
+   25,86%     0,15%  sandbox-out  [.] _SM31scala.scalanative.regex.MatcherD8genMatchiizEPT31scala.scalanative.regex.Matcher                                                                                      ▒
+   23,87%     5,72%  sandbox-out  [.] _SM31scala.scalanative.regex.MachineD4stepL37scala.scalanative.regex.Machine$QueueL37scala.scalanative.regex.Machine$QueueiiiiizuEPT31scala.scalanative.regex.Machine      ▒
+   19,54%     3,13%  sandbox-out  [.] scalanative_alloc_small                                                                                                                                                    ▒
+   18,26%     0,24%  sandbox-out  [.] _SM37scala.collection.immutable.StringLikeD6formatL20scala.collection.SeqL16java.lang.StringEO                                                                             ▒
+   17,59%     0,30%  sandbox-out  [.] _SM32scala.collection.TraversableOnceD7toArrayL22scala.reflect.ClassTagL16java.lang.ObjectEO                                                                               ▒
+   17,19%     0,06%  sandbox-out  [.] _SM39scala.collection.mutable.ResizableArrayD11copyToArrayL16java.lang.ObjectiiuEO                                                                                         ▒
+   17,16%     0,03%  sandbox-out  [.] _SM12scala.Array$D4copyL16java.lang.ObjectiL16java.lang.ObjectiiuEO                                                                                                        ▒
+   17,13%     0,00%  sandbox-out  [.] _SM36scala.collection.AbstractTraversableD11copyToArrayL16java.lang.ObjectiuEO                                                                                             ▒
+   17,13%     0,00%  sandbox-out  [.] _SM36scala.collection.mutable.ArrayBufferD11copyToArrayL16java.lang.ObjectiiuEO                                                                                            ▒
+   16,77%    14,69%  sandbox-out  [.] _SM15java.lang.ClassD2isL28scala.scalanative.unsafe.PtrL28scala.scalanative.unsafe.PtrL17java.lang.BooleanEPT15java.lang.Class                                             ▒
+   16,54%    11,38%  sandbox-out  [.] Heap_AllocSmall                                                                                                                         
```

Compiled with mode releaseFast

**Comment by sjrd** [comment]
OK, so in fact it's more related to the fact that there used to be a dedicated parser for the format specifiers, whereas now we have a regex-based one. We might need to reintroduce a dedicated parser.

**Comment by LeeTibbert** [comment]
C snprintf() should be considered, at least to the point of a design study to get some numbers.
I am willing to believe that it would be wicked fast, and contain fewer defects, that a custom
written {Integer, Long, UnsignedInt, UnsignedLong).

Real Life has prevented me from implementing the code I already have in my mind.

The C format is probably a subset of what Java accepts.   Running the Scala.js tests
on a design sketch would probably detect a few differences.  How many might determine
how viable an snprintf() solution might be.  

// Yecch! alert
One could say "For portability and JVM compliance, use String.format(). For performance
critical applications, use libc.snprintf() and here is a short example."   That would get out
of the unending business of "String.format() does not match JVM in this obscure case".
Not absolutely user friendly, but there are only so many development cycles available.

If that solution is unappealing, I believe the Ryu project had a standalone "printf'. 
Float.scala & Double.scala use Ryu IEEE754 conversion routines.  It might be
far faster to alter that RYU to accept only Java format strings.  

Then if some of Li Haoyi's utilities (FastParse?) do not already do it, there are C
parsers (is yacc appropriate here?).

I propose the first step is a small snprintf() program to time Catap's reproducer.

**Comment by sjrd** [comment]
`snprintf` is far from supporting all of what `String.format` supports. Here is a non exhaustive list of things it doesn't support:
* `h`, `b`, `n` conversions
* `BigInteger` and `BigDecimal` arguments
* Arbitrary arguments for `s`, and `Formattable` arguments
* Argument index specification
* The `(` and `,` flags
* The precision flag doesn't work the same
* Adapting its buffer too the required length
* Output to an arbitrary `Writer`
* Localization
* Throwing the right kind of exceptions

So no, `snprintf` is not an fair approximation of `String.format` by any measure.

Regarding parsing, the syntax of this thing is so trivial that using a parser generator would be more complex than implementing a custom parser.

There's no reason not to reintroduce a custom parser if that is the bottleneck.

**Comment by ekrich** [comment]
Given the recent work in Scala.js, couldn’t we just copy that work?

**Comment by sjrd** [comment]
We should also take the recent work from Scala.js, but that's not performance-oriented. And in Scala.js we also use a (JS) RegExp because that's super fast on JS.

**Comment by WojciechMazur** [comment]
Before rewriting Formatter to not use regex I've tried to reproduce this issue, my results quite differ from what you have observed, (In the following release means releaseFull mode): 
```bash
for prog in $(ls); do
  echo "Testing ${prog}"
  for i in $(seq 1 5); do
    ./${prog}
  done
done
Testing 0.4.0-M2-debug
Spent: 3488ms.
Spent: 3473ms.
Spent: 3477ms.
Spent: 3506ms.
Spent: 7024ms.
Testing 0.4.0-M2-releaseFast
Spent: 2581ms.
Spent: 2488ms.
Spent: 2468ms.
Spent: 2464ms.
Spent: 2463ms.
Spent: 2480ms.
Testing 0.4.0-M2-release
Spent: 2655ms.
Spent: 2612ms.
Spent: 2609ms.
Spent: 2621ms.
Spent: 2631ms.
Testing 0.4.0-debug
Spent: 3616ms.
Spent: 4375ms.
Spent: 4202ms.
Spent: 4208ms.
Spent: 4206ms.
Testing 0.4.0-releaseFast
Spent: 4276ms.
Spent: 4196ms.
Spent: 4251ms.
Spent: 4226ms.
Spent: 4237ms.
Testing 0.4.0-release
Spent: 606ms.
Spent: 615ms.
Spent: 610ms.
Spent: 616ms.
Spent: 612ms.
```

Also interesting fact, 0.4.0-release takes the same amount of time as running JVM (with JDK 11): 
```
for i in {0..5}; do 
   java -Xmx1024M -Xms1024M -classpath target/scala-2.11/classes:$HOME/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.12.jar Test
done
Spent: 614ms.
Spent: 635ms.
Spent: 642ms.
Spent: 617ms.
Spent: 651ms.
Spent: 601ms.
```
Of course in warmed up JVM, eg. when running Test from sbt, this number can 10x smaller.

**Comment by catap** [comment]
@WojciechMazur and your results explains it.

I discovered this exampel as part of unit tests, that is build as releaseFast I assume.

Interesting point.

**Comment by WojciechMazur** [comment]
Small update on this topic. After replacing regexp with the previous Apache Harmony-based format parser we were able to lower releaseFast times to **~450ms** - at this moment a lot of time spent for `j.l.Class` related operations. 
After rebasing onto Denysh changes in #2139, the time of this simple benchmark gets down to **~50ms!**

We really need to optimize our regex implementation as it really creates a lot of overhead right now.

**Comment by ekrich** [comment]
@LeeTibbert If you are not working on anything else big, maybe we could look at integrating code tables for regex along with the Unicode 13 upgrade. I have the upper lower code tables done but we need to upgrade the other character tables too.

**Comment by LeeTibbert** [comment]
@ekrich Perhaps you could start an Issue for co-ordination or we could move this discussion to
your existing more general Unicode Issue?  I believe that PR #1685 does some of what you 
describe.   Even though it is 18 months old, I think it, or some close edit of it, is still relevant.
It was shovel-ready as of January 2020 and could be rebased.
