### ISSUE TITLE
Missing java.time.Duration in 0.4.0

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#2173]
Scala-Native `0.4.0-M2` had `java.time.Duration` which was removed before `0.4.0` at https://github.com/scala-native/scala-native/commit/e2670984787ea4b9061e700fc1296358bb1d9757

As result existed code is broken.

For example @ekrich 's sconfig can't be linked with scala-native 0.4.0: https://github.com/ekrich/sconfig/issues/152

**Comment by ekrich** [comment]
You must now supply a `java.time` API for Scala Native and Scala.js because it is not included. See the comment on the `sconfig` issue above.
