### ISSUE TITLE
Mainline CI is broken

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2176]
CI broke sometime Tues, Feb 23 to Weds Feb 24.   See debugging discussion on SN gitter.

TL;DR  I suspect the problem is a/an (unintended?) change in the Ubuntu version used
in the docker file from 18.mumble to 20.04.2.  This probably changed the output
of `clang-format -V` (by putting Ubuntu as first on the output line, changing the required
-f3 to -f4 in scripts/clangfmt.)

Oops!

**Comment by ekrich** [comment]
https://github.com/scala-native/scala-native/pull/2177

**Comment by LeeTibbert** [comment]
@ekrich Thank you for tracking this down and fixing it.
