### ISSUE TITLE
isFinite(NaN) inconsistent with Java implementation 

### ISSUE THREAD

**Issue by tmccarthy** [scala-native/scala-native#2178]
[`Float.isFinite`](https://github.com/scala-native/scala-native/blob/252d9b746bd4bf18ea374d243a6e3ffdade76c66/javalib/src/main/scala/java/lang/Float.scala#L225) and [`Double.isFinite`](https://github.com/scala-native/scala-native/blob/252d9b746bd4bf18ea374d243a6e3ffdade76c66/javalib/src/main/scala/java/lang/Double.scala#L228) return `true` for `NaN`, which is inconsistent with the Java implementation which returns `false` (see [javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#isFinite-double-)).

This should be a relatively easy fix. I'll try to put together a PR in the next few weeks.

NOTE: original description mixed `true` and `false` up.

**Comment by LeeTibbert** [comment]
@tmccarthy Thank you for report.  Which version of Scala Native are you using/reporting?
I did some work implementing IEEE 754 support for Scala Native, mostly
with converting numbers to/from text.

Please let me understand your report.  I _think_ that you have validly
detected a defect,  but there is a typo (inverted sense) in your description.

On my Scala native 0.4.1-SNAPSHOT system, the code below returns 
"true" (you reported "false") which is indeed inconsistent with the spec
you so kindly provided. 

The code from `java.lang.Double` reveals the defect. As you point out,
`java.lang.Float` almost certainly has the same defect.
```
 @inline def isFinite(d: scala.Double): scala.Boolean =
    !isInfinite(d)  // LeeT 2021-02-24 Issue 2178, need NaN arg to return false here.

  @inline def isInfinite(v: scala.Double): scala.Boolean =
    v == POSITIVE_INFINITY || v == NEGATIVE_INFINITY

```
object Test {

import java.lang.Double._
  def main(args: Array[String]): Unit = {
    val	result = java.lang.Double.isFinite(java.lang.Double.NaN)
    println(s"j.l.Double.isFinite(Double.NaN) is: ${result}, expect false")
  }
}
```

If you have the time to submit a PR, the Scala Native actively appreciates contributions
especially from first time contributors.  If you time is at a premium, I could knock off
a PR (hopefully) tomorrow, listing you as a co-author and asking your review & confirmation
that the problem is fixed.  Please advise.



-----------------------------------------------------------------------------------------------------------------------------
On my Scala JVM 2.13.4 (java 8) system, which I had readily to hand due
to what I was actively working on, I get
```
java.lang.Double.isFinite(Double.NaN)
val res6: Boolean = false

```

I

**Comment by tmccarthy** [comment]
I'm running into the issue on a PR for `typelevel/cats` [here](https://github.com/typelevel/cats/runs/1975454144#step:7:6246), which is using `0.4.0`.

Sorry, yes you're right I got the boolean values mixed up in the report. I've edited the original statement.

I'm very happy for you to fix the issue if it's no trouble. I probably won't have time for a few days even given it's a small fix 👍.

**Comment by LeeTibbert** [comment]
@tmccarthy When you have a chance could you please review PR #2180. Do you concur with the fix?
Does it fix the problem on your system?  Most importantly, is it OK that i listed you as co-author and
did I spell your name correctly ;-)

Thank you for the original report and your review.

PS:  The build failures look scary, at least to me, but I believe that they are CI intermittents 
        entirely unrelated to the content of the PR.

**Comment by tmccarthy** [comment]
Done! Thanks for the quick turnaround!
