### ISSUE TITLE
CI scripts need to use explicit OS versions

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2181]
One or more build scripts (.yml) specify the OS on which to build as `ubuntu-latest`.  Earlier this week,
GitHub changed `ubuntu-latest` from 18.mumble to 20.04.02(?).  Fair enough, but his caused
the SN CI to stop working in mysterious, to me, ways, without warning.

Eric (at_ekrich) kindly fixed one .yml file, by using an explicit 18.mumble.    I propose that 
the other .yml files be changed across the board.  This would give better version control, a
more stable build, reproducibility, and virtue.

I am in the .yml files chasing two other categories of build/testing errors (intermittent docker failures in
Ubuntu build, attempting a macOS build for debugging long standing intermittent failures in test ensemble
 on macOS). If there is some consensus on the explicit version to use, I can submit a PR.

18.mumble would restore the behavior of last week.   An explicit 20.04.02, along with some announcement
to the SN community would keep current behavior.   Yes, an explicit value, rather than `latest` means that the
value needs to be manually changed for, say, 20.04.03. 

Much as I am usually a proponent for using bleeding edge software, I am 50.1/49.9 in favor of using
18.mumble, at least for the next 6-12 months.  

Using 20.04.02 would allow us to raise the minimal clang version above 6. to something more current,
like clang-8.  

Please advise.

Lee  - always in search of virtue, seldom achieving it.

**Comment by ekrich** [comment]
Seems fine to me, currently the ci-docker is the majority of the work in CI and there the OS is pegged.

**Comment by LeeTibbert** [comment]
On the run, so terse.   At least `.github/workflows/
```
$ grep runs-on *.yml
check-cla.yml:    runs-on: ubuntu-latest
check-lint.yml:    runs-on: ubuntu-18.04
run-tests.yml:    runs-on: ubuntu-latest
run-tests.yml:    runs-on: ubuntu-latest
run-tests.yml:    runs-on: ubuntu-latest
run-tests.yml:    runs-on: ubuntu-latest
run-tests.yml:    runs-on: ubuntu-latest
````

**Comment by LeeTibbert** [comment]
```
Ralph Waldo Emerson once wrote: “A foolish consistency is the hobgoblin of little minds, adored by little statesmen and philosophers and divines." 
```
and of engineers... An attempt at self-deprecating humor.

**Comment by LeeTibbert** [comment]
PR #2186 is meant to be minimal & non-controversial. Ha!

The basic idea is that, unless there is some compelling reason,
the operating system version used in GitHub Actions should,
on Linux, match that in the Docker image.  PR #2186 is 
intended to do that without roto-tilling the World.

Prior to Feb 2mumble, 2021, `runs-on: ubuntu-latest` 
referred to Ubuntu 18.04.  All was copacetic, harmonious,
and consistent.

Then, as they adequately document, is there right,
and is to be expected by design with the passage of time,
GitHub changed `ubuntu-latest` to 20.04.  

This broke the clang-format script. Ekrich promptly 
submitted a PR adding an explicit OS version to the
affected .yml.  

PR #2186 makes the other two .yml scripts consistent
with both the modified run-lint.yml and with the
CI practice before the GitHub bump in the middle of the night.

It uses the prior effective but non-explicit  "18.04" to reduce controversy.

The two .yml scripts seem to work just fine with the implicit Ubuntu 20.04.
After a pending PR, run-lint.yml ought to also.

I myself am a big fan of upgrading the entire build to Ubuntu 20.04 but
believe such a move should be an explicit decision, not by lack
of configuration control.
