### ISSUE TITLE
OS X: NumberFormatException parsing doubles 

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#2200]
Sorry for the weird title :)

SN: 0.4.0
OS: OS X 
Scala: 2.13

After doing some fixed number of iterations in parsing doubles from strings, an exception can be thrown on a valid number.

This only happens on OS X.

### Code

```scala
object Test {
  def main(args: Array[String]) = {
    val iters = args(0).toInt
    scala.util.Random.setSeed(500L)
    def lat = scala.util.Random.between(-90.0, 90.0)

    for (i <- 0 to iters) {
      val str = lat.toString

      try {
        str.toDouble
      } catch {
        case e =>
          println(s"Failed after $i iterations")
          throw e
      }
    }
  }
}
```

### Behaviour

On my OS X machine, it sees there's a magic number after which the number parsing can fail:

```
❯ ./target/native-2.13/core-out 100
❯ ./target/native-2.13/core-out 1000
❯ ./target/native-2.13/core-out 10000
❯ ./target/native-2.13/core-out 100000
Failed after 10767 iterations
java.lang.NumberFormatException: For input string "-34.98348554372167"
        <no stack trace available>
❯ ./target/native-2.13/core-out 10766
❯ ./target/native-2.13/core-out 10767
Failed after 10767 iterations
java.lang.NumberFormatException: For input string "-34.98348554372167"
        <no stack trace available>
```

On CI number is different, but same problem: https://github.com/keynmol/scala-native-repro-3/runs/2097599262?check_suite_focus=true#step:6:224

### reproduction

Repo and associated OS X failing build: https://github.com/keynmol/scala-native-repro-3/runs/2097599262?check_suite_focus=true#step:6:224

**Comment by LeeTibbert** [comment]
@keynmol Thank you for the helpful description and, especially, localization to 
macOS.   I am chasing this, on stolen cycles.

My current hypothesis is that strtod() is not parsing as many characters
on macOS as on Linux (where the code in question was developed).

I am in the process of setting up a macOS virtual environment.
Then I can add some private debugging code to the SN IEEE 
parsing code.

Will keep folks posted as/if I make progress.

**Comment by LeeTibbert** [comment]
The reproducer in the base topic is quite useful.  I have begun using derivatives of it on 
macOS trying to reproduce the reported problem.  So far, I have gotten as far as
discovering a bug in the presented code `: Unit` needs to be added to the `main()` declaration,
at least according to the Scala 2.13.4 compiler.

` def main(args: Array[String]): Unit = {`

I mention this to save others who may use the code as a bootstrap at some time in the future
some time.  And to show that I am chasing the Issue ;-)

**Comment by LeeTibbert** [comment]
Update:

I took one shot, to day, of replicating the reported problem using
SN 0.4.0-SNAPSHOT circa March 10 or so, 2021 and running as a GitHub Action
with macos_latest (10.15.mumble).

I do not know if it is good or bad news that I was not able to replicate, see below.
That does not mean that the problem does not exist, under some conditions,
just that it is not trivial to replicate.   

```
String.toDouble() Begin iterations: 100000000.

String.toDouble() End
[success] Total time: 477 s (07:57), completed Mar 14, 2021 11:33:39 PM
```
I am offline for a while, I have done a first pass of contrast & compare of my successful
environment with the failing environment; nothing obvious (beyond, possibly that
I am using a -SNAPSHOT) stands out.  I will try to make another pass to
compare phase-of-the-moon, latitude/longitude, circular vs linear
polarization, and serial-number-of-the-chip  differences,
