### ISSUE TITLE
Improve GC.none and add sbt setting for how much memory to preallocate

### ISSUE THREAD

**Issue by bjornregnell** [scala-native/scala-native#2202]
## Version
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.0")
scalaVersion := "2.13.4"

## Problem
Currently the performance when using GC.none is degraded due to page faults in some cases, see e.g.
https://github.com/lunduniversity/scalades/tree/main/benchmark

## Expectation
1. GC.none should be at least as efficient as GC.commix as long as it can cope using initial memory allocated

2. It would be good if GC.none could preallocate memory according to a setting in build.sbt.

**Comment by ekrich** [comment]
Thanks for the issue.

Currently, this should be controlled via ENV vars but I am not sure it is implemented. See #1826

**Comment by bjornregnell** [comment]
Here is a flamegraph of GC.none where page faults are happening
![image](https://user-images.githubusercontent.com/3601817/111381379-ec78d600-86a5-11eb-95ca-b83d4db541bf.png)
and the same program with GC.commix that does some minor GC work in the beginning and then runs unrestricted:
![image](https://user-images.githubusercontent.com/3601817/111381570-2b0e9080-86a6-11eb-8e3b-4e35826bd2e2.png)
Original SVG Graphs are here (but SVG cannot be uploaded to github):
https://github.com/lunduniversity/scalades/tree/main/benchmark/scala-native

**Comment by WojciechMazur** [comment]
Fixed in #2205
