### ISSUE TITLE
SN 2.13.4 test-tools compiled with release-fast warns of 910 errors

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2210]
Compiling `test-tools` with the `release-fast` option causes the compiler to warn
about 910 errors (in reachability analysis?).

I do not immediately recognize the errors reported and I have not gone searching for
what might be causing them. 

```
[info] Optimizing (release-fast mode) (9838 ms)
[warn] Found 910 errors on @"M50scala.scalanative.testinterface.common.RPCCoreTestD19msgEndpointOrderinguEO" :
[warn]   0000  didopt def @"M50scala.scalanative.testinterface.common.RPCCoreTestD19msgEndpointOrderinguEO" : (@"T50scala.scalanative.testinterface.common.RPCCoreTest") => unit {
[warn]   0001  %20000(%1 : @"T50scala.scalanative.testinterface.common.RPCCoreTest"):
[warn]   0002    %30001 = module @"T14scala.package$"
[warn]   0003    %30002 = fieldload[int] %30001 : !?@"T14scala.package$", 
```
`test-tools` completes successfully with `lto=none`. When `lto=thin`
is specified, `test-tools` completes but three tests fail. I am creating
another Issue for that.

This was discovered on macOS (10.15). I believe that it also happens with 
Ubuntu 18.10, which is why I am reporting it.

It happens when compiling for Scala Native 2.13.4, but neither
2.12 nor 2.11. 

 It does not happen when compiling in `debug` mode.
I did not try `release-full` mode, but I would expect it to happen there.

The SN CI build compiles `test-toos` only in `debug` mode, so this 
defect is not seen there.

**Comment by WojciechMazur** [comment]
Fixed in #2357
