### ISSUE TITLE
Linux  CI 2.13.4 release-fast test-runtime shows warning/errors

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2211]
Whilst creating reports of test failures on my private macOS CI, I discovered
that the mainline CI is reporting a warning about 8026 errors (in reachability 
analysis?).  I do not immediately recognize the errors reported but they
aren't mine ;-)

Issue 2210 reports something similar for `test-tools`. There the issue
does not show up in CI because `test-tools` only ever used `debug` mode.
Here is shows up plainly in the CI log.  I have not checked other
permutations.

Issue 2021 suggested that the warning in question be converted to a 
hard error.  I think the current case adds weight to that suggestion.
IIRC, from a quick exploration of the suggestion, implementing
it is harder than it sounds or one would expect.

```
[info] Optimizing (release-fast mode) (18203 ms)
[warn] Found 8026 errors on @"M34scala.scalanative.nio.fs.UnixPath$D10normalizedL33scala.scalanative.nio.fs.UnixPathL16java.lang.StringEO" :
[warn]   0000  didopt def @"M34scala.scalanative.nio.fs.UnixPath$D10normalizedL33scala.scalanative.nio.fs.UnixPathL16java.lang.StringEO" : (@"T34scala.scalanative.nio.fs.UnixPath$", @"T33scala.scalanative.nio.fs.UnixPath") => @"T16java.lang.String" {
[warn]   0001  %30000(%1 : @"T34scala.scalanative.nio.fs.UnixPath$", %2 : @"T33scala.scalanative.nio.fs.UnixPath"):
```

**Comment by ncordon** [comment]
Do you mind if I take a look at this and the companion #2212?

**Comment by LeeTibbert** [comment]
It would be wonderful if you could!    Yell if you have questions.

Not to prejudice the investigation, but some thoughts, which
may be useful, or may be a waste of time. Sorry if latter.

1)  the `test-tools` and `test-runtime` underlying flaw 
     is probably the same thing 

2) As usual, replicating the report is probably a good
    starting point.  Maybe I was just having a hard day
    that day (or maybe I was just dead wrong).

3) I suspect that the problem has something to do with
    the tools being built on Scala 2.12 and then
    being executed on 2.13.  If I had to bet on
    red or black, I would bet that `build.sbt` violated
    some requirement when I specified release-fast.

4) I did not try `release-full` on any of the cases but suspect the
    same or a similar failure.
