### ISSUE TITLE
Make commix GC more robust

### ISSUE THREAD

**Issue by ncordon** [scala-native/scala-native#2220]
This issue is a follow-up on the PR #2216, which fixed a problem with the lengths of the semaphores but did not make the commix garbage collector checks more robust, to tackle several outstanding problems in commix (see that PR for the detailed discussion):

* Assert on the semaphores names to not be longer than `_POSIX_NAME_MAX` and or `_XOPEN_NAME_MAX`.
* Check on the calls of `sem_open`, `sem_post`, `sem_wait`, etc to return 0, and if they don't, exit the process.
* Investigate how if `errno` is supposed to be thread specific (at least in Linux), and commix is supposed to be executing on another thread, the `errno` was being polluted. To reproduce that, the code in #2200 and the version `0.4.0` of the library in MacOS end up with an `errno` of 9 [here](https://github.com/scala-native/scala-native/blob/15ea60eef45c6263cbb7b736c66eec72c3ab51e6/javalib/src/main/scala/java/lang/IEEE754Helpers.scala#L58) because of a `sem_post` in commix for a semaphore that was not properly open.

**Comment by WojciechMazur** [comment]
To this list, we can also add a more portable implementation of structs using bit fields. As an example `GreyPacketRef` is a packed struct containing 2 fields declared as 3-byte bitfields and short integer, assuming a total size of 8 bytes. This condition holds on Unix, but on Windows size of that struct is 16 bytes, which leads to multiple undefined behaviours.

**Comment by ncordon** [comment]
I'll take a go at this

**Comment by LeeTibbert** [comment]
@ncordon Thank you for taking a run at this.  You might want to trace through the SN code which
handles errno.  IIRC  errno.scala and errno.c(?).  I believe that SN errno is defined as `extern`, meaning
that it gets resolved in the linked C library (almost always, glibc., that is on Linux. but a determined
person can use link options to defeat that, I think.)

It seems that one discussion  before the house is  is that appears, from your well appreciated reports,
that SN is linking to a single address space wide location rather than a thread-local location.  

(I do not meant to offend by repetition of what you probably well know already. It just needs
to be said a  public forum). To avoid triggering license issues one
can look at the gnu documentation to see what they say about errno & threads, 
but __not__ at the implementation/code. 
I must have read that section 20 or more times, but do not remember it well enough. Referring back
to primary sources is always worthwhile.  Someday I hope to read the Odyssey in the original
Classical Greek. 

I hope this helps the discussion, rather than wasting your time.

**Comment by ncordon** [comment]
* For the first point, the [docs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_open.html#) talk about `_POSIX_PATH_MAX` (256 in OSX) or `_XOPEN_PATH_MAX` (1024 in OSX), so those do not fit the 31 limit we were seeing in OSX. The Apple docs for [libc](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/sem_open.2.html) (the standard C library that is linked in a OSX instead of the GNU one) talk about `SEM_NAME_LEN` instead, but I have been unable to locate that variable anywhere. So sadly I do not think much can be done here. The OSX libc just does not seem to entirely comply with POSIX here.  Anyway if opening a semaphore fails because of the length of the name, that's already covered by the assertions added in #2229 
* The second point has been covered in the aforementioned PR.
* To the third point, TL, DR: Everything is correct here as is, it was my misunderstanding. `sem_post` is called from the same process that is executing the program code, because the structure of the commix GC is that master performs some mark and sweep + defragmentation and the worker nodes perform only mark and sweep, but all of them (master and workers) need to be signaled by something. The alternative for that signal is to have another thread which does that (the confusion comes from the fact I expected master to do that, but is my misunderstanding). With that approach we'd lose one process that could be doing mark and sweep instead.

**Comment by ekrich** [comment]
@ncordon I did a little poking around since I have a Mac and found this from `man sem_open`.

> ERRORS
     The named semaphore is opened unless:
     ...
    [ENAMETOOLONG]     name exceeded PSEMNAMLEN characters.

I checked this out via
```c
printf("PSEMNAMLEN: %d\n", PSEMNAMLEN);
```
And the result was as follow:
```
PSEMNAMLEN: 31
```

Hopefully this helps.

**Comment by ncordon** [comment]
That's certainly helpful @ekrich, thanks. Although that varialbe does not seem to exist in the libc I have in Linux. So do we have any alternative for not turning the check into platform dependent?

**Comment by ekrich** [comment]
Well, I should have probably run all the defines.
>[ENAMETOOLONG]
    The length of the name argument exceeds {_POSIX_PATH_MAX} on systems that do not support the XSI option [XSI] [Option Start]  or exceeds {_XOPEN_PATH_MAX} on XSI systems, [Option End]  or has a pathname component that is longer than {_POSIX_NAME_MAX} on systems that do not support the XSI option [XSI] [Option Start]  or longer than {_XOPEN_NAME_MAX} on XSI systems. 

Results:
```c
PSEMNAMLEN: 31
_POSIX_PATH_MAX: 256
_XOPEN_PATH_MAX: 1024
_POSIX_NAME_MAX: 14
_XOPEN_NAME_MAX: 255
```

I still think this means you need platform dependent code but maybe the `_POSIX_NAME_MAX` helps.

**Comment by ekrich** [comment]
@ncordon Maybe you can do a followup PR at some point and use the defines to remove the magic numbers.

**Comment by ncordon** [comment]
Done! 

Sorry for the back and forth @ekrich, it should probably have been all in the same PR, but when I could look at it this morning it was already merged (that was fast!)
