### ISSUE TITLE
GitHub CI does not support clang less than 9 for Ubuntu

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2238]
As of March 29th `clang-format` 6 is not found for Ubuntu 16.04, 18.04, and 20.04.

If we want to continue to support clang 6 as the minimum supported version we must install it in the CI scripts.

https://github.com/actions/virtual-environments/issues/2950

**Comment by ekrich** [comment]
I wonder if we could put something in to cancel runs - I can't believe there is not a button to kill a run.
https://github.com/marketplace/actions/cancel-workflow-action

**Comment by ekrich** [comment]
As long as all the tests that use `clang` are using the Docker containers, they are using `clang` 6. If this is the case then PR will close this issue. https://github.com/scala-native/scala-native/pull/2240

**Comment by WojciechMazur** [comment]
Fixed in #2240
