### ISSUE TITLE
InvokableConstructor#parameterTypes returns Array[Class[_]]

### ISSUE THREAD

**Issue by sideeffffect** [scala-native/scala-native#2242]
Currently, `InvokableConstructor#parameterTypes` has type `Array[Class[_]]`:

https://github.com/scala-native/scala-native/blob/7d35652c3b54686597d33a874daece7ea045d47f/nativelib/src/main/scala/scala/scalanative/reflect/Reflect.scala#L43

But it should be `List[Class[_]]`, so that is the same as the JS and JVM equivalent:

https://github.com/scala-js/scala-js/blob/0639d13421f01293090b35e294c06cf5a92969ca/library/src/main/scala/scala/scalajs/reflect/Reflect.scala#L57

https://github.com/portable-scala/portable-scala-reflect/blob/6303234059142b1d4a0609501f4f4d26b0067767/jvm/src/main/scala/org/portablescala/reflect/InvokableConstructor.scala#L10

**Comment by sjrd** [comment]
I'm afraid that ship has sailed :( Since it was shipped already, we cannot change the type without break backwards compatibility.

**Comment by sideeffffect** [comment]
Would such a breaking change be OK for the 0.5.x series?

**Comment by sjrd** [comment]
Only if the potential breakage is offset by the advantages, and in this case that's probably not the case.

**Comment by ekrich** [comment]
If we don't expect `0.4.x` libraries to work without rebuild on `0.5.x', is it because it is not source compatible or because it is a return type so we can't deprecate?

**Comment by sjrd** [comment]
> because it is a return type so we can't deprecate?

This ;)

**Comment by ekrich** [comment]
I guess the only saving break from a hard break is that reflection, _hopefully_, is a more advanced, less used feature.
