### ISSUE TITLE
Implicit conversion needed for Posix sockaddr_in.sin_addr.s_addr

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2250]
Whilst working on a correction for PR #1921, I needed to set a sin_addr.
To do so, I had to use the `._1` notation, and some SN specific knowledge.
Having an implicit conversion to allow access by name to the `s_addr` field
would make the life of at least one developer (me) trying to use Scala Native
for networking programming happier & more fulfilled.

The fix in `in.scala` should be relatively straightforward.  Note well that
an implicit conversion is needed for the value, not a Ptr[value].

**Comment by LeeTibbert** [comment]
This will be fixed in a PR I will be submitting after PR #2252 is merged.

**Comment by LeeTibbert** [comment]
I believe that I will be able to submit this fix in my Real Soon Now PR to
implement `sendto()`.  Having it there makes code to test that PR
far easier to read.

**Comment by WojciechMazur** [comment]
The implicit conversion was added in #2258
