### ISSUE TITLE
Division by zero in array manipulation

### ISSUE THREAD

**Issue by andreaTP** [scala-native/scala-native#226]
lldb says:
```
* thread #1: tid = 11734, 0x00000000004064db kmeans-out`kmeans.Main$::main_class.ssnr.ObjectArray_unit + 507, name = 'kmeans-out', stop reason = integer divide by zero
    frame #0: 0x00000000004064db kmeans-out`kmeans.Main$::main_class.ssnr.ObjectArray_unit + 507
-> 0x4064db <kmeans.Main$::main_class.ssnr.ObjectArray_unit+507>: idivq  %r9
   0x4064de <kmeans.Main$::main_class.ssnr.ObjectArray_unit+510>: movq   %rax, 0x98(%rsp)
   0x4064e6 <kmeans.Main$::main_class.ssnr.ObjectArray_unit+518>: callq  0x453560                  ; load.scala.scalanative.native.stdio$
   0x4064eb <kmeans.Main$::main_class.ssnr.ObjectArray_unit+523>: movq   %rax, 0x90(%rsp)
```
when running:
https://github.com/andreaTP/kmeans-scala-native/tree/scalalike

**Comment by densh** [comment]
Thanks for the report!

**Comment by fbertra** [comment]
@andreaTP   I think you have a division by zero in Main.scala at line 66 (the `var iterations` is previously decreased until reaching zero):

  `(((!after).tv_usec - (!before).tv_usec) / 1000)) / iterations`

It may be the cause of the `idivq` error.

**Comment by andreaTP** [comment]
@fbertra thanks!!! argh... yep, this was the problem thanks a lot!

anyhow we have something that doesn't work with ```groupBy```

**Comment by densh** [comment]
Division by zero is undefined behaviour in Scala Native at the moment. This seems to be failing as expected. Please resubmit with more actionable bug description if this is still an issue.
