### ISSUE TITLE
docs/user/profiling.rst has a broken link

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2267]
I ran "make linkcheck' whilst  re-basing and touching up PR #1862 to verify than all of my link edits
worked. The edits were mainly to change "http" to "https" (and a "typesafe" to "lightbend" change,
for good measure).  "linkcheck" reported a broken link at line #77 in the recently 
added `docs/user/profiling.rst` 

I hope that Fortune is kind to me and I am able to submit a PR in the next few days.

Importantly, my thanks to the original author, at_bjornregnell, for `profiling.rst`.

**Comment by LeeTibbert** [comment]
##### Design note
The change proposed in PR #2268 is not as visually pleasing as the original code and does
not direct the vision of the person following the link to the exact point of interest.  It
does, however, preserves the essential, intended content and passes "make linkcheck".
"make linkcheck" appears to have a problem with the "#flame-graphs-visualize-profiled-code"
portion of the URL in the original code.

If anybody can come up with a better solution, I am open & would like to learn it.  For now
and for lack of an economic & obvious better way a "not perfect but very good and does not break
 validity checking" will have to do. 

##### Review
@bjornregnell 

If you have time & interest, could you take a coffee break and review the change proposed in PR #2268.
It is always nice to have a second set of eyes and the opinion/blessing of the original author.
I understand if you are not able to look at it.

Thank you, either way.

**Comment by bjornregnell** [comment]
@LeeTibbert Good catch of broken link. I have read and tested and it LGTM. (I'm not sure how to realize the intention of the # syntax to link directly to a heading but here it is not important anyway. So this fix is fine and reads well. )

**Comment by LeeTibbert** [comment]
@bjornregnell Thank you for the timely review and verifying the fix, especially on what must have
been late on a Friday before the weekend.

I checked my sphinxbuild version and it is the latest stable 3.5.4, released two weeks ago.
As mentioned, I suspect a bug or limitation in sphinx "make linkcheck" dealing with the
header portion of an html document. It and/or I may be getting confused between 
markup and html headers.  The URL with the "#" looked good to me.

At least, now it is less likely that some builder will stumble over this in the
frantic few hours before (or just after) a release.  Those never go well.

**Comment by bjornregnell** [comment]
Great! Let's hope building succeeds without pain now :smile:
