### ISSUE TITLE
Bintray brownout, SN build is hard broken.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2271]
Prior to its total demise on May 1, Bintray has a planned brownout today, Monday, April 26, until 21:00 UTC.

The :"build-image" step of the Scala Native build attempts to download sbt 1.3.7 from Bintray,
It has a hard failure, which causes all the subsequent steps to be skipped.

For now, this is a "grin & bear it". I report it in case anyone else in the SN community
encounters it.  I hope to save them time & frustration.

Of course, the general issue is that the SN build will be entirely unusable on/after May 1,
unless there is a fix.

**Comment by sjrd** [comment]
It seems that we are trying to load the debian images directly from the Bintray URLs, instead of through `scala-sbt.org` URLs. I'm not sure where. There is some info about Debian packages for sbt in https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1

**Comment by sjrd** [comment]
This is where: https://github.com/scala-native/scala-native/blob/7682d1690338866377817eeaa54d695f52911a7c/ci-docker/Dockerfile#L32

**Comment by LeeTibbert** [comment]
sjrd.  Would you like me to submit a PR for that or to stay out of the kitchen whilst the
chefs are working? I am fine either way.  A PR on my end will be delayed a few hours,
at best.  Just promising only what I think I can deliver.

I can do a search of the other build files to see if "bintray" shows up somewhere else.
Doing this during the bintray brownout might make it easier to find failures.

**Comment by sjrd** [comment]
I'm out for the evening here. If you want to submit a PR, feel free to do so :)

**Comment by LeeTibbert** [comment]
Thank you for the problem localization, pointer to the proper fix, and timely review.

For general software engineering, I searched other obscure build files for  "Bintray" (case insensitive).
Nothing found and nothing broke in the PR.
