### ISSUE TITLE
Scala Native giter8 template could be updated.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2309]
This is a 'forget-me-not" because i do not have the cycles to do this now.

sbt 1.5.2
scala 2.13.6

The Scala Native .g8 template is now modestly out-of-date and could be upgraded.
As this Issue gets older & older, the benefit of upgrading the .g8 increases.

**Comment by keynmol** [comment]
@WojciechMazur I think this can be closed, thought I'd pick it up but the template is quite up-to-date: https://github.com/scala-native/scala-native.g8/blob/master/src/main/g8/build.sbt#L1
