### ISSUE TITLE
Caching bug in InetAddress.scala

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2310]
Whilst chasing other issues, I noticed that the caching in `InetAddress.scala` is well intended
but questionable:
```
def getHostName(): String = {
    if (host == null) {
      val ipString = createIPStringFromByteArray(ipAddress)
      host = SocketHelpers
        .ipToHost(ipString, isValidIPv6Address(ipString))
	.getOrElse {
          ipString
        }
    }
    host
  }

```

Imagine using this in a long (weeks, months, years) duration server.  The name associated
with the numeric address could change over that period.   A trip to the bind server on each
call is more expensive, but significant work has been done over decades to make the
bind server cashing both correct & (relatively) low cost.  IMO, the proper thing to do
here is to remove the caching (`  if (host == null) {` and closing bracket) and defer caching
to the bind server.

Now is this the most important of bugs?  No.  But a good first issue for someone.

**Comment by LeeTibbert** [comment]
I advise anyone picking up this Issue to read the Java 8 InetAddress specification carefully.
```
 By default, when a security manager is installed, in order to protect against DNS spoofing attacks, the result of positive host name resolutions are cached forever. When a security manager is not installed, the default behavior is to cache entries for a finite (implementation dependent) period of time. The result of unsuccessful host name resolution is cached for a very short period of time (10 seconds) to improve performance.

If the default behavior is not desired, then a Java security property can be set to a different Time-to-live (TTL) value for positive caching. Likewise, a system admin can configure a different negative caching TTL value when needed. 
```
Skipping lightly over the `security manager` discussion (I believe that such is entirely unimplemented 
in Scala Native javalib), I believe the fragment `the default behavior is to cache entries for a finite (implementation dependent) period of time. ` justifies & grounds my concern in the base note.  (probably , for implementation 
espediency,  just timeout == 0)

**Comment by LeeTibbert** [comment]
@TheElectronWill 

I was in this code and saw your InetAddress.host "networkaddress.cache.ttl" and
"networkaddress.cache.negative.ttl". To be honest, I was looking at it with an
eye to cribbing it for a System Properties lookup of "java.net.preferIPv6Addresses".

First, thank you for adding the caching.  Now, under the rubric of "No good deed goes unpunished",
The values chosen, especially for positive TTL seem to be an order of magnitude too small.
For example, a lookup of "ipv6.google.com", which I did for other reasons, gives a TTL of 300.

The negative TTL seems small but I have not evidence from the world there.  If something
failed once, it is likely to continue failing.  Looping every 10 seconds seems like it should be
every 10 minutes or once a day. 

Now, I understand that we both are trying to avoid implementing exponential backoff, or kin.
I also understand that opinions vary about "resonable" expenditure of resources.

The caching of this PR, especially the negative cases, if far better than what went before.

Thank you for any history you are able to reveal about design choices here.

I would like to understand, before cribbing (which is a mark of respect for the author).

Lee

**Comment by TheElectronWill** [comment]
Hello Lee

On my quest to find the "ideal" values, I hesitated, therefore I took a look at existing solutions.

- curl caches DNS results for 60 seconds
- Java [specifies](https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html) the default negative ttl to `10` and the positive ttl to an "implementation dependent" value. According to various [docs](https://www.ibm.com/support/pages/understanding-tuning-and-testing-inetaddress-class-and-cache), this value is 30 seconds (when there's no security manager, and on HotSpot 6+).

I've found these two default values debatable but good enough (for the first version of  the caching at least), given that they have been tested for a long time. That's why they are what they are :)

**Comment by LeeTibbert** [comment]
Thank you for the info.  Looks like you put thought & study into the values.
Now they are documented, so when people like me come along and wonder,
they will not have to pester you.

It is nice design that they can be changed at runtime. You went the extra kilometer/mile.
