### ISSUE TITLE
LTO thin fails on Mac OS X

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#2326]
LTO Thin fails on Mac OS X Big Sur in [current master](https://github.com/scala-native/scala-native/tree/15abb846e1ad7533e0614fe206164f9a6aef8096)

It is trigger either setting:
```scala
nativeMode := "release-fast"
nativeLTO := "thin"
```
or
```
nativeCompileOptions += "-flto=thin"
```

It is not related to the `release-fast` release mode but the LTO settings is set only if you have either `release-fast` or `release-full`. To prove that it fails with thin LTO only I set it manually using `nativeCompileOptions += "-flto=thin"` which led to the same error.

### Tried on:

- Apple Clang 12
- Brew Clang 12
- Brew Clang 11

### To reproduce:

- Set LTO settings on `sandbox` as showed above
- run `sandbox/nativeLink`

### Output:

```
[info] Linking (882 ms)
[info] Checking intermediate code (119 ms)
[info] Dumping intermediate code (linked) (269 ms)
[info] Discovered 669 classes and 4639 methods
[info] Optimizing (debug mode) (1216 ms)
[info] Checking intermediate code (79 ms)
[info] Dumping intermediate code (optimized) (351 ms)
[info] Dumping intermediate code (lowered) (346 ms)
[info] Generating intermediate code (1642 ms)
[info] Produced 8 files
[info] Compiling to native code (2433 ms)
[error] 0  0x10211c008  __assert_rtn + 123
[error] 1  0x1021228e0  ld::tool::SymbolTableAtom<x86_64>::addImport(ld::Atom const*, ld::tool::StringPoolAtom*) (.cold.1) + 0
[error] 2  0x10207eedd  ld::tool::SymbolTableAtom<x86_64>::addGlobal(ld::Atom const*, ld::tool::StringPoolAtom*) + 841
[error] 3  0x10207e7fc  ld::tool::SymbolTableAtom<x86_64>::encode() + 180
[error] 4  0x102064c8e  ld::tool::OutputFile::updateLINKEDITAddresses(ld::Internal&) + 446
[error] 5  0x10205c788  ld::tool::OutputFile::write(ld::Internal&) + 178
[error] 6  0x101fdb5f5  main + 774
[error] A linker snapshot was created at:
[error] 	/tmp/sandbox-out-2021-05-20-181837.ld-snapshot
[error] ld: Assertion failed: (_machoSection != 0), function machoSection, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-609.8/src/ld/ld.hpp, line 1137.
[error] clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
[info] Linking native code (immix gc, none lto) (6226 ms)
[info] Total (13279 ms)
```

**Comment by lolgab** [comment]
My bad, I had some local changes applied to my local master.
The issue doesn't exist on the master branch.

**Comment by keynmol** [comment]
I've seen this now multiple times (only with LTO.thin) locally on M1, and now finally on CI: https://github.com/indoorvivants/sn-demangler/runs/5692216949?check_suite_focus=true#step:7:29

It seems to me it's a legitimate issue.
