### ISSUE TITLE
`java.nio.file.InvalidPathException` missing

### ISSUE THREAD

**Issue by avdv** [scala-native/scala-native#2332]
Hi.

According to the javadoc of [java.nio.Paths.get](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html#get-java.lang.String-java.lang.String...-), it

> Throws:
>   InvalidPathException - if the path string cannot be converted to a Path

But this class is missing from scala-native's javalib.

Also, [java.nio.Path.resolve](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#resolve-java.lang.String-)

I'd be willing to create a PR, if wanted. (hesitating because there are already so many PRs and I don't know if that creates too much churn)

**Comment by ekrich** [comment]
@avdv We are trying to get through the backlog and close things out. If the PRs are small and with tests and not controversial then they should be easy to approve and get merged. Please remember to not look at JDK source if you go forward. This potentially could help me with something I am considering.

**Comment by avdv** [comment]
@ekrich thank you, I'll prepare a PR in the next few days when I have some time.

**Comment by WojciechMazur** [comment]
Fixed in #2358
