### ISSUE TITLE
Can't compile on macOS on jdk 1.8

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#2339]
Environment:
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

Error:
```
[error] ## Exception when compiling 59 sources to /Users/catap/src/scala-native/tools/target/scala-2.11/classes
[error] java.lang.StackOverflowError
[error] scala.tools.nsc.transform.patmat.Solving$Solver$class.findTseitinModelFor(Solving.scala:474)
[error] scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.findTseitinModelFor(PatternMatching.scala:89)
[error] scala.tools.nsc.transform.patmat.Solving$Solver$class.findTseitinModelFor(Solving.scala:484)
[error] scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.findTseitinModelFor(PatternMatching.scala:89)
[error] scala.tools.nsc.transform.patmat.Solving$Solver$class.findTseitinModelFor(Solving.scala:484)
[error] scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.findTseitinModelFor(PatternMatching.scala:89)
...
```

**Comment by ekrich** [comment]
@catap We would need some sort of minimization for this. Without some code to reproduce this, not much can be done.

**Comment by catap** [comment]
@ekrich this is my attempt to build SN itself, I've tried `sbt +publishLocal` and had two issues. This one and https://github.com/scala-native/scala-native/issues/2340

**Comment by ekrich** [comment]
If you want to build Scala Native locally the best way is `sbt` the `clean` then `sandbox/run`. This will build everything except tests and run the sandbox. Then it is recommended that you run the tasks listed here. https://scala-native.readthedocs.io/en/latest/contrib/build.html

That pretty much covers a bunch of the use cases. Details can be seen here: https://github.com/scala-native/scala-native/blob/master/build.sbt#L102-L140
