### ISSUE TITLE
Is scala native garbage collector compatible with C interoperability?

### ISSUE THREAD

**Issue by hurlebouc** [scala-native/scala-native#2346]
I wonder when Zone or stack allocation are necessary when using C interoperability. For instance, if I call C function which takes function pointer, can I use any Scala function (with conversion to CFuncPtr)? Or must I use only Scala function with stack allocated objects or zoned memory?

**Comment by catap** [comment]
@hurlebouc you may discover quite a wired behaviour which cause memory corruption. For example:
 - https://github.com/scala-native/scala-native/issues/2245
 - https://github.com/scala-native/scala-native/issues/2247

To make things easy I implemented in my application a concept similar to https://github.com/scala-native/scala-native/pull/2248

**Comment by armanbilge** [comment]
Great question!

> For instance, if I call C function which takes function pointer, can I use any Scala function (with conversion to CFuncPtr)?

Yes, you can any Scala function that can be represented as a `CFuncPtr` (note that not all Scala functions can; this should be enforced by the compiler). But as mentioned above, it is still possible to get into trouble in various situations: interop is inherently unsafe. It's often helpful to discuss a specific usecase, I encourage you to create a q/a in our discussions forum:
https://github.com/scala-native/scala-native/discussions
