### ISSUE TITLE
malloc Int vs. CSize issue

### ISSUE THREAD

**Issue by Maurycy-Sokolowski** [scala-native/scala-native#2353]
```
val size = 5
buffer = malloc(size).asInstanceOf[Ptr[Byte]]
```
=> malloc: Incorrect checksum for freed object ...: probably modified after being freed.

   ```
    val size = responseBytes.length.toULong.asInstanceOf[CSize]
    println(s"Allocating a buffer for the response (${size} bytes)")
    buffer = malloc(size).asInstanceOf[Ptr[Byte]]
```

=> works BUT still messes up with an incorrect checsum down the line.

I am using 0.4.0

The code I refactored from 0.3.9 was:

```
private def writeResponse(clientHandle: Ptr[TcpHandle], responseBytes: Array[Byte]): Unit = {
    println(s"Allocating a buffer for the response (${responseBytes.length} bytes)")
    val responseBuffer = stdlib.malloc(responseBytes.length)
```

Where we use an  Int but now the signature of malloc seems to be with CSize which is an unsigned long on 0.4.0.

Any advice on why it was changed and why it gives a nice checksum error now? Basically this cripples any attempt at allocating an arbitrary size chunk.

Of course  malloc(sizeof(Buffer)) will work nicely since sizeof gives CSize.

**Comment by ekrich** [comment]
@Maurycy-Sokolowski It is really hard to help if we don't have more code or a repo to refer to. We can't see where `free` is located or how you get the data across the C boundary into Scala. We have seen this message before. https://github.com/scala-native/scala-native/pull/2072

There are `Zone`s and `alloc` too to help manage the C memory. It is better to try and work these issues out via Discord or Gitter first before filing an issue. The links to Chat are now on the README.

**Comment by Maurycy-Sokolowski** [comment]
Here's the code you can look at:

[https://github.com/cb372/scala-native-example-webserver/blob/master/src/main/scala/webserver/Server.scala](url)

Look up writeResponse.

**Comment by ekrich** [comment]
The link is as follows: https://github.com/cb372/scala-native-example-webserver/blob/master/src/main/scala/webserver/Server.scala

**Comment by Maurycy-Sokolowski** [comment]
Got to have everything working. Let me know if you want the source code of the updated server.

**Comment by ekrich** [comment]
@Maurycy-Sokolowski Closing the issue since you got things to work.
