### ISSUE TITLE
Fatal error when trying to link with enabled LTO on Windows

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2372]
When trying to compile SN project with `LTO` enabled it ends up with a fatal error, even though compilation and linking use the same `-flto` setting. 

```
fatal error LNK1136: invalid or corrupt file
```

Tested on Clang 12.0.0
Target triple `x86_64-pc-windows-msvc`

**Comment by WojciechMazur** [comment]
Even compilation of simple hello world program written in C/C++ fails when trying to compile and link with `-flto=thin` setting. It might suggest that currently LTO is not supported in the MSVC compiler.

**Comment by david-bouyssie** [comment]
What about using the LLD linker?
https://lld.llvm.org/
https://lld.llvm.org/windows_support.html
https://stackoverflow.com/questions/68031372/cmake-how-to-compile-c-on-windows-with-clang-and-lld-with-mingw-w64-runtime

It seems to be the path taken in rust:
https://github.com/rust-lang/rust/issues/71520

**Comment by ekrich** [comment]
Note that it seems we would need `clang-cl.exe` plus maybe some other things as noted here. https://clang.llvm.org/docs/ThinLTO.html
