### ISSUE TITLE
Consider invalidating cached executable when sbt is reloaded

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2403]
Changing `NativeConfig` settings requires a `clean` after `reload` to re-compile/re-link.
https://github.com/scala-native/scala-native/pull/2389

**Comment by WojciechMazur** [comment]
I was going to submit a similar issue, I already spoke with @jchyb, he would try to fix this soon.

**Comment by ekrich** [comment]
Ok, cool. It is super nice to have the caching - thanks @jchyb. I wish the mechanism was simple enough to add to SN tools rather than use the sbt tools.
