### ISSUE TITLE
Conversions between unsigned integers and strings

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#242]
Those are not present in Harmony and need to be implemented from scratch. 

- [ ] java.lang.Integer::toUnsignedString
- [ ] java.lang.Long::toUnsignedString
- [ ] java.lang.Integer::parseUnsignedInt
- [ ] java.lang.Long::parseUnsignedLong

**Comment by andreaTP** [comment]
blocked by #190 and related, hope that @fbertra PR solves all the issues here...

**Comment by fbertra** [comment]
@andreaTP  I think you meant your last comment for issue "String interpolator #270".  PR #268 and issue  #190 are unrelated (yet) to this issue.

**Comment by densh** [comment]
#190 has been fixed and this issue doesn't seem to be blocked any longer.

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/346
