### ISSUE TITLE
Java 11, Missing Character.toString(Int) method

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2445]
This method is missing so calling it while using JDK 11 give the following error.
```scala
[error] Found 1 missing definitions while linking
[error] Not found Member(Top(java.lang.Character$),D8toStringiL16java.lang.StringEO)
[error] 	at /Users/eric/workspace/sconfig/sconfig/shared/src/test/scala/org/ekrich/config/impl/TokenizerTest.scala:278
[error] Undefined definitions found in reachability phase
```
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Character.html#toString(int)

Note: this is probably part of a bigger theme of JDK 11/17 support.

This works on Java 8 - the code called is `Character.toString(0)` so it must be interpreting `0` as a `Char`. I think the compiler should be treating `0` as an `Int` but not sure since it works on JVM too.

**Comment by LeeTibbert** [comment]
@ekrich

I was sifting through the Issue backlog and came across this one.

Can this be closed?  Looks like you added ` @inline def toString(codePoint: Int): String ` to Character.scala
two years or so ago.

**Comment by ekrich** [comment]
Completed in #2711
