### ISSUE TITLE
Implement java.util.Random 

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#246]
Can be ported from Harmony.

**Comment by densh** [comment]
Or from scala.js https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/Random.scala

**Comment by sjrd** [comment]
Note that, if taking it from Scala.js, note that [the current version](https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/Random.scala) was hand-optimized to avoid `Long`s at all cost. For SN, you should take [the older version from 0.6.0](https://github.com/scala-js/scala-js/blob/v0.6.0/javalib/src/main/scala/java/util/Random.scala).

**Comment by andreaTP** [comment]
I'm on this one:
https://github.com/andreaTP/scala-native/tree/jurandom

**Comment by soc** [comment]
I'd be careful with `Random`. If I remember correctly the implementation in OpenJDK seems to be a LCG with a very poor randomness and periodicity. http://www.javamex.com/tutorials/random_numbers/lcg_planes.shtml

If usual algorithm quality is assumed, Harmony will be many times worse.
I'd suggest skipping over stuff like this (and also Mersenne Twisters), and have a look at xoroshiro by Marsaglia which seems to be state-of-the-art right now: http://xoroshiro.di.unimi.it/#shootout

**Comment by sjrd** [comment]
@soc The "algorithm" for `java.util.Random` is [completely specified](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#next-int-). There is no room for "improvement" or "lower quality". It just have to be exactly correct.

If you want better quality PRNG, just don't use `java.util.Random`. Use something else.

**Comment by soc** [comment]
@sjrd Oh god. Didn't realize they really did that. Looks like at least `java.security.SecureRandom` is unaffected though.

**Comment by densh** [comment]
Fixed in #250
