### ISSUE TITLE
Implement java.util.Locale 

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#247]

**Comment by densh** [comment]
Blocked by: #58

**Comment by andreaTP** [comment]
as described here:
https://github.com/scala-js/scala-js/issues/1773

**Comment by MasseGuillaume** [comment]
blocking #245

**Comment by densh** [comment]
@MasseGuillaume Are you sure? Scala.js doesn't have support for locales yet but there is reasonable implementation of Formatter in place.

**Comment by MasseGuillaume** [comment]
@densh see constructors: https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html#constructor.summary

**Comment by MasseGuillaume** [comment]
@densh it depends on how far we should go with the implementation. That's why I asked: https://github.com/scala-native/scala-native/issues/245#issuecomment-246159011

**Comment by soc** [comment]
@densh There is an implementation of java.util.Locale and formatting-related stuff for Scala.js already. Probably needs some thought how to integrate scala-native in terms of using the host system's available data sources instead of shipping the locale data as code.

**Comment by ekrich** [comment]
A basic implementation with default en_US is included in this PR - https://github.com/scala-native/scala-native/pull/573

**Comment by densh** [comment]
Fixed in #573
