### ISSUE TITLE
[0.4.3-SNAPSHOT][Scala 3] Found a call to not defined static method that could not be rewritten

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#2484]
### Main.scala

```scala
package example

final class CallByNeed[A] private(private[this] var eval: () => A) {
  lazy val value: A = {
    val value0 = eval()
    eval = null
    value0
  }
}

object CallByNeed {
  def apply[A](a: => A): CallByNeed[A] = new CallByNeed[A](() => a)
  implicit val instance: Functor[CallByNeed] = new Functor[CallByNeed] {
    def map[A, B](fa: CallByNeed[A])(f: A => B) = CallByNeed(f(fa.value))
  }
}

trait Functor[F[_]] {
  def map[A, B](fa: F[A])(f: A => B): F[B]
}

object Main {
  def main(args: Array[String]): Unit = {
    println(CallByNeed.instance.map(CallByNeed(2))(_ + 3))
  }
}
```

### build.sbt

```scala
scalaVersion := "3.1.0"

resolvers += Opts.resolver.sonatypeSnapshots

enablePlugins(ScalaNativePlugin)
```

### project/build.properties

```
sbt.version=1.5.8
```

### project/plugins.sbt

```scala
resolvers += Opts.resolver.sonatypeSnapshots

addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.3-SNAPSHOT")
```

### sbt run

> [error] (Compile / nativeLink) Found a call to not defined static method Member(Top(example.CallByNeed),D44example$CallByNeed$$anon$1$$_$map$$anonfun$1L18example.CallByNeedL15scala.Function1L16java.lang.ObjectEo) that could not be rewritten. Static methods are generated since Scala Native 0.4.3, report this bug in the Scala Native issues.

### note

- https://github.com/scalaz/scalaz/blob/38b2197d2f7177ad3aada0545c60c151fe75c1fe/core/src/main/scala/scalaz/Name.scala#L10-L17
- https://github.com/scalaz/scalaz/blob/38b2197d2f7177ad3aada0545c60c151fe75c1fe/core/src/main/scala/scalaz/Name.scala#L62-L66

**Comment by WojciechMazur** [comment]
Thank you for reporting this issue. We'll try to fix it asap before full release
