### ISSUE TITLE
[0.4.3-SNAPSHOT] Failed to resolve function ref for extern forwarder

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#2486]
Scala 3.1.0:

```scala
opaque type Visitor = CFuncPtr1[Int, Int]
object Visitor:
  def apply(f: Int => Int): Visitor = CFuncPtr1.fromScalaFunction(f)
```

Fails compilation with `Failed to resolve function ref for extern forwarder`

In fact, opaque is not necessary here. It fails the pattern match here: https://github.com/scala-native/scala-native/blob/master/nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala#L2247 and the tree it matches on is `Ident(f)`

**Comment by WojciechMazur** [comment]
Thank you for reporting the issue, unfortunately, it's a know current limitation that is explained in this issue https://github.com/scala-native/scala-native/issues/2359

**Comment by WojciechMazur** [comment]
You can use Scala 3 inlining to workaround this behaviour, fixing it otherwise might be really difficult in Scala Native. 
https://github.com/scala-native/scala-native/issues/2359#issuecomment-1006950209 

Here's an example of that would work in your case: 
```
opaque type Visitor = CFuncPtr1[Int, Int]
object Visitor:
  inline def apply(inline f: Int => Int): Visitor = CFuncPtr1.fromScalaFunction(f)


def useVisitor(x: Visitor): Unit = extern

@main def test(n: Int): Unit = 
  def callback(x: Int) = x*x + 2*n*n
  val visitor: Visitor = (n: Int) => n * 10
  useVisitor(Visitor(callback))
  useVisitor(Visitor(_ * 10))
  useVisitor(visitor)

```
