### ISSUE TITLE
Accessing managed memory from a CFuncPtr throws an NPE

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#2487]
Scala 3.1.0, SN 0.4.3-SNAPSHOT, Apple M1, Java 17 - I pasted the repro into the sandbox and ran `sandbox3/run`

Perhaps I'm just not understanding, but if you do:

```scala
import scala.scalanative.unsafe.*
import scala.scalanative.unsigned.*
import scalanative.libc.*
import scala.language.implicitConversions

@main def test = 
  Zone { implicit z => 
    val mem1 = stackalloc[Int](5)
    val l = List.newBuilder[Ptr[Byte]]

    stdlib.qsort(mem1.asInstanceOf[Ptr[Byte]], 5.toUInt, sizeof[Int], CFuncPtr2.fromScalaFunction {
      (a: Ptr[Byte], b: Ptr[Byte]) =>
        println(s"comparing $a and $b")
        l.addOne(a) // SIC
        !(a.asInstanceOf[Ptr[Int]]) - !(b.asInstanceOf[Ptr[Int]])
    })
  }
```

it will throw an NPE when running:

```
comparing Ptr@16b7d7094 and Ptr@4
[error] java.lang.RuntimeException: Nonzero exit code: 139
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$17(ScalaNativePluginInternal.scala:216)
[error] 	at scala.Option.foreach(Option.scala:407)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$15(ScalaNativePluginInternal.scala:216)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$15$adapted(ScalaNativePluginInternal.scala:193)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```

If you remove the `l.addOne` line, you get a successful run through:

```
comparing Ptr@16b94b0a0 and Ptr@16b94b0a4
comparing Ptr@16b94b0a4 and Ptr@16b94b0a8
comparing Ptr@16b94b0a8 and Ptr@16b94b0ac
comparing Ptr@16b94b0ac and Ptr@16b94b0b0
```

**Comment by WojciechMazur** [comment]
The call fails because `l` is not statically reachable - resolving `this.l` is not possible because `this` is not available in `CFuncPtr`. It can be fixed by moving `l` to some helper object or passing it directly into to CFuncPtr (but this solution is not applicable in provided snipeet)

**Comment by armanbilge** [comment]
I always recommend to define lambdas you wish to use as C function pointers as (effectively static) methods on an `object`. This guarantees you are not closing over state that is not statically reachable.

Example:

https://github.com/http4s/http4s-curl/blob/9354df6461146ff060f5d029c05b714f71ac7bd6/curl/src/main/scala/org/http4s/curl/CurlClient.scala#L417-L436

https://github.com/http4s/http4s-curl/blob/9354df6461146ff060f5d029c05b714f71ac7bd6/curl/src/main/scala/org/http4s/curl/CurlClient.scala#L273-L277

**Comment by keynmol** [comment]
For posterity, in Scala Native 0.4.9 this results in compilation error and a much more helpful message:

```
Compiling project (Scala 3.2.2, Scala Native)
[error] ./test.scala:18:66: Closing over local state of value l in function transformed to CFuncPtr results in undefined behaviour.
[error]         !(a.asInstanceOf[Ptr[Int]]) - !(b.asInstanceOf[Ptr[Int]])
[error]                                                                  ^
Error compiling project (Scala 3.2.2, Scala Native)
Compilation failed
```

That said, I think the location of the error is confusing.
