### ISSUE TITLE
Runtime.exec spawns infinitely busylooping ProcessMonitor background thread

### ISSUE THREAD

**Issue by shado23** [scala-native/scala-native#2501]
```scala
  def main(args: Array[String]): Unit = {
    sys.runtime.exec(Array("/bin/echo"))
    Thread.sleep(60_000)
  }
```

This took me a while to track down, but using Runtime.exec gets you a free busylooping ProcessMonitor thread consuming 100% CPU for the remaining runtime of your program, even when all child processes have exited and none are being waited on. (See process_monitor.cpp)

It looks like this was done to support the timeout variant of waitFor the Java Process API offers. That does indeed appear to be a bit tricky to implement without OS-specific APIs, but this is arguably worse than not implementing the timeout variants at all and just implementing the non-timeout cases using vanilla waitpid / waitpid WNOHANG. Something like this maybe:
```scala
  private def checkResult(pid: Int): CInt = {
    val status: Ptr[CInt] = stackalloc[CInt]()

    val ret = waitpid(pid, status, WNOHANG)

    if (ret != 0)
      !status
    else
      -1
  }

  private def waitForPid(pid: Int): CInt = {
    val status: Ptr[CInt] = stackalloc[CInt]()

    waitpid(pid, status, 0)

    !status
  }
```

I suspect the busylooping solution is fundamentally unsalvagable. According to this stackoverflow post there might be some pipe tricks that could fit the non-busylooping and cross-platform waiting with timeout bill, and various OS-specific solutions, but that's a little outside of my experience:
https://stackoverflow.com/questions/282176/waitpid-equivalent-with-timeout

**Comment by WojciechMazur** [comment]
Thank you for spotting some light on this incorrect behaviour, we should indeed improve our process monitoring logic

**Comment by shado23** [comment]
You're welcome. Keep up the good work.
