### ISSUE TITLE
Resolving iterator of `java.util` immutable collections leads to segmentation fault in Scala 3 

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2504]
Scala 3 seems to be not compliant with Scala 2 behaviour, leading to segmentation faults when trying to resolve iterator of keySet of Immutable java.util collection. It seems that we're dealing with an infinite loop. 
```
    Collections.EMPTY_MAP.keySet().iterator()
    Collections.singletonMap("only", "value").keySet().iterator()
```
Replacing `val` with `lazy val` in `AbstractMap` keySet anonymous iterator seems to be fixing the issue, but we should also check other immutable collections to check if they also contain this runtime bug.

**Comment by ekrich** [comment]
Note that this was ported from Scala.js recently. I think it is unchanged and this only exhibits itself on Scala Native for Scala 3. So basically I think it has to be a compiler, optimizer, or GenCode bug. I know this is not too much help or maybe the opposite.

**Comment by WojciechMazur** [comment]
If I had to guess it probably would be generation of `This` tree in Compiler Plugin, I'll try to check this scenario as well

**Comment by ekrich** [comment]
The Scala.js folks are pretty good so I don't bet against them often 😄

**Comment by sjrd** [comment]
We don't compile the javalib using Scala 3, though. We reuse the artifacts compiled by Scala 2.13. So it could very well be code that is not valid in Scala 3 but valid in Scala 2.
