### ISSUE TITLE
Consider renaming master to main

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2507]
Scala.js has already done this so perhaps after the next release we should too.

Procedure: 

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by WojciechMazur** [comment]
I was thinking about it, but right now it would mean that 40 PR would suddenly become invalid. Of course, there is plenty of outdated PRs, that we can discard, but we probably should try to merge some of more recent ones first

**Comment by ekrich** [comment]
I just changed to `main` for Scala.js and rebased a PR so it wasn't bad at all. But yes less PRs is better.

**Comment by catap** [comment]
Let move to `trunk`!

**Comment by ekrich** [comment]
Almost everyone was using master and now most repos I have seen have switched to main so then you don't have to think about it.

**Comment by WojciechMazur** [comment]
The `master` branch have been renamed to `main`. Contributors should update their local environments and the upstream tracking using commands: 
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
