### ISSUE TITLE
`nativeLink` always relink output

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#2514]
Each time when you call `nativeLink` it triggers `clang` to recompile and relink an output binary.

Even when sources isn't changes.

For example `fastLinkJS` or `fullLinkJS` in scala.js nor original scalac, never re-run its optimizier / compiler when sources file aren't changes.

**Comment by WojciechMazur** [comment]
Are you using sbt or mill for compilation? In the case of sbt, there was introduced a caching mechanism. If it happens in sbt then it's a bug.

**Comment by catap** [comment]
@WojciechMazur I'm using sbt...

**Comment by WojciechMazur** [comment]
It's really strange, I cannot see such behaviour on my machine as it seems to be correctly skipping subsequent linking. 
Can you please provide us with more information about your environment, like, OS, sbt and Scala Native version and JDK distribution?

**Comment by catap** [comment]
@WojciechMazur seems that I'm driving crazy. It doesn't reproduces for each attempt.

The only explanation that I have that IDEA or backup tool or whatever is touching mtime and/or atime on file and it brokes catch.

let me close it now.

**Comment by catap** [comment]
Nope, I can reproduce it easy: https://github.com/kcrypt/scala-sha/runs/4750125615

You may see that at `Compile everything` it calls `sbt +compile +test:compile` to compile binaries which is used for test. Or I thing so. Anyway inside the next stage `Run tests` it calls `sbt +test` which re-link all scala-native binaries.

Have I missed something?

**Comment by WojciechMazur** [comment]
Ok, I can see the problem. When switching Scala versions we probably do override last linking result, so since it's different we try to link it again

**Comment by catap** [comment]
@WojciechMazur interesting that I was wrong: scala.js doesn't try to prepare `.js` on `test:compile`. Or I haven't see.

Let ping @sjrd here.

**Comment by sjrd** [comment]
It is intentional not to link when doing `compile` or `test:compile`, if that's what the last comment was about. If you want to prepare the .js file, use `fastLinkJS` or `test:fastLinkJS` instead.

**Comment by catap** [comment]
@sjrd I not sure that it is correct behaviour.

When I run `test:compile` I expect that everything is ready to run tests. Forcing to run `test:fastLinkJS` or `test:fullLinkJS` seems strange because which link is used for `test` is defined via `Test / scalaJSStage`.

I do not like an idea that I should define which stage should be used in tests in two places:
 - CI scripts;
 - `build.sbt`.

Anyway, I'd like to split compiling everything and testing everything. Why? Because compiling is costly, special when you test it for different Scala versions.

**Comment by sjrd** [comment]
If you want the result that already takes the stage into account, use (`test:`) `scalaJSLinkerResult`.

If you want exactly what will be fed to run/test, use (`test:`) `jsEnvInput`.

You can know these things with `inspect tree run` (or `test`).

**Comment by catap** [comment]
@sjrd I see your point. Anyway, if I use `sbt-crossproject` naive approach with `+scalaJSLinkerResult` or `+test:scalaJSLinkerResult` may leads to an issue when this task is applied to JVM subproject.

An example: https://github.com/catap/scala-blake3/runs/4753637193

From another hand I haven't see any reason to not simplified it and enjoy simple `+test:compile` and allow user to don't.

Have I missed something?

**Comment by sjrd** [comment]
> Have I missed something?

Off the top of my head:

* Your IDE, perhaps through BSP, will not be happy if it has to relink every time it wants the diagnostics from the compiler.
* In your test cycle, you won't be happy to force a relink of the Compile configuration, even though the only one you need is for the Test config.
* In project A that depends on B, you won't be happy to relink A every time even though its .js means nothing.

All of these are pure waste of CPU cycles.

**Comment by catap** [comment]
@sjrd thanks to make things clear.

Anyway, I can't achieve that sbt doesn't call scala.js and scala-native on `+test` even if I call `test:nativeLink` and `test:jsEnvInput`.

The github's CI: https://github.com/catap/scala-blake3/runs/4755426893
