### ISSUE TITLE
Path to linked binary for Test is same as for Compile

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#2517]
To make the output smaller, we can demonstrate this using `crossTarget` which `nativeLink` uses to construct the path:

(forgive the garbage path, it's a temp folder)
```
❯ sbtn 'show Test/crossTarget'
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
> show Test/crossTarget
[info] /private/var/folders/my/drt5584s2w59ncgxgxpq7v040000gn/T/tmp.2J2nD6Ia/scala-native-seed-project/target/scala-2.13
[success] Total time: 0 s, completed Jan 9, 2022 7:36:02 PM

❯ sbtn 'show Compile/crossTarget'
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
> show Compile/crossTarget
[info] /private/var/folders/my/drt5584s2w59ncgxgxpq7v040000gn/T/tmp.2J2nD6Ia/scala-native-seed-project/target/scala-2.13
[success] Total time: 0 s, completed Jan 9, 2022 7:36:07 PM
```

Why is this a problem?

The path to linked file is something one can use on CI, but you must be careful to use/move the binary **before** running any `test` commands, because that will change the binary to be a test runner.

I spotted this on CI exactly because of this, and had to change it to `nativeLink -> upload binary -> run tests`.

**Comment by WojciechMazur** [comment]
Thank you for spotting this issue, I'll try to fix this up
