### ISSUE TITLE
Two tests failing on JDK11

### ISSUE THREAD

**Issue by algobardo** [scala-native/scala-native#2541]
When running the entire test suite with `sbt test-all` on JDK 11 there are two tests failing:
```
[error] Failed tests:
[error] 	javalib.nio.file.UnixPathTest
[error] 	javalib.nio.channels.FileLockTest
```

I looked into the UnixPathTest, and indeed it seems that the test and the implementation of relativize is incorrect.
```
assertTrue(
      Paths
        .get("foo/../bar")
        .relativize(Paths.get("bar"))
        .toString == "../../../bar"
    )
```
should be
```
assertTrue(
      Paths
        .get("foo/../bar")
        .relativize(Paths.get("bar"))
        .toString == ""
    )
```
It seems that the current implementation has the same bug as the jdk before this commit https://github.com/openjdk/jdk/commit/97fca016abdf03b662f787f422b9024edc11829e.

What is the policy that you have? Do you prefer matching the behaviour with JDK8 or fix the bug?

**Comment by WojciechMazur** [comment]
In most cases, it would be better to match behaviour with the newer version of the JDK, so like in this case by fixing the bug. We can skip tests on the JDK8 using `assumeFalse("Why skipped info", org.scalanative.testsuite.utils.Platform.executingInJVMOnJDK8OrLower)`. I'm not sure in which version exactly was the bug fixed, so probably some dedicated version check should be added. 
Currently, CI is running using Java 8, so it would be needed to pass the tests there. 

I've seen that you already started to fix it in published draft PR, thank you!
