### ISSUE TITLE
Can't update scala-collection-compat

### ISSUE THREAD

**Issue by JD557** [scala-native/scala-native#2544]
I'm trying to update scala-collection-compat to Scala Native 0.4.3 / Scala 3.1.1

However, when I run the tests, I get the following error:

`scala.scalanative.util.UnsupportedException: can't cast from Ref(Top(java.lang.Object),false,true) to Nothing`

<details>
<summary>Stack trace</summary>
<pre>
[error] scala.scalanative.util.UnsupportedException: can't cast from Ref(Top(java.lang.Object),false,true) to Nothing
[error] 	at scala.scalanative.util.package$.unsupported(package.scala:18)
[error] 	at scala.scalanative.codegen.Lower$Impl.genAsOp(Lower.scala:750)
[error] 	at scala.scalanative.codegen.Lower$Impl.genOp(Lower.scala:354)
[error] 	at scala.scalanative.codegen.Lower$Impl.genLet(Lower.scala:318)
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$3(Lower.scala:132
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:43)
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$2(Lower.scala:132
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onInsts$2$adapted(Lower.scala:127)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.scalanative.codegen.Lower$Impl.onInsts(Lower.scala:127)
[error] 	at scala.scalanative.nir.Transform.onDefn(Transform.scala:18)
[error] 	at scala.scalanative.nir.Transform.onDefn$(Transform.scala:8)
[error] 	at scala.scalanative.codegen.Lower$Impl.super$onDefn(Lower.scala:84)
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefn$1(Lower.scala:84)
[error] 	at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:43)
[error] 	at scala.scalanative.codegen.Lower$Impl.onDefn(Lower.scala:84)
[error] 	at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefns$1(Lower.scala:72)
[error] 	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:242)
[error] 	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:148)
[error] 	at scala.scalanative.codegen.Lower$Impl.onDefns(Lower.scala:63)
[error] 	at scala.scalanative.codegen.Lower$.apply(Lower.scala:23)
[error] 	at scala.scalanative.codegen.CodeGen$.$anonfun$lower$2(CodeGen.scala:35)
[error] 	at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
[error] 	at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
[error] 	at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.map2combiner(ParHashMap.scala:80)
[error] 	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1064)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error] 	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1061)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error] 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
[error] 	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
[error] 	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
[error] 	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
[error] 	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
[error] 	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
[error] 	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
[error] 	at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
[error] 	at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
[error] 	at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:84)
[error] 	at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:968)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error] 	at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:963)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error] 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
</pre>
</details>

Here's the git diff, to try it out, simply run `sbt compat31Native/test`

```diff
diff --git a/build.sbt b/build.sbt
index 87f1cc6..710d63c 100644
--- a/build.sbt
+++ b/build.sbt
@@ -32,6 +32,7 @@ lazy val root = project
     compat213Native,
     compat30JVM,
     compat30JS,
+    compat31Native,
     scalafixData211,
     scalafixData212,
     scalafixData213,
@@ -53,6 +54,7 @@ lazy val scala211 = "2.11.12"
 lazy val scala212 = "2.12.15"
 lazy val scala213 = "2.13.8"
 lazy val scala30  = "3.0.2"
+lazy val scala31  = "3.1.1"
 
 lazy val compat = new MultiScalaCrossProject(
   "compat",
@@ -81,7 +83,7 @@ lazy val compat = new MultiScalaCrossProject(
             sharedSourceDir / "scala-2.11_2.12"
         }
       },
-      versionPolicyIntention := Compatibility.BinaryCompatible,
+      versionPolicyIntention := Compatibility.None,
       mimaBinaryIssueFilters ++= {
         import com.typesafe.tools.mima.core._
         import com.typesafe.tools.mima.core.ProblemFilters._
@@ -125,6 +127,7 @@ val compat211 = compat(Seq(JSPlatform, JVMPlatform, NativePlatform), scala211)
 val compat212 = compat(Seq(JSPlatform, JVMPlatform, NativePlatform), scala212)
 val compat213 = compat(Seq(JSPlatform, JVMPlatform, NativePlatform), scala213)
 val compat30  = compat(Seq(JSPlatform, JVMPlatform), scala30)
+val compat31  = compat(Seq(JVMPlatform, NativePlatform), scala31)
 
 lazy val compat211JVM    = compat211.jvm
 lazy val compat211JS     = compat211.js
@@ -137,6 +140,7 @@ lazy val compat213JS     = compat213.js
 lazy val compat213Native = compat213.native
 lazy val compat30JVM     = compat30.jvm
 lazy val compat30JS      = compat30.js
+lazy val compat31Native  = compat31.native
 
 lazy val binaryCompatOld = project
   .in(file("binary-compat/old"))
```

**Comment by ekrich** [comment]
I am not sure about your library but I believe you should have something like this for collection compat.
https://github.com/ekrich/sconfig/blob/main/build.sbt#L111-L123

**Comment by WojciechMazur** [comment]
Thank you for the report, we had similar issues in the past but at the time of compilation in scalac plugin, not in the linker. Should be easy to fix.

**Comment by ekrich** [comment]
@JD557 I had this issue in my repo - this wasn't related to you in any way was it? - https://github.com/ekrich/sconfig/issues/235

Just wondering if someone is needing a new release of `sconfig`.

**Comment by JD557** [comment]
Nope, it wasn't related to me.
