### ISSUE TITLE
Libraries built with Scala Native (0.4.3) can't be used via `for3Use2_13`

### ISSUE THREAD

**Issue by sideeffffect** [scala-native/scala-native#2546]
If I build a library for Scala Native 2.13, it has these as dependencies:
```
org.scala-native:windowslib_native0.4_2.13
org.scala-native:nativelib_native0.4_2.13
org.scala-native:javalib_native0.4_2.13
org.scala-native:clib_native0.4_2.13
org.scala-native:posixlib_native0.4_2.13
org.scala-native:auxlib_native0.4_2.13
```
For example [`portable-scala-reflect`](https://search.maven.org/artifact/org.portable-scala/portable-scala-reflect_native0.4_2.13/1.1.1/jar)

If then somebody tries to use my library in a Scala Native _3_ project via `.cross(CrossVersion.for3Use2_13)`, Scala is confused
```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/ondra/Projects/sbt-locales/"), "apiNative"):
[error]    org.scala-native:windowslib_native0.4 _3, _2.13
[error]    org.scala-native:nativelib_native0.4 _3, _2.13
[error]    org.scala-native:javalib_native0.4 _3, _2.13
[error]    org.scala-native:clib_native0.4 _3, _2.13
[error]    org.scala-native:posixlib_native0.4 _3, _2.13
[error]    org.scala-native:auxlib_native0.4 _3, _2.13
[error] stack trace is suppressed; run last apiNative / update for the full output
[error] (apiNative / update) Conflicting cross-version suffixes in: org.scala-native:windowslib_native0.4, org.scala-native:nativelib_native0.4, org.scala-native:javalib_native0.4, org.scala-native:clib_native0.4, org.scala-native:posixlib_native0.4, org.scala-native:auxlib_native0.4
```

Related:
https://github.com/portable-scala/portable-scala-reflect/issues/23#issuecomment-1021617780
https://github.com/cquiroz/sbt-locales/pull/190
https://github.com/scalameta/munit/pull/477

**Comment by ekrich** [comment]
@WojciechMazur Have you thought about this yet? There was discussion on Discord and @sjrd suggests we change the plugin to depend on the 2.13 artifacts like they do in Scala.js. I think I have this correct but we would also have to release again soon.

**Comment by WojciechMazur** [comment]
@ekrich Yeah, probably that's the best what we can do unless we would be able to figure out something better

**Comment by sideeffffect** [comment]
> depend on the 2.13 artifacts like they do in Scala.js

Is that really the case? In Scala.js variant of a library I don't see a dependency on `javalib` or any other library like that. These dependencies are there only for Scala Native variant.

https://search.maven.org/artifact/org.portable-scala/portable-scala-reflect_sjs1_2.13/1.1.1/jar
https://search.maven.org/artifact/org.portable-scala/portable-scala-reflect_native0.4_2.13/1.1.1/jar

**Comment by ekrich** [comment]
So as I understand it the Scala Native plugin would refer to the 2.13 artifacts and we would not publish `nativelib` and its dependencies as Scala 3 versions at all. Scala.js only has two dependencies but since our `javalib` depends on `scalalib` and `auxlib` etc. we have more.

I believe this is the reference: https://github.com/scala-js/scala-js/blob/main/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L775-L778

**Comment by sjrd** [comment]
In Scala.js, the sjsir files of the javalib, auxlib, and scalalib are all embedded in `scalajs-library_2.13`. That's why you don't see them, but they're there. And yes, they are only built for 2.x, and Scala 3 reuses the artifacts of 2.13.
