### ISSUE TITLE
java.util.TimeZone stub is used instead of scala-java-time

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#2547]
https://github.com/zio/zio/pull/6283 is failing because instead to link the java.util.TimeZone from scala-java-time it links the stub from Scala Native.

**Comment by ekrich** [comment]
We must have missed that. It should have been removed right?

**Comment by lolgab** [comment]
I think so 👍

**Comment by WojciechMazur** [comment]
It needs to be removed or we should  try to adjust our linker to handle situations when both stub and real method are both accessible

**Comment by ekrich** [comment]
I think we just need to ditch it. I'm pretty sure it was just an oversight when we removed Locale and java.time and we really don't want to add that sort of complexity to the linker.
