### ISSUE TITLE
Missing `RuntimeException` protected constructor 

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2561]
Our implementation of `java.lang.RuntimeException` does not define constructor 
```
protected RuntimeException​(
     String message,
     Throwable cause,
     boolean enableSuppression,
     boolean writableStackTrace
     )
```
  which is present since Java 1.7. Additionally, we should check other throwables and add missing methods.

**Comment by KikiManjaro** [comment]
Hi @WojciechMazur ! :) I would love to learn more about this project starting with this issue,
Could I have more informations on what's needed to be done ?

**Comment by WojciechMazur** [comment]
Hey, that's great news! Scala Native cannot use JDK that's why we keep our own implementation for a subset of the java standard library, it's defined in `javalib` project. Similarly, Scala.js defines its own javalib implementation, is some cases we can reuse them by porting them to Scala Native. 

In our case RuntimeException is defined in this file https://github.com/scala-native/scala-native/blob/63d07093f6d0a6e9de28cd8f9fb6bc1d6596c6ec/javalib/src/main/scala/java/lang/Throwables.scala#L494-L498 , we keep most of the java.lang exception in this file. 
[Here's a reference](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/RuntimeException.html#%3Cinit%3E(java.lang.String,java.lang.Throwable,boolean,boolean)) to official JDK were the mentioned constructor is described.


What needs to be done is to compare Exception classes defined in our javalib and compare it with official jdk. We should add missing constructors, and add some unit tests using them. Unit tests are defined in `unit-tests` directory, in `shared` subdirectory we keep tests that should be run both on JVM and using Scala Native (to check compliance), that would be a best place to create new tests. `native` subdirectory contains tests that should be run only using Scala Native (due to dependency on Scala Native specific methods)
Since Scala Native currently might not be able to fully support JDK behaviour when it comes to handling Exceptions and stack traces we might ignore new variables right now and not introduce new logic if it would be too difficult to introduce right now. 

If you have any more questions you can ask here or on the [SN discord channel](https://discordapp.com/channels/632150470000902164/635668881951686686)

**Comment by ekrich** [comment]
@KikiManjaro Most of the exceptions are in this file - https://github.com/scala-native/scala-native/blob/main/javalib/src/main/scala/java/lang/Throwables.scala

The job would be to review the exceptions in that file and add missing methods and constructors to match the JVM.

**Note:** You cannot look at Java source code as it has a GPL license.

We use the Javadoc (https://docs.oracle.com/javase/8/docs/api/) and write tests that can run against the JVM and in Scala Native to make sure the results are the same. The tests are in the `unit-tests` project.

You can jump on Discord to join in the conversation there for anything. https://discord.com/invite/scala
