### ISSUE TITLE
Potential updates needed to Java lib

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2586]
As we have ported some of our code from Scala.js, this may be applicable.
https://github.com/scala-js/scala-js/pull/4650

**Comment by LeeTibbert** [comment]
I looked at the referenced Scala.js commit.  Some notes for
memory.

The text after the numeral is the  commit comment from referenced Scala.js commit.
This helps keep track of the menagerie.  

1) "Avoid using scala.concurrent.duration in the javalib." 
  
   I believe this one is not needed. Looks to me like "Timer*.scala" never
   ported.

2) "Avoid` using Scala's Option in Reader, Writer and URI." 

     Scala Native URI was ported from Apache Harmony not
     Scala.js.  So no direct change needed, but a motivated
     person could probably port the entire file from Scala.js
     and pick up the change.

    The changes in that Scala.js commit are applicable to
    Scala Native `Reader` & `Writer`.

3) "Refactor URLDecoder not to use any local lazy val"

    `URLDecoder.scala` was ported from Scala.js and
     contains the lines which the referenced commit
     changed.

     Probably easier to re-port the file (and give
     the new commit hash) than to do a bunch of point edits.

**Comment by LeeTibbert** [comment]
See PR #2694 :   
* `Reader.scala`, `Writer.scala`, and `URLDecoder.scala` were re-ported.

* `URI.scala` was not ported because it uses Scala.js regular expressions 
   and the port would not be trivial.

* `Timer*.scala` changes are not relevant to Scala Native. Those files do not
   exist.
