### ISSUE TITLE
declaring typeclass as an argument to function triggers weird error: `?1 is an unknown value of type scala.runtime.TypeBox[Nothing, Any]`

### ISSUE THREAD

**Issue by fiatjaf** [scala-native/scala-native#2615]
I don't know if this is a bug, probably not, but it's very weird and since the compiler isn't helping me and Metals didn't say anything I figured I would create an issue here and maybe help someone else in the future.

The gist of it is that I've defined these traits (working as typeclasses, right? I don't remember the nomenclature) and implemented them (in multiple case classes):
![2022-05-16-205114_499x322_scrot](https://user-images.githubusercontent.com/1653275/168700623-61a3d9d7-9573-43ff-a7dd-2767cdc1cf8e.png)

Then I've defined this function elsewhere that should be able to take the given trait/typeclass as a parameter:
![2022-05-16-205138_604x328_scrot](https://user-images.githubusercontent.com/1653275/168700634-2645df32-65cf-42cc-bb96-fd7dbc27c6dd.png)

But compilation fails with this weird error: `?1 is an unknown value of type scala.runtime.TypeBox[Nothing, Any]` (and there is also the cryptic `?1.CAP` thing):
![2022-05-16-205215_796x250_scrot](https://user-images.githubusercontent.com/1653275/168700639-cd59f35b-f0f3-49ba-a87e-d947e9e7eb4b.png)

**Comment by ekrich** [comment]
@fiatjaf Thanks for the issue. Please note that you can use markdown instead of images which will help people who may want to cut and paste. Also, complete minimized reproductions are welcome.

**Comment by fiatjaf** [comment]
Sorry @ekrich, I'll make a reproducible copypastable snippet. It's just that I didn't know this was a bug or not. So you think it looks like a bug?

**Comment by fiatjaf** [comment]
After many attempts I've failed to make a reproducible snippet. I'm unsure how to proceed, but I think the most sensible decision is to abandon this issue and adopt a different approach on my codebase.

For future reference, the code I've screenshotted above is at https://github.com/fiatjaf/poncho/blob/3001fa609cf2f7258fa1072920a5261f87d96193/src/main/scala/codecs/HostedChannelMessages.scala#L23-L37 and https://github.com/fiatjaf/poncho/blob/3001fa609cf2f7258fa1072920a5261f87d96193/src/main/scala/CLN.scala#L108-L116.

**Comment by ekrich** [comment]
@fiatjaf A minimal reproducer is desired but not required. Does your code work on the JVM? It may be something that needs fixing so you can reopen if you change your mind.

**Comment by fiatjaf** [comment]
Thanks.

I can't test my full code on the JVM, it's very tailored to Scala Native. I tried to write a reproducible trimmed down version I could test on the JVM but I couldn't get the issue to show up even on Scala Native -- so I imagine it is something specific to my code or some interaction between dependencies or I don't know.

If I encounter it again on the future in a different circumstance that will probably give me more insight on the exact causes so I can come back here with a reproducible example.

**Comment by hmf** [comment]
@fiatjaf 
Here is a simple example that seems to reproduce your issue:

```scala
val sString = "String 1"
val listOfSortOfString: List[Class[_ <: String]] = List(sString.getClass)
val listOfString: List[Class[String]] = List(sString.getClass)
```

The error is:

    Found:    Class[?1.CAP] 
    Required: Class[String]
    where:    ?1 is an unknown value of type scala.runtime.TypeBox[Nothing, String]
​
The first `listOfSortOfString`compiles Ok. The `listOfString` fails. You can experiment here:

https://scastie.scala-lang.org/6ZcYOoriS1u0f0YWj0ezwA

Maybe this will give you a clue.

HTHs
