### ISSUE TITLE
Scala 3: Can't override a `def` member with `()`  with a mere `val`

### ISSUE THREAD

**Issue by sideeffffect** [scala-native/scala-native#2616]
The baffling thing is that
 * I _can_ override `def f(): A` with `override val f: A` on Scala 3 JVM and Scala 3 JS, _but_
 * I _can't_ do that on Scala 3 Native

Case in point:

trait `Runner` with method `def remoteArgs(): Array[String]`
JS: https://github.com/scala-js/scala-js/blob/main/test-interface/src/main/scala/sbt/testing/Runner.scala#L123=
Native: https://github.com/scala-native/scala-native/blob/main/test-interface-sbt-defs/src/main/scala/sbt/testing/Runner.scala#L92=

Override for JS
works with a mere `val`: https://github.com/zio/zio/blob/master/test-sbt/js/src/main/scala/zio/test/sbt/ZTestRunner.scala#L27=

Override for Native
I had to work around it: https://github.com/sideeffffect/zio/blob/patch-3/test-sbt/native/src/main/scala/zio/test/sbt/ZTestRunner.scala#L27=

Otherwise I would get
```scala
[error] -- [E163] Declaration Error: /home/runner/work/zio/zio/test-sbt/native/src/main/scala/zio/test/sbt/ZTestRunner.scala:27:6 
[error] 27 |  val remoteArgs: Array[String],
[error]    |      ^
[error]    |error overriding method remoteArgs in trait Runner of type (): Array[String];
[error]    |  value remoteArgs of type Array[String] has incompatible type
```

Related PR:
https://github.com/zio/zio/pull/6310

Discord discussion:
https://discord.com/channels/632150470000902164/635668881951686686/978015784997634118

**Comment by WojciechMazur** [comment]
It is not a Scala Native related issue, but rather Scala itself. As an example let's try to run the following snippet of code: 
```
//> using scala "3.1.0" //fails with
// //> using scala "2.13.7" // compiles with

trait Foo{
  def remoteArgs(): Array[String]
}
case class Bar(remoteArgs: Array[String]) extends Foo
class Bar2(val remoteArgs: Array[String]) extends Foo
```

In Scala 2.13 it would compile correctly, in Scala 3 it would fail with some exception as you describe before. 
Scala.js re-defines the Runner interface in Scala based on the original Java interface https://github.com/sbt/test-interface/blob/master/src/main/java/sbt/testing/Runner.java 
Scala Native have copied Runner from Scala.js 1:1, it's exactly the same. 

Scala Native test-interface module is cross-compiled for both Scala 2.x and 3, while Scala.js publishes only Scala 2.x artefacts. I believe that if you would swap [test-interface](https://repo1.maven.org/maven2/org/scala-native/test-interface_native0.4_3/) library (probably introduced transitively to your build) with the 2.13 variant it would work in a similar manner as in the Scala.js

**Comment by sideeffffect** [comment]
I see, thanks for the explanation. Too bad that Scala Native behaves slightly differently from Scala JS in this regard, but we can always just work around it one way or another.
