### ISSUE TITLE
Porting java.time.* to Scala

### ISSUE THREAD

**Issue by justf0rfun** [scala-native/scala-native#2617]
Should the java.time API respective package being ported to Scala and included in scala-native's library?

I think that would be useful.

Which aspects have to be payed attention to? Licensing, source compatibility, binary compatibility...?

P.S. Now I see there is already something going on at:
https://github.com/scala-native/scala-native/tree/main/javalib-ext-dummies/src/main/scala/java/time

What is the purpose of the "javalib-ext-dummies" folder?

**Comment by TheElectronWill** [comment]
`java.time` has been ported outside of the scala-native library.
To use it, add [scala-java-time](https://github.com/cquiroz/scala-java-time) to your project.

**Comment by ekrich** [comment]
We don't plan to add this feature so closing. There is also this port from Scala.js. https://github.com/ekrich/sjavatime
