### ISSUE TITLE
GC misses the ability to add roots 

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#2621]
All is better explained in this page about D language: https://dlang.org/library/core/memory/gc.add_root.html

In short, using C-style callbacks with GC-managed objects is currently dangerous, as the object can be collected at any point, corrupting the memory one points to.

This manifests itself in sporadic, hard to debug exceptions.

**Comment by lolgab** [comment]
There is a workaround to this problem, which is to manually maintain the references of the objects in memory so the GC will not get them.
```scala
object GCRoots {
  private val references = new java.util.IdentityHashMap[Object, Unit]
  def addRoot(o: Object): Unit = references.put(o, ())
  def removeRoot(o: Object): Unit = references.remove(o)
}
```

**Comment by coreyoconnor** [comment]
You say workaround but I see an interface proposal and default implementation. ;)

I was expecting `AnyRef` not `Object`. Is `Object` more appropriate when referring to GC-able references?

**Comment by armanbilge** [comment]
This feature was added in:
- https://github.com/scala-native/scala-native/pull/3039
