### ISSUE TITLE
regex/ParserTest should have a minimal body

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2639]
#### Proposal

I propose to keep `regex/ParserTest.scala` but to comment out most or all of the `@Test`
blocks within.  The idea is to radically reduce the execution time.

Developers turn over. Keeping the file, but with a minimal body, allows it to be
found by new developers.

I invite comment.  Yes? No?  Discussion? Suggested alternatives?

##### Background
Currently the `regex/ParserTest` takes about 1 minute to run on the hardware I use 
for development. That is a significant fraction, 25%?, 50%?, of the total time for a
`tests3/test` run. (insert appreciation for the hardware I have.) `.  

I have  not taken the time to figure out how much time it is taking on CI, but the
test is run __a_lot__ on CI, so it must have a significant clock time & carbon impact.
Anything to keep veracity while decreasing the time spent to see if a PR passes CI
is probably a good thing.

All the time & carbon spent would be just the cost of veracity if `ParserTest` actually
provided some value in the general case.  That test is a specialist tool which is
essential for people making changes to re2s regex.  Such changes are almost
never made and it would be easy for a regex devo to enable the test, understanding
that it takes time to run and grateful for the validation.  The test was never meant
to live in full CI for more than a few months.  It has now been years.  Hoist by my own petard.

**Comment by ekrich** [comment]
I think it is fine to `@Ignore` what is necessary in the test (or the whole test) as long in there is a good comment. Perhaps a comment in the parser itself pointing to the the test and explaining that it should be activated on changes to the regex implementation would be good as well.
