### ISSUE TITLE
support llvm 15

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#2647]
When linking in release mode on a machine with llvm 15 I get the following errors:
```
[error] /usr/bin/ld: error: LLVM gold plugin: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0' Reader: 'LLVM 15.0.0')
```

**Comment by WojciechMazur** [comment]
Thank you for the report, however, I've failed to reproduce this behavior. Can you specify a bit more information, especially OS you're using and some minimalization in the case in throws only in the same cases? 

When compiling and running Scala Native unit tests on x86 Linux with clang `15.0.0-++20220609052943+1be3669dda4d-1~exp1~20220609173032.279` it worked correctly with both LTO thin and with disabled LTO. 
Let's also remember that LLVM-15 is still in the pre-release phase, so some spurious bugs might happen while it's being in the development.

**Comment by armanbilge** [comment]
Unfortunately I couldn't minimize but I was able to reproduce. 
```
$ uname -a
Linux typelevel-spire-c3q1erovzxo 5.16.20-051620-generic #202204131933 SMP PREEMPT Wed Apr 13 19:37:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I use gitpod default environment for development, so you can reproduce it yourself:

1. Open https://gitpod.io/#https://github.com/typelevel/spire/tree/reproducer/sn-2647
2. `sdk install sbt`
3. `sbt testsNative/test`

```
sbt:root> testsNative/test
[info] Generating spire/std/tuples.scala
[info] Linking (2503 ms)
[info] Discovered 8128 classes and 48387 methods
[info] Optimizing (release-fast mode) (16201 ms)
[info] Generating intermediate code (4459 ms)
[info] Produced 6 files
[info] Compiling to native code (12030 ms)
[error] /usr/bin/ld: error: LLVM gold plugin: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0' Reader: 'LLVM 15.0.0')
[error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[error] Failed to link /workspace/spire/tests/native/target/scala-3.1.3/spire-tests-test-out
[error] (testsNative / Test / nativeLink) Failed to link /workspace/spire/tests/native/target/scala-3.1.3/spire-tests-test-out
[error] Total time: 38 s, completed Jun 23, 2022, 3:40:04 PM
```

**Comment by armanbilge** [comment]
Here's a further-minimzed reproducer. It only includes the munit test dependency.

https://gitpod.io/#https://github.com/armanbilge/sandbox/tree/reproducer/sn-2647

**Comment by WojciechMazur** [comment]
It's clearly the issue with LLVM, I've built your reproducer locally with latest version of LLVM and it worked. Then I've updated the version of clang in the gitpod to the latest version and it also worked.

**Comment by armanbilge** [comment]
Thanks for looking into it!
