### ISSUE TITLE
Posix netdb.scala does not define numerous EAI_ values

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2661]
This issue is related to Issue #2660.  Whilst writing a test case for the resolution of
that issue, I discovered that Posix netdb.scala does not define EAI error codes.

That file is know to be incomplete. Adding the EAI codes is unlikely to complete
it and there are likely to be numerous "netdb.scala is missing X, Y, Z" issues
coming.  A total sweep to bring netdb.scala into compliance with posix
but even the incremental fix of providing EAI values would be progress.

**Comment by WojciechMazur** [comment]
Fixed in #2662
