### ISSUE TITLE
Scripts: makedocs needs to be executable in Git repository.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2680]
First and foremost, my praise & thanks to the person/people who
created the "Building the documentation" section in the ReadTheDocs pages
and the `scripts/makedocs` script.  It saved me both time & spirit.

It might be me and/or my system, but `scripts/makedocs` seems to be
missing `+x`  executable permission for at least user.  Some of the
other scripts, such as `scripts/scalafmt` have such permission
out-of-the box.   

When I change the permission on my local system, git wants
to change it back. This leads me to think that it needs to 
be changed in the repository.  

Is it as simple as my creating a PR with `scripts/makedocs`
having execute permission?   If yes, and if this is not
a problem local to my system, I can do such a PR.

Thank you for advice and/or direction.

**Comment by WojciechMazur** [comment]
Fixed in #2689
