### ISSUE TITLE
posixlib time.scala needs improvment: clock & timer methods & definitions

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2706]
Recent discussions on Discord brought me to discover that posixlib `time.scala` is missing
a number of commonly used methods & definitions.  The goal would be as complete
as feasible compliance with POSIX `time.h`. Iterative improvement is better than none.
This Issue addresses two groups of methods and punts the completion question to
a day that I will regret later (but not today).

Of course, each group of methods need Tests, if they an be done in economic 
time.

- [ ] `clock_*` methods &  definitions
- [ ]  `timer_*` methods & definitions

This issue will probably take a couple of PR passes.

Linux & FreeBSD have had these methods for a decade or more.
Guards will be put into  `time.c` to detect attempts to compile
on macOS < 10.12, where those methods are missing. Those versions
have been unsupported by Apple for years.

The advantage of this PR is that users will have access to `clock_gettime()`
for CLOCK_MONOTONIC and CLOCK_RUNTIME and two less frequently
used CLOCKs.  Users will still have to 'roll their own' for clib extensions
 CLOCK_REALTIME_COARSE and others.

If posixlib CLOCKs are provided, users will have a working model of the
definition & use of CLOCKs in Scala Native for their private clib extension needs.
Such extensions tend to be operating system specific and are an explicit
non-goal of this Issue.

**Comment by ekrich** [comment]
We also could consider jumping from C99 to C11 to get https://en.cppreference.com/w/c/chrono/timespec_get

**Comment by LeeTibbert** [comment]
I thought we were already using C11, with C extensions, specifically "-std=gnu11".
I thought this was across the board, in all projects, all scala versions.

I just recently learned how to turn "-v" verbose reporting for Clang in the
`NativeConfig` environment.  I am at the end of a sprint now, but I will
turn it on in a scratch project to see what I get.

re: timespec_get  
From a quick read of the URL provided and current reading of the POSIX 2017 spec,
I believe that `timespec_get` is a candidate for a clib `time.h` and implementation
and not POSIX.   To get the `clock_*` stuff in, I think it should go into posixlib, soon,
rather than waiting.

Yes, you bring up the perennially punted issue of how do posixlib & clib relate
and how do we avoid doing duplicate implementations in the cases where
the behaviors are the same.  Can we come up with a consistent model
for users?  Can we come up with a consistent model for SN devos?
I punt that once again, and know that it __will__ come back to not
only haunt but punish.

**Comment by LeeTibbert** [comment]
`LLVM.scala`
```
val stdflag = {
          if (isLl) Seq()
          else if (isCpp) {
            // C++14 or newer standard is needed to compile code using Windows API                                                                             
            // shipped with Windows 10 / Server 2016+ (we do not plan supporting older versions)                                                               
            if (config.targetsWindows) Seq("-std=c++14")
            else Seq("-std=c++11")
          } else Seq("-std=gnu11")
        }
```
I find the code hard to trace, but it looks to me like the C path yields "-std=gnu11"

Indeed, buried deep in the "-v" output for `complex.c' (an arbitrary C file from the log file)
is `-std=gnu11`.

**Comment by ekrich** [comment]
Didn't realize we had switched that in the middle of the night - better to put it in the C lib then as all platforms can use it.
