### ISSUE TITLE
Package private at the top level of build breaks easy import

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2730]
In the documents, we advertise the following:
```scala
import scala.scalanative.build._

nativeConfig ~= {
  _.withLTO(LTO.thin)
    .withMode(Mode.releaseFast)
    .withGC(GC.commix)
}
```

Now we get the following due to changes:
```
[error] /Users/eric/workspace/scala-native/project/Build.scala:547:13: object IO in package build cannot be accessed in package scala.scalanative.build
[error]             IO.createDirectory(trgDir)
```

One import is highly useful so perhaps we should move these to an `internal` package.

**Comment by ekrich** [comment]
The code above was put into `sandbox` so it should have been easy to test - I was actually thinking about adding the above with the defaults settings instead so that is is easy to just tweak settings when needed to test things.

**Comment by ekrich** [comment]
Refer to this line in the build - https://github.com/scala-native/scala-native/blob/main/project/Build.scala#L541

**Comment by ekrich** [comment]
If I remove the import from the build then the error goes away. The package is `build` for `Build.scala` so things work without the import before the change but not after adding the import so I think we need to look at this because we can't do this simple thing before the change as the package is working in one case but conflicting in the other. I would like to add the to the build just to make it easy for developers.

```Scala
import scala.scalanative.build._

  lazy val sandbox =
    MultiScalaProject("sandbox", file("sandbox"))
      .enablePlugins(MyScalaNativePlugin)
      .settings(nativeConfig ~= {
        _.withLTO(LTO.default)
          .withMode(Mode.default)
          .withGC(GC.default)
      })
      .withNativeCompilerPlugin
      ...
```

**Comment by ekrich** [comment]
@WojciechMazur Since I have found the actual problem - any idea how we should handle this?
I am not sure what package the `Build.scala` file should be in but just just `package build` seems kind of dangerous.

**Comment by ekrich** [comment]
@WojciechMazur Reopening this because the `IO.createDirectory(trgDir)` was viewing the `package build` in the `Build.scala` as `scala.scalanative.build` which was causing the conflict with the proper import needed for the `sandbox` options. I don't think we want  even our sbt build to use internals of the tools or build packages. The `IO` utility can be public perhaps but we need to have a unique non-conflicting package for our build - maybe `scalanative.sbt`? Any suggestion recommended - we can create another PR and maybe revert some portions of the previous PR if needed.

**Comment by WojciechMazur** [comment]
So for a quick summary `sbt.IO` was being shadowed by `scala.scalanative.build.IO`. In most of cases I would say not to change anything, but allow users to use aliases for imports. However, since the `sbt.IO` is quite commonly used in build definitions. I think we are left with 3 possibilities here:
1. Don't change anything, assume it's not that common
2. Move`scala.scalanative.build.IO` to some other package (already done with `build.core`)
3. Move `scala.scalanative.build.*` interfaces to separate package, similarly to `org.scalajs.linker.interface` in Scala.js 

`scalanative.sbt` might not be a good package name, since you can imagine to have:
```
import scala.scalanative._ 
import sbt._ // Wanted to import all SBT stuff, but imported scala.scalanative.sbt._ instead
```

**Comment by ekrich** [comment]
Based on your comment then I think what we have done by moving our private `IO` which I think is basically a copy of `sbt.IO` into core is a good thing - this way it can never be mistaken for the `sbt` one. I think we can specifically prefix it in the build just to be explicit and not make other changes other than adding the settings in the sandbox so people don't have to reinvent that every time they want to test settings.
