### ISSUE TITLE
Need better way to detect 32-bit platforms

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2731]
Currently we get the following warning on macOS M1 (arm64).
```
Unexpected architecture in target triple: arm64, defaulting to 64-bit
```

**Comment by LeeTibbert** [comment]
Eric,

Whilst waiting for CI, I am trying to close out stale/fixed Issues
I have still lying around.  Although this is not my Issue, I noticed
it.

Is this issue still active or has it been resolved?

I have not seen that warning on macOS M1 for a long time. Have
I become acclimated?
