### ISSUE TITLE
Scalalib needs a new strategy for publishing artifacts

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2740]
During added support for Scala 3.2.x I've found a fatal problem related to publishing artifacts. Up until now, we could have always published for a single Scala binary version (Scala 2) or Tasty version (Scala 3). However, as we approach a new minor release of Scala 3, we get into a problem with how to publish new artifacts for scalalib. 
If we would stick to the usage of the latest Scala version to publish scalalib we would force users to update to the latest version of Scala, in that case, 3.2.x. 
If the scalalib would be based on 3.1.1 some of the new runtime methods might be missing or bug fixes would not be applied in our NIR distribution. 

A partial solution would involve the compilation of the Scala standard library for 3.2.x using the 3.1.x compiler, however, this solution has some risks since forward source compatibility is not guaranteed. This however could be addressed by usage of our current patches mechanism. 

The ultimate solution would involve moving the generation of scalalib to the Scala compiler, similarly, as it is done for Scala.js, however, that might not be a good idea when both NIR format and its generation (inside compiler plugin) is not yet stable.

Until we would finish the stabilization period we might need to introduce CrossVersion.Full for scalalib starting from the 0.5.0 release, while 0.4.x branch would only support Scala 3.1.x and only partially newer version.

**Comment by WojciechMazur** [comment]
Since Scala 3.3.1 we're no longer are able to compile Scala 3 stdlib using Scala 3.1.x (change in compiler internals leading to compilation failures of Qutoes.scala`). This means that if we still want Scala Native users to be able to use any version of comiler since 3.1.x we need to implement new publishing strategy. Otherwise, we would be forced to upgrade minimal supported Scala 3 version to 3.3.x

**Comment by SethTisue** [comment]
> upgrade minimal supported Scala 3 version to 3.3.x

dooooooo iiiiiiit

**Comment by armanbilge** [comment]
All major Typelevel projects are on 3.3.x now, I think we should be okay.
