### ISSUE TITLE
Write-opening a read-only file doesn't throw an exception

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#2750]
I added a test for this in https://github.com/scala-native/scala-native/commit/0847cfa75241272bd3d6917ee44340bbce6ebd9d. It passes on JVM and fails on Native.

**Comment by LeeTibbert** [comment]
Now ?who? would ever do such a thing? ;-)  

Thank you for the report.  Would you like me to isolate & PR
so that you can focus on your project?

**Comment by armanbilge** [comment]
@LeeTibbert would also appreciate your help here!! I made an attempt to fix it in https://github.com/scala-native/scala-native/commit/35bb301566f104a6bacf75c07ff9a3c7050cbbc4 but only discovered more problems I'm afraid :)

**Comment by LeeTibbert** [comment]
I am scouting around on this issue whilst CI batters the DirectoryNotEmpty PR.  I am trying to scope out
the issue.  Sorry if I am behind the curve on understanding.

Does the reported write-opening a read-only file happen using java methods.  In the commit you pointed
out you were editing `FileChannelImpl`. I did not quite follow what you were trying to do or how
it relates to the issue.    

Do you have and can you post a snippet of the call which is failing for you?    That would help.
I am at the end of a sprint now. When I return, I will poke around FilesTest to see if there
is a case there which tests this condition.  FilesTest is just my first guess, probably because
I have just spent the evening there.

**Comment by LeeTibbert** [comment]
Progress!

I believe that I have found the underlying defect on the Unix path.  I am paying off
karmic debt for the times I have not done status result checking.

The Windows path will have to be done in consultation with somebody who
knows Windows. (mumble, getLastError mumble mumble). On a glance
it look to me to have the same defect, only in its realm.

For now, I want to get the Unix path fixed & shipping.  

FileChannel.scala calls into RandomAccessFile, which has a private
method ` private def fileDescriptor(file: File, _flags: String) `
to open the file.  On unix, that method has a chunk of code:
```
      val fd = open(toCString(file.getPath()), flags, mode)
      new FileDescriptor(FileDescriptor.FileHandle(fd), readOnly = false)
```
When I put debugging printfs to test the value of fd, sure enough it is -1 (failure)
and errno.errno is 13 (EACCES, "Permission denied").  Oops!

Now fixing the defect is not as simple as it looks.  RandomAccessFile is
in `java.io` and the obvious code for the fix (PosixExceptions.scala) is
in `java.nio`.  I believe the (undocumented) convention is that the latter
can call into the former, but not visa versa. Hosed!

The Java 8 documentation describes RandomAccessFile as possibly
throwing SecurityException but not the required AccessDeniedException.
Fun in the sun!  So putting the obvious Exception in the obvious place
is ruled out.

An additional design constraint is that any fix is intended for the 
0.4.x branch.  Things can be added but not deleted or moved around.

My current thought, at the end of a long sprint, is to optimize
for the success path. Have RandomAccessFile raise its SecurityException
and have FileChannel catch it and re-throw AccessDenied.
The success path should be a only few instructions longer for a try/catch
block.  Any information in errno gets lost, sigh.

I am hoping that a better solution occurs to me overnight, or that 
someone in the community can suggest one.

I think I am going to create a secret identity for submitting these
"best of a bad lot" solutions.

**Comment by LeeTibbert** [comment]
@armanbilge   

I have sketched out a PR to fix this issue. I like to create the tests before
I do the edits for the fix.   

Both University & commercial work have trained me to be
respectful of Intellectual Property rights.

May I use the body of your original FileChannelTest
you kindly posted in commit 0847cfa above?   I would submit the PR
with ourselves as joint authors.    I have not written the test
for the RandomAccessFile but I think I would use either the
logic or something close to it in that test.

If you are not comfortable with that, and I understand, an
alternative would be for me to submit this PR, again jointly,
and for you to submit the ChannelFileTest in a follow on PR.

Your thoughts?  Please advise.  Thank you.

**Comment by armanbilge** [comment]
@LeeTibbert very kind of you to ask. Please use the contents of my commits as you see fit, I appreciate your work!

**Comment by armanbilge** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/2756.
