### ISSUE TITLE
Many deprecated methods should be removed in 0.5.0

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2765]
There are probably a large (?) number of places where methods have been deprecated in 0.4.x.

2022-11-19 The alloc/stackalloc deprecations are removed in PR #3003 

The 0.5.0 release offers the opportunity to remove those methods.  This reduces the amount
of dead code in SN and its attendant costs.

In particular, whilst trying to track down solutions to my favorite 0.5.0 annoyances, I came
across code in the aforementioned `UnsafePackageCompat.scala` (beware there are two
of them, both probably need the same fix).
```
 /** Heap allocate and zero-initialize n values using current implicit         
   *  allocator. This method takes argument of type `CSSize` for easier interop\
,                                                                               
   *  but it' always converted into `CSize`                                     
   */
  @deprecated(
    "alloc with signed type is deprecated, convert size to unsigned value",
    since = "0.4.0"
  )
  inline def alloc[T](inline n: CSSize)(using Tag[T], Zone): Ptr[T] =
    alloc[T](n.toUInt)
```
  
and
```
/** Stack allocate n values of given type.                                    
   *                                                                            
   *  Note: unlike alloc, the memory is not zero-initialized. This method takes 
   *  argument of type `CSSize` for easier interop, but it's always converted   
   *  into `CSize`                                                              
   */
  @deprecated(
    "alloc with signed type is deprecated, convert size to unsigned value",
    since = "0.4.0"
  )
```
Note well that the comment about memory not being cleared is patently wrong
and has been for a while.  

If given the go ahead, I can make a PR for this case in two files.

Please advise.

What is really needed is a sweep through all the code looking for `@deprecated`, hopefully
with a SN version when it was deprecated.  I can understand that code deprecated in 0.4.4, 0.4.5, 0.4.next, 
might not be a candidate for removal. Certainly it is worth cleaning out items deprecated in earlier versions.
Yes, Java still has entry points deprecated in Java 1.1 & 1.2 and wears them as a badge of honor.

**Comment by ekrich** [comment]
Since we are essentially using Early Semantic versioning, we should be able to remove or change behaviors between 0.4.x and 0.5.0. I think these can be removed for 0.5.0 since everyone will need to rebuild. Looking for other deprecation is a good idea too.

**Comment by LeeTibbert** [comment]
Looking for low hanging fruit whilst I have some intensive tests running.

Not comprehensive, just reporting as I am finding.

`nativelib/src/main/scala/scala/scalanative/runtime/Platform.scala` has
some '0.4.1'

nativelib has some GC deprecations. A brave soul could examine those.
I am afraid of the Curse of the Mummy.

Javalib has a few deprecations, but then Java likes deprecations.

Posixlib appears to have one "0.4.5" deprecation, according
to the letter it could be removed. Seems better to let it
be until 0.6.0.  Other views solicited.

**Comment by LeeTibbert** [comment]
```
tools/src/main/scala/scala/scalanative/build/Config.scala:  @deprecated("Not nee
ded: discovery is internal", "0.4.0")
tools/src/main/scala/scala/scalanative/build/Config.scala:  @deprecated("Not nee
ded: discovery is internal", "0.4.0")

```

**Comment by LeeTibbert** [comment]
```
sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePlugin.sc
ala:  @deprecated("use autoImport instead", "0.3.7")

```

**Comment by ekrich** [comment]
I think the most important thing if we remove deprecated code is that we somehow make sure we capture them with workarounds for the release notes. Maybe we should add release notes or add to them as we go.

**Comment by LeeTibbert** [comment]
I did a quick run through a number of other directories, skipping scalalib. Not pristine but
pleasantly & surprisingly clean.

**Comment by LeeTibbert** [comment]
> I think the most important thing if we remove deprecated code is that we somehow make sure we capture them with workarounds for the release notes. Maybe we should add release notes or add to them as we go.

Yes, a section describing removed routines would be essential.  The deprecation messages themselves
usually offer workarounds, that could be copied over to the docs.   

I, for one, do not want to be creating new workarounds for things which have been deprecated for many versions.
(Could you forecast that I was going to say something like that?)
I almost never want to disappoint customers, but there is always the corner case, held well in reserve.

Much as I would like to pick these of one by one, since this sieving appears to have come up
with only a few, I am thinking one PR, sometime when CI is particularly slow.

**Comment by ekrich** [comment]
You can copy `0.4.0.md` since that was the last breaking version to `0.5.0.md` and start filling that out with details of the removals. That would give us a head start.

**Comment by LeeTibbert** [comment]
Another one for the hit parade:
`ScalaNativePlugin.scala`

```
  @deprecated("use autoImport instead", "0.3.7")
  val AutoImport = autoImport
```

**Comment by LeeTibbert** [comment]
Trying to keep accurate score. 

PR #2988 removed two deprecated declarations in libc.signal.  PR #2991 updates the changelog.
I also added the "Suggested replacement" from this discussion.  Kinder than just "you're hosed!".

**Comment by LeeTibbert** [comment]
I am still pecking away at removing deprecated items.   I think I have 5+ files to go.

Someday this Issue can Rest In Peace.
