### ISSUE TITLE
Fun with signals

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2770]
clib signal.scala declares SIGTERM but not SIGKILL

posixlib signal.scala declares SIGKILL but not SIGTERM
both are required for POSIX conformance.

Gotta love it!

I recommend that both signal.scala files be examined
closely for completeness.  Yes, at some point
there should not be two lists of "constants"
but that is not my biggest problem today.

I think I am going to the coral reefs of South West Florida
to get back in touch with the joys of growth by 
slow accretion.

**Comment by ekrich** [comment]
Interesting I deprecated the following in `clib` but it is also in `posixlib` probably linking with the C file included in the `clib`.
```scala
@name("scalanative_sigusr1")
  def SIGUSR1: CInt = extern
```

**Comment by LeeTibbert** [comment]
`SIGUSR1` is in POSIX 2018, I just looked.  Any idea why you deprecated?   
Using the same underlying C file seems like a good idea, indeed, the only
way to go.

From the debugging I have been able to do, looks like we are dealing
with good, straightforward SIGTERM (that is the one I am provoking,
if I can figure that out, I will go on to SIGKILL).

**Comment by LeeTibbert** [comment]
Progress report:  The good news is that there are two places in `UnixProcess` where the
results of a call to `kill(pid, SIGx)` are not checked, at least the SIGTERM call is succeeding.
I do not want to get distracted from the presenting problem so I can not fix those now,
but will put those defects in my heap and hope to fix them later.

Trying do keep others posted by what I am finding.

Now it is donning a rescue harness and tying two lifelines
to it before I plunge into libunwind (and macOS's local
version). Send more coffee.

**Comment by TheElectronWill** [comment]
Here you are!
> ~~java cup~~

oops, I mean:

> regular coffee :coffee: :)

**Comment by LeeTibbert** [comment]
I believe this was fixed by @ekrich soon after the "extern trait" PR merged.
Thank you, Eric.
