### ISSUE TITLE
Drop Scala 2.11

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2780]
Since the ecosystem will have to rebuild this is a great time to drop 2.11. This will also help those projects with current 2.11 support since we are not getting new Scala 2.11 releases or security patches anyway. Our CI load burden will go down as well. It is quite large given all the combinations.

**Comment by armanbilge** [comment]
Speaking for the Typelevel ecosystem, Native+2.11 will not be missed. We currently have no projects with this cross-build.

Speaking as a contributor to Scala Native, I would appreciate this change.

Note that many projects are adopting Scala Native for the first time ever, only on Scala 3. E.g. see https://github.com/disneystreaming/smithy4s/pull/289
> Adds Scala Native support (for Scala 3 only, to avoid the matrix increasing in size too much for something that is quite bleeding edge).

**Comment by sideeffffect** [comment]
We still use 2.11 in ZIO. Would be nice to keep it. :pray:

**Comment by ekrich** [comment]
> I can't speak for Ziverge or the official ZIO team, but I know we still use 2.11 in ZIO. Would be nice to keep it. 🙏

Thanks for speaking up. Are there some reasons why your still want it?

**Comment by sideeffffect** [comment]
Note that I myself am not a 2.11 user.

Scala binary incompatibility between 2.x versions is an unfortunate thing which causes a lot of friction. Supporting as many of them and dropping support only as late as possible and only as the last resort eases the otherwise unfortunate user (developer) experience. I'm sure, somewhere in the world, there are people stuck with 2.11, most likely for stupid reasons, but still stuck. So far, they should be able to be served well (among others) by the ZIO (& family) libraries.

Supporting wider array of Scala versions could be a comparative competitive advantage of certain libraries over others.

Also please note that dropping 2.11 could make the lives of library maintainers more difficult. AFAIK _"JVM"_ and _JS_ still support 2.11, so _Native_ would be an exception here, and exceptions tend to be painful for library maintainers.

**Comment by ekrich** [comment]
> Supporting wider array of Scala versions could be a comparative competitive advantage of certain libraries over others.

Certainly Typelevel does not want to support 2.11, nor do I. My major focus is that it would be better for Scala Native but only if downstream wants to drop as well.

**Comment by armanbilge** [comment]
> Certainly Typelevel does not want to support 2.11, nor do I.

Nor does the Scala 2 compiler team ... 2.11 is EOL.

@sideeffffect I appreciate your pain. Besides zio/zio, which zio libraries still build for 2.11 and Native (or have potential to cross-build for Native?). Are you planning to build async I/O libraries for 2.11+native?

**Comment by sideeffffect** [comment]
just looking for `_native0.4_2.11` at https://repo1.maven.org/maven2/dev/zio/ yields
zio-cache, zio-prelude, zio-config, zio-optics

And adding 2.11 support to more libs shouldn't be exceptionally difficult... I personally added it for ZIO Prelude.

**Comment by ekrich** [comment]
Since the latest version of 2.12 supports features making it easier to unify 2.12 code with Scala 3 code this make the case stronger - https://github.com/scala/scala/releases/tag/v2.12.17

**Comment by armanbilge** [comment]
@damianreeves I undestand you are working on Scala Native support for the projects that @sideeffffect mentioned. What are your thoughts on this issue?

**Comment by ahjohannessen** [comment]
2.11, 2.12, 2.13 and 3. Personally, I think keeping three supported Scala versions is more than generous. Who is on Scala 2.11 and needs Scala Native 0.5.0? 1% of the users?

**Comment by strelec** [comment]
> I'm sure, somewhere in the world, there are people stuck with 2.11, most likely for stupid reasons, but still stuck. So far, they should be able to be served well (among others) by the ZIO (& family) libraries.

A team that is stuck on 2.11 will not just go and adopt ZIO. You are over-optimizing for one in a million usecase.

**Comment by ahjohannessen** [comment]
@strelec Right on

**Comment by ekrich** [comment]
Good news. It is happening. https://github.com/scala-js/scala-js/pull/4761

**Comment by JD557** [comment]
Looks like the scala-js PR was merged 2 days ago 🚀

**Comment by DamianReeves** [comment]
Just realized I was tagged on this, but I believe I answered @sideeffffect in another forum. Glad to see 2.11 go and I'd actually embrace EOL for 2.12 too 😉 (too soon???).

**Comment by sideeffffect** [comment]
> 2.12

The whole sbt world depends on it :sweat_smile: 

Anyway, so very grateful that 2.11 was sunset by Scala Native and Scala.js in coordination :bow:

**Comment by plokhotnyuk** [comment]
If you are starting voting to drop something next then I vote to drop JDK 8 support or at least to have _full_ JDK 11 support.

Do we have such kind of umbrella issue?
