### ISSUE TITLE
The state of `java.net.Socket`

### ISSUE THREAD

**Issue by fiatjaf** [scala-native/scala-native#2787]
I'm creating this issue after a message from @LeeTibbert at https://discord.com/channels/632150470000902164/635668881951686686/1008354765492736031.

I saw in a PR from 2017 that there seems to be some support for `java.net.Socket`, but I don't know how much or what part.

I am interested specifically in these methods for my ongoing port of https://github.com/btcontract/immortan and https://github.com/fiatjaf/cliche to SN:
- `.getOutputStream()`
- `.getInputStream()`
- `.connect()`
- `.close()`

I am also confused about how will these things work in single-threaded mode or if that is even relevant, but I guess I will just try eventually and learn in the process.

Thank you!

**Comment by armanbilge** [comment]
FYI I'm planning to implement some Javalib socket APIs to support the Native cross-build of fs2-io. This will be a fully async implementation. I haven't decided yet, but it will be either:
- [`SocketChannel`](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/SocketChannel.html) paired with [`Selector`](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/Selector.html); or
- [`AsynchronousSocketChannel`](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/AsynchronousSocketChannel.html)

It is very likely to live in [epollcat](https://github.com/armanbilge/epollcat/), but i have not yet decided this either. It would be great to upstream this work into Scala Native itself, but as @fiatjaf points out the single threaded runtime complicates this.

Any interest, feedback, and help is appreciated :)

**Comment by LeeTibbert** [comment]
@fiatjaf  Thank you for creating this PR.

Let's see if we can get your application pushing data over the wire.

If you are talking "normal" network, a.k.a socket, communication,
that is connected streams, known as TCP (Transmission Control Protocol)
and its most wide spread & historical implementation, IPv4 (Internet Protocol, version 4)
then the methods you helpfully listed and many more are in Scala Native `0.4.5` and
many prior versions. 

`java.net.Socket` & friends are mostly, but not entirely complete.  I was in
that area this past weekend and noticed a few obscure things missing,
such as a Socket constructor using Proxy, and some setPerformance methods.

I have actively used the methods you mention just this past weekend. There
are examples of use in Scala Native specifically in the SN repository. Examples
of using them in Scala JVM should work unchanged (with the exception of totally missing methods 
as reported by the linker)  and should be available on the web.
I have not looked at the code in the scripted tests `java-net-server-socket` & `java-net-socket`
to remember exactly which calls they exercise.

I think there was discussion on Discord last week about an `echo-server` application
in Scala Native available on the Web. 

Are you having difficulty using these routines?  There is a learning curve.
If misery lovers company :I find myself getting someway up it, then falling off and having 
to start all over.

In another issue you had posted the URL of one of your projects, is that the one?
Is that URL still available?  If yes, sorry but could you post it again.  I can give
the code a quick examination.

**Comment by LeeTibbert** [comment]
Having said that `javalib` `java.net` is functional, but not complete, for TCP IPv4 I must fill out the picture.

`java.net` in any public version of SN does not support IPv6. It also does not support Datagram (UDP) sockets.
These are specialist cases.  

SN `posixlib` supports both of these, with UDP support becoming more complete in `0.5.0-SNAPSHOT`.

There is a chance that you have fallen into one of these `javalib` "holes" without meaning to. 
Can you describe the problems you are seeing?

Let's get you up and running.

...........................................................................................................................................
There is hope of seeing `javalib` support for IPv6 in a future release of SN.  Motivated by
your discussion in the Discourse channel, I have a private implementation a 10-day away,
with any luck or skill, from a PR. May the hurricanes hold off.

**Comment by fiatjaf** [comment]
@LeeTibbert thank you. The issue was https://github.com/scala-native/scala-native/issues/2784, but the problem was unrelated, it had to do with a bad call to `Inet6Adress.getbyAddress`. That was part of my ongoing work to port this enormous thing to SN.

I haven't yet reached the moment in which I will try to port the final application, as I am still porting https://github.com/fiatjaf/scoin to SN and ScalaJS. Then I will refactor https://github.com/fiatjaf/immortan to use that library instead of the super messy vendored code it currently uses, and then I have to rewrite some parts of it that use `netty` and `RxScala`. Then finally I will get to https://github.com/fiatjaf/cliche and try to use it with `java.net.Socket` in SN.

So don't worry about this, there are many months ahead of me in work before I reach anything close to the point in which SN may -- or may not -- become the bottleneck.

**Comment by armanbilge** [comment]
@fiatjaf update: I've now implemented `AsynchronousSocketChannel` and `AsynchronousServerSocketChannel` in [epollcat](https://github.com/armanbilge/epollcat). These are fully async, non-blocking implementations. More details and snapshot are in the README :)

**Comment by LeeTibbert** [comment]
@armanbilge re: epollcat   Very interesting.  Nice to see that you are making progress.

**Comment by LeeTibbert** [comment]
@fiatjaf 
Hi! 

I am sifting thru the SN backlog. SN has made a lot of
progress over the last 6 months.

 Is this still an issue or can it be closed?  

I hope you got up & running.

Thank you. 

Lee

**Comment by fiatjaf** [comment]
I think it should be good. Thank you very much!
