### ISSUE TITLE
Port partest integration from scala-js

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#28]
This will be the initial foundation for the test suite. 

Starting point: https://github.com/scala-js/scala-js/tree/master/partest/src/main/scala/scala/tools/partest/scalajs

**Comment by andreaTP** [comment]
trying to make an effort on this, I think I will need some help at some point.... available on gitter most of the time

**Comment by densh** [comment]
@andreaTP I'm available on gitter for help, ping me if you have any specific things you need.

**Comment by andreaTP** [comment]
unfortunately this come out to be a bit harder than I thought, probably I will need some more understanding on the actual infrastructure to help on this, sorry....

**Comment by densh** [comment]
@andreaTP no worries.

**Comment by Duhemm** [comment]
@andreaTP @densh What's the status with this issue? In the meantime, could sbt scripted-tests be enough ? See https://github.com/scala-native/scala-native/compare/master...Duhemm:add-scripted-tests

**Comment by densh** [comment]
@Duhemm I didn't know about scripted tests. That would be a great starting point for now! We'll still need partest to run existing tests from scalac, but that will come later.

**Comment by densh** [comment]
This got less critical with https://github.com/scala-native/scala-native/pull/263.
