### ISSUE TITLE
Add support for ThinLTO

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#280]
Currently we emit one huge blob of code to LLVM. This has previously been the same thing to what clang did to enable regular link-time optimisations. This has changed in 3.9 where something called [ThinLTO](http://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html) was introduced. It combines best of both worlds, we should be able to emit code in similar fashion.

Related: #182

**Comment by ekrich** [comment]
@densh Just a a data point I was experimenting with this on the standard link phase. I added `nativeLinkingOptions := Seq("-flto")` to my build. This option with no setting corresponds to `-flto=full` vs `-flto=thin` as mentioned here. The executable was a little bit bigger but everything seemed to work ok. 

This also shows we would need Xcode 8 or higher - http://releases.llvm.org/4.0.0/tools/clang/docs/ThinLTO.html . I am using the xcode 8.3.2 with macOS 10.12 but travis shows you can still support macOS 10.11 with Xcode 8 - https://docs.travis-ci.com/user/reference/osx/#OS-X-Version

I also tried with thin option.
```
[debug] running
[debug] /usr/bin/clang++
[debug] 	-o
[debug] 	/Users/eric/workspace/scala-native-ml/blas/target/scala-2.11/scala-native-blas-out
[debug] 	-lcblas
[debug] 	-flto=thin
[debug] 	-target
[debug] 	x86_64-apple-macosx10.12.0
[debug] 	/Users/eric/workspace/scala-native-ml/blas/target/scala-2.11/native/__class_has_trait.ll.o
[debug] 	/Users/eric/workspace/scala-native-ml/blas/target/scala-2.11/native/__const.ll.o
[debug] 	/Users/eric/workspace/scala-native-ml/blas/target/scala-2.11/native/__dispatch.ll.o
...
[info] Linking native code (281 ms)
```

**Comment by ekrich** [comment]
Maybe using 4.0+ maybe be better. http://releases.llvm.org/4.0.1/docs/ReleaseNotes.html#improvements-to-thinlto-flto-thin
