### ISSUE TITLE
Add more platform checks to `LinktimeInfo`

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#2802]
Currently only `isWindows` is offered.
https://github.com/scala-native/scala-native/blob/2f2d322f29239bd77220e52c4ecd5833fbe0132c/nativelib/src/main/scala/scala/scalanative/meta/LinktimeInfo.scala#L10-L11

I would find more of these useful: specifically I am seeking `isLinux` and `isBSD` so that I can conditionally call either the [`epoll`](https://man7.org/linux/man-pages/man7/epoll.7.html) or [`kqueue`](https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2) APIs.

But there are an infinite number of platforms, so there are important questions here:
1. how do we decide which are important enough to include in `LinktimeInfo`?
2. or, can we support userland-extensibility? as teased in the [0.4.1 release notes](https://scala-native.readthedocs.io/en/latest/changelog/0.4.1.html).
  > Currently, the list of linktime resolved expressions is limited and users cannot create new ones, but it might change in the future.

Alternatively: is there any way we could expose the target-triple string in the `LinktimeInfo` for useful link-time checks to be written against it in user code?

**Comment by armanbilge** [comment]
Here are some additional ideas from Wojciech on Discord:

> Working with the raw target triple might be really hard, if we would like to allow for ops, like .contains or .startsWith . It would require changes in compiler plugin or in the linker. I think maybe a better idea would be parsing the target triple and exposing it's fragments in the linktime infos. Then we would be able to easily match them with == operator. Here, we can find llvm API including all possible parts of the target triple, parsing them manually might be really error prone https://llvm.org/doxygen/classllvm_1_1Triple.html

> One option would be to use JNI to access the LLVM parser directly. I don't have an experience with that, and I worry about the portability. The safest way would be reimplementing parser in the Scala, but then it might require a maintance in the future. In theory it's should be that hard

**Comment by armanbilge** [comment]
And from Denys:
> In my experience it’s always easier to launch a C/C++ subprocess than use JNI. (For one, there is no easy way to distribute JNI code portably.) 
For example we could write a tiny cli tool in C++ that calls llvm APIs and prints it to stdout in some structured format (json?). SN sbt plugin will compile it on user machine and invoke it as a sub process to extract all the platform info and parse the output on JVM side.

**Comment by JD557** [comment]
I think this can be closed now (it was closed by #2809)

**Comment by armanbilge** [comment]
Well, yes and no. https://github.com/scala-native/scala-native/pull/2809 did the easy solution of adding a few more booleans. But this issue also discusses a far general solution of encoding the target triple into `LinktimeInfo`. That is the real, long-term solution.

**Comment by armanbilge** [comment]
I just realized my fix from https://github.com/scala-native/scala-native/pull/2809 is broken.
https://github.com/scala-native/scala-native/blob/8a15c88bf0a2c9757b37633dde79c2d431675d01/tools/src/main/scala/scala/scalanative/linker/LinktimeValueResolver.scala#L14-L17

The problem is that the value is derived from `Platform`, which is based on where sbt is running. In fact, it should be derived from the target triple. Fixing this requires parsing the target triple. Fixing this bug is effectively equivalent to properly solving this problem discussed above i.e. providing the parsed target triple in `LinktimeInfo`.
