### ISSUE TITLE
Standard lib readiness

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#282]
We need to have a docs page that lists all of the available library APIs and their current status. 

As suggested by @rom1dep on our gitter channel.

**Comment by frgomes** [comment]
I suggest a project in github, on the lines of awesome-scala or awesome-rust, etc.


On Mon, Sep 05, 2016 at 8:02 AM, Denys Shabalin < notifications@github.com [notifications@github.com] > wrote:
We need to have a docs page that lists all of the available library APIs and their current status.

As suggested by @rom1dep [https://github.com/rom1dep] on our gitter channel.

**Comment by densh** [comment]
This one is more along the lines of what classes in JDK we currently support, this should be included in the docs. Awesome lists are usually about third-party libraries.

**Comment by densh** [comment]
Docs are going to be hosted at http://scala-native.readthedocs.io/en/latest/lib/javalib.html

We still need to go through all the Java classes we have and list current state for each one of them.

Quite a few classes in `java.lang` are fully implemented already.

**Comment by MasseGuillaume** [comment]
@densh do you want to do this manually?

This is the idea I have to do it automatically:

* extract JVM methods to Scala interfaces/stubs automatically. (traversing via java reflection for example)
* traverse the Scala Interfaces (via Scala Meta for example) and find unimplemented / implemented methods
* provide additional meta information, for example, we will never implement java.awt.

**Comment by densh** [comment]
I think we can just list all implemented classes for now. That information is trivial to get from the names of class files in the `target/` folder of the `javalib/` project.
