### ISSUE TITLE
Posixlib grp.scala, pwd.scala, and sys/stat.scala need to use common types from sys/types.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2832]
Almost always, Single Points of Truth are worth the effort.

Discovered whilst chasing attempting to fix Issue #2831.

I have known about it for years, but it has never bubbled to the 
top of my list.  Time to do something about it now, so that
fix for #2831 does not get messier than it already needs to be.

**Comment by LeeTibbert** [comment]
@WojciechMazur  

Could you please consider creating a GitHub Label, similar to 'has_pr' for
'component:posixlib'?   Not a necessity, but it would help keep track of what is changing
where.  I have found the existing 'component:javalib' to be handy.

Thank you, L.

**Comment by WojciechMazur** [comment]
Hey @LeeTibbert I've added the request label. That was a good idea. It should help to organize the repo.

Btw. I think that currently, we don't really need a `has_pr` label. Currently, in GitHub, we can just link an issue with a  PR. In multiple cases, it's better because it would automatically close the issue as soon as the related PR is merged. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by LeeTibbert** [comment]
@Wojciech   Thank you for the fast turnaround on the component keyword.

Also, thank you, for the URL.  I had taken a run at linking issues before
but had not had the benefit of that info.  It was not evident how to do so,
so I thought I lacked the privilege. 

The "Development" section on the right of my screen has no "gear wheel",
so I wheel.  I just took a run at doing it automatically, using the right magic
word in the creation comment, not just in the Title.   Seemed to work, so 
know I know that I have sufficient privileges. 

I think the "has_pr" label still has some value so that other developers
can know at a flash that something is being worked on.  Should really
have a, voluntary, "Work started" label that is placed when someone "takes"
an item off the queue.  The community is pretty good about
letting folks know about what is being worked on and what is not,
but there are too few of us to waste development cycles on
duplication.

I can stop using the "has_pr" if it complicates your end of
the development process.  Looks like devo's being able
to use automatic linking and the spread of that practice
will simplify all of our tasks.

I learned something to start by day and found out I had more power 
that I thought.  Could be a good day.   May yours be better.

**Comment by armanbilge** [comment]
> Should really have a, voluntary, "Work started" label that is placed when someone "takes"
an item off the queue. 

We can use "assignment" for that. Here, I will assign this issue to you :)

**Comment by LeeTibbert** [comment]
Where it is OK to use self-assignment?   I like that idea/practice.
@ekrich  Can we loop you in on this discussion?  What do you think?

1) using auto-linking in the PR creation message

2) voluntarily using "assignment" to  "take a soft lock" when
   starting work in an Issue?
