### ISSUE TITLE
llvm-15-0-0 is released

### ISSUE THREAD

**Issue by He-Pin** [scala-native/scala-native#2838]
refs: https://discourse.llvm.org/t/llvm-15-0-0-release/65099

**Comment by LeeTibbert** [comment]
Have you tried it? 

My private builds of SN using LLVM 15.0 have worked well so far.
Alway like to hear the experience of others in the community
I really have not noticed a difference, but then I am usually head down 
chasing the bug/bugs I am after.


After giving LLVM 15 a weeks burn-in time, SN could probably switch to 
LLVM 15.0.  Doing so means changing things in CI, which is always a 
time-sink, one way or another for the community's most limited but
well-natured  resource.

**Comment by LeeTibbert** [comment]
Traditionally the version of Clang used in CI has been kept behind the bleeding edge.

For a long while (years?) it was held at Clang 6.
Some background, in the hope that it might be helpful.

The imminent forced move on CI from Ubuntu 18.mumble to 20.04.mumble will 
probably occasion an upgrade to clang version.  I have not heard of any discussions.
I think Windows may be using Clang 11 or even a bit higher, for its builds.

I would like to see the Clang version go to 13 or so, probably not 15. That is
the van (head of the list)  but not the bleeding edge of the van. 

When the discussion of what Clang version rolls around, I think I am going to claim that it is 
peak hurricane season and demure.  Who care if it is December?

**Comment by LeeTibbert** [comment]
@He-Pin Is any action in SN needed here?  

If not, does it make sense for you to close this Issue?  That would reduce the backlog
and let Issues needing action stand out.

Scala Native seems to build just fine with  Clang 15.0.4.mumble. I use it pretty
intensively.  Are you experiencing something different?   

I think the Clang version in the SN Continuous Integration flows has
been recently (3 months?) reviewed.  I doubt that it will go to Clang 15 anytime
soon.

Please let me/us know if you have continuing concerns about this Issue.

Thank you.  Lee.   Trying to do some housekeeping whilst I wait for CI and
a hurricane.
