### ISSUE TITLE
Add test case for linking Scala code as native library

### ISSUE THREAD

**Issue by phdoerfler** [scala-native/scala-native#285]
I suggest a simple test case for (https://github.com/scala-native/scala-native/issues/155) in which a simple native dynamic library is created with scala native and used by another scala native program.
This of course assumes that the current test framework allows for introducing such a compile time dependency since the library would have to be compiled before the actual test code.

**Comment by densh** [comment]
I've been thinking about this one for a while. We definitely need better infrastructure to test interop-related functionality. One way to do it is to add some basic support for building C code from sbt via clang and having mixed Scala/C projects.

**Comment by densh** [comment]
Given that we don't officially support linking Scala code as a native library yet, I'm closing this should be addressed as a part of #155
