### ISSUE TITLE
Port of java lang throwables from Scala.js got outdated

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#287]
I'm currently diffing javalib to create https://github.com/MasseGuillaume/multi-platforms-javalibs. I found some notable difference(s)
- [Throwables](https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/io/Throwables.scala#L4) vs [Throwables](https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/io/Throwables.scala#L4)

**Comment by sjrd** [comment]
See https://github.com/scala-js/scala-js/pull/2560

**Comment by densh** [comment]
Yep, we need to bring those update with respect to SJS.

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/437
