### ISSUE TITLE
Posixlib is missing "sys/un.h" for Unix sockets

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2900]
Discussion in Issue #2899  revealed that posixlib `sys/un.h` is not implemented in Scala Native.
This file contains declarations which make declaring storage for Unix sockets easier.

Arman Bilge is willing to donate a good starting point. Thank you, Arman.

Scala Native 0.5.0 already contains code under the same license.  A backport to 0.4.x would need to check that the
 SN License file is up to date. License is not a big issue, but is essential housekeeping.

| If it's any help, I also have un.h here:
| https://github.com/armanbilge/fs2-io_uring/blob/2d7df694371cb0fa0fdd33e8966b72274106f8d7/
| uring/src/main/scala/fs2/io/uring/unsafe/sysun.scala

This will not fix the 0.4.n `bind` flaw reported in #2899 but should make it easier for
developers to use Unix sockets.

A developer picking up this Issue should check carefully the "108" number in the structure
declaration also works on (or is adjusted for) macOS and the BSD family.   As always
this-is-posix-and-Windows-is-not-but-what-should-be-done-on-Windows-paths?

A unit-test would be useful, but this probably requires creating a child process
and communicating over the Unix socket.  More than an afternoon's work
(fork() is probably the only thing that will work seemlessly across 0.4.x & 0.5.0).

A related issue, which should not hold up resolution of this one, is that one
should check javalib. Does Java support unix sockets?  If yes, does
SN support them also?  I would put beverage money on "sorry, no".

**Comment by armanbilge** [comment]
> Does Java support unix sockets

Yes it does, in recent JDKs. Here is an example use:
https://github.com/typelevel/fs2/blob/e77cb9fe0caeb060b5341c5873aa7cde24d47ca7/io/jvm/src/main/scala/fs2/io/net/unixsocket/JdkUnixSockets.scala#L39-L41

>  If yes, does SN support them also?

No, because SN does not currently implement the `java.nio.channels` APIs for network sockets.
