### ISSUE TITLE
j.l.AbstractStringBuilder contains problematical "breakable'

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2918]
Ekrich rightly noted in his review of PR #2971 that `java.lang.AbstractStringBuilder` 
contains scala `breakable` statements. Since we are trying to remove
scala library dependencies from all of javalib, those 'breakable' blocks
will soon prove problematic.

The solutions are to implement javalib in C or, if one wants to be
_au courant_ , Rust.  Ada might be a bit too cumbersome.

So, something is coming, and it is not Santa Claus.

**Comment by LeeTibbert** [comment]
David,   You are leading the effort here & I will follow it.

Sorry if I complicated things.  I had been hoping to simplify them
by factoring the 'breakable' issue out of your PR, since you did not touch any of it.  Guess now you have ;-)

**Comment by david-bouyssie** [comment]
No problem, I'm guilty on this point.
I should have filed all the issues I encountered first, instead of dispatching them along days.

**Comment by LeeTibbert** [comment]
I think good will, and you have mine, trumps any "Cathedral" style approach.  Given the number of highly interconnected
things you are dealing with now, I can understand wanting to access the "size of the problem" before
taking the interrupt of untangling & reporting things.  I am dealing with a couple of similar beasts in the
`java.net` space.
