### ISSUE TITLE
j.l.AbstractStringBuilder could have performance problem due to use of 'breakable' 

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2919]
From Ekrich's spot-on comment in #2917

> If any of the breakables are in the hot path that could affect your performance.

Some 21st century style guides, such as Google, even _recommend_ "return from the middle of a method"
coding.  As someone who started out that way and was educated to "one entry, one exit" coding, I simply
can not understand that style.  I try, and often fail, to summon understanding and compassion for "return from the middle"
when I have to go fix it.  Color me grumpy (or prudent with how I want to spend my time).

Full disclosure: I have used that style in critical section assembly code, where every instruction counted and nobody understood the write-only code in the first place.

**Comment by david-bouyssie** [comment]
Already replied in #2918.
To me this issue can been seen as duplicated.

I would only keep the #2918 one open, and change the title to "Remove the use of 'breakable' in j.l.AbstractStringBuilder".
Otherwise I will put this title in the PR name and link the two issues.

**Comment by LeeTibbert** [comment]
I think that the recommended replacement for `beakable` is going to be re-visited/re-worked
for Scala 3.n, where n > 2.

Any work on this issue should probably be postponed until such re-work is done.

**Comment by ekrich** [comment]
We want to remove the Scala library code from `javalib` anyway. Maybe just reorganize the code to remove `breakable` - it is bad anyway. The only use I can see is for porting Java code to Scala where `break` and `continue` are a thing.

**Comment by LeeTibbert** [comment]
I seem to remember hastily investigating a re-write without breakable at the time.
Preliminary triage put it in the "nightmare" pile, and there were more pressing issues
at the time.

When I read about another round of changes to Scala's `breakable`, I put this topic
in the "wait until the dust settles, or it becomes critical, whichever comes first".

If I understood the descriptions/conversation_thread, breakable is not going
to become part of the language, but there might be something more going on
than it being a library routine that we want to avoid. That is, some compiler
support, which might be fair game.

**Comment by LeeTibbert** [comment]
Under heading of "less bad",  there is an off chance that the places which use "breakable" could 
be replaced by "return" statements which do not trigger "non-local return error".  

I think that local return has its own set of problems, similar to "breakable".  That is one
of the reasons that I wanted to let the people who know what they are doing sort out "breakable" & kin.
