### ISSUE TITLE
Add support for Thread.sleep()

### ISSUE THREAD

**Issue by mkotsbak** [scala-native/scala-native#292]
Even before a full threading support is added (#101), it should be easy to add support for Thread.sleep() by using e.g. this: http://linux.die.net/man/3/usleep

This works as a workaround:

```scala
@extern object Unistd {
  def usleep(usecs: Long): Int = extern
}

object Thread {
  def sleep(millis: Long) = Unistd.usleep(millis * 1000)
}
```

Not sure if this is the proper way to solve it generally.

**Comment by densh** [comment]
As long as the unix function you're using is available across all common *nix operating systems (e.g. Linux, FreeBSD and macOS), it's fine to use in our implementation. Windows support is on the longer-term horizon.

**Comment by mkotsbak** [comment]
Ok. Could my code above be included somewhere as it is?

**Comment by densh** [comment]
Yep, just make a PR. 😉

**Comment by mkotsbak** [comment]
I'm trying here: https://github.com/mkotsbak/scala-native/tree/Thread.sleep_support

But when I test, I get:

```
Unresolved dependencies:
  `@java.lang.Thread$::sleep_i64_unit`
```

**Comment by mkotsbak** [comment]
Ah, seems it was that I forgot to add Unit as return value as the unistd function returned int.
