### ISSUE TITLE
Spurious "missing definitions while linking"

### ISSUE THREAD

**Issue by sideeffffect** [scala-native/scala-native#2920]
When trying to run ZIO tests, there are some issues when linking. They are very suspicious, most likely wrong:
```
[error] Found 1 missing definitions while linking
[error] Not found Top(scala.Nothing)
[error] 	at /home/runner/work/zio/zio/test-tests/shared/src/test/scala/zio/test/mock/PolyMockSpec.scala:15
```
```
[error] Found 1 missing definitions while linking
[error] Not found Top(scala.Nothing)
[error] 	at /home/runner/work/zio/zio/test/shared/src/main/scala/zio/test/mock/MockRandom.scala:33
```
https://github.com/zio/zio/actions/runs/3283699177/jobs/5408751779#step:7:687 in the PR https://github.com/zio/zio/pull/7031

/cc @lolgab

**Comment by armanbilge** [comment]
Are you able to minimize it a bit?

**Comment by sideeffffect** [comment]
We're still seeing these errors with Scala Native 0.4.9
```
[error] Found 4 missing definitions while linking
[error] Not found Member(Top(java.lang.String),D5charsL26java.util.stream.IntStreamEO)
[error] 	at /home/runner/work/zio/zio/test/jvm-native/src/main/scala/zio/test/TestDebug.scala:37
[error] Not found Top(java.util.function.IntFunction)
[error] Not found Top(java.util.function.IntPredicate)
[error] Not found Top(java.util.stream.IntStream)
[error] 	at /home/runner/work/zio/zio/test/jvm-native/src/main/scala/zio/test/TestDebug.scala:36
```
https://github.com/zio/zio/actions/runs/4243167436/jobs/7375568271#step:7:175
Was this supposed to be solved or is this a different kind of error?
/cc @armanbilge @WojciechMazur

**Comment by armanbilge** [comment]
@sideeffffect those errors are not "spurious", those are legitimately missing APIs. For example, there is no implementation of `java.util.stream.IntStream`.

https://github.com/scala-native/scala-native/tree/v0.4.10/javalib/src/main/scala/java/util/stream
