### ISSUE TITLE
Clang 15.0.3 fails build because of  missing prototype in Commix.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2921]
Clang 15.0.3 started reported an error building the indicated file.

```
/scala-native/gc/commix/Heap.c:239:33: warning: passing arguments to 'WeakRefGreyList_CallHandlers' without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
[error]     WeakRefGreyList_CallHandlers(heap);
[error]                                 ^
```

Is there anyone looking out for Commix?   If not, should I try to provide the indicated function prototype
 (or, if it already exists), why it is not being used/seen.

Please advise.

I did not see this error with Clang 15.0.2.  For now, I will fall back to an earlier version of Clang.

**Comment by armanbilge** [comment]
Could this be related to:
- https://github.com/scala-native/scala-native/issues/2889
- https://github.com/scala-native/scala-native/pull/2890

> Is there anyone looking out for Commix?

Good question. Is CI testing Commix?

**Comment by LeeTibbert** [comment]
Arman,

I will check those out.  I examined the code and it looks like a total space shot error to me.
There is a prototype, it is in scope, and the code being detected is not matching the prototype.
The prototype matches its implementation, but the code being detected is sending an argument,
which the implementing code totally ignores.  Compler gets a point for detecting this one.

My first trial build of the obvious fix succeeded. I am now trying a "double sure totally clean" run.

I had thought Commix was in the CI matrix, but times change. I will have to check.
I am using a much more current compiler than CI, so CI not detecting the fault is
no problem.  Until noon time today, the compiler on my machine did not detect 
it either.  

| Is there anyone looking out for Commix?

I had meant in terms of Parental Unit or supervising developer or "someone to whom I can punt this".
Guess I did not express myself well enough.

Anyway, I think running a PR up the flagpole is the way to go.  No harm done unless it get merged.
At this point doing the PR is easier than backing off my compiler version.

**Comment by LeeTibbert** [comment]
Arman, you earn your bread another day, Thank you.

PR #2890 changed the prototype definition to match the implementation.
That is what I am seeing (so my local repository is up to date).  It _did_
not change the call site, which is what Clang 15.0.3 is now detecting.

I am now more confident in the PR I will soon submit.

**Comment by ekrich** [comment]
Note that all GC code should be compiled but then not linked if not selected. The CI should test each as well - not sure about None.
