### ISSUE TITLE
Bug in String constructor accepting a StringBuffer: String immutability is broken

### ISSUE THREAD

**Issue by david-bouyssie** [scala-native/scala-native#2925]
As discussed in the PR #2908, the following String constructor is buggy:
https://github.com/scala-native/scala-native/blob/main/javalib/src/main/scala/java/lang/String.scala#L137

It is illustrated by the following test:
```scala
@Test def createStringThenModifyStringBuffer(): Unit = {
  val buf = newBuf
  buf.append("foobar")

  val s = new String(buf)
  buf.setCharAt(0, 'm')

  assertTrue(
    s"foobar should start with 'f' instead of '${s.charAt(0)}''",
    'f' == s.charAt(0)
  )
}
```

In the current main branch it gives `failed: java.lang.AssertionError: foobar should start with 'f' instead of 'm'`.
It means that modifying a StringBuffer, that has been previously been wrapped in a String, may corrupt the created String.

However, `StringBuffer.toString` is not affected, and this can be verified with the following successful test:

```scala
@Test def toStringThenModifyStringBuffer(): Unit = {
  val buf = newBuf
  buf.append("foobar")

  val s = buf.toString
  buf.setCharAt(0, 'm')

  assertTrue(
    s"foobar should start with 'f' instead of '${s.charAt(0)}''",
    'f' == s.charAt(0)
  )
}
````

**Comment by LeeTibbert** [comment]
re: PR 290  Is that missing a digit?  

When I follow the link as-is I get "Add doc for @link". Nothing there seemed to
be currently relevant.
