### ISSUE TITLE
javalib should be more strict about the visibility of things when can mutate strings.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2930]
I do not want to submit these now so that I do not interfere with or hinder David B's 
incredible progress in the java.lang.String world.

In my private sandbox I have tried out some ideas which restrict the visibility to
the underlying Array[Char] of, especially, StringBuffer but also, theoretically,  StringBuilder.
Some of these have come up in discussions that David & I have had. Some come from
code inspection.

`protected abstract class AbstractStringBuilder private (unit: Unit) {`
Works. 

Without this change, any class in scala can access it, and its method
which gives mutable access to StringBuffer & StringBuilder underlying Arrays.

With this change, only StringBuffer & StringBuilder can access each others
vitals.

```
 final def shareValue(): Array[scala.Char] = {
    shared = true
    value
  }

```
Unused method `shareValue` can go away so that people are not tempted down the
road to ruin.

```
 final def getValue(): Array[scala.Char] = value

```
With its class becoming protected, `getValue` becomes less capable of providing an 
avenue for harm (mutability).   Much as I would like to delete the method, it
provides a performance path for an obscure StringBuilder append(StringBuffer) method.

I believe the method can stay, but needs some comments. The paragraph above
about who it helps. It desperately needs a comment that it should be `value.clone` 
but is not, to avoid an array copy in the append method'' above. Not having
".clone" means that it relies upon the good behavior of its cousin StringBuilder.
Previously it relied upon the good behavior of all of Scala Native.

I would expect the actual comment in the PR to be clearer & more succinct.

All of these changes, with some corresponding edits in String.scala compile
and pass tests on my machine.

**Comment by david-bouyssie** [comment]
I agree on most of your suggestions, except one: removal of `shareValue()`.

I would not remove it but I would set at it as `protected` inside `AbstractStringBuilder`.
This would have to be treated in PR #2908, where I have still a use case for this.

And if one day we change our mind about the behavior of `new String(sb: StringBuilder/StringBuffer)`, meaning not copying chars, one could easily call `sb.shareValue()` inside those constructors, and everything should be managed correctly.

**Comment by david-bouyssie** [comment]
Finally decided to do it in PR #2909, which I hope well get merged soon

See relative commit https://github.com/scala-native/scala-native/pull/2909/commits/4dce8104eafe5d232a70271da113eb1e63b867c8
