### ISSUE TITLE
Two related new build defects

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2956]
I am reporting/capturing these to save other people time & energy 
if they start seeing them also.

1) scalafmt seems to now be reporting a error
```
partest-check-files.scala:1: error: [dialect scala213] illegal start of definition identifier
#!/usr/bin/env -S scala-cli shebang
^

```
A shebang inside a scala file does indeed look weird/suspicious. I did not
track down when that change entered the Repository. Probably in the 
past few days.

2) More concerning is the fact that the `lint` CI action detects that
    error but does not fail the linting.

    I think the is actually the more important of the two defects.

**Comment by ekrich** [comment]
See: https://github.com/scalameta/scalafmt/issues/3267

**Comment by WojciechMazur** [comment]
The shebang can be safely removed it was added just for convenience when migrating the ammonite script to scala-cli due to CI deprecation warnings. However the fact that CI job has not finished with an error should be investigated

**Comment by WojciechMazur** [comment]
It seems that on parser error, eg. when finding shebang scalafmt prints `error: ParseError=2` and returns 0. If the code is misformatted it would return 1

**Comment by WojciechMazur** [comment]
Added an issue to scalafmt https://github.com/scalameta/scalafmt/issues/3354
