### ISSUE TITLE
Platform should take into account the targetTriple

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#2987]
When cross-compiling to a different operative system, the Platform defined [here](https://github.com/scala-native/scala-native/blob/210eedd3958fc1e1ac9bd354d8534d5b826b6219/tools/src/main/scala/scala/scalanative/build/Platform.scala#L9) is not a constant but depends on the target triple we are compiling to.
If the target triple is set to `"x86_64-windows-gnu"` I expect `Platform.isWindows` to be `true`.

**Comment by armanbilge** [comment]
See discussion / proposed solution in:
- https://github.com/scala-native/scala-native/issues/2802#issuecomment-1271823960

**Comment by lolgab** [comment]
I think this issue was closed by mistake @WojciechMazur
