### ISSUE TITLE
Deprecation warning in ThreadTest.scala, probably macOS specific

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3006]
macOS, 12.6, M1  Scala Native 3.2.1

New-to-me deprecation warning.   I do not remember seeing this on Intel Linux.

I am off on not one but two snark hunts right now and can not take the interrupt
but want to capture it for later; like a lioness saving a kill to be enjoyed at leisure.

```
/unit-tests/native/.3/target/scala-3.2.1/test-classes ...
[warn] -- Deprecation Warning: /Users/lee49/Devo/ScalaNative/WorkSpace_A1/study_j_l_InetAddressWrongException_I3005_2022-11-21T1032-0500/unit-tests/shared/src/test/scala/javalib/lang/ThreadTest.scala:43:38 
[warn] 43 |    assertTrue(Thread.currentThread().getId > 0)
[warn]    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]    |method getId in class Thread is deprecated since : see corresponding Javadoc for more information.
```

**Comment by WojciechMazur** [comment]
What JDK were you using? Probabl `getId()` is going to be deprecated in the context of upcoming Loom project in Java 19+

**Comment by LeeTibbert** [comment]
You called it.

> build 19.0.1+10

That is my "current Java system", so it floats (to catch things like this).

If/when I get tired of looking at it, I can spend some time checking for any 
suggested replacement. 

Nice to know the "size" of the problem.

**Comment by kyouko-taiga** [comment]
Gentle bump.

I hit the same issue on my system, except that it has turned into an error.
```
java 20.0.2 2023-07-18
Java(TM) SE Runtime Environment (build 20.0.2+9-78)
```

If we can't replace the use of the deprecated method, we should then document that we're getting tied to some specific version of the JDK.

**Comment by ekrich** [comment]
See: https://bugs.openjdk.org/browse/JDK-8017617
Deprecated in Java 19: 
[java.lang.Thread.getId()](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/Thread.html#getId())
This method is not final and may be overridden to return a value that is not the thread ID. Use [Thread.threadId()](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/Thread.html#threadId()) instead.

**Comment by LeeTibbert** [comment]
IIRC,  the issue is that Java version specific code is needed. We have a way to deal with that in actual 
src, say,javalib, with the  `require-jdk9` etc directories.   Similarly, we can do Tests which only run
in JDK 9 or 17 or such.

The hard nut which has prevented an overnight fix to this is that the problem occurs in the Test harness code.
I encounter it when I do my daily driving on Java 21.  Bad words ensue until I remember the times I have
taken a quick run at fixing it and bailed because of complexity. 

A more determined or focused person may have more success; My contribution is to say that it is "Bigger than a breadbox, and smaller than Robin Hood's barn, but closer to the latter".

**Comment by ekrich** [comment]
The tough part here is this code - https://github.com/scala-native/scala-native/blob/main/test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala#L105

The actual implementation is fine - https://github.com/scala-native/scala-native/blob/main/test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala#L105

I think will will have to use `-Wconf` or `@nowarn` for the first one. It'll be quite some time before we mandate something so new.

**Comment by LeeTibbert** [comment]
Eric, the two URLs look the same L105.

In daydreams, well nightmares, I had been thinking about yet-another link-time-resolved for Java version.
There may actually be such. It is easier to curse the darkness than fix the underlying problem.  I just
new that I did not want to go anywhere near cloning the `TestAdapter.scala` code.  Mama may have raised
a fool or two, but they were not named Lee.


  With the pending (but do not hold your breath) Virtual Threads, such will probably raise the need.
