### ISSUE TITLE
Problem building scaladoc

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#3017]
Scala Version: `3.2.1`
Scala Native: `0.4.9`
Using `ScalaNativeJUnitPlugin`

Command/Message:
```
sbt:stensorflow-root> doc
[info] Main Scala API documentation to /Users/eric/workspace/stensorflow/stensorflow/target/scala-3.2.1/api...
[info] Skipping unused scalacOptions: -Xplugin
[warn] Setting -Xplugin is currently not supported.
[warn] one warning found
[info] Main Scala API documentation successful.
```
Result:
No docs generated.

Suspect line is here: https://github.com/scala-native/scala-native/blob/main/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativeJUnitPlugin.scala#L32

**Comment by armanbilge** [comment]
The `-Xplugin` is not the issue; indeed it says it's being skipped.

All my projects show that warning and still generate scaladoc:
https://www.javadoc.io/doc/com.armanbilge/fs2-io_uring_native0.4_3/latest/index.html

There must be some other misconfiguration in your project.

**Comment by armanbilge** [comment]
The problem in your build is probably this business:
https://github.com/ekrich/stensorflow/blob/0ab858b822f3e6f0dbd437277246350cfd88a88e/build.sbt#L40-L43

**Comment by ekrich** [comment]
This is indeed just a warning and the docs are generated but the user was looking in the wrong directory.
The business above is just so you can call `doc` rather than `stensorflow/doc`. I think it is okay.
