### ISSUE TITLE
Support stack traces with `-static`

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#3018]
One of the benefits of Scala Native is that it allows you to build small binaries, for example to ship in small docker images.
Nowadays you can't use a vanilla `FROM scratch` or `FROM alpine` image to ship your binaries since they depend on various runtime dependencies. This makes it harder to adopt Scala Native in the cloud vs JVM or Graalvm native-image, since it makes `Dockerfile`s more complicated that need to be (IMO).
This is what `ldd` prints for a Scala Native executable built with Alpine toolchain these days:
```
$ ldd out/app/nativeLink.dest/out
        /lib/ld-musl-x86_64.so.1 (0x7f8dec1ad000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f8debe0a000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f8debdf1000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f8dec1ad000)
```
These files are not very small files:
```
> ls -ls /lib/ld-musl-x86_64.so.1 /usr/lib/libstdc++.so.6.0.29 /usr/lib/libgcc_s.so.1 /lib/ld-musl-x86_64.so.1
   592 -rwxr-xr-x    1 root     root        604704 Nov 12 11:19 /lib/ld-musl-x86_64.so.1*
   592 -rwxr-xr-x    1 root     root        604704 Nov 12 11:19 /lib/ld-musl-x86_64.so.1*
    96 -rw-r--r--    1 root     root         96080 Apr 11  2022 /usr/lib/libgcc_s.so.1
  1872 -rwxr-xr-x    1 root     root       1915480 Apr 11  2022 /usr/lib/libstdc++.so.6.0.29*
```

It's more than 3MB of runtime dependencies, that you need to manually install in case of a Dockerfile

It would be nice if Scala Native was able to build static linked binaries, or binaries that depend on the minimum runtime dependencies (`crt0.o` in Mac OS X, nothing on Linux).
I tried many times to improve the situation but failed in all of them.
Other languages with similar stacks like [crystal-lang](https://crystal-lang.org/) [suggest](https://crystal-lang.org/reference/1.6/guides/static_linking.html#fully-static-linking) to use [musl libc](https://musl.libc.org/) and [alpine](https://alpinelinux.org/) to build static binaries. Trying to do so in Scala Native doesn't work.
Stacktraces stop working when you build with `-static`.
Given a program like:
```scala
object Main extends App {
  println("Hello world!")
  throw new Exception("BOOM!")
}
```

Scala Native adds the `-rdynamic` flag when linking (you can notice it in the `llvmLinkInfo` file in `nativeWorkdir.value`.
Building without it breaks the stack traces:
```scala
# without -rdynamic
Hello world!
java.lang.Exception: BOOOM!
        at <none>.(Unknown Source)
        at <none>.(Unknown Source)
        at <none>.(Unknown Source)
        at <none>.(Unknown Source)
        at <none>.(Unknown Source)
        at <none>.(Unknown Source)
```

```scala
# with -rdynamic
Hello world!
java.lang.Exception: BOOM!
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at Main$.<init>(Unknown Source)
        at <none>._SM5Main$G4load(Unknown Source)
        at Main.main(Unknown Source)
        at <none>.main(Unknown Source)
```

The same thing happens if you add `-static` to the linking options.

Tried this on an alpine virtual machine with OpenJDK 11 and clang.

To rapidly tweak the linking options you can build the binary with Sbt and then change the `llvmLinkInfo` file.
Then you can link again with  `clang++ @path/to/llvmLinkInfo`

**Update:**
The problem is the usage of `unw_get_proc_name` which is supported only in dynamic binaries. To properly support stack traces in static binaries, Scala Native should stop  relying on that function to get function names.

**Comment by lolgab** [comment]
The problem is not related to throwing exceptions (which throws an exception using C++ code).
You can reproduce the same behavior just by printing a stacktrace which is written in Scala Native calling some C functions which call libunwind:
```scala
object Main extends App {
  println("Hello world!")
  new Exception("BOOM!").printStackTrace()
}
```

**Comment by lolgab** [comment]
I opened an issue in the llvm project since I could reproduce the missing procedure name also using plain C:
https://github.com/llvm/llvm-project/issues/60492

**Comment by tanishiking** [comment]
While llvm-libunwind [depends on dynamic symbol table via dladdr](https://github.com/llvm/llvm-project/blob/543705641adb1d3533be141947264ca1b7b04479/libunwind/src/AddressSpace.hpp#L670-L678) as mentioned in https://github.com/llvm/llvm-project/issues/60492#issuecomment-1416564650
It seems like [nongnu libunwind](https://www.nongnu.org/libunwind/) can access the function name without `-rdynamic`

`main.c` is the same one as https://github.com/llvm/llvm-project/issues/60492

```
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.0
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

/ # apk info libunwind-dev
libunwind-dev-1.6.2-r3 description:
Portable and efficient C programming interface (API) to determine the call-chain of a program (development files)
...

/ # apk add clang libunwind

/work # clang -o main main.c -lunwind-aarch64
/work # ./main
UNW_EUNSPEC = 1
UNW_ENOINFO = 10
UNW_ENOMEM = 2
result = 0, name = 'main'
UNW_EUNSPEC = 1
UNW_ENOINFO = 10
UNW_ENOMEM = 2
result = 0, name = '_init'
UNW_EUNSPEC = 1
UNW_ENOINFO = 10
UNW_ENOMEM = 2
result = 0, name = '_init'
```

Actually they don't have `main` 

```
/work # readelf --dyn-sym main

Symbol table '.dynsym' contains 18 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000790     0 SECTION LOCAL  DEFAULT    8 .init
     2: 0000000000020000     0 SECTION LOCAL  DEFAULT   19 .data
     3: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _Uaarch64_get_pr[...]
     4: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND printf
     5: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _Uaarch64_step
     6: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND __stack_chk_guard
     7: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND __cxa_finalize
     8: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __stack_chk_fail
     9: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __deregister_fra[...]
    10: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMC[...]
    11: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterT[...]
    12: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND memset
    13: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _Uaarch64_init_local
    14: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __libc_start_main
    15: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __register_frame_info
    16: 0000000000000790     4 FUNC    GLOBAL DEFAULT    8 _init
    17: 0000000000000b4c     4 FUNC    GLOBAL DEFAULT   11 _fini
```

I haven't check how nongnu libunwind retrieve the function name without dynsym yet, but maybe it's from symbol table?

**Comment by tanishiking** [comment]
Maybe something around here https://github.com/libunwind/libunwind/blob/9233f4f5555ded20b080feb7ab0820b68253ef2e/src/mi/Gget_proc_name.c#L91-L94

**Comment by tanishiking** [comment]
Once scala-native started generating the debug information https://github.com/scala-native/scala-native/pull/2869 we should be able to generate stack trace by converting the program counter to stack trace element (file name / procedure name / line number...).
However, I guess it would be handy to read from symbol table as `nongnu libunwind`, my two cents.

**Comment by tanishiking** [comment]
Now, we have enough information to retrieve a function name when `libunwind` fails to get it from the dynsym table.
When ScalaNative [uses the `get_proc_name` of `libunwind`](https://github.com/scala-native/scala-native/blob/42568f6b5ec75fd795118209cc7245fc974cae9c/nativelib/src/main/scala/scala/scalanative/runtime/Throwables.scala#L91), and the resulting name is "empty" (or null?), we can fall back to retrieving the function name from DWARF information.

The [BackTrace.decodePosition](https://github.com/scala-native/scala-native/blob/42568f6b5ec75fd795118209cc7245fc974cae9c/nativelib/src/main/scala/scala/scalanative/runtime/Backtrace.scala#L52) currently retrieves only the line/column and filename. However, it essentially identifies a `subprogram DIE`, which represents a function and contains details such as parameters, local variables, lexical scopes, and of course the function name. (make sure there's that information using `dwarfdump` or something).

The `DW_AT_name`  attribute has the function's name indirectly. Its value is an offset pointing to the actual name string in the `.debug_str` section.
To implement that, we can retrieve the offset by `die.getName` [around here](https://github.com/scala-native/scala-native/blob/42568f6b5ec75fd795118209cc7245fc974cae9c/nativelib/src/main/scala/scala/scalanative/runtime/Backtrace.scala#L139), and then read the function name from the `.debug_str` section using [info.strings.read](https://github.com/scala-native/scala-native/blob/42568f6b5ec75fd795118209cc7245fc974cae9c/nativelib/src/main/scala/scala/scalanative/runtime/Backtrace.scala#L85)) around here (like we do for retrieving filenames via `val filename = info.strings.read(at)`).
