### ISSUE TITLE
Add support for scala.App

### ISSUE THREAD

**Issue by mkotsbak** [scala-native/scala-native#302]
It is convenient to create an application in Scala by creating an object that inherits from "App" trait. When I try that in Scala Native, I get:

```
Unresolved dependencies:
  `@java.lang.Class::getResourceAsStream_class.java.lang.String_class.java.io.InputStream`
  `@java.lang.System$::currentTimeMillis_i64`
  `@java.util.jar.Attributes$Name::init_class.java.lang.String`
  `@java.util.jar.Attributes$Name`
```

**Comment by densh** [comment]
TIL: Did you know that `scala.App` optionally (via a property) supports printing how much it took to run the app? And that's why it uses properties and currentTimeMillis.

**Comment by densh** [comment]
Short-term solution would be to patch the `scala.App` in overrides not to have this magic feature.

**Comment by fbertra** [comment]
Easy?  I volunteer!

Copy/paste from gitter feed

```
1) Copy existing App.scala into overrides folder. 
2) Remove code that adds support for timing the run of the application. 
3) Write a scripted test that uses App. 
4) Open a PR.
```

**Comment by densh** [comment]
@fbertra Thanks!
