### ISSUE TITLE
Two `InetAddressTest` test can fail on Ubuntu

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#3046]
Two tests can fail on Ubuntu 20.04
* `InetAddressTest.getByName` for
 ```scala 
    assertThrows(
      "getByName(not.example.com)",
      classOf[UnknownHostException],
      InetAddress.getByName("not.example.com")
    )
```
    
* `InetAddressTest.getByNameInvalidIPv4Addresses`  for 
```scala
 assertThrows(
      "getByName(\"240.0.0.\" )",
      classOf[UnknownHostException],
      InetAddress.getByName("240.0.0.")
    )
```
In both of the cases they throw `IOException` instead of `UnknownHostExcpeiton`. It seems to fail due to unexpected code `EAI_NODATA` in places where we expect `EAI_NONAME`. It's one of the currently unmapped error codes specific to GNU 
netdb.h defines them as follows.
```c
# ifdef __USE_GNU
#  define EAI_NODATA	  -5	/* No address associated with NAME.  */
#  define EAI_ADDRFAMILY  -9	/* Address family for NAME not supported.  */
#  define EAI_INPROGRESS  -100	/* Processing request in progress.  */
#  define EAI_CANCELED	  -101	/* Request canceled.  */
#  define EAI_NOTCANCELED -102	/* Request not canceled.  */
#  define EAI_ALLDONE	  -103	/* All requests done.  */
#  define EAI_INTR	  -104	/* Interrupted by a signal.  */
#  define EAI_IDN_ENCODE  -105	/* IDN encoding failed.  */
# endif
```

It seems that `EAI_NODATA` mapped to `WSANO_DATA` on Windows, but I could not find any additional information on possible mappings for other error codes.

**Comment by armanbilge** [comment]
There was some discussion about `EAI_NODATA` in https://github.com/scala-native/scala-native/pull/3007#issue-1460730837.

**Comment by ekrich** [comment]
I mentioned in a previous PR review that we should do what the JVM does - maybe not the exact message but at least the correct Exception type.

**Comment by WojciechMazur** [comment]
Looks like the changes made in #3007 were removed, probably that's my fault when rebasing between 0.4.x and main branch. I'll try to restore this change
