### ISSUE TITLE
What to do about Posixlib getopt.scala 

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3052]
Whilst studying PR #3048, I discovered that posixlib has the current 2018 definition
of `getopt` and relatives in `unistd` .  It also has a `getopt.scala` which was probably
part of POSIX when the former was created.  `getopt.scala` is documented in
`posixlib.rst`

The best solution is to delete getopt.scala and document that in 0.5.0.md changelog.

If that is deemed as hostile to current users, the file should be edited to indicate
that `unistd.h` is the 2018-current idiom and the `getopt` line dropped from the
changelog.

If that is still to disruptive, the `getopt` line could be kept with a footnote
that it is nolonger part of POSIX and that `unistd.h` is the 2018-current idiom.

**Comment by i10416** [comment]
https://github.com/scala-native/scala-native/pull/3054

**Comment by LeeTibbert** [comment]
I believe this issue is now or will soon be moot/resolved.

Thank you @i10416
