### ISSUE TITLE
Test hangs forever on Linux & commix

### ISSUE THREAD

**Issue by i10416** [scala-native/scala-native#3058]
I have not observed this behavior except Scala 3.2.1, but I suspect this can happen on Scala 2.x

**Comment by WojciechMazur** [comment]
Not sure if it's directly related, but in case if assertion are enabled Commix GC can fail with following errors: 
```
scala-native/gc/commix/datastructures/Bytemap.h:37: ObjectMeta *Bytemap_Get(Bytemap *, word_t *): Assertion `((word_t)address & ALLOCATION_ALIGNMENT_INVERSE_MASK) == (word_t)address' failed.
scala-native/gc/commix/Sweeper.c:637: void Sweeper_AssertIsConsistent(Heap *): Assertion `!BlockMeta_IsMarked(current)' failed.
```

By default C assertions  are disabled (also in CI, but we should change that). I assume that commix has removed/mutated some object and though lead to infinite loop
