### ISSUE TITLE
Scala Native project no longer compiles on FreeBSD

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3065]
A number of .c files fail to compile on FreeBSD when attempting to build the Scala Native project on FreeBSD (13.1).
I experience this on 0.5.0-SNAPSHOT but it is probably also true for recent 0.4.n versions.

To some extent, this is by design, as _Static_assert code has been put into a number of .c file to increase
confidence that the operating system structures & definitions match those expected by Scala Native.

I have recently spun up a FreeBSD system for building & testing Scala Native.  I hope to work my
way through the compilation issues and then work on getting the full SN test suite to pass.
The plan/hope is to then loop back and check/backport to 0.4.n.

Issues do not look hard, just time consuming & picky.

A Work In Progress list, to keep track of the players:
- [  ]  nativelib time_nano.c
- [  ]  javalib net/if_dl.c
- [  ]  posixlib unistd.c
- [  ]  posixlib times.c
- [  ]  posixlib wordexp.c

**Comment by LeeTibbert** [comment]
@ekrich re: time_nano.c

Remember the several cycles of fun you & we had with time_nano.c.  May I ask for your advice and/or
direction on another round? I'd appreciate it.

FreeBSD has not CLOCK_MONOTONIC_RAW.  I believe it has no pure CLOCK_MONOTONIC.  It does have
CLOCK_MONOTONIC_PRECISE & CLOCK_MONOTONIC_COARSE (sometimes typedef'ed to CLOCK_MONOTONIC).

Give the nature of time_nano.c, I believe that people using it are more interested in the results of the more expensive
CLOCK_MONOTONIC_PRECISE than the faster CLOCK_MONOTONIC_COARSE.

I propose to modify the time_nano.c code for FreeBSD to use CLOCK_MONOTONIC_PRECISE.  Linux, macOS, and
unknown would continue to use CLOCK_MONOTONIC_RAW.    Does this fit with & extend your original design & intent?

Thank you.

**Comment by ekrich** [comment]
@LeeTibbert I chose CLOCK_MONOTONIC_RAW because it doesn't adjust for time adjustments. It also seemed to have better resolution on macOS. I am ok with CLOCK_MONOTONIC because it is POSIX but I'll leave it in your hands to do the best thing. Maybe when you get FreeBSD working you can figure out a way to add it to CI.

**Comment by ekrich** [comment]
@LeeTibbert I also found this that you might find interesting.
https://github.com/vmactions/freebsd-vm
