### ISSUE TITLE
ExternTest now has getopt deprecation warning

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3068]
A placeholder so that I can complete the PR I am working on.

A recent (days,  a fortnight?) PR deprecated posixlib getopt (which is goodness).

unit-tests ExternTest seems to use getopt, a lot.  Now it is showing several 
deprecation messages.

Solution is given in the nice deprecation message: use unistd.  
Such a change will make the head version of ExternTest 0.5.0 only,
so we must be careful to _not_ backport the changed.

**Comment by i10416** [comment]
ref #3056

**Comment by LeeTibbert** [comment]
Fixed in PR #3075
