### ISSUE TITLE
Missing `Path.of` in javalib's `java.nio.file.Path` class

### ISSUE THREAD

**Issue by floating-cat** [scala-native/scala-native#3070]
There are two static `Path.of` methods added in the JDK 11 but not in Scala Native's javalib.
Two methods in JavaDoc are here:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Path.html#of(java.lang.String,java.lang.String...)
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Path.html#of(java.net.URI)

It seems we could delegate these methods to `Paths.of` or conversely which do the same thing.
These two methods were added because Java 11 supports the default method in the interface and these two methods are in a better namespace and maybe better names compared to `Paths.get`.

Also, see
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Paths.html
> It is recommended to obtain a Path via the Path.of methods instead of via the get methods defined in this class as this class may be deprecated in a future release.

**Comment by LeeTibbert** [comment]
@floating-cat Thank you for reporting this.

In general, the Scala Native javalib supports Java 8. Even for Java 8 there is much work to be
done to make the work complete. 

Many of us wish & and work towards a correct & reasonably complete Java 8 javalib.  

Someday a radical SN developer will suggest that SN move the baseline to Java 11.

There are a few Java 9 and above methods.  They have generally been contributed by community
members as Pull Requests (PRs).  If you would like to add these methods, there are members
of the Scala Native community, myself included, who would be glad to help you set up
a Scala Native build environment and guide you through the PR process.  

Unfortunately, the ReadTheDocs Contributor's Guide has fallen into extreme disrepair.  If
you have thoughts of doing a PR, please call out, here or on Discourse.
