### ISSUE TITLE
Missing `Files.writeString` in javalib's `java.nio.file.Files`

### ISSUE THREAD

**Issue by floating-cat** [scala-native/scala-native#3071]
There are two static `Path.writeString` methods added in the JDK 11 but not in Scala Native's javalib.
Two methods in JavaDoc are here:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Files.html#writeString(java.nio.file.Path,java.lang.CharSequence,java.nio.file.OpenOption...)

These methods are used to write string to a file directly which is two very convenience methods in the JDK:
```scala
Files.writeString(Paths.get("a_file"), "some_string")
```

**Comment by LeeTibbert** [comment]
See also Issue #3135, for the dual `readString()`.

I have fixes for `writeString()` & `readString()` in testing.  I need to ensure that I
get the handling of large strings reasonably right.

I have also implemented and am testing the Java 11 `transferTo()` method.
