### ISSUE TITLE
Missing `IntFunction` and much of the `java.util.function` package.

### ISSUE THREAD

**Issue by DamianReeves** [scala-native/scala-native#3092]
Scala Native is missing much of the `java.util.function` package. It appears this exists for ScalaJS: https://github.com/scala-js/scala-js/tree/main/javalib/src/main/scala/java/util/function.

**Comment by armanbilge** [comment]
I don't think we are missing the entire package, although probably quite a bit of it :)
https://github.com/scala-native/scala-native/tree/main/javalib/src/main/scala/java/util/function

**Comment by ekrich** [comment]
Note that Scala.js has this all implemented so the code and tests could be ported to Scala Native.

Code: https://github.com/scala-js/scala-js/tree/main/javalib/src/main/scala/java/util/function
Tests: https://github.com/scala-js/scala-js/tree/main/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/function

**Comment by DamianReeves** [comment]
I see you tempting me to pick this one up @ekrich 😄

**Comment by DamianReeves** [comment]
> don't think we are missing the entire package, although probably quite a bit of it :)

Updated the title and description to reflect that oversight.

**Comment by ekrich** [comment]
Scala.js is tight so porting is actually fun, but I wanted to give someone not too familiar a head start.

**Comment by DamianReeves** [comment]
Is this the sort of thing where a PR implementing some of the parts would be accepted?
