### ISSUE TITLE
Typelevel Cats Application Throws scala.scalanative.runtime.UndefinedBehaviorError At Runtime in IntelliJ 2022.3

### ISSUE THREAD

**Issue by sshark** [scala-native/scala-native#3093]
I am using this https://typelevel.org/cats-effect/docs/core/scala-native as my guide but I am using Scala Native plugin v0.4.9 instead because of the compilation error. My project runs fine with GraavlVM JDK 11 and 17 on top of Windows 11. 
```
// build.sbt
sbt.version = 1.6.2

// plugins.sbt
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.9")

// build.sbt
ThisBuild / scalaVersion := "3.2.1"

lazy val ixSqrNative = project
  .in(file("."))
  .enablePlugins(ScalaNativePlugin)
  .settings(
    Compile / mainClass := Some("org.acme.Main"),
    name                := "cats-native",
    libraryDependencies ++= Seq(
      "org.typelevel" %%% "cats-effect" % "3.4.4"
    )
  )

// Main.scala
package org.acme

import cats.effect.{IO, IOApp}

object CatsMain extends IOApp.Simple {
  override def run: IO[Unit] = IO.println("Hello, World!")
}
```

Everything runs fine with `sbt run`.  A `.exe` file is generated and it runs without a hitch in the command line. Everything is fine. What is wrong is, it throws `UndefinedBehaviorError` when I execute this project in IntelliJ IDEA 2022.3.2 Preview (Community Edition) Build #IC-223.8617.9, built on January 11, 2023. 

```
Exception in thread "main" scala.scalanative.runtime.UndefinedBehaviorError
    at scala.scalanative.runtime.package$.throwUndefined(package.scala:80)
    at scala.scalanative.runtime.package$.intrinsic(package.scala:26)
    at scala.scalanative.unsafe.package$.extern(package.scala:107)
    at scala.scalanative.runtime.Platform$.SizeOfWChar(Platform.scala:40)
    at scala.scalanative.unsafe.package$.<clinit>(package.scala:179)
    at scala.scalanative.meta.LinktimeInfo$.debugMode(LinktimeInfo.scala:10)
    at cats.effect.tracing.TracingPlatform.calculateTracingEvent(TracingPlatform.scala:30)
    at cats.effect.IO$.async(IO.scala:1121)
    at cats.effect.IO$$anon$2.async(IO.scala:1610)
    at cats.effect.IO$$anon$2.async(IO.scala:1609)
    at cats.effect.kernel.Async.never(Async.scala:102)
    at cats.effect.kernel.Async.never$(Async.scala:62)
    at cats.effect.IO$$anon$2.never(IO.scala:1606)
    at cats.effect.IO$.<clinit>(IO.scala:1797)
    at cats.effect.IOApp.main(IOApp.scala:220)
    at cats.effect.IOApp.main$(IOApp.scala:143)
...
```

I come across https://scala-native.org/en/v0.4.9/contrib/ides.html# but I could not find anything related to my IntelliJ project. Is there any setting I have missed? I observe the same exception in Linux too. Thanks

**Comment by armanbilge** [comment]
Actually you are not running a native binary here, but you are attempting to run the `.class` files that Scala Native produces in a JVM, which is obviously impossible. I can tell because there are line numbers in the stack trace, and in fact line numbers are currently not supported.

I am not sure if it is possible to run a Native binary from IntelliJ.

**Comment by sshark** [comment]
I suppose we can only run `.class` in IntelliJ and the same goes with `sbt run`. I could be wrong. That aside, I can run this example in IntelliJ, SBT, and as a native app. Why does CatsMain throw an exception when it is executed in IntelliJ?

```
object Main  {
  def main(args: Array[String]): Unit = println("hello ordinary world")
}
```

**Comment by armanbilge** [comment]
> and the same goes with `sbt run`

`sbt run` will run a Native binary (not `.class` files) because the Scala Native sbt plugin modifies its behavior to support this usecase. However, Intellij does not know about this.

---

> That aside, I can run this example in IntelliJ, SBT, and as a native app

Are you _sure_ it's running as a Native App in Intellij? It's not using any Scala Native features, so it's probably just running as an ordinary classfile.

Try this one instead:

```scala
import scala.scalanative.unsafe._

object Main  {
  def main(args: Array[String]): Unit = println(fromCString(c"hello ordinary world"))
}
```

**Comment by sshark** [comment]
I am getting what you are saying. Scala Native apps should run as an OS platform native app all the time. Before this discussion, I thought it is like GraalVM native where class files are generated and used/executed unless the native compilation option is set.
Btw, `import scala.scalanative.unsafe._` does not have any effect, it is grayed out in IntelliJ and I can still run `object Main` in IntelliJ and SBT.

**Comment by armanbilge** [comment]
> Btw, `import scala.scalanative.unsafe._` does not have any effect, it is grayed out in IntelliJ and I can still run `object Main` in IntelliJ and SBT.

Did you change the definition of `main` to use `fromCString` ?

**Comment by sshark** [comment]
No, I didn't. 

When I did I get this exception,
```
Exception in thread "main" scala.scalanative.runtime.UndefinedBehaviorError
	at scala.scalanative.runtime.package$.throwUndefined(package.scala:80)
	at scala.scalanative.runtime.package$.intrinsic(package.scala:26)
	at scala.scalanative.unsafe.package$.extern(package.scala:107)
	at scala.scalanative.runtime.Platform$.SizeOfWChar(Platform.scala:40)
	at scala.scalanative.unsafe.package$.<clinit>(package.scala:179)
	at org.teckhooi.fake.Main$.main(Main.scala:6)
	at org.teckhooi.fake.Main.main(Main.scala)
```

**Comment by armanbilge** [comment]
> Scala Native apps should run as an OS platform native app all the time. Before this discussion, I thought it is like GraalVM native where class files are generated and used/executed unless the native compilation option is set.

Right, exactly! Unlike GraalVM Native, Scala Native provides direct interop with C libraries, which is impossible to support from a JVM. That's why if you using these special Native interop features, and try to run the classfiles in a JVM, you get undefined behavior exceptions.

**Comment by sshark** [comment]
Thank you for the explanation that set me in the right direction. I guess Cats lib has the Native feature (like the example you showed me) set inside its code.

**Comment by armanbilge** [comment]
> I guess Cats lib has the Native feature (like the example you showed me) set inside its code.

Yes, exactly. Cats Effect Native is specially designed and optimized for the Native runtime, so it uses Native features when possible.
