### ISSUE TITLE
Initial java.io support

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#311]
Here is a list of classes we want to support soon:
- [ ] java.io.BufferedInputStream
- [ ] java.io.BufferedOutputStream
- [ ] java.io.BufferedReader
- [ ] java.io.File
- [ ] java.io.FileFilter
- [ ] java.io.FileInputStream
- [ ] java.io.FileOutputStream
- [ ] java.io.InputStream
- [ ] java.io.OutputStream
- [ ] java.io.PrintStream
- [ ] java.io.PrintWriter
- [ ] java.io.Reader
- [ ] java.io.Writer

**Comment by sjrd** [comment]
Note that a bunch of those already available in Scala.js, in https://github.com/scala-js/scala-js/tree/master/javalib/src/main/scala/java/io

* `BufferedReader`
* `InputStream`
* `OutputStream`
* `PrintStream`
* `PrintWriter`
* `Reader`
* `Writer`

The following would be nice to have in Scala.js as well, so if you're working on them, contributions to Scala.js are welcome: :)

* `BufferedInputStream`
* `BufferedOutputStream`

**Comment by densh** [comment]
Yep, some of those are already done. 👍 

That's just a list of things of things that @cedricviaccoz will be looking at.

**Comment by densh** [comment]
Superseded by #572
