### ISSUE TITLE
LLVM 15 breaks test-tools

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3161]
LTO=thin, release-fast problems on macOS are, in some circles, well known to exist.
I report this again because the "opaque pointer removal" issue seems to be bigger than a breadbox.
Especially since "eh.cpp" comes from an external source.

Here I was seeing if the problems in year old Issue #2212 still exists in order to see if I 
could make progress on it/them and/or other Issues.

This particular run is on SN 0.5.0-SNAPSHOT, macOS (latest, 16?), M1 hardware , LTO=thin, release-fast.

I have seen this before. This time I was able to capture it.

Starting at LLVM V13.0, that group has been moving to deprecate and then disable opaque pointers.
LLVM 15.0 gives this error.  I thnk -opaque-pointers mode goes away with LLVM 16.0.

I have not seen this error using either LLVM 15 or 16 with test-runtime or test-scripted.

```
[info] Compiling to native code (2520 ms)
[error] ThinLTO: /Volumes/AngelGSdd1/lee49/DevoSdd1/ScalaNative/WorkSpace_1/2023/study_macos_testToolsFailure_I2212_2023-02-11T1820-0500/test-interface/.3/target/scala-3.2.1/native-test/native-code-nativelib_native0.5.0-SNAPSHOT_3-0.5.0-SNAPSHOT-0/scala-native/eh.cpp.o17: error: 
Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.7' Reader: 'LLVM 15.0.7')
[error] LLVM ERROR: Can't load module, abort.
```
###### Background information

test-runtime executes to completion  but the test harness does not display if LTO & releaseFast are
actually being used. Terse to the point of useless.

Note: CharSetTest fails with extra "default" Charset reported by system.

test-scripted fails in a different way, just to try my patience.  I believe the failure is because of
the Java version I am using (Java 19). When/If I recover my humor, I might try Java 8.

**Comment by LeeTibbert** [comment]
Obviously the trivial solutions are "Don't use LLVM > 13.0" and "Don't use LTO=thin"

**Comment by WojciechMazur** [comment]
Since LLVM 15 opaque pointers are default, but typed pointers are still supported, in the future versions (16 or 17) the typed pointers will no longer be supported. 
The solution might require detecting the used version of LLVM and compiling it with an additional `-opaque-pointers` flag. Later it should also involve changes to our codegen to use opaque pointers.

**Comment by LeeTibbert** [comment]
Wojciech,

Thank you for fixing this.  From looking at the PR, it looks like the fix was more than
a few lines of code.  I appreciate your time & expertise.

**Comment by LeeTibbert** [comment]
A data point.
After this PR the case (test-tools) where it had been broken before is now working using most recent (daily) LLVM 16 .
   
The expected result, given the CI runs, but I hope confirmation helps.  

Now I have to find something else to break.
