### ISSUE TITLE
javalib Files.newDirectoryStream fails with empty Path.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3163]
Whilst being thrashed trying to fix Issue #2937, I discovered a problem with `Files.newDirectoryStream()`.

The following file returns "Found: List()" on Scala JVM,. 
On Scala Native 0.5.x, it throws an exception (NoSuchFileException??).

```
import java.nio.file.{Files, Paths}
import scala.jdk.CollectionConverters._

object Main {
  def main(args: Array[String]): Unit = {
    val files = Files.newDirectoryStream(Paths.get(""), "*.sbt").iterator().asScala.toList
    println(s"Found: $files")
  }
}
```

My thanks to iRevive for the code snippet in Issue #2937.

Once again down the Rabbit Hole, dear friends, once more.

**Comment by ekrich** [comment]
Should it be `Paths.get(".")`?

**Comment by LeeTibbert** [comment]
@ekrich 
Welcome to my nightmare.   Or another way, "Want to share the fun?"   I have taken 
quite a tour in what looked like a simple fix and sunk many an hour.

The Java 8 documentation, (I think it a mumble  FileSystem .getPath() section) describes the
empty path ("") as referring, in an OS specific manner, to the current working directory.
So, `""` is legitimate, in the Java world.

As mentioned in the base note, Scala JVM (macOS M1) accepts the snippet
and produces expected results: empty where it should be empty and a list
of items where it should have them.

The place where it gets wierd, for me, is that 
`Files.newDirectoryStream(Paths.get("."), "./*.sbt")`
does not match on JVM, even though the DirectoryStream
returns values relative to the "." path and of the form "./foo.sbt".
If I pretzel my brain long enough, the glob failure makes sense.
Sense or not, it is what the JVM does (and as SN will soon do).

**Comment by LeeTibbert** [comment]
Later, Re:
```
The place where it gets weird, for me, is that
Files.newDirectoryStream(Paths.get("."), "./*.sbt")
does not match on JVM
```

I think what is happening is that the "." in get(".") is being
normalized to "", and then regex is comparing "" with "./*.sbt".
The initial path elements now do not match (i.e. no "" to "./" 
retry).  Guess this made sense to somebody, sometime.
For now, my concern/goal is that SN match JVM and
that I never get asked this as an interview question
or by some bright eyed peer who thinks I know what
I am doing.
