### ISSUE TITLE
Build: echoing value of nativeConfig multithreadSupport used

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3174]
Another indication of  maturing multithread support.

As part of initial work on some JSR-166 files, I am trying convince myself that 
`multithreadingSupport`  is being used at each stage of a SN build. 

Currently SN compiler clearly indicates/echos  the Mode, LTO, GC 
configuration variables. It would be nice if the multithreadingSupport
value were also given.   This would give an audit trail.

Currently I am using private code to do this and it has increased
my confidence that multithreading is being used. (Before some
private hackery, it was not.  A PR in waiting, if it proves out 
after exercising it for a week or so).

I could contribute (improvements to) my private  as a PR.  Easier to do that
than maintain it out-of-tree.

I believe this feature  would make it easier for SN devos, users, & maintainers to 
establish exactly the configuration with which they are working.

```
[info] Linking (multithread true) (10256 ms)
[info] Checking intermediate code (2678 ms)
[info] Dumping intermediate code (linked) (6584 ms)
[info] Discovered 9756 classes and 55480 methods
[info] Optimizing (debug mode) (23901 ms)
[info] Checking intermediate code (2202 ms)
[info] Dumping intermediate code (optimized) (8290 ms)
[info] Dumping intermediate code (lowered) (13761 ms)
[info] Generating intermediate code (35790 ms)
<elided>
[info] Produced 136 files
[info] Compiling to native code (29966 ms)
[info] Linking native code (immix gc, none lto) (417 ms)
```

**Comment by armanbilge** [comment]
👍 I would find this useful as well.
