### ISSUE TITLE
git branch "relese/0.4.13" has a typo

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3305]
I am reporting this because it is the kind of thing which tends to propagate
further down the build chain, growing stronger, and then escape into the wild,
causing confusion.

**Comment by WojciechMazur** [comment]
Branch was merged and deleted. I would try to not make anymore typos in the future

**Comment by LeeTibbert** [comment]
@WojciechMazur  

re:  I would try to not make anymore typos in the future

There are far greater defects than typos.  I know, I have created 
many of both and you have kindly corrected both in passing.

I pointed it out, as a supporting second line of editing, not to be picky because 
we, the greater effort, are dealing with  "International English".

L.  -- off to make hopefully more good than defect.
