### ISSUE TITLE
Document void* equivalent 

### ISSUE THREAD

**Issue by tindzk** [scala-native/scala-native#331]
Scala's pointer arithmetic does not behave the same way as in C:

``` scala
val voidPtr: Ptr[_]     = null
val charPtr: Ptr[CChar] = null

printf(c"voidPtr = %i\n", voidPtr + 1)
printf(c"charPtr = %i\n", charPtr + 1)
```

``` bash
voidPtr = 8
charPtr = 1
```

vs.

``` c
void *voidPtr = NULL;
char *charPtr = NULL;
printf("voidPtr = %i\n", voidPtr + 1);
printf("charPtr = %i\n", charPtr + 1);
```

``` bash
voidPtr = 1
charPtr = 1
```

**Comment by densh** [comment]
Good find @tindzk, thanks for the report!

**Comment by densh** [comment]
While this is surprising coming from C background, the semantics is correct here. sizeof[_] is 8 bytes, this is due to the fact that the universal type is pointer-sized in Scala, and that's the correct increment given the invariant of `(ptr: Ptr[T]) + 1` being the same as `(ptr: Ptr[T]).cast[Ptr[Byte]] + 1 * sizeof[T]`.

**Comment by tindzk** [comment]
I see. In that case, the bindings should not return `Ptr[_]` as an equivalent for C's `void` pointer. For example, pointer arithmetic behaves differently on `stdlib.malloc(1024)` than in C.

We also need to mention it in the manual to prevent confusion. Perhaps something similar to https://www.scala-js.org/doc/interoperability/types.html?

**Comment by densh** [comment]
Indeed, `Ptr[Byte]` is a better equivalent for `void*`. I've reopened this issue to make sure we update our bindings & document this.

**Comment by densh** [comment]
`void* <-> Ptr[Byte]` equivalence is now mentioned in the updated interop docs in #472.

**Comment by tindzk** [comment]
Thanks!
