### ISSUE TITLE
Support for arrays in structs

### ISSUE THREAD

**Issue by tindzk** [scala-native/scala-native#332]
I would like to use array members in structs. The length probably needs to be expressed as a separate type parameter, e.g. using Shapeless natural numbers:

```scala
  @struct class FileEntry(val inode: CUnsignedLong,
                          val offset: CUnsignedLong,
                          val entrySize: CUnsignedShort,
                          val name: CArray[CChar, _0])  // char[]
```

Right now, it is quite inconvenient to access `name`, requiring pointer arithmetic.

We need to ensure that such a variable-length array can only be the last member in the struct declaration.

See also https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html

**Comment by densh** [comment]
Yep, we definitely want that. But the issue itself is duplicate wrt #35
