### ISSUE TITLE
CI doc build contains a warning

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3321]
"Come with the dust, but not gone with the wind.", with apology to W. Guthrie.

Adding building the documentation as a CI run is, IMO, a welcome improvement.

While looking for the causes of broken CI runs in my own PR candidates, I noticed
that the doc CI gives the warning.

```

build-docs
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

```

I followed the provided link. TL; DR - We should upgrade the .yml to use actions/checkout@v3 across the board.
Can anyone think or have reason to believe that we should not?

If I do not hear any objections in the next short while (days), I will take a run in my free time. First changing the 
doc .yml. If that succeeds, I'll check the other .yml files to see what they are using.

Later:  I just checked and the doc .yml is the only one using `checkout@v2` all the rest use `checkout@v3`.
            So I am just going to PR now.

**Comment by WojciechMazur** [comment]
Fixed by #3322
