### ISSUE TITLE
Cannot store UInt value in Option

### ISSUE THREAD

**Issue by tindzk** [scala-native/scala-native#333]
The following program does not compile:

```scala
import scala.scalanative.native._

object Main {
  def main(args: Array[String]): Unit =
    Some(42.toUInt)
}
```
```
Unresolved dependencies:
  `@java.lang.Integer$::toUnsignedString_i32_class.java.lang.String`
```

I am curious as to why it works without the `Some` call. Also, why does it try to convert the number to a string in the first place?

**Comment by densh** [comment]
Linking is quite conservative at the moment, and it often over-approximates the methods that are needed. The root cause for this is https://github.com/scala-native/scala-native/issues/242
