### ISSUE TITLE
Support java.util.StringJoiner

### ISSUE THREAD

**Issue by He-Pin** [scala-native/scala-native#3355]
refs: https://github.com/scala-js/scala-js/issues/4872

**Comment by LeeTibbert** [comment]
To anybody who picks this up, let me mention a couple of conventions which to ease the learning
rampup.

1) The hardest part of a PR is probably adding the class to `javalib.rst` and doing a trial build
     of the documentation.  CI will now do a proof build (my humble thanks to the person or people
     who recently implemented that).

2) It is incredibly useful to put a one line comment at the top of each ported file saying something
    like this like from `TreeMapTest.scala` `// Ported from Scala.js commit def516f dated: 2023-01-22.`
    Sadly, different developers use different date formats. The commit id and commit date are 
   __incredibly_ useful when one has to go back and figure out if the SN and scala-js versions 
   correspond. This is especially true if there have been SN additions. 

   Hacking is easy, Software Engineering is hard.

**Comment by LeeTibbert** [comment]
Kerr,  What is your timeframe/hope for this?   Is it something you need/would_like for 0.4.next?

The reason that I ask is if there is no urgency, it is, as Armand tagged, a great first issue if
here is someone looking for an easier entry to Scala Native development. It might be useful
to let this sit for two weeks or so to see if anybody expresses an interest.

Make sense?

BTW, thank you for pointing out the availability in scala.js.

**Comment by He-Pin** [comment]
COOL, LET'S leave this and see if someone interested.

**Comment by LeeTibbert** [comment]
Good low hanging fruit to reward the eager, but fruit should not be left to rot... Good plan.
