### ISSUE TITLE
UUID comparison doesn't match JVM

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#3393]
Copying from https://github.com/scala-js/scala-js/issues/4882

TL;DR from the upstream - it's a JVM bug: https://bugs.openjdk.org/browse/JDK-7025832, question is whether to maintain compliance with spec, or parity with JVM.

Repro:

```scala
//> using dep org.scalameta::munit::1.0.0-M8

import munit.FunSuite

import java.util.UUID

class UUIDSuite extends FunSuite {

  test("v0 UUID should be less than v1 UUID") {
    val v0 = UUID.fromString("1ee23e57-7fff-6490-8018-c46dfbd6cdf7")
    val v1 = UUID.fromString("1ee23e57-8001-6ba0-8000-824f2f22b333")

    assertEquals(v0.compareTo(v1), -1)
  }

}
```

With scala-cli run `scala-cli test test.scala --native`

**Comment by LeeTibbert** [comment]
* I think the overall question is: Who is impacted by this issue?    Is somebody waiting at real time
   or is it a lack of perfection which should be expunged at the earliest convenience.

* From reading the several pointers kindly provided, including the Scala.js discussion but closing my
eyes to avoid looking at OpenJDK code in the Java bug report, my suggestion is that Scala Native should
hunker down until the Scala.js devos make a decision and then follow that. Pretty craven, but time effective.

Give the years-old "will not fix" in the JDK bug tracker, I suspect the decision will be to follow what the
JDK actually implements. That and $10 will get you a (small) cup of coffee.

**Comment by ekrich** [comment]
This can now be ported from Scala.js - https://github.com/scala-js/scala-js/pull/4884
