### ISSUE TITLE
Can we provide a friendlier default handler for unhandled exceptions?

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#3418]
Seems like if you have an exception thrown while rendering another exception, you get a pretty scary C++ ABI error.

Consider this:

```scala
case class MyErr(msg: String) extends Exception:
  override def toString() = msg(0) + "!"

@main def hello = 
  throw MyErr("")
```

See the difference between JVM and Native:

```
$ scli run .
Exception in thread "main"
Exception: java.lang.StringIndexOutOfBoundsException thrown from the UncaughtExceptionHandler in thread "main"

$ scli run . --native
libc++abi: terminating due to uncaught exception of type scalanative::ExceptionWrapper: std::exception
fish: Job 1, 'scala-cli $argv' terminated by signal SIGABRT (Abort)
```

Note how there's at least _some_ clue in JVM version as to what the original exception was

**Comment by WojciechMazur** [comment]
For the 0.5.x series we should be able to use default Thread.uncoughtExceptionHandler, which later can be also customized. I'll try to adjust the generated main to allow for that
