### ISSUE TITLE
BoxingElimination became non-local due to implicit block refactoring

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#342]
Now it produces code that uses values that might not be defined yet:

```
alwaysinline def @java.util.Arrays$::java$util$Arrays$$checkRangeIndices_i32_i32_i32_unit : (module @java.util.Arrays$, i32, i32, i32) => unit {
  ...
  %src.5:
    ...
    %src.21 = call[(module @scala.runtime.BoxesRunTime$, i32) => class @java.lang.Integer] @scala.runtime.BoxesRunTime$::boxToInteger_i32_class.java.lang.Integer(%src.20: module @scala.runtime.BoxesRunTime$, %src.3: i32)
    ...
    throw %src.9: class @java.lang.IllegalArgumentException
  %src.42:
    ...
    %src.50 = copy %src.21: class @java.lang.Integer
    ...
    throw %src.46: class @java.lang.ArrayIndexOutOfBoundsException
  ...
}
```

As discovered by @hkapp

**Comment by densh** [comment]
As we've discussed today there are two possible fixes for this: 

1. Easy one is to use CFG and make it work on one basic block at a time as before. 
2. Harder one is to use dominator tree to that @hkapp is currently working on to make it properly non-local.

**Comment by hkapp** [comment]
The dominator tree version is working, so we can go with that. The solution is really simple. I'll create the PR as soon as the dominator tree PR is merged.

**Comment by densh** [comment]
@hkapp Fantastic!

**Comment by densh** [comment]
Dominator tree implementation has just been merged.
