### ISSUE TITLE
Random Scala stdlib Resources bundled in every executable

### ISSUE THREAD

**Issue by TonioGela** [scala-native/scala-native#3433]
Hello!
I just noticed that in every executable that bundles resources a bunch of files are always present, in particular, if you run this MRE (after creating a `foo` empty folder):

```scala
//> using scala 3.3.0
//> using platform native
//> using nativeVersion 0.4.14
//> using resourceDir ./foo

object Main extends App:

  List(
    "/LICENSE",
    "/NOTICE",
    "/library.properties",
    "/rootdoc.txt",
    "/META-INF/MANIFEST.MF"
  ).foreach(res =>
    val array = getClass().getResourceAsStream(res).readAllBytes()
    val string = new String(array)
    println(s"$res\n\n$string")
  )

end Main
```

These lines will always be logged during compilation:

```
[info] Embedded resource: /LICENSE
[info] Embedded resource: /NOTICE
[info] Embedded resource: /library.properties
[info] Embedded resource: /rootdoc.txt
[info] Embedded resource: /META-INF/MANIFEST.MF
```

and the example prints out the text of these always-embedded resources.

In particular the files seems to be:
- [rootdoc.txt](https://github.com/scala/scala/blob/2.13.x/src/library/rootdoc.txt)
- [NOTICE](https://github.com/scala/scala/blob/2.13.x/NOTICE)
- [LICENSE](https://github.com/scala/scala/blob/2.13.x/LICENSE)
- library.properties is mentioned [here](https://github.com/scala/scala/blob/2.13.x/src/library/scala/util/Properties.scala#L20)
- MANIFEST.MF has sense to exists as it's mentioned [here](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/util/ClassPath.scala#L191)

I understand that this issue might be more Scala 2.13 std-lib related, but I thought it was worth mentioning it here.

Also, I scavenged the doc and the code, but I haven't found a way to ignore some classpath resources, does it exists?

**Comment by LeeTibbert** [comment]
@TonioGela 

Please help me understand this Issue. The limits are at my end, not yours?

1) What do you mean the "MRE" acronym? Probably not the "Meal, ready to eat" expansion
     with which I am familiar?

2) By "Random" do you mean "Arbitrary", "Unexpected", truly Random, or some combination?

3) Scala has a `stdlib`???

4) Are those files or names in the actual binary executable or somewhere in the 
     project directory or .scala-build directory?

Making guesses at the answers to the above (with respect for "beginner's mind", starting 
from a lack of understanding is almost always a poor idea), I am trying to determine, in
my mind, if what you are seeing is coming from scala-cli or from some phase in the
scalanative build.

Thank you for bearing with & reducing my lack of understanding.

**Comment by TonioGela** [comment]
Hi Lee, here are my answers

> 1. What do you mean the "MRE" acronym? Probably not the "Meal, ready to eat" expansioν with which I am familiar?

Minimal Reproducible example, if you run it, you'll experience the same issue I'm having.

> 2. By "Random" do you mean "Arbitrary", "Unexpected", truly Random, or some combination? You seem to imply that the set of files is reproducible, implying "Unexpected"

Yep, "Unexpected" or "Unrelated to the current build or project". I haven't manually brought that files into the build.

> 3. Scala has a `stdlib`???

With `stdlib` I mean the Scala jar that (when packaging a JVM app) is necessary to run the application. I usually call it `stdlib`, I don't know if it's the correct name.

> 4. Are those files or names in the actual binary executable or somewhere in the project directory or .scala-build directory?

The files will end up in the final binary (in EVERY final binary in fact), and the issue is not `scala-cli` related, as I'm experiencing the same issue even when packaging using sbt.

Actually, I noticed that it happens that other libraries bring some random files with them (something in the Typelevel Stack brings a `CONTRIBUTING` file into the classpath for example).

To the best of my understanding, the issue might simply be that [here](https://github.com/scala-native/scala-native/blob/main/tools/src/main/scala/scala/scalanative/codegen/ResourceEmbedder.scala#L36) in the `ResourceEmbedder`, all the classpath's resources are scanned and added to the final binary. 

I'm not saying that is a mistake of course, but probably having a way to ignore some classpath resources will be handy in this situation.

**Comment by TonioGela** [comment]
> Have you brought this up in the scala-cli discord to see what they say?

I haven't, but just because it happens even using sbt and scala native 👉👈

**Comment by ekrich** [comment]
Right, right, sorry. These are in the Scala stdlib and other places. We will just have to decide the best path for each item added. We already exclude the `resources/scala-native` dir.

**Comment by tanishiking** [comment]
Would allowing scala-native to configure which files to exclude by regex be a first step to improve the situation?

**Comment by TonioGela** [comment]
> Would allowing scala-native to configure which files to exclude by regex be a first step to improve the situation?

IMHO yes, but I'll prefer to have 2 conpiler/linker options: a regex to include and a regex to exclude resources, mutually exclusive. In this way it will be more usable.

**Comment by ekrich** [comment]
Right now it includes everything except the special `scala-native` directory which should be excluded. Seems to me just excluding should cover the use case. I think a list of glob patterns would be easier for the user.

Maybe using PathMatcher but maybe that won't work with virtual directories.
https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-

The user would also have to be careful excluding because some library could need the file included in resources.

**Comment by WojciechMazur** [comment]
I think resources embedding should be opt-in, not opt-out. So I'm mostly in favour of include filters, possibly via glob filters. If there would be exclude filters they should be applied after include filter.

**Comment by ekrich** [comment]
But are you considering the fact that these get included at link time and maybe a dependency has embedded configuration that shouldn't be removed? 

Also, with the principle of least surprises, including everything doesn't kill the executable, it just makes it fat. As an example, I am working on the config library Native so it can read embedded configuration like the JVM version and it can read `.conf`, `.properties`, and `.json` just with the default `load` call. Hopefully, this will be used by Pekko Native. Akka has default configuration included so I assume Pekko will have it as well. With this plan you would have to include all these.

IMHO it is better to remove files you know not to need rather trying to figure out what files may be needed. We can always inform upstream dependencies on files that show up. Perhaps they could put stuff in `META_INF` and we could ignore that as well.

**Comment by WojciechMazur** [comment]
I agree about the default. It probably would be best when empty list of include patterns would simple behave as include all and would print a warning about its behaviour. Then it can be explicitly silenced by usage of `.*` or other include all pattern. 
This way we can both easy start for beginners and better control for experts. 
For the usage of resources embedded by dependencies we can add log-once warnings in `Class.getResourceAsStream` when some file is not found. This should ease the debugging. 

> IMHO it is better to remove files you know not to need rather trying to figure out what files may be needed 

As we all know, everybody has it's own preferences. When going with 2 filters - include (with include when empty) + exclude, we should be able to satisfy both camps of opt-in and opt-out.

**Comment by LeeTibbert** [comment]
The overall idea of getting rid of arbitrary junk in every executable is worthy.  Some
advanced regex test stuff is getting included. I have been trying to find the time for a year now
to eliminate it.  I spend a _lot_ of time watching & reading SN build logs, and it gouges my
eyes each and every time I see it.

> Would allowing scala-native to configure which files to exclude by regex be a first step to improve the situation?

Let me add weight to  @WojciechMazur suggestion of `glob` over regex here.  `glob` works in file situations,
where regex is for general pattern matching.

There are slight but significant differences.
I.e. ever wonder why "rm 1*" will remove the file "1A" but not the file "A"
when most regexen implemetations would match both?   Most globen take "*" to mean "1 or more occurence",
most regexen take it to mean "0 or more".

**Comment by LeeTibbert** [comment]
IIRC, scalafmt originally used regex and changed, 2 year ago or so, to glob.  A lot of file-type things
started working as expected.

I think I checked once and the javalib implementation of `glob` is different and necessarily different
from the posixlib specification of `glob`.  So one must be careful of which glob one is using.
Scala Native build code _should_ naturally end up using either JVM or javalib glob, but it is
also worthwhile to know that a path to much unhappiness exists and is all too easy to take.

**Comment by tanishiking** [comment]
I am embarrassed to say that I did not have a clear distinction between the glob pattern and regex and said regex 🤣 , but I also think it is better to provide the glob pattern for specifying file patterns, as you have said.

> When going with 2 filters - include (with include when empty) + exclude, we should be able to satisfy both camps of opt-in and opt-out.
As @WojciechMazur mentioned, let's go with two filters (include + exclude) with glob pattern 👍 

> I think I checked once and the javalib implementation of glob is different and necessarily different
from the posixlib specification of glob. So one must be careful of which glob one is using.

Thanks @LeeTibbert I'll double check the difference prior to work on it.
