### ISSUE TITLE
`UnixProcessGen2.waitFor` returns pid instead of exit code on MacOS Arm64

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#3452]
A bug discovered in #2156, `waitFor` returned pid instead of exit code (which was equal to 0) 
I'm not sure if this bug is also present on other platforms 
https://github.com/ekrich/scala-native/blob/a44baf676c5511bb2049eb359ab76b9a7b15cfe7/tools/src/test/scala/scala/scalanative/NIRCompiler.scala#L149-L151

**Comment by LeeTibbert** [comment]
@WojciechMazur 

Thank you for reporting this defect. Sorry that it took your time and that of @ekrich.

From inspecting the code & running OS tests, my ~~blunder~~ oversight is independent
of OS and architecture.  I removed those labels and suggest that they also be removed 
from the title.
