### ISSUE TITLE
Regex bug?

### ISSUE THREAD

**Issue by pablf** [scala-native/scala-native#3460]
When implementing support for `zio-json`, I've found the following bug while testing. It would seem that it comes from the implementation of the Parser, either because there is something not implemented or because it uses a different convention. The same test for the JVM and scalajs passes without problems. 

Problematic code in `zio-json/shared/src/test/scala/zio/json/CodecSpec.scala`:
```
str
  .split("(?=\\p{Upper})")
  .map(part => s"${part.head.toLower}${part.substring(1, part.length).toUpperCase}")
  .mkString
```

Stacktrace:
```
- key transformation
      ✗ ERROR: java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?=\p{Upper})
  ^
        java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)
        java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)
        scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        java.lang.StackTrace$.currentStackTrace(Unknown Source)
        java.lang.Throwable.fillInStackTrace(Unknown Source)
        scala.scalanative.regex.Parser.parsePerlFlags(Unknown Source)
        scala.scalanative.regex.Parser.scala$scalanative$regex$Parser$$parseInternal(Unknown Source)
        scala.scalanative.regex.Parser$.parse(Unknown Source)
        scala.scalanative.regex.RE2$.compileImpl(Unknown Source)
        scala.scalanative.regex.Pattern$.compile(Unknown Source)
        scala.scalanative.regex.Pattern$.compile(Unknown Source)
        java.util.regex.Pattern$.compile(Unknown Source)
        java.util.regex.Pattern$.compile(Unknown Source)
        java.lang.String.split(Unknown Source)
        java.lang.String.split(Unknown Source)
        testzio.json.CodecSpec$exampletransformkeys$Custom$.indianaJonesCase(Unknown Source)
        testzio.json.CodecSpec$exampletransformkeys$Custom$$anon$25$$anonfun$$lessinit$greater$1.apply(Unknown Source)
        testzio.json.CodecSpec$exampletransformkeys$Custom$$anon$25$$anonfun$$lessinit$greater$1.apply(Unknown Source)
        zio.json.CustomCase.apply(Unknown Source)
        zio.json.CustomCase.apply(Unknown Source)
        zio.json.DeriveJsonEncoder$$anon$6.$anonfun$names$2(Unknown Source)
        zio.json.DeriveJsonEncoder$$anon$6$$Lambda$5.apply(Unknown Source)
        scala.Option.getOrElse(Unknown Source)
        zio.json.DeriveJsonEncoder$$anon$6.$anonfun$names$1(Unknown Source)
        zio.json.DeriveJsonEncoder$$anon$6$$Lambda$14.apply(Unknown Source)
        scala.collection.TraversableLike.$anonfun$map$1(Unknown Source)
        scala.collection.TraversableLike$$Lambda$2.apply(Unknown Source)
        scala.collection.IndexedSeqOptimized.foreach(Unknown Source)
        scala.collection.mutable.ArrayOps$ofRef.foreach(Unknown Source)
        scala.collection.TraversableLike.map(Unknown Source)
        scala.collection.mutable.ArrayOps$ofRef.map(Unknown Source)
        zio.json.DeriveJsonEncoder$.join(Unknown Source)
        testzio.json.CodecSpec$exampletransformkeys$Custom$.<init>(Unknown Source)
        <none>._SM51testzio.json.CodecSpec$exampletransformkeys$Custom$G4load(Unknown Source)
        testzio.json.CodecSpec$.$anonfun$spec$38(Unknown Source)
        testzio.json.CodecSpec$$$Lambda$28.apply(Unknown Source)
        zio.test.Assertion$.value0$lzycompute$1(Unknown Source)
        zio.test.Assertion$.value0$1(Unknown Source)
        zio.test.Assertion$.$anonfun$smartAssert$3(Unknown Source)
        zio.test.Assertion$$$Lambda$2.apply(Unknown Source)
      indianaJones.fromJson[Custom] did not satisfy isRight(equalTo(Custom("")))
      indianaJones.fromJson[Custom] = java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
      (?=\p{Upper})
        ^
      at /home/runner/work/zio-json/zio-json/zio-json/shared/src/test/scala/zio/json/CodecSpec.scala:106 
      ✗ ERROR: java.lang.NullPointerException
        java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)
        java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)
        scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        java.lang.StackTrace$.currentStackTrace(Unknown Source)
        java.lang.Throwable.fillInStackTrace(Unknown Source)
        scala.scalanative.runtime.package$.throwNullPointer(Unknown Source)
        <none>.(Unknown Source)
        zio.json.JsonEncoder$.fromCodec(Unknown Source)
        testzio.json.CodecSpec$.$anonfun$spec$84(Unknown Source)
        testzio.json.CodecSpec$$$Lambda$74.apply(Unknown Source)
        scala.Function1.$anonfun$andThen$1(Unknown Source)
        scala.Function1$$Lambda$2.apply(Unknown Source)
      Custom("").toJson == indianaJones
      ("") = Custom( = "")
      Custom = testzio.json.CodecSpec$exampletransformkeys$Custom$@c074067f
      at /home/runner/work/zio-json/zio-json/zio-json/shared/src/test/scala/zio/json/CodecSpec.scala:120 
      ✗ ERROR: java.lang.NullPointerException
        java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)
        java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)
        scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        java.lang.StackTrace$.currentStackTrace(Unknown Source)
        java.lang.Throwable.fillInStackTrace(Unknown Source)
        scala.scalanative.runtime.package$.throwNullPointer(Unknown Source)
        <none>.(Unknown Source)
        zio.json.JsonEncoder$.fromCodec(Unknown Source)
        testzio.json.CodecSpec$.$anonfun$spec$87(Unknown Source)
        testzio.json.CodecSpec$$$Lambda$77.apply(Unknown Source)
        scala.Function1.$anonfun$andThen$1(Unknown Source)
        scala.Function1$$Lambda$2.apply(Unknown Source)
      Custom("").toJsonAST.toOption.get == indianaJones.fromJson[Json].toOption.get
      ("") = Custom( = "")
      Custom = testzio.json.CodecSpec$exampletransformkeys$Custom$@c074067f
      at /home/runner/work/zio-json/zio-json/zio-json/shared/src/test/scala/zio/json/CodecSpec.scala:121 
```

**Comment by armanbilge** [comment]
See https://github.com/scala-native/scala-native/issues/620#issuecomment-740170448.

**Comment by pablf** [comment]
Thank you! Do you know if it's intended to be implemented at some point or if this would be the final implementation?

**Comment by armanbilge** [comment]
If unlimited time and resources became available, I am sure we would love to implement it 😁 but realistically there are no concrete plans to implement this in the indefinite future.

**Comment by pablf** [comment]
Great, thanks! I might give it a try if I find some time.

**Comment by LeeTibbert** [comment]
@pablf 

Thank you for the offer to do something positive.
"?=" in a regex is what is known as a (positive) lookahead.  They are not supported in the RE2 implementation
which underlies Scala Native regex.  Implementing such a lookahead would mean replacing that implementation.
Such is likely to be a work of many months. Actually, I am minimizing the effort here, so as not to be too
discouraging.

Given the Scala Native "feature", lets see what we can do to get the zio-json test up and running.
I suspect that is your primary interest and, to be selfish, more strategic for Scala Native.

I am in the midst of preparing for a possible hurricane to hit sometime this week, so I can not
provide a full, working & tested example of a small bit of Scala Native code to replace the `str
  .split("(?=\\p{Upper})")` in the code you posted.  The overall goal of Scala Native javalib is to
be bug for bug compatible with JVM, but, living in an imperfect world, sometimes small bits
of SN specific code are needed.

What I can do in a few moments is to outline what I think would work.  Sorry to be terse.
I'll describe an approach which should work on SN 0.4.* & 0.5.* (the higher the * in 0.4.* the better).

Streams in recent (three or so months) 0.4.n and 0.5.* simplify things but introduce version
dependencies.
 
This approach creates a Matcher, call it m, using a slightly different regex (see below). It also creates
an ArrayList[String].  The method then does repeated calls to find, and add any capture group found
to the ArrayList.  After the last successful cal to `find()`, `toArray` is called on the Array list.  One then
should have an array, say src. One can then call src.forEach() where each Consumer adds the
transformed src element into a destination arrayList.  Yes, a side-effecting Consumer is not pretty,
but it has a small, contained scope. `dst.mkString()` should give the desired result. 

 Again, streams make this much easier.

```
stm // Stream
   .map(part => s"${part.head.toLower}${part.substring(1, part.length).toUpperCase}")
  .mkString
```
This [Matcher.find() example](https://www.tutorialspoint.com/matcher-group-method-in-java-with-examples)
shows the idea.

The key, as with most things regex, is getting the proper regex.
If I understand your example correctly, we want a regex which says "capture zero-or-one (Unicode, not just ASCII) Uppercase characters, followed by zero-or-more non-Uppercase characters".  
I think, but, as mentioned, have not tried "(\\p{Upper}?\\P{Upper}*)".

aaaBBc7+D<unseen space>
should return "aaa", "B", "Bc7+", "D<unseen space>"

Here, the string is assumed to not have a trailing new-line.

Those tokens could then be passed on to become  "aAA", "b", "bC7+", "d<unseen space>"

In closing, please let me know what would be useful to you & zio-json.  I will be on and off the 
air for the next ten-day or so, mostly off, but I would like to help you make progress.

Lee
having a knowledge of regex is like having a wild tattoo from one's teenage years .

**Comment by LeeTibbert** [comment]
@pablf   If you have time and interest and if it is not more than, say, 10 minutes, could you post
3 to 5 example pairs where the first element is a string & the second element is the expected output.
I would like to make sure that I am reverse engineering the regex correctly.

I think, but have not coded, that a nice functional solution is posible.  I it looks like it would run on each 
of Scala JVM, Scala.Js , and Scala Native and have better performance than the  existing regex. Regexen
tend to be CPU intensive: i.e. hogs.

Thank you.

**Comment by pablf** [comment]
@LeeTibbert Thanks for your response! Actually, what that test do test is the behaviour of a `JsonCodec` defined with a custom function. So the exact function is not important, it just happened to use regex in the test, but it could be a different one, even something like
```
def f(str: String): String = str + "a"
```
Even if we find the correct regex, some zio-json user might need to use a different one, so I don't think we can really do anything about it. If he (or maybe some library dependent on zio-json) intends to use scala-native, he will have to find the regex.

In your last comment are you refeering to the concrete regex from the test?

**Comment by LeeTibbert** [comment]
pablf,

Thank you for the info & context. 
```
So I don't think we should try to find a replacement regex for this, because even if we find the correct regex, some zio-json user might need to use a different one and we can't really do anything about that one. If he (or maybe some library dependent on zio-json) intends to use scala-native, he will have to find the correct regex.
```
I concur.  In a better world, SN would handle any j-random (Java) regex.  In the current & foreseeable world,
I think the best we can do is document what we do, do that correctly, and give clear messages when
the bounds are exceeded.

`In your last comment are you refeering to the concrete regex from the test?`

Yes, I was, but that issue seems moot/no_longer_relevant at this point.  Still a burr under
my saddle.  I think I could fix (and improve) the specific case by using a (tiny) state machine
but I can not fix the general "provided by user" case.

Please let me know if you encounter additional problems with Scala Native. It would be good
