### ISSUE TITLE
javalib missing Exception symbols at link time

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3467]
Scala Native 0.4.14 -- scala-cli --native  Linux

##### Defect
Missing symbols during link phase.
```
 Found 4 missing definitions while linking
[error] Not found Top(java.nio.file.FileSystemAlreadyExistsException)
[error] Not found Member(Top(java.nio.file.FileSystemAlreadyExistsException),RE)
[error] 	at https://raw.githubusercontent.com/scala-native/scala-native/v0.4.12/javalib/src/main/scala/scala/scalanative/nio/fs/GenericFileSystemProvider.scala:32
[error] Not found Top(java.nio.file.ProviderNotFoundException)
[error] Not found Member(Top(java.nio.file.ProviderNotFoundException),RE)
[error] 	at https://raw.githubusercontent.com/scala-native/scala-native/v0.4.12/javalib/src/main/scala/java/nio/file/FileSystems.scala:53
Exception in thread "main" scala.scalanative.linker.LinkingException: Undefined definitions found in reachability phase
```

##### Discussion

Source files for the indicated symbols appear to exist.  What may be happening is missing parenthesis at the 
call sites.

For example, one call site: java/nio/file/FileSystems.scala ` provider.getOrElse(throw new ProviderNotFoundException)`
note missing parens. The no-arg constructor is a secondary constructor so, magic thinking & wild guess, it might
require the "()".

**Comment by WojciechMazur** [comment]
These should be already added in main branch, we can backport them

**Comment by LeeTibbert** [comment]
Thank you. I just took a look at the 0.4.n branch.  Yes, the symbols are in 0.5.0 and not in 0.4.n.


Anything I can do to ease the backport?     There is no rush at my end, I will be working with SN 0.5.0
and Java for the next few weeks.
