### ISSUE TITLE
Add support for interop with C's fixed-size arrays

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#35]
One way to do it would be to introduce a new `CArray[T, N <: Size]` value type that corrresponds to C's `T[N]` type. It must also have a constructor that automatically infers the length. One can get a mutable array by stack allocating a value type and mutating the resulting pointer.

**Comment by Yoitsumi** [comment]
Maybe, as a workaround until we get singleton types, we could use an annotation for that? Something like:
```scala
@struct
class Foo(
  @size(10) bar: CArray[Ptr[_]]
)
```

**Comment by densh** [comment]
https://github.com/scala-native/scala-native/pull/473 introduced type-encoded natural numbers to represent the array length. It's a bit more cumbersome than native singleton types, but it's good enough to get this functionality working today.

**Comment by densh** [comment]
Fixed in #473

**Comment by tindzk** [comment]
Looks great, thanks!
