### ISSUE TITLE
Add last updated time to the footer or header of the document

### ISSUE THREAD

**Issue by tanishiking** [scala-native/scala-native#3519]
https://github.com/scala-native/scala-native/pull/3513 added a date that the document is built to the top of index page. And we're trying to add the same thing to the quickstart guide in https://github.com/scala-native/scala-native/pull/3496.

It would be great if we can add the last updated time of the document in all the pages using template than writing the same thing all over the pages like `Last updated: |today|`

## Adding a last updated to footer

It seems if we set `html_last_updated_fmt` to the `docs/conf.py` we can add the last updated to the footer of the documents.

> If this is not None, a ‘Last updated on:’ timestamp is inserted at every page bottom, using the given [strftime()](https://docs.python.org/3/library/time.html#time.strftime) format. The empty string is equivalent to '%b %d, %Y' (or a locale-dependent equivalent).
> https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_last_updated_fmt

The problem is, the current sphinx theme alabaster doesn't render the last updated time in footer 
 https://groups.google.com/g/sphinx-users/c/XWq5pYhk3sQ/m/XBkXjW_LBwAJ Other themes such as [classic](https://sphinx-themes.org/sample-sites/default-classic/#quickstart) and [pydata-sphinx-theme](https://github.com/pydata/pydata-sphinx-theme/blob/95f46a10fee125818e9f0ef2a6a3f0f2de87b943/docs/user_guide/layout.rst#build-date) (but many other themes should also support it).

One thing to consider is, is it ok to put this on footer? should we put it on header instead, which isn't possible without custom template AFAIK. I personally it's ok to put it to the footer as long as we can check the last updated at.

## Should we add last updated at of the documents?
`|today|` will be substituted by the built date of the document, which means it will be updated because of the CI even though we haven't updated the documents.

[mgeier/sphinx-last-updated-by-git: :watch: Get the "last updated" time for each Sphinx page from Git](https://github.com/mgeier/sphinx-last-updated-by-git) may help to show more accurate last updated time for the documents.

**Comment by LeeTibbert** [comment]
I left a note in PR #3520 expressing a preference for top over bottom and either over nothing at all.
