### ISSUE TITLE
Non-descriptive choice of terms

### ISSUE THREAD

**Issue by kyouko-taiga** [scala-native/scala-native#3534]
As I am going through the code, I stumble upon this object definition:
https://github.com/scala-native/scala-native/blob/53187dc09882846f860c27def8dfd37ba9478ce7/tools/src/main/scala/scala/scalanative/interflow/Whitelist.scala#L8

The term "whitelist" is a little problematic (see [rationale](https://www.splunk.com/en_us/blog/learn/blacklist-whitelist-inclusivity.html)) and it is also not very descriptive. I'm happy to rename and document this code but I'm not sure to understand what these lists represent. Could someone shed some light?

**Comment by armanbilge** [comment]
See also: https://docs.scala-lang.org/contribute/inclusive-language-guide.html

**Comment by ekrich** [comment]
There are also some areas for tests that should probably be changed to `include` /  `exclude` as well, which is better English to boot.
