### ISSUE TITLE
Need to cordon off sinkholes before 0.5.0 Release

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3539]
As talk of an official 0.5.0 release increases, I suggest that there are at least two
known Issues with Scala Native 0.5.0-SNAPSHOT which should be made impossible
for a user of 0.5.0 to ever reach.

We can not catch every "gotcha", but I believe we have a duty to users to fix know,
glaring causes of unhappiness.

1) Our friend, macOS, LTO, and releaseFast (and releaseFull?) not working.
    That combination should be disallowed.

2) Last I checked `commix` GC is not safe with experimental multithreading.
    If that is going to be true at 0.5.0 release time, then I think that configuration
    combination should not be allowed.

3) Last week or so,  a Discourse user tried to use Scala Native `Future`. I believe the resolution is that they
    need to enable multhreading. If this is true (and I could believe that), it is another combination which
    should be sealed off. I think this one might be harder to do because it involves Scala JVM code.

**Comment by armanbilge** [comment]
> 3\. `Future`. I believe the resolution is that they
>         need to enable multhreading.

It's possible to use `Future` without multi-threading. This is what we've been doing all along in the 0.4.x series :)

If I remember correctly, the user was not disappointed because their code did not run, they were disappointed because its behavior did not match the JVM, which is multi-threaded.

> it is another combination which should be sealed off.

Absolutely not, we have an entire ecosystem built on this combination :)

**Comment by WojciechMazur** [comment]
> Our friend, macOS, LTO, and releaseFast (and releaseFull?) not working.
That combination should be disallowed.

We examine this combination in scheduled (extended builds) and it seems to work just fine https://github.com/scala-native/scala-native/actions/runs/6426677503/job/17452990045 (latest build) 
The real issue with LTO.thin is related to Arm64 (Apple Mx) architectures. It seems like this target is having some issues with lto even when compiling some simple C++ code https://github.com/llvm/llvm-project/issues/67129 
In our case on M1 we have two issues related to linker: 
 - When using Apple LLVM default linker (/usr/bin/ld) there are assertions failing in builds when linking files compiled with -flto flag (links fine when linked with this flag, but compiled without) 
 - When using official LLVM linker (lld using linking flag `-fuse-ld=lld`) it can link the executable, but there is a high chance the exceptions won't work (see llvm issue linked before) 
 
 Becouse of that I don't think this combination shall be disallowed

**Comment by LeeTibbert** [comment]
PS:  Nice to see that those nightly and/or extended scheduled tests are being run.
        Progress happens.  Thank you.

**Comment by ekrich** [comment]
Actually, I was going to report this to Apple as they were interested but scala-cli did not support lto at the time. It has been fixed so the standalone use case is very simple now. I am sure it would be helpful if someone has time to file it.

**Comment by LeeTibbert** [comment]
A first step could be Scala Native doing a relatively easily seal of the particular quartet: arm, macOS, LTO, & release*.

From an earlier run at this problem, even when it was Intel, that Eric and I (anybody else willing to admit
participation? Thank you) made I suspect that Apple would only be interested in Xcode.

This time around I think I made a run with the latest Xcode and encountered an even worse mess. I got all turned around
by the number of combinations and my strong belief that `Discover` was hosing me. Oops, I should be saying
that I had not configured `Discover` correctly.

I could take another run, ensuring that I was solely using Apple tools and see what happens.  

After some reflection & a short discussion in this Community, a second
phase there would be to set up a "standalone" reproducer, possibly/probably using (and documenting the relevant
version) of scala-cli.

I think none of us want to spend person-months, beyond a probably 1, on this but it would be
nice to get rid of this blemish.  If for no other reason than:
 1) it has been around so long and has survived a number of attempts to fix it.
2) I want to use it.   It it should give us a pretty good story for performance and a good hardware 
    path forward.

Thoughts?

**Comment by ekrich** [comment]
Not to be a critic but I think individual issues could be linked to a central issue with checkboxes. I think this way we could have discussion about real and perceived issues. I have some thoughts about the build but they are many and varied.

**Comment by LeeTibbert** [comment]
Eric,   This is a collaborative effort; discussion & suggestions are welcome.

From discussions in Discourse, I believe that you are highly involved in your day job.

If you come up for air, could you sketch out your idea about organizing this Issue, or a better
replacement, a bit more?    My concern here is to remove/reduce some known, obvious dissatisfiers
that new & existing users will encounter when they try out the new, spiffy SN 0.5.0 (whenever that may
be in the fullness of time).

I'll follow your lead, that has proven wise in the past.

**Comment by ekrich** [comment]
I was just suggesting you could make this a summary ticket and put check marks in the first comment and more as needed and check them off when complete. Then we could have individual tickets for each item and add that item to the 0.5.0 milestone.
