### ISSUE TITLE
OS link now giving ld error 

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3552]
I've started seeing an error when I try to build 0.5.0-SNAPSHOT. I have not
had time to chase this.  Mentioning it to reduce angina in case other people see it also.

macOs 14 (Sonoma), M1 // have not tried Linux
Clang-17 (brew) // Have not tried lower versions
Scala 3.3.1 // Have not tried other versions

```
[info] Compiling to native code (10332 ms)
[error] ld: warning: ignoring duplicate libraries: '-ldl', '-lpthread'
```
It appears that the system `ld` and not `lld-17` is being used. Latter
should probably give the same error.

Build completes and `tests3/testOnly *.InetAddressTest` executes successfully.

**Comment by keynmol** [comment]
That's not really an error - it's a linker warning, but it's prefixed by `[error]` because I guess that's how SBT marks `stderr` output from subprocesses.

**Comment by LeeTibbert** [comment]
Yes, error at sbt level, wrapping an ld warning.  By any name, an "unexpected and unacceptable event".
A linker "warning" is almost an indication of bad cess.

The fact that the sbt build did not hard fail with the ld warning, is also unexpected and worthy of another
Issue.  

I believe that product builds should be "clean".     When I am ten or more levels down trying to replicate
intermittent, os & hardware related bugs, I do not want to be worrying if the OS link of my executable
is OK.      

Probably easy enough to fix, if I ever get tired of twitching whenever see it.

**Comment by WojciechMazur** [comment]
The easiest fix for that would be to just make the compile and linking options distinct, but these might be sometimes tricky, especially since order does matter when interacting with clang linker, so it might be hard to correctly create a general purpose solution. We might check the combination of LLVM + OS version, but then we might not cover all cases. Since it's just a warning then it does not have a high priority yet

**Comment by ekrich** [comment]
I was thinking that we could have links and includes be separate config options. We could make them sets to avoid duplication and not add the `-I` and `-l` and adapt for windows until we use it - this would make it easier for users to add and remove as needed. This also means we could make sure they are put in the correct place in the bigger command. We could also do the same for `-D` defines if that is helpful.

**Comment by LeeTibbert** [comment]
I am beginning to question, well, am well into questioning the attempt/drive to be all things to all builders and
or autoconfiguration.

Yes, simple end user applications should work out-of-the-box for the core, documented combinations which
are exercised in CI (which information almost certainly needs to be dynamically generated, a sub-issue).
If "HelloWorld.scala" or `sandbox3/run`  work, it gives people new to Scala Native some early success.

Folks who have highly complex needs for highly complex projects are probably better served by offering
Left and Right, Pre- and Post- hooks,  LinkOptions either side of what Scala Native writes for its central
link command.

That is, if one is not reasonably sure one can get all the corner cases reasonably write, don't do it but do
provide the capability of an application developer doing it write for their particular complex configurations.

**Comment by LeeTibbert** [comment]
@WojciechMazur  thank you for fixing this. Small engineering minds are thrown off their feed by little defects.
