### ISSUE TITLE
`@link("lib")` is ignored with top-level `@extern` methods

### ISSUE THREAD

**Issue by lolgab** [scala-native/scala-native#3603]
While
```scala
@extern
@link("unit")
object externs {
  def nxt_unit_init(init: Ptr[Byte]): Ptr[Byte] = extern
}
```
does add `-lunit` to the linking options, the equivalent top-level definition doesn't add linking options:
```scala
@extern
@link("unit")
def nxt_unit_init(init: Ptr[Byte]): Ptr[Byte] = extern
```

**Comment by armanbilge** [comment]
I think `@define` will have the same issue, I noticed this when working on it. The reachability analysis currently doesn't only consideres these annotation/attributes for modules (i.e. `object`s), not for methods. But it can be fixed :)

https://github.com/scala-native/scala-native/blob/de3119696c3d186d2be4ede205cde05b665f0741/tools/src/main/scala/scala/scalanative/linker/Reach.scala#L630-L643

**Comment by WojciechMazur** [comment]
Thank you for report and the reproducer. I think we were not checking method annotations in the compiler plugin. The fix is on the way.
