### ISSUE TITLE
Linker now shows double specification of pthread library.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3677]
Today's PR #3674 added the ability to display the libraries in the link command. This is goodness.
My simple builds of sandbox3 now start showing

```
[info] Linking with [pthread, dl, pthread]
```

Notice the double "pthread".  Sometimes this is necessary on a link line, when a second
pass is needed. I doubt such is need here.

Someday when I have nothing but spare time on my hands, I'll turn on the "-v" link flag and
see if the double specification is necessary or just noise that one must pick through.

The double specification has probably been there all along, the new PR makes it
visible and, hopefully, prompts fixing.

Not the biggest of concerns but enough to make an engineer twitch.

**Comment by LeeTibbert** [comment]
In a fury of debugging another Issue, I noticed that this issue is almost identical to Issue #3552.
Only now, the duplication is visible, in a gentler way, on Linux (and possibly others) in addition to the
original macOS.

**Comment by ekrich** [comment]
I have been thinking about this and a solution but I was thinking that it could be rolled into a bigger issue that addresses defaults and cross compiling which is liable to be controversial as well as none of this is super straightforward.

**Comment by LeeTibbert** [comment]
> as none of this is super straightforward

Amen!

**Comment by LeeTibbert** [comment]
For Linux (non) executable stack work, I have been looking at a lot of link log raw output.  I also had
cause to visit `LLVM.scala` yesterday.    I was focused on the monkey at hand and did not trace deeply,
but it looks to me like the duplication is a product of evolution. That is, the result of evolution does not
need to be perfect, it just needs to work.

Here, I suspect that a later phase of a pipeline does not check if an earlier phase has already added
the required libraries.   Simpler, would be for the later phase to filter them out and then unconditionally
add its own.  With current SN, dropping either the first or later excess library specifications would be
equivalent (to my eyes). Both are after the last -L library specification and there is no intervening code
option between the sets.
