### ISSUE TITLE
_CRT_SECURE_NO_WARNINGS definition missing during compilation on windows

### ISSUE THREAD

**Issue by ldeluigi** [scala-native/scala-native#3686]
Missing `_CRT_SECURE_NO_WARNINGS` definition on windows, leading to:
```
[error] In file included from D:/a/scafi-xc/scafi-xc/core/.native/target/scala-3.3.1/native-test/native-code-nativelib_native0.4_3-0.4.16-1/scala-native/gc/immix/ImmixGC.c:15:
[error] D:/a/scafi-xc/scafi-xc/core/.native/target/scala-3.3.1/native-test/native-code-nativelib_native0.4_3-0.4.16-1/scala-native/gc/shared\Parsing.h:17:9: warning: 'sscanf' is deprecated: This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations]
[error]         sscanf(str, "%zu", &size);
[error]         ^
[error] C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\stdio.h:2239:20: note: 'sscanf' has been explicitly marked deprecated here
[error]     _Check_return_ _CRT_INSECURE_DEPRECATE(sscanf_s)
[error]                    ^
[error] C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\vcruntime.h:355:55: note: expanded from macro '_CRT_INSECURE_DEPRECATE'
[error]         #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
[error]                                                       ^
[error] C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\vcruntime.h:345:47: note: expanded from macro '_CRT_DEPRECATE_TEXT'
[error] #define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
```

**Comment by JD557** [comment]
I've been noticing this errors for a while, but I'm not sure why they happen.

If I look at the problematic file (Parsing.h) I do see the `_CRST_SECURE_NO_WARNINGS` and `WIN32_LEAN_AND_MEAN` definitions: https://github.com/scala-native/scala-native/blob/5356ca5aa1dbb115e415d86928768400e2416c4a/nativelib/src/main/resources/scala-native/gc/shared/Parsing.h#L3-L8

**Comment by ldeluigi** [comment]
> Parsing.h:17:9: warning: 'sscanf' is deprecated
As you can see from the error, the sscanf is seen in line 17, but the filte doesn't mention sscanf in line 17.

I'm assuming the compiler complains about a file generated/manipulated in some way instead

**Comment by ldeluigi** [comment]
I'm assuming is not enough to define _CRT_SECURE_NO_WARNINGS at the file level, it should be defined for the whole compilation

**Comment by JD557** [comment]
I'm not at home to check, but here's what I think is happening:
- `ImmixGC.c` imports `stdio.h`. Since `_CRT_SECURE_NO_WARNINGS` is not defined, this includes the version of `sscan` that throws the warning
- `ImmixGC.c` imports `Parsing.h`/`Parsing.c`
- `Parsing.h`/`Parsing.c` define `_CRT_SECURE_NO_WARNINGS`
- `Parsing.h`/`Parsing.c` import `stdio.h` but, either due to a `#pragma once` or a `#ifndef` check, the header is not imported again, so it keeps the version of `sscan` that throws the warning.

I'm not entirely convinced that setting `_CRT_SECURE_NO_WARNINGS` for the whole compilation is a good idea. I feel like those warnings are still useful and it's nice to have an indication if the code is insecure.

**Comment by ldeluigi** [comment]
> I'm not at home to check, but here's what I think is happening:
> 
> * `ImmixGC.c` imports `stdio.h`. Since `_CRT_SECURE_NO_WARNINGS` is not defined, this includes the version of `sscan` that throws the warning
> * `ImmixGC.c` imports `Parsing.h`/`Parsing.c`
> * `Parsing.h`/`Parsing.c` define `_CRT_SECURE_NO_WARNINGS`
> * `Parsing.h`/`Parsing.c` import `stdio.h` but, either due to a `#pragma once` or a `#ifndef` check, the header is not imported again, so it keeps the version of `sscan` that throws the warning.
> 
> I'm not entirely convinced that setting `_CRT_SECURE_NO_WARNINGS` for the whole compilation is a good idea. I feel like those warnings are still useful and it's nice to have an indication if the code is insecure.

what about redirecting the subprocess standard error to standard output before sbt catches it and displays errors everywhere?

**Comment by JD557** [comment]
I was checking this ticket, but it looks like the issue is gone in 0.5.0.

Not sure what fixed it, though.

**Comment by ldeluigi** [comment]
cool. looking forward to 0.5.0! You can close the issue if that's the case
