### ISSUE TITLE
Publish artifact name are the same as Scalac

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#370]
I'm using [sbt-multi-platforms](https://github.com/MasseGuillaume/sbt-multi-platforms) to release scala-native artifacts. When I run publishLocal the artifact name is the same for scala-native and jvm. My current workaround is to provide an alternative artifact name.

we would need something similar to what Scala.js has for cross-publishing:
https://github.com/scala-js/scala-js/blob/7640e858efbf8dbf52c99ca8a82cfb2350836e02/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSCrossVersion.scala#L10

**Comment by densh** [comment]
Fixed in #392
