### ISSUE TITLE
Files.walkFileTree does not throw FileSystemLoopException

### ISSUE THREAD

**Issue by mpilquist** [scala-native/scala-native#3744]
Similar to #2392, `Files.walkFileTree` is inconsistent with JVM behavior in presence of walks while following links and encountering cycles.

Reproduction case:

```scala
//> using scala 3.3.1

import java.nio.file.*
import java.nio.file.attribute.BasicFileAttributes

import scala.jdk.CollectionConverters.*

val dir = Files.createTempDirectory("example")
Files.createSymbolicLink(dir.resolve("link"), dir)
var count = 0
Files.walkFileTree(dir, Set(FileVisitOption.FOLLOW_LINKS).asJava, Int.MaxValue,
  new SimpleFileVisitor[Path] {
    override def visitFile(f: Path, attrs: BasicFileAttributes) = {
      count += 1
      FileVisitResult.CONTINUE
    }
  }
)
println(count)
```

Running on the JVM throws the expected exception:
```
➜  scala-cli run walk.sc
Exception in thread "main" java.nio.file.FileSystemLoopException: /var/folders/q4/tm2l78qj6zq0x4_7hrlpckcm0000gn/T/example6714710748694412623/link
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:295)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2845)
	at walk$_.<init>(walk.sc:17)
	at walk_sc$.script$lzyINIT1(walk.sc:36)
	at walk_sc$.script(walk.sc:36)
	at walk_sc$.main(walk.sc:40)
	at walk_sc.main(walk.sc)
```

Whereas Native doesn't:
```
➜  scala-cli run --native walk.sc
0
```

**Comment by ekrich** [comment]
Thank you for this report.

**Comment by LeeTibbert** [comment]
Yes, thank you for reporting this and giving a reproducer.

Brings to mind my old Mother telling me that I should be careful about which neighborhoods I go
walking in.

Just to help triage.  The goal is to remove all defects.  Would you categorize this as "We found this and
are being good citizens by kindly reporting it." or "This keeps us from supporting Scala Native because
we would have to implement 5K lines of code to work around it."?

**Comment by mpilquist** [comment]
Definitely former. :)

This bug makes us skip on a small optimization in FS2's `Files[F].walk` routine (on native only).

**Comment by LeeTibbert** [comment]
mpilquist

Thank you for the info. It helps me size the problem.

I _hate_ having to code around operating or device specific quirks when I am writing code.
Very annoying.   

I can not dispatch this one quickly, sorry.
At least having an issue will keep it from getting forgotten. 

Sometimes I contemplate if it is better to have known bugs or not (and wonder if that code
is being used).
