### ISSUE TITLE
Stdout flush not synchronized between threads

### ISSUE THREAD

**Issue by JD557** [scala-native/scala-native#3745]
The behavior of `println` on multiple threads seems to differ slightly from the JVM.

Reproduction code:
```scala
val threadA = new Thread {
  override def run() = {
    println("Start A")
    Thread.sleep(5000)
    println("End A")
  }
}

val threadB = new Thread {
  override def run() = {
    println("Start B")
    Thread.sleep(5000)
    println("End B")
  }
}

threadA.start()
threadB.start()
```

On the JVM, the output is always clean, like:
```
Start A
Start B
End A
End B
```

While on Native (0.5.0-SNAPSHOT on Windows, as of 36509f7f50d3f53cf64e3ec2457d63e3d3890766) I get garbled outputs, like:

```Start A

art AStart B
End A
d A
```

or

```
Start A

Start B
End A

d A
```

**Comment by LeeTibbert** [comment]
Thank you for reporting this problem.  

The small reproducer will is much appreciated. 

SN multithreading is yet young, so it is nice to see someone using it and flushing the bugs out.
Of course, those bugs do you no good when you are trying to get work done.

SN `println` and the "print*" may not be recognizing that it/they can be blocking and so `yielding`.

I am wondering if writing to `stderr` shows a similar pattern.  This Issue may be bigger than it presents.

**Comment by LeeTibbert** [comment]
I do understand that the presented code is vastly simplified.

For future readers:

In the general case, I believe there is no guarantee that ThreadA will either start execution or start "println"
before ThreadB does either.  

Also, if two threads are accessing the same resource, they should do their own synchronization, such as
`java.concurrent.locks`.

Looks  like the JVM `Console.println` is helpfully doing that under the covers. I'd have to re-read the JVM
description.  That is what long waits for CI to complete are for.
