### ISSUE TITLE
getOrElse crash the application on mutable map

### ISSUE THREAD

**Issue by cedricviaccoz** [scala-native/scala-native#376]
The method getOrElse on a mutable map produce a java.lang.RuntimeException with exit code 134.
```
val m = mutable.Map.empty[String, String]
val hello = "hello"
val world = "world"
m(hello) = world
val h = m.getOrElse(hello, "Failed !")  // crash the app !
assert(h equals world)
```
I've encountered this issue while working on #311 when using the forName method from java.nio.Charset.

**Comment by densh** [comment]
Hi @cedricviaccoz, it seem that's the failure in your test case is not reproducible. 

CI: https://travis-ci.org/scala-native/scala-native/jobs/174193854#L1061
PR: https://github.com/scala-native/scala-native/pull/377
