### ISSUE TITLE
Proposal: don't include @struct's in 0.1

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#378]
There are a number of non-trivial issues we've accumulated so far:

* No way to dereference a single field of a struct #39 
* Interaction between structs and stack allocation is not obvious #115 
* Structs don't box when they escape to generic context #178 
* Structs don't respect C's ABI in extern methods #195 
* Structs don't support inheriting from traits #38 

Instead of releasing a half-baked implementation immediately or delaying a first developer preview release, I propose to temporarily drop structs as a user-facing language extension for `0.1`. Revised version of structs (or its equivalent) is going to be re-considered in one of the future releases of Scala Native.

/cc @sjrd @MasseGuillaume

**Comment by sjrd** [comment]
IMO this is a reasonable thing to do.

**Comment by mdedetrich** [comment]
I don't have any issues with this as long as structs are still considered a high priority and they aren't getting pushed down the priority table

**Comment by andreaTP** [comment]
I understand your point @densh but in this way you basically have to drop even C interop feature, or am I wrong?

**Comment by fbertra** [comment]
Interop with C is a mayor feature for 0.1.  And a lot of C functions use structs or pointers to struct as parameters/return value.

Is there is a way to simplify the semantic of struct and avoid the issues above?  For example:

- define structs as pure value classes which cannot define methods or implement traits (https://github.com/scala-native/scala-native/issues/38),
- allocated on stack by default (as in C): it simplify https://github.com/scala-native/scala-native/issues/115
- never escape from local context.  Explicit conversion to a Scala object is required.

Finnally the workaround proposed in https://github.com/scala-native/scala-native/issues/39 is good enought for 0.1.

**Comment by densh** [comment]
@mdedetrich 

Having a good value types story is high priority goal. There are a number of ways we can get there, current prototype of structs is the approach we've tried so far. 

@andreaTP 

Interop is still there. There only thing you will not be able to do temporarily is pass structs by value, but you'll still be able to pass them by reference. I'll do a PR to add support for storing tuples to pointers soon. E.g. before we had:

```
@struct class Vec(val x: Double, val y: Double, val z: Double)

val vec = stackalloc[Vec]     // pointer to stack allocation
!vec = new Vec(1.0, 2.0, 3.0) // store value to stack
length(vec)                   // pass by reference
```

Now this will be:

```
type Vec = (Double, Double, Double)

val vec = stackalloc[Vec] // pointer to stack allocation
!vec = (1.0, 2.0, 3.0)    // store value to stack
length(vec)               // pass by reference
```

@fbertra 

Unfortunately, properly enforcing the constraints you proposed is as hard as fixing the issues above.

**Comment by densh** [comment]
**Note:** This proposal is regarding the scope of 0.1 only.

**Comment by andreaTP** [comment]
IMO this is a key feature for the effectiveness of Scala-Native, if effort for supporting proper structs delay the belated 0.1 of some months nobody will complain at this point.
Again, this is a personal opinion.

Is there any constrains to quickly release a non-snapshot?

**Comment by vossad01** [comment]
Maybe I am more cautious to "drink from the firehose" than I should be, but I like this proposal.
I would like to see a "stable" milestone/snapshot to develop against sooner knowing that more good things are to come later.  That is so long as it does not mean scala-native itself would be implementing a lot of things it does not intend to keep to make that happen (which does not sound like the case here).

**Comment by densh** [comment]
Evolution of this discussion: https://github.com/scala-native/scala-native/pull/472

`@struct` can stay under the rug as experimental unsupported functionality.

**Comment by densh** [comment]
#474 closes this. `@struct` is now semi-private but it's still there as @andreaTP requested.
