### ISSUE TITLE
Fast Future chains crash application

### ISSUE THREAD

**Issue by JD557** [scala-native/scala-native#3799]
On Scala-Native 0.5.0-RC1, chaining a sequence of `Futures` in a busy loop seems to crash the application when the futures are too fast.

I can only reproduce this with `release` (the code seems fine with `debug` and `release-fast`). Adding more computations inside also seems to make the problem go away.

Tested on Windows 11. The application simply hangs and then quits with no exit code. Trying to print the result of the `Future` also doesn't work.
The error logs seem to point to a [`0xC00000FD`](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) error (`STATUS_STACK_OVERFLOW`: A new guard page for the stack cannot be created).

Example code

```scala
import scala.concurrent.*
import scala.concurrent.duration.*

given ExecutionContext = ExecutionContext.global
private def loop(nextSchedule: Long): Future[Unit] = Future {
  if (System.currentTimeMillis() > nextSchedule) {
    println("GO")
    System.currentTimeMillis() + 100
  } else nextSchedule
}.flatMap { next => loop(next) }

Await.result(loop(0), 5.seconds)
```

Run with: `scala-cli --native --native-version 0.5.0-RC1 --native-mode release .\future-cycle.sc`

<details>
<summary>Windows error logs</summary>
<pre>
Faulting application name: main.exe, version: 0.0.0.0, time stamp: 0x65e329ef
Faulting module name: main.exe, version: 0.0.0.0, time stamp: 0x65e329ef
Exception code: 0xc00000fd
Fault offset: 0x00000000001fce22
Faulting process id: 0x0xAEC
Faulting application start time: 0x0x1DA6CA794E604A2
Faulting application path: D:\Projects\cli-tests\.scala-build\cli-tests_86ff520fec-d6e28639fb\native\main.exe
Faulting module path: D:\Projects\cli-tests\.scala-build\cli-tests_86ff520fec-d6e28639fb\native\main.exe
Report Id: 6dbd600f-c1c6-4741-b8a7-917681a7c401
Faulting package full name: 
Faulting package-relative application ID: 
</pre>
</details>

**Comment by armanbilge** [comment]
Great catch. I was able to replicate.

```
Linux armanbilge-sandbox-vrjq2ofty49 6.1.75-060175-generic #202402010024 SMP PREEMPT_DYNAMIC Thu Feb  1 01:44:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

```
...
GO
GO
Segmentation fault
```

**Comment by keynmol** [comment]
On macOS:

```
GO
GO
GO
GO
GO
GO
fish: Job 1, 'scala-cli --native --native-ver…' terminated by signal SIGILL (Illegal instruction)
```

In LLDB:

```
Process 54518 stopped
* thread #12, stop reason = signal SIGBUS
    frame #0: 0x000000010013be94 test`_SM33java.util.concurrent.ForkJoinPoolD9awaitWorkL43java.util.concurrent.ForkJoinPool$WorkQueueiEPT33java.util.concurrent.ForkJoinPool + 540
test`:
->  0x10013be94 <+540>: ldr    xzr, [x8]
    0x10013be98 <+544>: mov    w0, #0x0
    0x10013be9c <+548>: bl     0x100168920               ; scalanative_GC_set_mutator_thread_state
    0x10013bea0 <+552>: ldr    x8, [x26]
Target 0: (test) stopped.
```

**Comment by WojciechMazur** [comment]
These are actually coused by StackOverflow (unfortunately we don't detect and throw StackOveflowExceptions yet). The initial debugging shows that it was caused by some missing corner case for detection of stack allocations in the loops - we have mechanism to reset stack state.
