### ISSUE TITLE
Settings table is broken on the 0.5.0 Documentation

### ISSUE THREAD

**Issue by JD557** [scala-native/scala-native#3800]
Old: https://scala-native.org/en/stable/user/sbt.html

![imagem](https://github.com/scala-native/scala-native/assets/1187242/5385b3f6-5f13-4b35-8992-4444a9b1c2b9)

New: https://scala-native.org/en/latest/user/sbt.html

![imagem](https://github.com/scala-native/scala-native/assets/1187242/d2b1eb89-19b7-477d-b49a-92af9a3c9966)

**Comment by JD557** [comment]
Also, I think `withMultithreadingSupport` is missing from the documentation (that's what I was looking for in the first place 😛  )

**Comment by WojciechMazur** [comment]
Most of the entries from this table should be removed, as they were deprecated/removed at this point. 
The formatting was fixed already (Thank you!) but we should link to scaladoc with NativeConfig 
https://www.javadoc.io/doc/org.scala-native/tools_3/latest/scala/scalanative/build/NativeConfig.html 
I'll adjust it for the final release
