### ISSUE TITLE
Rename sbtplugin to sbt-native

### ISSUE THREAD

**Issue by soc** [scala-native/scala-native#384]
It would be great if Scala-Native adopted the naming convention for more consistency with other sbt plugins like sbt-scalajs, sbt-android, sbt-coursier, ...

I tried to write it down here: http://www.scala-sbt.org/1.0/docs/Plugins-Best-Practices.html#Follow+the+naming+conventions

**Comment by densh** [comment]
Good idea, thanks for suggestion!

**Comment by densh** [comment]
More discussion on this: https://github.com/scala-native/scala-native/pull/392/files#r89504455

**Comment by densh** [comment]
Fixed in #392
