### ISSUE TITLE
`java.nio.file.Files.delete` misbehaves on broken symlinks

### ISSUE THREAD

**Issue by lihaoyi** [scala-native/scala-native#3878]
```scala
    import java.nio.file.{Files, Paths}
    val file = Paths.get("broken-link")
    Files.createSymbolicLink(file, Paths.get("doesnt-exist"))
    Files.delete(file)
```

This code completes successfully on Scala-JVM, fails with the below exception on Scala-Native

```
Exception in thread "main"java.nio.file.NoSuchFileException: broken-link
	at java.nio.file.Files$.delete(Unknown Source)
	at java.nio.file.Files.delete(Unknown Source)
	at test.os.OsTestMain$.main(Unknown Source)
	at test.os.OsTestMain.main(Unknown Source)
	at <none>.main(Unknown Source)
```

I think it's incorrectly trying to de-reference the broken symlink rather than just deleting the link

**Comment by LeeTibbert** [comment]
lihaoyi

Thank you for reporting this and providing the reproducer.  Sorry that this defect took your time.
(I have been offline for an extended period, so I could not fix this earlier.)

> I think it's incorrectly trying to de-reference the broken symlink rather than just deleting the link

It appears that your analysis was spot on. It hastened finding & resolving the defect.
