### ISSUE TITLE
Add support for equivalent of C's `ptr->field`

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#39]
Finding an equivalent for this in Scala is complicated:
1. We could use a combination of `Dynamic` and whitebox macros but that would make it unusable in IDEs and not portable to dotty. The syntax would be `ptr.field` which is not the same but close enough.
2. If we try to use exactly the same syntax as in C `ptr->field`, it gets parsed as `ptr.->(field)`, meaning that `field` has to be in scope, defined somewhere else. I don't really see how can one make it happen without some dark arcane magic (untyped macros?). 

**Workaround**: `(!ptr).field`. This will load a whole struct and then extract a field from it.

**Comment by densh** [comment]
I've chatted with IntelliJ guys on Scala Days and they say it might be possible to add support for derivation of field types through an official extension mechanism they have. So using a whitebox macro for this seems to be the best way to go so far.

**Comment by nafg** [comment]
@densh instead of Dynamic, for one extra character how about use Symbols: `ptr -> 'field`

**Comment by densh** [comment]
The eventual solution to this one landed in https://github.com/scala-native/scala-native/pull/472. We make structs anonymous by default and one can access fields via `ptr._N` where `N` is the index of the field.
