### ISSUE TITLE
Please take over Scala Native java.util.logging port

### ISSUE THREAD

**Issue by sideeffffect** [scala-native/scala-native#3904]
Hello everybody here! I've noticed that we don't have any kind of implementation of java.util.logging aka JUL, not even anything rudimentary.
Folks over at Scala.js have at least https://github.com/scala-js/scala-js-java-logging .
So I took it and ported it in the most straightforward manner, including typos: https://github.com/sideeffffect/scala-native-java-logging

@WojciechMazur would you be open to bringing this repo under the https://github.com/scala-native/ umbrella and making a release?
I've already sent an invitation to you to join that repository of mine, and I can transfer the ownership to you, if it helps.

**Comment by WojciechMazur** [comment]
Thank you for this great initiative! I'd be glad to move it common organisation and make a release. 
Seems like I cannot transfer it right now, but you, as an owner should be able to do it right now as soon you'd accept invitation to Scala Native organisation. As a member of the org you should have permissions to create new repositories which is required to transfer.

**Comment by sideeffffect** [comment]
:tada: transferred https://github.com/scala-native/scala-native-java-logging
Now just the release :crossed_fingers:

**Comment by WojciechMazur** [comment]
Thank you! I'll setup the CI with credentials for releasing later today, we should have a first version available this evening or tomorrow morning
