### ISSUE TITLE
Scala Native / Fails to compile & produce object files for the larger header (.h) files

### ISSUE THREAD

**Issue by prabhugopal** [scala-native/scala-native#3973]
When i am trying to create a bindgen wrapper for [Nuklear](https://github.com/Immediate-Mode-UI/Nuklear), i consistently see the scala native fails to compile with the following exception.I initially thought the issue could be with the [bindgen](https://github.com/indoorvivants/sn-bindgen) library which i am using, but i get the same issue with other libraries too, particularly when the header file is large in size.

```scala
[info] compiling 2 Scala sources to /Users/prabhugopal/Learning/scala/hello-native/jvmti/target/scala-3.3.3/classes ...
java.lang.IllegalArgumentException: UTF8 string too large
  | => rat scala.tools.asm.ByteVector.putUTF8(ByteVector.java:255)
        at scala.tools.asm.SymbolTable.addConstantUtf8(SymbolTable.java:774)
        at scala.tools.asm.MethodWriter.<init>(MethodWriter.java:603)
        at scala.tools.asm.ClassWriter.visitMethod(ClassWriter.java:468)
        at scala.tools.asm.tree.MethodNode.accept(MethodNode.java:645)
        at scala.tools.asm.tree.ClassNode.accept(ClassNode.java:468)
```

**Comment by WojciechMazur** [comment]
The stack traces are actually a part of Scala JVM backend and might be related to limits enforced by the JVM.  Full stacktrace would be useful to confirm it, because typically these should end with `ClassTooLargeException`. As a quick debug check you can try to compile it using Scala 3.4.2/3.5.0-RC1 instead of 3.3.3 (LTS) as it might miss some improvements. 
It seems more like an issue in Scala compiler. Not sure why it crashed on too large string, maybe it tried to embed the whole generated by bindgen source file - I guess it shouldn't.

**Comment by prabhugopal** [comment]
> The stack traces are actually a part of Scala JVM backend and might be related to limits enforced by the JVM. Full stacktrace would be useful to confirm it, because typically these should end with `ClassTooLargeException`. As a quick debug check you can try to compile it using Scala 3.4.2/3.5.0-RC1 instead of 3.3.3 (LTS) as it might miss some improvements. It seems more like an issue in Scala compiler. Not sure why it crashed on too large string, maybe it tried to embed the whole generated by bindgen source file - I guess it shouldn't.

@WojciechMazur I see the issue already reported here https://github.com/scala/scala3/issues/15850 and fortunately same with Nuklear.

**Comment by keynmol** [comment]
This can be closed as it's not a Scala Native issue.
The compiler crashes trying to write the signature of the gigantic types that are produced for Nuklear structs.

The only way to circumvent this is to use Bindgen's "opaque structs" feature: https://github.com/indoorvivants/nuklear-bindings/blob/main/build.sbt#L23

But that only exposes further issues. Making Bindgen work with nuklear is on my personal roadmap, but this will require some further changes to how bindings are generated.

**Comment by prabhugopal** [comment]
> This can be closed as it's not a Scala Native issue. The compiler crashes trying to write the signature of the gigantic types that are produced for Nuklear structs.
> 
> The only way to circumvent this is to use Bindgen's "opaque structs" feature: https://github.com/indoorvivants/nuklear-bindings/blob/main/build.sbt#L23
> 
> But that only exposes further issues. Making Bindgen work with nuklear is on my personal roadmap, but this will require some further changes to how bindings are generated.

Thanks @keynmol
