### ISSUE TITLE
[docs] request - remove `$` from commands for copy pasting

### ISSUE THREAD

**Issue by spaceunifyfifty** [scala-native/scala-native#4001]
An example from the docs https://scala-native.org/en/stable/user/setup.html#installing-clang-and-runtime-dependencies shows

# macOS
```sh
$ brew install llvm
$ brew install bdw-gc # optional
```
the `$` prevents users from easily copy pasting both commands into their terminal. I must instead now manually click and drag my cursor to select first line making sure not to include `$`, paste it into my terminal, and then repeat that process for the second command as well. Instead of a quick copy paste for both at once. In this case, it is double the effort, but even worse for command snippets that have more than two consecutive commands.

Small quality of life thing that would make the docs better. Is expected and appreciated by unix people.

**Comment by keynmol** [comment]
A PR adjusting that would be appreciated: https://github.com/scala-native/scala-native/blob/e6f9721948c4679251e74157309ec80b8667df19/docs/user/setup.md

**Comment by LeeTibbert** [comment]
I am one of the people who believe that indicating the required/intended scope or context of the 'cmd'
brings critical information.  Is the text intended for the command line? inside of sbt? inside of scala-cli?

Authors tend to know their intended scope. They may even leave breadcrumbs in the enclosing
description. Readers bring varying expectations of 'current scope'. One must establish common ground.
