### ISSUE TITLE
sbt test fails when setting `.withOptimize(false)` in nativeConfig

### ISSUE THREAD

**Issue by scalavision** [scala-native/scala-native#4010]
When setting `withOptimize(false)` in `nativeConfig` in my `build.sbt`, I am not able to run the tests:

```bash
[info] Optimizing skipped
[info] Total (3965 ms)
[info] Generating intermediate code (with debug metadata) (1340 ms)
[error] java.util.NoSuchElementException: key not found: Local(5)
```

I created a basic reproducible project example here:

https://github.com/scalavision/scalanative-testproblems

EDIT:

I also wonder why inside sbt shell `~test` doubles the compile time compared to `~run` ? Is that expected ?

As a side note I also wonder if one should add this compilation flag as default?

```scala
c .withCompileOptions(_ :+ "-O")
```

Without I get a lot of warnings, which might be a show stopper for a beginner not knowing sbt etc.

**Comment by LeeTibbert** [comment]
scalavision,

Sorry that you are experiencing problems.  I suspect that you are exercising a little visited area
of  Scala Native.

It has gone August and probably everybody in Europe is on holiday or reduced hours, if what my
analyst tells me is true.  A response from someone who might be able to help you may be
a long time coming.

Do you have a workaround?

Personal wonderment:
My "man clang" page shows me options for "-O0" (minus-Oh-zero) but no simple "-O" (minus-Oh).
What are you trying to do with the snippet you posted?  Please forgive my lack of comprehension or
appreciation of subtlety.

**Comment by LeeTibbert** [comment]
> I also wonder why inside sbt shell ~test doubles the compile time compared to ~run ? Is that expected ?

`~test` must have either a kickback agreement with the power company or else a 'it is OK to reduce my power
when there is high demand' :-)

**Comment by WojciechMazur** [comment]
Thank you for reproducer. Probably codegen or lowering is behaving incorrectly. I'll try to fix it over the weekend
