### ISSUE TITLE
Add Support for AtomicDouble

### ISSUE THREAD

**Issue by varshith257** [scala-native/scala-native#4025]
Scala-native already supports many atomic operations and is moving closer to supporting multi-thread concurrency like JVM. It will also be beneficial if we also add support for AtomicDouble.

cc: @sideeffffect   Once this added now or future we can have good compatibility towards jvm-native in ZIO

**Comment by WojciechMazur** [comment]
Hey, thank you for raising this issue. By AtomicDouble do you mean `java.util.concurrent.atomic.DoubleAdder`? No `AtomicDouble` is defined in the JDK, so it's a bit confusing to me what you had in mind.

**Comment by bishabosha** [comment]
Probably referring to ZIO AtomicDouble which wraps and AtomicLong https://github.com/zio/zio/blob/18e8c851c4db105b544d58f198b280d38e80f2f7/core/jvm/src/main/scala/zio/internal/metrics/ConcurrentMetricHooksPlatformSpecific.scala#L246

**Comment by varshith257** [comment]
@WojciechMazur Yes what I intended is of @bishabosha comment above

**Comment by varshith257** [comment]
Also, do you have any idea of what is the cause, although the test fails, Native Testrunner has not reported it to the SBT 

https://github.com/zio/zio/actions/runs/10425893870/job/28877735096?pr=9117#step:7:4583

This behaviour is started in this PR only of reworking to support multithreading

**Comment by bishabosha** [comment]
@varshith257 that test fails because you changed the expected value from "A" to "B" which has nothing to do with AtomicDouble?

**Comment by varshith257** [comment]
Yes, the intended behaviour is that the test fail should report to SBT

**Comment by sideeffffect** [comment]
I think this ticket can be closed. @varshith257 you can (should?) use the same implementation of `AtomicDouble` for both `jvm` and `native`.

**Comment by varshith257** [comment]
But DoubleAdder isn't supported

**Comment by WojciechMazur** [comment]
> Also, do you have any idea of what is the cause, although the test fails, Native Testrunner has not reported it to the SBT
> 
> https://github.com/zio/zio/actions/runs/10425893870/job/28877735096?pr=9117#step:7:4583
> 
> This behaviour is started in this PR only of reworking to support multithreading of Scala Native in ZIO

It might be similar to the issue in the munit https://github.com/scala-native/scala-native/issues/3464#issuecomment-1705503874 
Hard to tell right now, would need to go through the source code

**Comment by varshith257** [comment]
@WojciechMazur Yes, we need a fix for it but perhaps the same problem exists before the support of multithreading

**Comment by varshith257** [comment]
Ref: https://github.com/zio/zio/tree/series/2.x/test-sbt/native/src/main/scala/zio/test/sbt/native
