### ISSUE TITLE
Test Framework Puts Out Nothing

### ISSUE THREAD

**Issue by reid-spencer** [scala-native/scala-native#4053]
My module builds correctly and apparently runs the native tests successfully, to wit:
```shell
[info] Generating intermediate code (759 ms)
[info] Compiling to native code (1367 ms)
[info] Linking with [pthread, dl]
[info] Linking native code (none gc, none lto) (67 ms)
[info] Postprocessing (0 ms)
[info] Total (2552 ms)
[info] Starting process '/Users/reid/Code/ossuminc/riddl/utils/native/target/scala-3.4.3/riddl-utils-native-test' on port '51208'.
[success] Total time: 4 s, completed Sep 19, 2024, 6:02:58 AM
[IJ]riddl(utilsNative) : native-build : 0.52.2-8-98db8851-20240919-0551>
```
This output does not, however, tell me if any of the tests fail or succeed.  I tried to put `println` statements in my test cases to get some kind of positive acknowledgement that it at least ran the test. Running exactly the same test cases with the JVM yields output like this:
```shell
[info] compiling 1 Scala source to /Users/reid/Code/ossuminc/riddl/utils/jvm/target/scala-3.4.3/classes ...
[info] done compiling
[info] compiling 12 Scala sources to /Users/reid/Code/ossuminc/riddl/utils/jvm/target/scala-3.4.3/test-classes ...
[info] done compiling
[info] URLTest2:
[info] URL
[info] - should create with fromCwdPath
[info] - should create with fromFullPath
[info] TextFileWriterTest:
[info] TextFileWriter
[info] - must implement template substitutions
[info] - must fill a template from a resource
[info] FileBuilderTest:
[info] FileBuilder
[info] - should handle indent
[info] TimerTest:
[info] timer
[info] - should measure the correct time
[info] - should not print anything
[info] URLTest:
[info] URL
[info] - should construct a file URL from string
[info] - should throws on bad syntax
[info] - should accepts http, https & file schemes
[info] BuildInfoTest:
[info] BuildInfo
[info] - must have all the fields
[info] - must has functioning toMap
[info] - must has functioning toJson
[info] LoaderTest:
[info] Loader
[info] - must load
[info] TarSpec:
[info] Tar
[info] - must untar a .tar.gz file correctly
[info] SysLoggerTest:
[info] SysLogger
[info] - should print error message
[info] - should print severe message
[info] - should print warning message
[info] - should print info message
[info] - should print many message
[info] PathUtilsSpec:
[info] PathUtils
[info] - should compare empty directories
[info] - should compare size difference directories
[info] - should compare content difference directories
[info] InterruptTest:
[info] InterruptTest
[info] - must work non-interactively
[info] - must work interactively (pending)
[info] Run completed in 535 milliseconds.
[info] Total number of tests run: 24
[info] Suites: completed 11, aborted 0
[info] Tests: succeeded 24, failed 0, canceled 0, ignored 0, pending 1
[info] All tests passed.
[success] Total time: 2 s, completed Sep 19, 2024, 6:08:20 AM
[IJ]riddl(utils) : native-build : 0.52.2-8-98db8851-20240919-0551>
```
I don't need the output for scala-native to be identical to JVM, but most developers will want some kind of positive acknowledgement that their test cases ran at the very least.

**Comment by lolgab** [comment]
Did you use `%%%` to add the test framework dependency?
This happens when you use JVM dependencies by mistake which compile successfully but don't expose any class in the linking phase (which uses `nir` files instead of the `class` files).

**Comment by reid-spencer** [comment]
Nope, completely forgot to specialize that for the Scala Native case. Will try it and report bak.

**Comment by reid-spencer** [comment]
That fixed it. Onwards to the next issue.

**Comment by reid-spencer** [comment]
FYI: The output now looks like:
```shell
[info] Starting process '/Users/reid/Code/ossuminc/riddl/utils/native/target/scala-3.4.3/riddl-utils-native-test' on port '55572'.
[info] Starting process '/Users/reid/Code/ossuminc/riddl/utils/native/target/scala-3.4.3/riddl-utils-native-test' on port '55575'.
[info] Starting process '/Users/reid/Code/ossuminc/riddl/utils/native/target/scala-3.4.3/riddl-utils-native-test' on port '55577'.
[info] Run completed in 19 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] Error during tests:
[error] 	com.ossuminc.riddl.utils.TimerTest
[error] 	com.ossuminc.riddl.utils.URLTest
[error] 	com.ossuminc.riddl.utils.BuildInfoTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6 s, completed Sep 19, 2024, 10:38:05 AM
```

**Comment by ekrich** [comment]
Maybe try the `sbt> testOnly com.ossuminc.riddl.utils.TimerTest` to see if you can get more info. Also try the `sbt` `last` command after it fails.

**Comment by reid-spencer** [comment]
The last command yields:
```shell
last
[debug] > Exec(last, None, None)
```
not particularly helpful. 

The `testOnly` command wasn't very helpful either:
```shell
[info] Total (3609 ms)
[info] Starting process '/Users/reid/Code/ossuminc/riddl/utils/native/target/scala-3.4.3/riddl-utils-native-test' on port '58037'.
[info] Run completed in 11 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] Error during tests:
[error] 	com.ossuminc.riddl.utils.TimerTest
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 5 s, completed Sep 19, 2024, 1:42:37 PM
```

**Comment by reid-spencer** [comment]
I have just noted that what stopped the test run was an `sbt.TestsFailedException` which is generally only used to report unsuccessful test runs. Howeve,r it also reports 0 tests ran. I can only assume that the program crashed before it could deliver any results back to the test framework. So ...

Does scalaNative place any restrictions on the KINDS of tests that can be executed? I noticed that the documentation says it supports JUNIT tests. The above is ScalaTest. Perhaps ScalaTest is not supported (yet) ?

**Comment by ekrich** [comment]
So perhaps the best way forward is to give your OS, Java, sbt, clang, Scala Native versions. Also, all of your dependencies need to be `%%%` so you also should have [sbt-crossproject](https://github.com/portable-scala/sbt-crossproject) because it sounds like it works on JVM. All, of your software versions need to support Scala Native `0.5` although you should be using the Scala Native `0.5.5` version for you project.

**Comment by ekrich** [comment]
We also have a chat if you can do that - sometimes that is helpful - https://discord.gg/8ayqUT68

**Comment by reid-spencer** [comment]
I'm in the discord chat and happy to continue there. Here are the versions:
* Chipset: Apple M2 Max on MacBrook Pro, 64GB RAM
* OS: MacOS Sonoma 14.6.1
* Java: openjdk 21 2023-09-19,  OpenJDK Runtime Environment (build 21+35-2513)
* scala-native: 0.5.5
* scala-js: 1.16.0
* SBT: 0.10.2
* clang:
  Homebrew clang version 18.1.8
  Target: arm64-apple-darwin23.6.0
  Thread model: posix
  InstalledDir: /opt/homebrew/opt/llvm/bin

All dependencies are specified with %%% - its really just scalatest

**Comment by ekrich** [comment]
Looks like this version is ok - https://mvnrepository.com/artifact/org.scalatest/scalatest_3/3.2.19

**Comment by reid-spencer** [comment]
That's the one I'm using, and yes, it is new to scala-native. Do you think the issue lies with scalatest?

**Comment by ekrich** [comment]
You do have a cross project, something like this?
```scala
lazy val myProject = crossProject(JVMPlatform, NativePlatform, JSPlatform)
  .crossType(CrossType.Full)
```

**Comment by reid-spencer** [comment]
SOMETHING like that, yes :) Details: https://github.com/ossuminc/sbt-ossuminc (not well documented yet)
