### ISSUE TITLE
GC stops all threads because one thread is blocking

### ISSUE THREAD

**Issue by amsen20** [scala-native/scala-native#4060]
It appears that during memory allocations, the GC is trapping threads, forcing them to stop for the GC's marking/nullifying operations. 

However, if a thread is blocked in a system call such as `epoll_wait`, it seems that this thread never reaches the GC's trap. 
As a result, the other threads are forced to wait for this blocking thread to resume.

I am sure that a minimal example can be created by opening files but here is the [link](https://github.com/amsen20/pollerBear/blob/main/tests/src/test/scala/MultiThreadedSuite.scala) to the test that I got into this problem.
The problem is solved by disabling GC (setting it to `none`).

**Comment by amsen20** [comment]
Thanks for your reply :), it worked.

I annotated the `epoll_wait` external method and did work. But I did it for the caller of that method (`waitEvents`) and it didn't. What is the specific rule for using this annotation?

**Comment by armanbilge** [comment]
> What is the specific rule for using this annotation?

The annotation must go on a natively-bound method, not on a Scala method.

**Comment by amsen20** [comment]
Got it,
thanks!

**Comment by ekrich** [comment]
Is there currently documentation on this in the guide particularly in the multi-thread section? I reminder ticket would be great if documentation is needed.

**Comment by amsen20** [comment]
I couldn't find proper documentation on how to do multi-threaded programming in scala.
Should we use java conversions or not and so on?

**Comment by armanbilge** [comment]
> I couldn't find proper documentation on how to do multi-threaded programming in scala.

@amsen20 https://docs.scala-lang.org/scala3/book/concurrency.html

**Comment by amsen20** [comment]
I meant more low-level scala native threading, as a simple example, threads in JVM are supported by fibers but in native it is OS threads (and I know it because I read the release notes and implementations).

More specifically I mean documentation around implementation in this [folder](https://github.com/scala-native/scala-native/tree/main/javalib/src/main/scala/java/util/concurrent) and the best way to use them.

**Comment by armanbilge** [comment]
> More specifically I mean documentation around implementation in this [folder](https://github.com/scala-native/scala-native/tree/main/javalib/src/main/scala/java/util/concurrent) and the best way to use them.

Aha, those are implementations of the JDK concurrency API. To learn the best way to use them, I encourage you to read any tutorial or book about concurrent programming in Java.

**Comment by amsen20** [comment]
Thanks for the advice but I am more interested in the native part of the scala. (as I am trying to implement projects for the Scala native). So a book/blog/documentation about the native scala implementation for multi-threading other than the main thesis and release notes would be helpful a lot.

**Comment by amsen20** [comment]
And also, do the native implementations guarantee to behave the same as their JDK counterparts in the link you provided?
If yes reading the documentation would be greate next step for me.

**Comment by armanbilge** [comment]
> And also, do the native implementations guarantee to behave the same as their JDK counterparts in the link you provided?

Yes. If you find that they behave differently, that's a bug and we should fix it :)

---

> I am more interested in the native part of the scala

If you want to learn more about native APIs, instead I direct you to C documentation e.g.

https://man7.org/linux/man-pages/man7/pthreads.7.html

---

> So a book/blog/documentation about the native scala implementation for multi-threading

Multithreading in Scala Native is fairly new, so the best source of information about how it works is reading the code and discussions on GitHub. However for the most part, Scala Native is directly implementing the JDK concurrency APIs using C APIs. Even most of those implementations are more-or-less direct ports of their [Java counterparts](https://gee.cs.oswego.edu/dl/concurrency-interest/).

So understanding the JDK APIs and understanding the C APIs will help you a lot to understand how Scala Native works.

Some parts of Scala Native are experimental and research e.g. @natsukagami's work. This is also new and developing.

**Comment by amsen20** [comment]
Great thank you!
