### ISSUE TITLE
Incorrect codegen in `getkyo/kyo`

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#4082]
Needs to be minimized based on https://github.com/getkyo/kyo/issues/845

**Comment by fwbrasil** [comment]
I forgot to mention that the issue happens only in Linux. It's ok in my Mac. Minimized version:

```scala
object repro extends App:

    def test[I[_], O[_], S](f: [C] => (I[C], I[C] => O[C]) => O[C]): Unit = ()

    val x = test[List, List, Any]([C] => (input, cont) => List.empty)

    println(x)
end repro
```

**Comment by WojciechMazur** [comment]
Strange, it should not depend on the OS. I was able to reproduce it on Mac. Anyway there's a fix for that. It would be shipped in the next relelease

**Comment by fwbrasil** [comment]
@WojciechMazur thank you for the quick turnaround!
