### ISSUE TITLE
Did commit b780d6f (publish local changes) break scala-native "getting started"?

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#410]
Looks like the publish local changes in commit b780d6f broke the introduction
to scala-native getting started instructions at URL:
   http://scala-native.readthedocs.io/en/latest/index.html

Specifically the line "now simply run sbt run to get everything compiled and have the expected output!"
on page: http://scala-native.readthedocs.io/en/latest/user/sbt.html#sbt

I am just starting with scala-native . When I following those excellent instructions
 and ended up with missing *-SNAPSHOT* dependencies. Looks like I caught
things betwixt & between.

Thought I would report my experience, to smooth other peoples starting
experience with scala-native. Sorry if I made a mistake at my end.

Most importantly, thank you for scala-native.  I am most interested
in seeing it progress.

 Lee

**Comment by LeeTibbert** [comment]
Supporting info:
 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-native#nativelib_native0.1.0-SNAPSHOT_2.11;0.1.0-SNAPSHOT: not found
[warn] 	:: org.scala-native#javalib_native0.1.0-SNAPSHOT_2.11;0.1.0-SNAPSHOT: not found
[warn] 	:: org.scala-native#scalalib_native0.1.0-SNAPSHOT_2.11;0.1.0-SNAPSHOT: not found
[warn] 	:: org.scala-native#nscplugin_2.11.8;0.1.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by densh** [comment]
@LeeTibbert Thanks a lot for the report! We've just updated the docs in https://github.com/scala-native/scala-native/pull/411/files to fix the issue.
