### ISSUE TITLE
 warning: overriding the module target triple with x86_64-unknown-linux-gnu [-Woverride-module]

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#414]
llvm should be aware of target

http://clang.llvm.org/docs/CrossCompilation.html#general-cross-compilation-options-in-clang

**Comment by densh** [comment]
This is caused by the fact that we don't specify compilation target in the emitted code. Simple fix for this would be to use `$ llvm-config --host-target` to explicitly define host target and the compilation target.
