### ISSUE TITLE
Scala-native scala println appears broken/no-op/not-yet-implemented/black-hole-sink

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#426]
In issue #413, I reported running the tutorial example (not demo) program and
getting no output. I am closing that issue and opening this one because I have
developed more specific information.

Forgive me if this is a known issue or design decision.  Looks like a 
regression to me, so I am reporting. 

The impact of this issue is that others may try to follow the
tutorial, encounter this issue, and be turned of to scala-native.

Short story:

It appears that the scala-native implementation of scala println is broken or
a no-op or not-yet-implemented or a black-hole-sink-to-dev-null.

Longer story.

The demo code at scala-native-example (& scala-native/demo)
builds and executes just fine (once one manually folds in
pending snapshot repository dependencies).  Thank you for
the wonderful example.

When, in the same project, I replace smallpt.scala by
the HelloWorld.scala code at  the 'getting started' [tutorial]
(http://scala-native.readthedocs.io/en/latest/user/sbt.html#sbt)
execution fails. The main seems to run but there is no output (stdout).

No surprise almost identical code at scala-native/sandbox/Test.scala
also fails in the same way.

The apparently significant difference between the cases which work
and those which do not is that the former use C fprintf and the latter
use scala println. Both System.out.println & Console.println fail in the
same way).

Being a great believer in the Koch tests, I made the minor edits
necessary to convert HelloWorld.C to use fprintf. 
HelloWorld_fprintf.scala gives the expected, visible output.

This seems to indict scala println.

I found the PrintStream.scala  and PrintWriter.scala
sources at ~/Sandbox/scala_native/scala-native-master/javalib/src/main/scala/java/io
but could not see an obvious error.

Now that I know that my system configuration is OK and that scala-native
really does call the main program, I can fall back, use fprintf, and wait
for the fullness of time.

**Comment by densh** [comment]
Can you please provide more details about your environment, e.g. versions of OS/Clang/LLVM.

**Comment by LeeTibbert** [comment]
Gladly. Please let me know if you would like additional info.

```
HW: Intel 32

OS: Ubuntu 16.10 with latest (daily) updates

    Ubuntu did make a change in the -noPIC (?) flags it
    uses with gcc but that info seems not to be relevant
    here.

Kernel: Linux 4.9-rc8 (custom running BFQ I/O scheduler)

    Does not seem like a kernel issue, but for grins I will
    try with current stock Ubuntu 16.10 kernel.
```
```
$ clang -v
clang version 3.8.1-12ubuntu1 (tags/RELEASE_381/final)
Target: i686-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.4.1
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.2.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.2.0
Selected GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.2.0
Candidate multilib: .;@m32
Selected multilib: .;@m32

$ clang++ -v
clang version 3.8.1-12ubuntu1 (tags/RELEASE_381/final)
Target: i686-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.4.1
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.2.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.2.0
Selected GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.2.0
Candidate multilib: .;@m32
Selected multilib: .;@m32

$ llc --version
LLVM (http://llvm.org/):
 LLVM version 3.8.1
  
  Optimized build.
  Built Sep 13 2016 (13:40:48).
  Default target: i686-pc-linux-gnu
  Host CPU: prescott

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    armeb      - ARM (big endian)
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    cpp        - C++ backend
    hexagon    - Hexagon
    mips       - Mips
    mips64     - Mips64 [experimental]
    mips64el   - Mips64el [experimental]
    mipsel     - Mipsel
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    r600       - AMD GPUs HD2XXX-HD6XXX
    sparc      - Sparc
    sparcel    - Sparc LE
    sparcv9    - Sparc V9
    systemz    - SystemZ
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
    xcore      - XCore

$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.10.2-b14)
OpenJDK Server VM (build 25.111-b14, mixed mode)

$ gcc --version
gcc (Ubuntu 6.2.0-7ubuntu11) 6.2.0 20161018

```
```
I believe my scala-native SNAPSHOTS are
up to date. A few minutes ago, I 
deleted ~/.scalanative & did an sbt
update in my minimal project for this issue.
same result: no scala println output
```
```
Phase of Moon: various, currently waxing gibbous
Magnetic declination: 5° 34' W 
```

**Comment by densh** [comment]
> HW: Intel 32

I think that's our problem right there. We've not ported Scala Native to 32-bit yet. We currently test on 64-bit intel on Linux and macOS. People reported it working on 64-bit ARM. 

Thanks for the report we'll put it on the stack of platforms to support in the future.

**Comment by LeeTibbert** [comment]
@densh, Thank you for looking at this.  Looks like I am living beyond the
frontier. Exciting!

It looks like a lot of friendly work has gone into scala-native
README.md & the readthedocs tutorial.  I, for one, found them
quite helpful. 

It might reduce your support costs and ease your first contact
with new users to add the text similar to (freely cribbed from
your reply) to each: 
```
We currently test on 64-bit Intel on Linux and macOS. 
People have reported it working on 64-bit ARM. Some but 
not all (not printf) X86 32 bit features are reported working.
```

For my own understanding & if I get time I may dive down
the implementation stack to see where this goes off the
rails for 32 bit. Probably a block copy or such.

**Comment by LeeTibbert** [comment]
@densh 
If/when the time comes that you are beginning to think about adding
X86 support, please feel free to contact me.  I do not have a 64 bit
for testing, but I am willing, depending upon what else is going on
in my life, to submit PRs for the easier issues. The double NUL
and fwrite issues are beyond me but the others look possible.

I feel it is not fair for me to create a bunch of issues and at least
not offer to submit PRs at the appropriate time.  I understand entirely
that right now you folks have greater issues.

I look forward to tracking scala-native development (and having
my private port track it, best effort). 

Thank you.

Lee

**Comment by densh** [comment]
I've created a big summary issue https://github.com/scala-native/scala-native/issues/727 to accumulate all reports on x86.
