### ISSUE TITLE
scala-native javalib strings appear with 2 initial NULs?

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#441]
<h5>Prolegomenon:
</h5>

 I observed this problem in X86 32-bit, which I know to be
untested & unsupported. I am creating this issue in case valid
64 bit users also see it. If that happens, this "heads up" can
be raised to a proper bug report.

<h4> Observed Behavior</h4>

Whilst chasing my missing scala println output, I discovered what
may be a problem with scala-native javalib strings. Namely,
the first two bytes appear as NULs, The rest of the string
is shifted right by two places & truncated at the original string 
length.  That is, "abcdef" becomes (using 0 for NUL) "00abcd"

This behavior is totally determinate, it happens the same way every
run.

ScalaJVM does not have this issue.

I suspect the offset variable, in _String class,  based on no evidence 
beyond the name.  If I am able to create more debugging time,
I will try to better localize this issue, starting with _String
constructors.

<h4> Curious output from a dead simple SBT project:
</h4>

```
./target/scala-2.11/study_broken_strings-out 
str.len is 6
str(0) is ||
str(1) is ||
str(2) is |a|
str(3) is |b|
str(4) is |c|
str(5) is |d|
str(0) is NULL
str(0) is decimal 0
str(1) is NULL
cstr(1) is decimal 0
```
Code, sorry that it is raw, not presentation:
```
package example

import scalanative.native._, stdlib._, stdio._, string.strlen

object Main {
  def main(args: Array[String]): Unit ={

    val str = "abcdef"

    stdio.printf(c"str.len is %d\n", str.length)

    stdio.printf(c"str(0) is |%c|\n", str(0))
    stdio.printf(c"str(1) is |%c|\n", str(1))
    stdio.printf(c"str(2) is |%c|\n", str(2))
    stdio.printf(c"str(3) is |%c|\n", str(3))
    stdio.printf(c"str(4) is |%c|\n", str(4))
    stdio.printf(c"str(5) is |%c|\n", str(5))


    if (str(0) == 0.toByte)
      stdio.printf(c"str(0) is NULL\n")
    else
      stdio.printf(c"str(0) is not NULL\n")

    stdio.printf(c"str(0) is decimal %d\n", str(0).toInt)

    if (str(1) == 0.toByte)
      stdio.printf(c"str(1) is NULL\n")
    else
      stdio.printf(c"str(1) is not NULL\n")

    stdio.printf(c"str(1) is decimal %d\n", str(1).toInt)
  }   
}

```

<h4>Impact.
</h4>

The full string with initial NULs gets passed back up the
call chain by toCString(). Subsequent calls to the C printf family  
print what they believe to be an empty  NUL terminated string.

In the short run, this makes debugging efforts hard because
dynamic strings, such as those giving variable values, are
not available.

In the middle run, I am hoping that this is the cause of my
missing scala println output.  Seems like a candidate.

**Comment by densh** [comment]
String lowering inserts padding in https://github.com/scala-native/scala-native/blob/master/tools/src/main/scala/scala/scalanative/optimizer/pass/StringLowering.scala#L37 which is not necessary on `x86`.

**Comment by LeeTibbert** [comment]
@densh 
Thank you for looking at this and for the specific line of code.
I hacked my local copy & did a publishLocal.  That gave
me toCString() and got me on my way debugging.

If it has been 6 months since that edit was introduced, 
probably not many people trying to use scala-native
on X86.

**Comment by densh** [comment]
I've created a big summary issue https://github.com/scala-native/scala-native/issues/727 to accumulate all reports on x86.
