### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by hustnn** [scala-native/scala-native#443]
I try to compile scala-native by running sbt the scala-native root path and met this problem:

unresolved dependency: org.scala-native#sbt-cross;0.1.0-SNAPSHOT: not found****

Is there anything wrong?

Thanks.

**Comment by hustnn** [comment]
I resolved this problem by cloning https://github.com/scala-native/sbt-cross and use sbt publishLocal to generate the local repository for sbt-cross.

**Comment by densh** [comment]
Hi @hustnn, currently before we publish `sbt-cross` non-snapshot release one has to build it locally before building Scala Native. Our [travis script](https://github.com/scala-native/scala-native/blob/master/.travis.yml#L51) always contains reference build sequence for the project.
