### ISSUE TITLE
Equality between boxes of different types has wrong semantics

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#445]
```scala
object Test {
  def main(args: Array[String]): Unit = {
    val x: Any = 66
    val y: Any = 66.toByte
    println(x == y)
  }
}
```
This should print `true`, but prints `false` at the moment.

**Comment by sjrd** [comment]
You need to call [`BoxesRunTime.equals`](https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/scala/scala/runtime/BoxesRunTime.scala#L67) when translating an `==` primitive in the scalac back-end.

**Comment by densh** [comment]
Yep, currently we mistakingly just call `java.lang.Object.equals` instead. It obviously doesn't support cooperative equality between primitive boxes.

**Comment by sjrd** [comment]
Well in fact, in the case of SN, you *could* actually change `Integer.equals` and friends so that they *do* support cooperative equality. That would help SN with the bad `==` performance of Scala. But you will have to trade some of the semantics of `Object.equals` for that.

**Comment by densh** [comment]
Alternatively, we can also add a new virtual method (e.g. `java.lang.Object.==` that behaves) like cooperative Scala equality from `BoxesRunTime.equals` and is overridden for all box types without touching `equals`. Win-win. 👏
