### ISSUE TITLE
Casting error when trying to cast an array of primitive into a pointer

### ISSUE THREAD

**Issue by cedricviaccoz** [scala-native/scala-native#449]
```scala
import scalanative.native._, stdlib._, stdio._

object Test {
  def main(args: Array[String]): Unit = {
    val bytes = new Array[Byte](2)
    bytes(0) = "b".toByte
    bytes(1) = "a".toByte
    val p: Ptr[Byte] = bytes.asInstanceOf[scala.scalanative.runtime.ByteArray].at(0)
    assert(!p == "b".toByte)
    assert(!(p+1) == "a".toByte)
  }
}
```
Runnin this code result in a ``` scala.scalanative.util.package$UnsupportedException: can't cast from I(32) to I(8) (class java.lang.String) ```

**Comment by densh** [comment]
I can't reproduce this one, I made a PR #452 to ensure that it indeed works as expected.

I think the issue was that you didn't do full clean rebuild after rebasing on top of master.

**Comment by densh** [comment]
`"b".toByte` fails with an exception, that was the real failure there. You probably wanted `'b'.toByte`.
