### ISSUE TITLE
Developer guide

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#45]
Things that need to be covered in the guide:
- [x] Building and running Scala Native projects with sbt
- [x] Overview of low-level language extensions in Scala Native
- [x] Writing bindings for C libraries 
- [x] Publishing NIR for Scala libraries with sbt

**Comment by frgomes** [comment]
List of requirements:
$ apt-get install clang-3.8 # what else?

**Comment by densh** [comment]
Need to mention that Java 8 is required as a build dependency (e.g. https://github.com/scala-native/scala-native/issues/179)

**Comment by densh** [comment]
I've been working on this lately. We have a new docs website at [scala-native.readthedocs.io](http://scala-native.readthedocs.io/). There's not much text on the language and interop yet, that's something that still remains to be covered.
