### ISSUE TITLE
X86: fwrite fails to output, fprintf & fputs succeed.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#451]
For if/when X86 support becomes possible. I understand & expect
this issue to immediately go into backlog. I do not want to take
devo time.

I have managed to find the proximal cause of my zero
output from println in the "Getting Started" tutorial example.

The C function fwrite is used by 
javalib/src/main/scala/java/lang/System.scala#CFileOutputStream,
which println eventually calls.

It seems that scala-native fwrite gives zero output, causing
the behavior I was seeing.

fprintf and fputc work just fine, both with file I/0
and stdout. demo/native/smallpt.scala uses fprintf and works!
Surprisingly, to me, fputc works also, I would have expected
that to translate immediately to a call to fwrite.

fwrite in a C program works just fine. 

In examining the code, the major difference I see between
fwrite & the calls that work is that fwrite takes two CSize
parameters.  I tried various ways (strlen, cast, etc.) of 
specifying those parameters and could not figure it out.

When I hack my local copy of CFileOutputStream to use
fputc, the example program works for me.  Better yet,
I can run the test suite in unit-tests and see something
useful. Yeah!

I hope this report is useful to you.

Lee
happily running on my locally published copy

**Comment by densh** [comment]
Thanks for the investigation!

**Comment by densh** [comment]
I've created a big summary issue https://github.com/scala-native/scala-native/issues/727 to accumulate all reports on x86.
