### ISSUE TITLE
X86:  SizeofSuite.scala test of pointer size fails

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#478]
One more for the X86 backlog corral, if/when if X86 support is ever considered.

Pull #472  added unit-tests/src/main/scala/scala/scalanative/native/SizeofSuite.scala.
The test of pointer size in that suite Is doing its job. On 32 bit systems, it correctly
detects that pointers are not 8 bytes.

On my 32 bit system, changing the test to expect 4 bytes works.

No smoke yet in the rest of scala-native for me after rebuilding with this pull.

**Comment by densh** [comment]
I've created a big summary issue https://github.com/scala-native/scala-native/issues/727 to accumulate all reports on x86.
