### ISSUE TITLE
Build Documentation needs an update

### ISSUE THREAD

**Issue by yousry** [scala-native/scala-native#485]
I get following error during the scala-native build (Archlinux):

[warn]   https://repo1.maven.org/maven2/org/scala-native/sbt-cross_2.10_0.13/0.1.0-SNAPSHOT/sbt-cross-0.1.0-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-native#sbt-cross;0.1.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.scala-native:sbt-cross:0.1.0-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scala-native:sbt-cross:0.1.0-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13) (/home/yousry/Dokumente/sourceProjects/scala-native/project/build.sbt#L21-22)
[warn] 		  +- default:scala-native-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.scala-native#sbt-cross;0.1.0-SNAPSHOT: not found

**Comment by densh** [comment]
Thanks for the report!

**Comment by densh** [comment]
Fixed in #526
