### ISSUE TITLE
X86: compensating for libunwind

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#491]
For the X86 hobbyist following along at home, not to distract
devos from mainline work:

Commit #477 introduced the use of libunwind.  At least on
Ubuntu 16.10 32-bit some changes are needed beyond 
installing the libunwind package in order for the link & run
to succeed.

There are probably a number of ways to compensate. I will
describe what, of the ways that I tried, I found easiest. 

Note well: for me this got the link & run of my private Cfunction
project to work & the tests, benchmarks, & nativeDemo targets
of sbt-native to link & run.  I believe that I have not hit a case
where the libunwind code is invoked, so I have no idea what will
happen then.

The basic idea I used was to use symbolic links to build on
what scala-native was already providing.  This meant minimal
changes to my project & my local scala-native.

Steps:

0. Install 3 libunwind packages (especially libunwind-dev & its dependency).

1. Create a well known, common to all local projects directory. Here I call it /foo/bar/Clib

2. cd to /foo/bar/Clib and create (ln -s) links to libunwind shared libraries. __Note well the
    name changes/redirection.__  Here I use the Ubuntu X86 names, The .8 will almost 
certainly change  in the future. For a number of reasons, I did not want to create
 proper links in the /usr/lib/ i386-linux-gnu system library).
```
ls -l
total 8
lrwxrwxrwx 1 ZZZ ZZZ 49 42 Jan 16 16:10 libunwind-i686.so -> /usr/lib/i386-linux-gnu/libunwind-x86.so.8
lrwxrwxrwx 1 ZZZ ZZZ 38 Jan 16 16:10 libunwind.so -> /usr/lib/i386-linux-gnu/libunwind.so.8
```
3. Add the following line to local project build.sbt (and, adapted, to local sbt-native, for tests/run & friends)
```
      nativeClangOptions ++= Seq("-L" ++ "/foo/bar/Clib")
```

**Comment by densh** [comment]
> I believe that I have not hit a case
where the libunwind code is invoked, so I have no idea what will
happen then.

We use libunwind to generate friendly stack traces when application crashes. You can trigger libunwind invocation by doing `(new Exception).printStackTrace()`. 

> For a number of reasons, I did not want to create
proper links in the /usr/lib/ i386-linux-gnu system library

We attempt to link with correct platform-specific part libunwind automatically in the sbt plugin:

https://github.com/scala-native/scala-native/blob/master/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala#L193

This part might need a patch for x86 to remove an extra step of aliasing system libraries.

**Comment by densh** [comment]
I've created a big summary issue https://github.com/scala-native/scala-native/issues/727 to accumulate all reports on x86.
