### ISSUE TITLE
Warning in new MathSuite.scala

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#492]
@gregor-i 

First of all, thank you for the correction to Math.min (good catch!) & the new MathSuite.scala.

Commit #489 introduced the new file MathSuite.scala.  When I build tests, I get the warning:
```
[warn] /scala_native/scala-native-git/unit-tests/src/main/scala/java/lang/MathSuite.scala:3: imported `Math' is permanently hidden by definition of object Math in package lang
[warn] import java.lang.Math
```
This warning looks to be legitimate (and architecture independent). 

 I believe the fix is to either simply remove the import or comment it out, with an
 explanation that the intent is to use the package Math object 
(so that is the one being tested). You may have intended something else.

I hope this is useful to you.

**Comment by densh** [comment]
Indeed, this import is not necessary. Thanks for the report!
