### ISSUE TITLE
native libs in ~/.scalanative is unexpected

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#505]
native libs are compile to `~/.scalanatve` https://github.com/scala-native/scala-native/blob/master/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala#L43

I think we should keep it in the baseDirectory. It can be confusing to check at multiple places to do a clean rebuild.

**Comment by densh** [comment]
I agree, minor duplication across projects should not be an issue and will make things far less surprising.

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/508
