### ISSUE TITLE
CSize should be unsigned 

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#519]
My language lawyer license has long expired, so please forgive
the waste of valuable devo time if I am just muddled here.

In scala-native-git/nativelib/src/main/scala/scala/scalanative/native.package CSize
is defined as type Word, which is defined as type Long, which is signed.
```
type CSize = Word

 /** Int on 32-bit architectures and Long on 64-bit ones. */
type Word = Long
```
if CSize is supposed to be a strict analog for the C language  size_t,
shouldn't the underlying type be UWord, which is a ULong?
ssize_t is the signed variant.

I do not have a test case, but I would expect a test case such 
as (strlen(longString) > 0) to fail when the string had a length
greater than 32K.  Since size_t is expected, by the standard,
to hold at least 64K, this could probably happen.

The ULong to Long, unsigned to signed issue, probably gets
handled somewhere further down in the internals. Changing
to unsigned would preserve intended types to at least this level,
increasing readability/traceability/believability.

Thank you.
Lee

**Comment by densh** [comment]
That's a bug, thanks!

**Comment by densh** [comment]
It's an artefact of older times when we haven't had unsigned types yet. It will have to stay this way for 0.1 and we'll change it to become unsigned in next breaking release.
