### ISSUE TITLE
X86: Multiple test failures after PR #520 (Memory layout, etc.)

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#527]
First & most importantly, congratulations to the scala-native team
for achieving 0.1.0. Yeah! and thank you. 

I understand entirely that 32 bit X86 is not supported. 
I suggest making this  non support boldly evident in both
the README.md and in the 0.1.0 announcement.
The 0.1.0 announcement is likely to attract a number
of new users. Some of those may be on X86 and are
likely to walk away unhappy if the support boundaries
are not made clear. The reduced support costs 
ought to justify the devo labor invested.

This a high water marker for folks attempting scala-native X86
as an at-home hobby project.  That is "this is where the world changed".

After (exactly) PR #520 (Memory Layout, clone, etc.), tests/run reports
multiple (5? 10? more than felt like counting) failures. Also the string 
output reporting the failures looks mangled (missing first 5 characters or so.)
These failures make scala-native X86 unusable.

As time allows, I will peck away at seeing if I can understand the change
which caused the problem.  At the very least, I should be able to deepen
my understanding of what the compiler is doing.

**Comment by densh** [comment]
You are absolutely right, we should make it clear in the docs what's supported at the moment.

**Comment by densh** [comment]
I've created a big summary issue https://github.com/scala-native/scala-native/issues/727 to accumulate all reports on x86.
