### ISSUE TITLE
Migrate linux travis ci to drone for faster ci cycles

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#528]
We have a beefy machine in house, let's use it!

* make shure you can login into http://drone.geirsson.com:8001
* add http://drone.geirsson.com:8001/scala-native/scala-native and http://drone.geirsson.com:8001/scala-native/sbt-crossproject
* I will remove the linux travis part and migrate it to drone.

The only difference is that we will run alpine linux with a nix packager, where in travis you run ubuntu. I can also create a ubuntu docker image if you wish.

**Comment by densh** [comment]
@MasseGuillaume Unfortunately I can not log in.

**Comment by densh** [comment]
Superseded by #1060.
