### ISSUE TITLE
show sub-projects status

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#531]
Scala-Native is evolving really fast. It would be great to have a page with an overall status. What's already implemented. What's missing, What's in progress, Who is working on what, etc.

Here is what I have in my head:

Done:

* [x] Interop with C (Scala to C)
* [x] parallel compilation

In progress:

* [ ] testing framework (sbt testing interface)
* [ ] javalib
  * [ ] java.io.File
  * ...
* [ ] Improved Garbage Collection
* [ ] Google Summer of Code Student Proposals

Future Work:

* [ ] multi-threading
* [ ] x86 support
* [ ] window support
* [ ] Scala 2.12
* [ ] Interop with C (C to Scala)

We can also use the Project View to organize this: 
https://github.com/scala-native/scala-native/projects

**Comment by densh** [comment]
Good idea, thanks for suggestion!

**Comment by densh** [comment]
We don't really have resources to maintain anything apart from our issue tracker at the moment.
