### ISSUE TITLE
Exceptions thrown when trying to pass a CArray to unistd.pipe()

### ISSUE THREAD

**Issue by Korf74** [scala-native/scala-native#533]
I tried to use the pipe function from the syscalls :
`val p = stackalloc[CArray[CInt, _2]]`
`val err = pipe(!p)`

and I had this error : https://gist.github.com/Korf74/adc45412dcfdbe8b72ece5238414e824

It seems we can't use the CArray as is, we can only access its elements and manipulate a pointer to it.

**Comment by jonas** [comment]
Sounds related to #555

**Comment by densh** [comment]
Yep, that's a duplicate of #555.
