### ISSUE TITLE
Compile Java code to NIR

### ISSUE THREAD

**Issue by bzEq** [scala-native/scala-native#537]
I wonder if it is viable to compile java source code to NIR, then we might have a compiler from java to LLVM IR

**Comment by ekrich** [comment]
There was a project to do this in the past. https://vmkit.llvm.org/

**Comment by densh** [comment]
I think the idea has its merit. It might be slightly easier to compile JVM bytecode to NIR than Java source code as they are conceptually very close.

**Comment by densh** [comment]
After careful consideration we think that this is out of scope for Scala Native core. The idea is interesting and is probably going to be quite useful if implemented but we have to focus on the core product.
