### ISSUE TITLE
java.lang.String toUpperCase and toLowerCase not implemented

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#538]

**Comment by densh** [comment]
Yep, now that corresponding methods on `java.lang.Character` are fixed, these two should be quite easy to implement.

**Comment by ekrich** [comment]
This requires `java.util.Locale` which requires `java.util.Properties` which requires some notion of reading properties from the environment or variables put into the environment by the runtime. There is also reference in the Apache code of `java.security.AccessController` and the `SecurityManager` if all the API is implemented. I plan to stub out `Locale` to a certain point.

**Comment by ekrich** [comment]
Implemented via the following PR.
https://github.com/scala-native/scala-native/pull/573
