### ISSUE TITLE
Reference Counting

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#54]
As a gap stop measure if it possible to have RC variables to avoid GC by annotating them with `@rc`

**Comment by densh** [comment]
We are extremely conservative about any changes in semantics with respect to reference implementation of Scala on JVM. Currently we do not plan to adopt any non-GC memory management strategies for regular Scala allocations. Scala is a garbage collected language at its core.

**Comment by sirinath** [comment]
I am not saying that everything should be non GCed. Only if you use a variable annotated with `@rc`. LLVM should support this as Objective C and Swift uses it. For any variable without the annotation then you can use GC for the time being until https://github.com/scala-native/scala-native/issues/55. If none of the variable does not have `@rc` the whole set of variables will be GCed. This will only be opt in. Hence for the time being keep this open.

**Comment by sirinath** [comment]
This can be like use of allocators in Scala off heap but with the additional safety net of using RC to free the memory, and also having to use `@data` for definition. They will not be part of the GCed Memory.

**Comment by sirinath** [comment]
Also this is very useful to maintain hard real time SLA. E.g. this is even used in Java for HFT: https://github.com/OpenHFT/Chronicle-Core#resource-reference-counting
