### ISSUE TITLE
Effect System to Track Memory, Resource Usage and Concurrency Issues to Eliminate GC and Unnecessary Runtime Overhead for Lowest Possible Latency and Highest Possible Throughput

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#55]
Some time in the future is it possible to leverage the [effect system](https://en.wikipedia.org/wiki/Effect_system) in future Scala to track memory allocation and freeing so GC will not be necessary. Also track and identify issues like race conditions, resource contention, resource leakings. Ultimately the program should produce the results with minimum number of cycles and memory from the given input. Any code path not tainted or only partly trained by IO effect should be evaluated at compile time. Any additional runtime computation is just and overhead.

**Comment by joprice** [comment]
A reference for tracking concurrency issues using capabilities by Haller and Odersky: http://lampwww.epfl.ch/~phaller/capabilities.html.

**Comment by densh** [comment]
Research in front-end language features, like effect systems, is not the primary goal of the project. There are some plans to do experiments in this area under http://github.com/lampepfl/dotty project.

**Comment by sirinath** [comment]
Dotty being primarily JVM based cannot take advantage of the effect teaching regarding allocation and deallocation of memory. This portion of the research perhaps which should be done as part of this project. Nim language currently is GCed but looking at doing all allocation and de allocation through static analysis. It has a great effect system (http://nim-lang.org/docs/manual.html#effect-system) which perhaps can also track memory usage effects. Also can be used for better GC: http://nim-lang.org/docs/manual.html#threads-gc-safety.
