### ISSUE TITLE
Improve CONTRIBUTIONG.md

### ISSUE THREAD

**Issue by kmizu** [scala-native/scala-native#553]
I want to contribute scala-native regarding Windows support.  However, how to contribute is not written in [CONTRIBUTIONG.md](https://github.com/scala-native/scala-native/blob/master/CONTRIBUTING.md).  It is desirable that how to build and debug scala-native itself are  written since it is needed to contribute scala-native.

**Comment by densh** [comment]
Hi @kmizu, we've migrated most of the docs to `docs/` folder but forgot about this one. There is some more information about contributing in http://www.scala-native.org/en/latest/contrib/contributing.html

**Comment by densh** [comment]
Additionally, dropping by for a quick gitter chat is good place to start.

**Comment by kmizu** [comment]
@densh Many thanks.  I'll read http://www.scala-native.org/en/latest/contrib/contributing.html
