### ISSUE TITLE
Extern function without return type

### ISSUE THREAD

**Issue by regb** [scala-native/scala-native#554]
Hello,

I'm getting a segmentation fault because I forgot to annotate a return type to an @extern function. Obviously it's my mistake, but the issue was quite challenging to track down without some compiler error. Here is a minimal example:

mport scalanative.native._

```
object Main {
  import SDL._  
  def main(args: Array[String]): Unit = {
    println("Hello Native")
    SDL_Delay(2000.toUInt)
    println("done waiting")
  }
}
@extern
@link("SDL")
object SDL {
  def SDL_Delay(ms: UInt) = extern
}
```

**Comment by sjrd** [comment]
In Scala.js we have some front-end code to protect users from the same mistake: https://github.com/scala-js/scala-js/blob/v0.6.14/compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala#L986

**Comment by densh** [comment]
Another instance of #317, thanks for the report!
