### ISSUE TITLE
Scala.js and Apache Harmony license violation

### ISSUE THREAD

**Issue by fommil** [scala-native/scala-native#561]
scala-native does not include the copyright headings, NOTICE or LICENSE file necessary when including code copied from Apache Harmony or Scala.js. This is a license violation.

In addition, you should be aware that contributors who submit code that they have not written themselves are explicitly breaking the terms of the Scala CLA. I have added wording to this effect in #560 which I feel captures what you actually want... but you should check this with the EPFL legal department to ensure that they are happy that you are distributing (at least parts of) scala-native under the terms of the Apache 2.0 license.

**Comment by sjrd** [comment]
For Scala.js, there cannot be any license violation, since the two projects have the same license and are bound by the same CLA, which covers any project copyrighted by EPFL.

**Comment by fommil** [comment]
@sjrd it was called the BSD-3 in the docs, do you use the Scala License? (the copyright notice is part of the license with BSD licenses... so the exact full text must be copied even if the clauses are the same)

**Comment by fommil** [comment]
https://github.com/scala-js/scala-js/blob/master/LICENSE ok, then scalajs is ok here. But you must then apply the same level of rigour in our code as I'm proposing in the scala-native PR.

**Comment by fommil** [comment]
(btw, everybody accepting contributions under the Scala CLA need to be more careful about making a distinction between **who** wrote the code, regardless of the license, because it is a CLA violation even if it is not a License violation)
