### ISSUE TITLE
don't break JVM/JS builds in same project when clang isn't present

### ISSUE THREAD

**Issue by SethTisue** [scala-native/scala-native#562]
details at https://github.com/scala/community-builds/issues/500

note that I wasn't trying to actually compile a Scala Native based subproject here — I was just trying to run sbt in order to compile the JVM version of scalaz. but the mere presence of the Scala Native sbt plugin in projects/plugins.sbt stopped me.

can this be handled differently in the plugin...?

**Comment by SethTisue** [comment]
(scalaz is only the first of the 90 projects in the Scala community build to add Scala Native support, but I expect — and hope — that there will be more soon)

**Comment by MasseGuillaume** [comment]
So you still want to build JVM/JS. Do you want it to fail only when running scala-native task?

**Comment by SethTisue** [comment]
right. I won't be running those, but their mere presence in the build shouldn't prevent me from getting other work done.

**Comment by MasseGuillaume** [comment]
Agreed. On a tangent note. Would it be possible to support the Scala-Native target in dbuild? There is only a few dependenties to add.

**Comment by MasseGuillaume** [comment]
@densh I'm fixing this right now.

**Comment by SethTisue** [comment]
> Would it be possible to support the Scala-Native target in dbuild?

@MasseGuillaume I'd suggest asking Toni about it either at https://github.com/typesafehub/dbuild/issues/193 or in a new ticket

**Comment by densh** [comment]
The fix is coming in 0.2 that's tentatively planned for next week.
