### ISSUE TITLE
java.util.Date is not implemented

### ISSUE THREAD

**Issue by mscharley** [scala-native/scala-native#563]
I wonder if it's worth digging all the way into the Calendar API just yet or if we could at least get out a basic implementation of `java.util.Date` from the 1.0 JDK spec as a simple way to get *some* interface to the system time.

Further to this, it looks like nativelib doesn't have an implementation for `time.h` yet either. How much is involved to get these bindings off the ground?

**Comment by densh** [comment]
Related: https://github.com/scala-js/scala-js-java-time

I think we should cross-compile that one for native and concentrate our Date-related efforts over there.

**Comment by densh** [comment]
Oh, wait. `java.util.Date` is part of the Scala.js core, not scala-js-java-time. And implementation is based on JavaScript time api. We need to implement it ourselves then.

**Comment by densh** [comment]
Initial support in #602 but we still have more work to do for feature completeness wrt Scala.js
