### ISSUE TITLE
Proposal: embed resources into executable

### ISSUE THREAD

**Issue by regb** [scala-native/scala-native#567]
Currently, the resource folder seems to be ignored by the packaging system. On the JVM, a JAR file contains resources as well, and the JDK exposes some API to access these files, in particular:

    def getResource(name: String): URL
    def getResourceAsStream(name: String): InputStream

It would be quite nice if we could pack the content of the resource folder into the executable, with these functions providing a way to extract the data as files.

**Comment by ekrich** [comment]
Excellent proposal: This may be related to #155 where we would like DLLs or shared object files as there are cross platform and build changes needed. Libraries may need resources as well.

This may be a bit more high level as it involves user application packaging. 

The next level up to package for a distribution seems to be covered by https://github.com/sbt/sbt-native-packager

I looked around to found this first for just resource files in C.
http://stackoverflow.com/questions/1997172/is-there-a-linux-equivalent-of-windows-resource-files

Points to the following:
http://www.linuxjournal.com/content/embedding-file-executable-aka-hello-world-version-5967

And Mac uses resource bundles.
https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1

Windows:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa380599(v=vs.85).aspx

**Comment by densh** [comment]
Thanks for the proposal @regb, we'll definitely review for inclusion in one of post-0.2 releases !

**Comment by jonas** [comment]
If we disregard support for dynamic linking, resources could be bundled by packaging the executable as a zip file with the binary as the prelude and open `argv[0]` to read resources from the zip

**Comment by benwaffle** [comment]
GTK+ apps use [gresources](https://developer.gnome.org/gio/stable/glib-compile-resources.html) for bundling files into the executable. It produces a .c file containing a byte array encoded as a [GVariant](https://developer.gnome.org/glib/stable/glib-GVariant.html) db with all the data and registers it on startup. On Linux it puts it in its own ELF section.

**Comment by Andrei-Pozolotin** [comment]
+1 https://gitter.im/scala-native/scala-native?at=5ab570c1e4ff28713a68da2a

**Comment by ahjohannessen** [comment]
+1

**Comment by felipe-vieira0** [comment]
+1 for this!

**Comment by WojciechMazur** [comment]
Base64 approach was implemented in PR #2475
