### ISSUE TITLE
Implement System.getProperties and related methods

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#577]
Properties are needed specifically to support creating the `Locale.getDefault` method which supplies the default Locale. Currently this is defaulted to `US en`. This relies on reading `env` variables and/or using various native functions. For this task we need `user.country` and `user.language` via C or parsed from LANG env variable.

- Needs #556 to read from the environment
- Or, `System.getenv` - `def getenv(): Map[String, String]`

The following are the properties retrieved from my machine using JDK 8. Probably would focus on the most important or ones of interest.

-- listing properties --
- [ ] java.runtime.name=Java(TM) SE Runtime Environment
- [ ] sun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk...
- [ ] java.vm.version=25.66-b17
- [ ] gopherProxySet=false
- [ ] java.vm.vendor=Oracle Corporation
- [ ] java.vendor.url=http://java.oracle.com/
- [ ] path.separator=:
- [ ] java.vm.name=Java HotSpot(TM) 64-Bit Server VM
- [ ] file.encoding.pkg=sun.io
- [ ] user.country=US
- [ ] sun.java.launcher=SUN_STANDARD
- [ ] sun.os.patch.level=unknown
- [ ] java.vm.specification.name=Java Virtual Machine Specification
- [ ] user.dir=/Users/eric/workspace/scala-native-sc...
- [ ] java.runtime.version=1.8.0_66-b17
- [ ] java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
- [ ] java.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk...
- [ ] os.arch=x86_64
- [ ] java.io.tmpdir=/var/folders/p3/jyf7rkws0899cy450njtg...
- [ ] line.separator=

- [ ] java.vm.specification.vendor=Oracle Corporation
- [ ] os.name=Mac OS X
- [ ] sun.jnu.encoding=UTF-8
- [ ] java.library.path=/Users/eric/Library/Java/Extensions:/...
- [ ] java.specification.name=Java Platform API Specification
- [ ] java.class.version=52.0
- [ ] sun.management.compiler=HotSpot 64-Bit Tiered Compilers
- [ ] os.version=10.11.6
- [ ] http.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
- [ ] user.home=/Users/eric
- [ ] user.timezone=
- [ ] java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
- [ ] file.encoding=UTF-8
- [ ] java.specification.version=1.8
- [ ] user.name=eric
- [ ] java.class.path=/Users/eric/workspace/scala-native-sc...
- [ ] java.vm.specification.version=1.8
- [ ] sun.arch.data.model=64
- [ ] java.home=/Library/Java/JavaVirtualMachines/jdk...
- [ ] sun.java.command=LocaleTest
- [ ] java.specification.vendor=Oracle Corporation
- [ ] user.language=en
- [ ] awt.toolkit=sun.lwawt.macosx.LWCToolkit
- [ ] java.vm.info=mixed mode
- [ ] java.version=1.8.0_66
- [ ] java.ext.dirs=/Users/eric/Library/Java/Extensions:/...
- [ ] sun.boot.class.path=/Applications/eclipse.app/Contents/Ec...
- [ ] java.vendor=Oracle Corporation
- [ ] file.separator=/
- [ ] java.vendor.url.bug=http://bugreport.sun.com/bugreport/
- [ ] sun.cpu.endian=little
- [ ] sun.io.unicode.encoding=UnicodeBig
- [ ] socksNonProxyHosts=local|*.local|169.254/16|*.169.254/16
- [ ] ftp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
- [ ] sun.cpu.isalist=

**Comment by asoltysik** [comment]
I am going to work on this issue.

**Comment by ekrich** [comment]
I was going to work on it so I could get the properties needed to create the Locale which I was working on but I could look for something else.

**Comment by ekrich** [comment]
Was doing some playing on the JVM with the following code.
```
//System.setProperties(new Properties()) // does work
    val props = System.getProperties
    props.list(System.out)
    //LANG does not show even with env
    val env = System.getenv
    println("Env: " + env)
    val lang = System.getenv("LANG")
    println("Lang: " + lang)
    val is = Runtime.getRuntime.exec("env").getInputStream
    var data = is.read()
    while(data != -1) {
      data = is.read()
      print(data.toChar)
    }
```
Note that the env var `LANG` which we need to parse to get `user.country` and `user.language` does not even show from the JVM. Clearly it is set on my box.
```
Erics-MBP:scala-native eric$ echo $LANG
en_US.UTF-8
Erics-MBP:scala-native eric$ env | grep LANG
LANG=en_US.UTF-8
```
In the JVM there is the security manager and there could be some reason that it does not show from the env. Hope this helps.

**Comment by asoltysik** [comment]
Actually, according to API specification, default user locale is determined on startup and is not accessible from `getProperties`. Do You think we should provide it through properties anyway?
