### ISSUE TITLE
Segfault in demoNative/run when running in docker

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#585]
https://platform-ci.scala-lang.org/scala-native/scala-native/20

I cannot reproduce locally.

**Comment by densh** [comment]
This needs more info on how to reproduce the failure. Neither mine local ubuntu nor Travis' environments can reproduce this failure.

**Comment by densh** [comment]
Not reproducible on latest master and 0.2.4 version of docker image.
