### ISSUE TITLE
Provide a way to determine user's operating system

### ISSUE THREAD

**Issue by asoltysik** [scala-native/scala-native#589]
To implement #577 I need to know user's operating system because properties like line separator are different on Windows and Linux. Any idea how to do that? One advice I got from @MasseGuillaume is: "you can write platform specific things with sbt and publish artifacts depending on the target".

**Comment by Duhemm** [comment]
I wrote this while adding support for `java.io.File`:
https://github.com/Duhemm/scala-native/commit/431766543924714fb9b6b4db45061adf5bef3b1f#diff-a74c6ca6cf06fb771feb7a443c7023a4
https://github.com/Duhemm/scala-native/commit/431766543924714fb9b6b4db45061adf5bef3b1f#diff-e103faf5c980325deb947e95d3f09e44

**Comment by asoltysik** [comment]
Nice! Any chance it will get merged soon?

**Comment by MasseGuillaume** [comment]
@asoltysik you can copy paste that on your branch. It will get merge automatically

**Comment by asoltysik** [comment]
Oh, I will do that, thanks ;)

**Comment by densh** [comment]
Fixed in #591
