### ISSUE TITLE
Add support for interoperability via extern methods using AnyVals

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#593]
let say we have a c function returning a value (CInt).

It would be cool to lift that type into something more precise.

I tried to do that and I got a segfault, it was trying to access the location of a value (address 1 for example if returning 1).

**Comment by densh** [comment]
AnyVals work both as arguments and as return values:

```
import scalanative.native._

final case class ArgAnyVal(value: CSize) extends AnyVal
final case class RetAnyVal(value: Ptr[Byte]) extends AnyVal

@extern
object MyMalloc {
  def malloc(size: ArgAnyVal): RetAnyVal = extern
}

object Test {
  def main(args: Array[String]): Unit = {
    val ptr = MyMalloc.malloc(ArgAnyVal(16)).value
    !ptr = 10.toByte
    println(!ptr)
  }
}
```
This runs and prints 10.  Feel free to reopen if you have a more concrete example that fails.
