### ISSUE TITLE
Add support for `sun.misc.Unsafe`

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#594]
Many Java and Scala libraries use this class to get around JVM restrictions and it tends to be used in many high performance libraries such as Spark. Use of this Java internal library is so widespread that Oracle plans to make portions of this API formal as a public API. See the following as a starting point to the issue: https://blogs.oracle.com/java/get-ready-jdk9

**Comment by densh** [comment]
This one has largely been a non-issue so far. As long as you can do equivalent things with our interop (and you can) you can use cross-projects to either use `sun.misc.Unsafe` or `scalanative.native` APIs depending on the platform.
