### ISSUE TITLE
Enhance java.util.Locale to create the Locale based on the system environment

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#595]
The following system properties are needed:
- `user.country`
- `user.language`
- `user.variant`

Blocked by https://github.com/scala-native/scala-native/issues/577
Active pull request to solve this issue - https://github.com/scala-native/scala-native/pull/573
References: http://www.oracle.com/us/technologies/java/locale-140624.html

**Comment by densh** [comment]
Thanks for looking into this!

**Comment by asoltysik** [comment]
#591 Although I currently cannot find a way to get `user.variation` on Windows. Is that necessary or can it be omitted for now and implemented later when I find something?

**Comment by ekrich** [comment]
Country and language are most important.

**Comment by WojciechMazur** [comment]
java.text package was removed in #2079. Also System properies are populate with "user.language" and "user.country"
