### ISSUE TITLE
Add support for pointer substraction

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#598]
https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/scala/scala/scalanative/native/Ptr.scala

```scala
Ptr[T] - Ptr[T]
Ptr[T] + Ptr[T]
```

this one is useful in regex to find the distance(lenght) between a subsection of a string.

**Comment by sjrd** [comment]
`Ptr[T] + Ptr[T]` is not a thing. Only `-` exists.

**Comment by jonas** [comment]
I am interested in working on this, but need some help to understand the compiler part.

After adding `def -(ptr: Ptr[T]): CPtrdiff = undefined` where `CPtrdiff` is supposed to model `ptrdiff_t` I get the following `.ll` code:

```
  // ptr - ptr
  %src.14 = call i8* (i8*, i64, i8*) @"scala.scalanative.native.Ptr::-_i64_class.ssnn.Tag_ptr"(i8* %src.9, i64 4, i8* %src.12)

  // ptr - 4
  %src.19 = call i64 (i8*, i8*, i8*) @"scala.scalanative.native.Ptr::-_ptr_class.ssnn.Tag_i64"(i8* %src.9, i8* %src.7, i8* %src.17)
```

My understanding of how `PTR_SUB` is implemented, it is currently only active when argument is a primitive type. So my question is, should  `Ptr[]` be a primitive type?

**Comment by densh** [comment]
@jonas [Lets move discussion to gitter.](https://gitter.im/scala-native/scala-native?at=58e50e52f22385553d102248)

**Comment by MasseGuillaume** [comment]
Todo in the regex PR:
* [ ] remove cre2_distance in cre2.cpp
* [ ] remove cre2_distance in cre2.h
* [ ] remove cre2_distance in cre2.scala
* [ ] replace `val start = cre2_distance(m.data, in)` with `val start = m.data - in` in Matche.scala (doMatch)
