### ISSUE TITLE
Disable incremental compilation for javalib

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#599]
see https://github.com/sbt/sbt/issues/3065

I tried what they have in Scala.js but this gave me null pointer exception in NirCodeGen

https://github.com/scala-native/scala-native/blob/b211e202c22846c64e9ea2222c0b8062d85b73e8/nscplugin/src/main/scala/scala/scalanative/nscplugin/NirCodeGen.scala#L1030

**Comment by densh** [comment]
@Duhemm Seems to have discovered a workaround for this one: https://github.com/sbt/sbt/issues/3065#issuecomment-290934320
