### ISSUE TITLE
Move away from git submodules 

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#61]
Git submodules are extremely confusing as they don't get cloned by default. It looks like using something like jgit to checkout Scala standard library is in fact far superior. We'll also be able to support more than one minor version of the Scala library this way too.

**Comment by joprice** [comment]
Have you considered subtree? https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging

**Comment by densh** [comment]
Unfortunately, subtree still won't help with the cross-building across several Scala versions.

**Comment by densh** [comment]
Starting point for someone to look at this issue: https://github.com/scala-js/scala-js/blob/master/project/Build.scala#L1460

**Comment by andreaTP** [comment]
just to avoid duplicated work, I'm working on this, PR will come in the next hours...

**Comment by t-hiroyoshi** [comment]
Sorry, we conflict... X(

**Comment by andreaTP** [comment]
...sorry .... I updated dockerfile too ... let @densh choose anyhow

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/93
