### ISSUE TITLE
Meta: Potential Useful Resources

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#62]
Java Interop:
 - https://github.com/robovm/robovm/tree/master/rt
 - https://github.com/robovm/robovm/tree/master/vm

GC and Language Infrastructure:
 - https://projects.eclipse.org/proposals/omr
   - Perhaps you can use the OMR GC integrated with LLVM to get a better GC
 - Also you can explore if you can borrow something from LLILC - https://github.com/dotnet/llilc/blob/master/Documentation/llilc-gc.md, https://github.com/dotnet/llilc

**Comment by densh** [comment]
Eclipse OMR seems to be quite relevant. RoboVM has incompatible license (GPL), we can't use it in any form. I'm closing the ticket as it's not actionable.

**Comment by sirinath** [comment]
RoboVM has ASL 2.0 for part of it. At least part on which they improved on Apache Harmony. You can use the ASL 2.0 parts which has alternative definition of Java class. This is what you might need for Java Interop. The GPL part is the compile and infrastructure which you cannot use. The parts which are ASL 2.0 are:

- https://github.com/robovm/robovm/tree/master/rt
- https://github.com/robovm/robovm/tree/master/vm
- https://github.com/robovm/robovm/tree/master/cocoatouch
- https://github.com/robovm/robovm/tree/master/objc

The rest is GPL.
