### ISSUE TITLE
Some java java.util.regex.Pattern are not supported

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#620]
This issue is a follow up of https://github.com/scala-native/scala-native/pull/588.

We implemented java.util.regex with RE2. There is some mismatches with the java api:

Those patterns are not supported by RE2
  * Character Classes
    * unions: [a-d[m-p]]
    * intersections: [a-z&&[^aeiou]]
  * predefined character classes: \h, \H, \v, \V
  * java character function classes
    * \p{javaLowerCase}
    * \p{javaUpperCase}
    * \p{javaWhitespace}
    * \p{javaMirrored}
  * boundary matchers: \G, \Z, \R
  * possessive quantifiers
    * X?+
    * X*+
    * X++
    * X{n}+
    * X{n,}+
    * X{n,m}+
  * lookaheads
    * (?=X)
    * (?!X)
    * (?<=X)
    * (?<!X)
    * (?>X)

RE2 philosophy is to avoid infinite regex so they disallow lookaheads.

https://github.com/google/re2/wiki/WhyRE2
https://github.com/google/re2/blob/2017-03-01/doc/syntax.txt

**Comment by jokade** [comment]
Java-style numbered backreferences for capture groups don't work with RE2:
```scala
"showAll".replaceAll("([A-Z]","_$1")
```
gives `show_$1ll` with SN 0.3.6, instead of `show_All`

**Comment by LeeTibbert** [comment]
@WojciechMazur I believe that this can be closed.  There may be some PRs waiting to be merged.
I believe that when they are, all the patterns that are feasible to implement will have been.
In addition, I believe all the supported & unsupported patterns are documented in `docs/mumble.rst`.

Is simply is not feasible to implement some patterns, such as backtracking, in Scala Native in
economic time.  Details upon request.
