### ISSUE TITLE
Add support for Scala 2.11.11

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#629]

**Comment by sjrd** [comment]
Scala.js 0.6.15 is already available for Scala 2.11.10.

**Comment by densh** [comment]
Coming early next week, together with the other goodies in 0.2. 👏

**Comment by sjrd** [comment]
Oh lol ... I saw the notification, and blindly replied. I didn't notice the issue was on scala-native and not on scala-js :P

**Comment by densh** [comment]
It seems like [`2.11.10` is not happening either](https://github.com/scala/scala-dev/issues/359#issuecomment-293436670) and we need to wait for `2.11.11`. We'll stay on `2.11.8` for now until the problem is resolved.

**Comment by densh** [comment]
Now that 2.11.11 is out, we should use that for 0.2.
