### ISSUE TITLE
improvement idea: autogenerate JVM bindings for Scala.native code

### ISSUE THREAD

**Issue by antonkulaga** [scala-native/scala-native#641]
There is often a need to call performance-critical native code from JVM projects. It will be great if one can compile performance-critical code to Scala.native and automatically get bindings to call it from his JVM project (esp. if compiling everything to Scala.native is not possible due to dependencies on Java libs).

**Comment by jonas** [comment]
Related to #450

**Comment by antonkulaga** [comment]
Looks like I've opened a duplicate

**Comment by densh** [comment]
Yep, this one is a duplicate of #450.
