### ISSUE TITLE
Unexpected "reordering" of Thread.sleep and System.out calls

### ISSUE THREAD

**Issue by propensive** [scala-native/scala-native#646]
Running code such as the following:
```scala
object Main {
  def main(args: Array[String]): Unit = {
    println("1")
    Thread.sleep(1000)
    println("2")
    Thread.sleep(1000)
    println("3")
  }
}
```
exhibits the behavior of waiting two full seconds (producing no output), and then prints
```
1
2
3
```
at the same time.

**Comment by jonas** [comment]
`System.out` is currently implemented using C's buffered `stdio.h` primitives. To fix this `System.out` should either flush the stream after each write or use `write(STDOUT_FILENO, ...)`.

Inserting `stdio.fflush(stdio.stdout)` after each `println()` gives the expected behavior.

**Comment by densh** [comment]
This is a bug in the way we start native binary from sbt process. It currently waits for the process to complete, before showing the end result.

**Comment by densh** [comment]
Likely fixed in https://github.com/scala-native/scala-native/pull/622

**Comment by densh** [comment]
**Workaround for 0.1:** start your app manually from the shell, instead of using `sbt run`.
