### ISSUE TITLE
Meta: Critical Success Factors (CSF) for Scala Native (SN)

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#65]
I think we should think about what are the CSF which will make SN a success. Based on who SN caters for here is my 1st list:
 - High throughput
   - Close to metal performance  in comparison to C/C++, D, Rust, Swift
   - Highly optimised code
 - Low latency
   - Predictable performance with ability to manage GC gitter on critical sections
   - Highly optimised code
   - Eliminate synchronization, locking, coordination overheads and gitter
 - Hard real time commitments
   - Ability to use predictable memory usage avoiding GC gitter
   - Programmer should be able to avoid GC

**Comment by densh** [comment]
This is not an actionable item. Github Issues are not a place for open-ended discussions, we have gitter for that.
