### ISSUE TITLE
Supply an "sbt new" template for getting started

### ISSUE THREAD

**Issue by SethTisue** [scala-native/scala-native#652]
it would be pretty cool if the instructions at http://www.scala-native.org/en/latest/user/sbt.html#sbt also said "you can get the same initial project setup with a single command: `sbt new scala-native/hello-world.g8`"

**Comment by densh** [comment]
Thanks for suggestion!

**Comment by muxanick** [comment]
@densh 
I created very small hello world sample, inspired by: `https://github.com/matil019` and `https://github.com/scala/hello-world.g8`.
Before install:
http://www.scala-native.org/en/latest/user/setup.html
To install:
```
mkdir hello
cd hello
sbt new muxanick/hello-native.g8
sbt helloNative/run
```
it's just as example, need add comments to all files and move to this repo.
What do you think?

**Comment by densh** [comment]
We have two template now:

- http://github.com/scala-native/scala-native.g8
- https://github.com/scala-native/sbt-crossproject.g8
