### ISSUE TITLE
string.strtok should return CString, not CChar

### ISSUE THREAD

**Issue by rwhaling** [scala-native/scala-native#655]
I was having trouble getting `string.strtok` to work right, and noticed it's return type is `CChar` -- since the C function returns `char *`, I think that should be `CString`, instead?
http://man7.org/linux/man-pages/man3/strtok.3.html
``` 
#include <string.h>

       char *strtok(char *str, const char *delim);
```

I'll quickly submit a one-line patch now with the change, but I'm happy to write a unit test if that's merited.

**Comment by densh** [comment]
Fixed in #656
