### ISSUE TITLE
Remove the need of @struct at point of class definition

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#66]
Remove the need of @struct at the point of definition. Any class should be converted to be allocated on the stack in SN. If at all the annotation should be associated at the point of definition or the variable and not at the class definition. Having it at the point of class definition is too restrictive.

In addition you can support structs like in C#.

**Comment by densh** [comment]
Scala Native's `@struct` serves the same purpose as structs in C#. `@struct` annotation changes semantics (pass-by-value vs pass-by-reference) and therefore can't just be inserted automatically.

**Comment by sirinath** [comment]
What I meant is to have any class being able to be stack allocated like in C++. If the a class you want on the stack is in a 3rd party library you cannot make it a @struct. This is something you have to think about.

**Comment by densh** [comment]
Having every class being stack-allocated would completely change the language semantics. We can't do this.

**Comment by sirinath** [comment]
No have being able to allocate a class on the stack. Not every class. Perhaps what you need is just `val vec = stackalloc[Vec] ` without the rest.

**Comment by sirinath** [comment]
Likewise if you can devise a way to get rid of `@data` in Scala Off Heap this would be a great help.

**Comment by sirinath** [comment]
`stackalloc[Vec]` is enough information to signal this is a stack allocated object

**Comment by sirinath** [comment]
Likewise you can perhaps have `rc[Vec] ` to say this is heap allocated (off heap in Scala Off Heap) but reference counted
