### ISSUE TITLE
Inline/Seperate Project LLVM Assembly

### ISSUE THREAD

**Issue by mdedetrich** [scala-native/scala-native#67]
Definitely not top priority, but something that may be worth looking into sometime down the track, for the people that **REALLY** want their performance.

It may be possible to even provide some sought of DSL to make this easier

You could either inline it (which is popular in C), or you can do whats done in macros where the definition is put in a different place and you call it from within your code.

**Comment by sjrd** [comment]
I strongly recommend against doing this. See https://github.com/scala-js/scala-js/issues/1846 for some reasons why it's not a good idea in Scala.js, which should also apply to Scala Native.

Also any kind of such inline LLVM will prevent Scala Native's own optimizer to understand the code, and that means it will actively break code.

**Comment by mdedetrich** [comment]
> Also any kind of such inline LLVM will prevent Scala Native's own optimizer to understand the code, and that means it will actively break code.

Yes it will, its also pretty much implied/obvious. Note that it doesn't break the optimisation that LLVM will do itself (if we are inlining LLVM bytecode, rather than just raw assembler, LLVM itself will be able to optimize that with the rest of the LLVM that is generated by the project)

> Also any kind of such inline LLVM will prevent Scala Native's own optimizer to understand the code, and that means it will actively break code.

Scala-native already has things like Structs and memory allocation which normal Scala has no concept of. This isn't a convincing argument.

**Comment by densh** [comment]
We're never going to add inline assembly in any form, neither LLVM, nor platform-dependent ones to the Scala Native language itself. As @sjrd mentioned, this would add unnecessary complexity throughout the toolchain and also make it harder to read and understand Scala Native programs.

For performance-sensitive code I'd advice on trying one of two options:

1. Use lower-level features that we have (like pointers and structs), which compile down to LLVM base primitives without any additional overhead. 

2. Write LLVM assembly or even platform-dependent assembly module and then call it through an `@extern object`. This does not impose any overhead over regular function call unlike JNI. This is no different from calling normal C code. Sbt plugin needs some more work to support this kind of use case better.
