### ISSUE TITLE
Compile error on Ubuntu 16.04 with clang/llvm 3.8

### ISSUE THREAD

**Issue by mkotsbak** [scala-native/scala-native#68]
[info] Compiling 1 Scala source to [...]/scala-native/demo-native/target/scala-2.11/classes...
warning: overriding the module target triple with x86_64-pc-linux-gnu [-Woverride-module]
1 warning generated.
/tmp/demonative-out-4ef622.o: In function `demo.Main::main_class.ssnr.ObjectArray_unit':
[...]/scala-native/demo-native/target/scala-2.11/demonative-out.ll:(.text+0x1a77): undefined reference to `__stderrp'

 clang++ --version
clang version 3.8.0-2ubuntu3 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by andreaTP** [comment]
on linux you need to run
```
sed -i 's|__stdoutp|stdout|;s|__stderrp|stderr|' demo-native/smallpt.scala nativelib/src/main/scala/scala/scalanative/native/stdlib.scala
```

I've checked with clang 3.7

**Comment by mkotsbak** [comment]
Yes, the above change solved it :)

**Comment by densh** [comment]
Getting things build on Linux a bit complicated at the moment, @andreaTP's docker/ script is the easiest way to do it semi-automatically right now. We're currently working on making it easier. I've gathered all the common issues people are hitting in #102 , follow that ticket for updates.
