### ISSUE TITLE
sys/socket.h bindings

### ISSUE THREAD

**Issue by rwhaling** [scala-native/scala-native#688]
Having support for most/all of socket.h would make a lot of other things possible:

http://pubs.opengroup.org/onlinepubs/7908799/xns/syssocket.h.html
http://man7.org/linux/man-pages/man2/socket.2.html

I'd be happy to work on it if no one else is.

**Comment by densh** [comment]
Some work for this has been done in https://github.com/scala-native/scala-native/pull/530

But I agree, we should provide bindings for `sys/socket.h`.

**Comment by rwhaling** [comment]
I've been keeping an eye on #530 and now #698 -- It looks like socket.h is back up for grabs? 

Anyhow, looking at it a bit closer, getting robust cross-platform socket support could be messy.  I've started reading up on it, and the amount of ugly casts between platform-specific structs with byte-alignment requirements is kind of terrifying.

So, one way to do that would be with a .c file with some platform-specific macros.  That'd be a decent amount of work, but I'd be up for it.  I'm not sure I've fully understood the consequences of that for the Scala side, though.

Another approach would be to just define `sockaddr` itself conservatively, and treat it more like a void pointer.  This would leave actual instantiation of concrete sockets and ugly casts to application code.  If there's a long-term plan to provide some abstractions on top of the POSIX api's, this might make more sense.

Anyhow, I'd appreciate guidance if anyone else is thinking about this.

**Comment by densh** [comment]
@rwhaling Sorry for late response, but we have an outstanding PR for this now: #758

**Comment by densh** [comment]
This was a fixed a while ago under #914.
