### ISSUE TITLE
The sbt plugin sometimes freezes in `nativeTarget`

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#696]
Here's Travis' log: https://travis-ci.org/Duhemm/scala-native/jobs/228616392#L6432-L6435

This explains the timeouts that we've been experiencing on Travis. Adding some debugging output to Travis, we see:

```
...
[info] Entering nativeTarget
[info] [info] Compiling 1 Scala source to /tmp/sbt_eb6b381b/java-io-file-2/target/scala-2.11/classes...
[info] Entering NirCodeGen for Main.scala
[info] Exiting NirCodeGen for Main.scala
```

We're never leaving `nativeTarget`.

Unfortunately, I can't reproduce this reliably on my machine.

**Comment by densh** [comment]
I suspect this might have been introduced in: https://github.com/scala-native/scala-native/pull/639

**Comment by Duhemm** [comment]
A new datapoint: https://travis-ci.org/Duhemm/scala-native/jobs/228633621#L6856

It appears it failed while "Compiling to native code"...

**Comment by jonas** [comment]
Reworked the change from #639 to use files in #705

**Comment by densh** [comment]
@Duhemm We haven't been seeing this issue for a while. Do you it's fixed for good now?

**Comment by densh** [comment]
I'm closing this for now, it does seem to be fixed now.

**Comment by matil019** [comment]
I've been experiencing sbt freezes lately. It seems to happen after programs run by e.g. `tests/run` segfaulted several times. I'm not sure at which task this freeze occurs, however.

**Comment by densh** [comment]
@matil019 If you can reproduce it, please do file another issue. This one was mostly about CI freezes, and those have been gone for some time now.
