### ISSUE TITLE
Add support for Await.result

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#699]
```
val f = Future { ... }
Await.result(f, 5 second)
```
Results in the following link errors.
```
[error] cannot link: @java.util.concurrent.locks.AbstractQueuedSynchronizer::acquireSharedInterruptibly_i32_unit
[error] cannot link: @java.util.concurrent.locks.AbstractQueuedSynchronizer::releaseShared_i32_bool
[error] cannot link: @java.util.concurrent.locks.AbstractQueuedSynchronizer::toString_java.lang.String
[error] cannot link: @java.util.concurrent.locks.AbstractQueuedSynchronizer::tryAcquireSharedNanos_i32_i64_bool
```

**Comment by ekrich** [comment]
Here is a branch that may save a few minutes that was used to remove the link errors.
https://github.com/ekrich/scala-native/tree/topic/concurrent

**Comment by densh** [comment]
This is expected given that we're only supporting a single physical thread. The limitation could be lifted as soon as we do proper support for threading.

**Comment by JD557** [comment]
I just noticed that this now "works", as in, there is no link error.

It mostly times out with the default execution context, but it works with other contexts (such as parasitic).

So, I guess this can be closed?
