### ISSUE TITLE
Unicode characters not working properly in regex

### ISSUE THREAD

**Issue by asoltysik** [scala-native/scala-native#700]
Trying to compile this code:

    val other = "^[^\u0000-\u00a0\u1680\u2000-\u200a\u202f\u205f\u3000\u2028\u2029]$"

    Pattern.compile(other, Pattern.CASE_INSENSITIVE)

Gives me this error:
`java.util.regex.PatternSyntaxException: Unclosed character class near index 1
^[^-   -   　  ]$
 ^
	at java.lang.Throwable::fillInStackTrace_class.java.lang.Throwable
	at java.lang.Throwable::init_class.java.lang.String_class.java.lang.Throwable
	at java.lang.Exception::init_class.java.lang.String_class.java.lang.Throwable
	at java.lang.RuntimeException::init_class.java.lang.String_class.java.lang.Throwable
	at java.lang.IllegalArgumentException::init_class.java.lang.String_class.java.lang.Throwable
	at java.lang.IllegalArgumentException::init
	at java.util.regex.PatternSyntaxException::init_class.java.lang.String_class.java.lang.String_i32
	at java.util.regex.Pattern$::compile_class.java.lang.String_i32_bool_class.java.util.regex.Pattern
	at java.util.regex.Pattern$::compile_class.java.lang.String_i32_class.java.util.regex.Pattern
	at example.Main$::main_class.ssnr.ObjectArray_unit
	at main
	at __libc_start_main
	at _start
	at 
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
`

It compiles on JVM: http://ideone.com/r2I2gm
And it does in Go, which uses re2: http://ideone.com/CGrZar

**Comment by densh** [comment]
Thanks for the bug report!

**Comment by densh** [comment]
From the first glance it looks like our current regex completely ignores the fact utf-8 and utf-16 that we use for strings are two completely separate beasts.
