### ISSUE TITLE
Futures do not seem to run to completion

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#703]
Related to this feature: https://github.com/scala-native/scala-native/issues/617
Context: was trying to break monotonic on this new OS with a new implemetation
macOS sierra 10.12.4
```
package example

import scala.concurrent.Future
import scala.concurrent.Await
import scala.concurrent.duration._
import scala.concurrent.ExecutionContext.Implicits.global

object NanoTime {
  def main(args: Array[String]) {
   val t1 = runTest(1)
   val t2 = runTest(2)
   val t3 = runTest(3)
   val t4 = runTest(4)
  }
  def runTest(test: Int): Future[Unit] = {
    Future { 
      val threadName = Thread.currentThread.getName
      println(s"$test: $threadName: System.nanoTime is monotonically increasing") 
      var t0 = 0L
      var t1 = 0L
      val iters = 10000000L
      for (i <- 1L to iters) {
        t1 = System.nanoTime()
        assert(t0 - t1 < 0L)
        t0 = t1
        if (i % 100000 == 0) println(s"$test: $i")
      }
      println(s"$test: Done.")
      System.out.flush()
    }
  }
}
```

**Comment by densh** [comment]
I am seeing the following on macOS:
```
1: main: System.nanoTime is monotonically increasing
1: 100000
1: 200000
1: 300000
1: 400000
1: 500000
1: 600000
1: 700000
2: main: System.nanoTime is monotonically increasing
2: 100000
2: 200000
2: 300000
2: 400000
2: 500000
2: 600000
2: 700000
2: 800000
3: main: System.nanoTime is monotonically increasing
3: 100000
3: 200000
3: 300000
3: 400000
3: 500000
3: 600000
3: 700000
3: 800000
4: main: System.nanoTime is monotonically increasing
4: 100000
4: 200000
4: 300000
4: 400000
4: 500000
4: 600000
4: 700000
4: 800000
4: 900000
4: 1000000
4: 1100000
4: 1200000
4: 1300000
4: 1400000
4: 1500000
4: 1600000
```
What's the expected behavior?

**Comment by densh** [comment]
Current output is inconsistent with JVM but that's not a bug, it's a consequence of our event loop semantics.

**Comment by ekrich** [comment]
It seems that each of those loops should have gone to 10,000,000 iterations. The tasks don't seem to be running to completion. Running single threaded makes sense for Scala Native at this time.

**Comment by densh** [comment]
I see what you mean, it's doesn't show `println(s"$test: Done.")`.

**Comment by ekrich** [comment]
This was that whole stream flushing path I went down to try and see if there was a problem - found and fixed some things but not what I was expecting. Also, was trying to see how `Await` fits into the picture. And this was because I was trying to fix the `System.nanoTime` monotonic problem on macOS. It was all related. :-)

**Comment by muxanick** [comment]
This works for me if I add `=` to `<`:
`assert(t0 - t1 <= 0L)`
I see `done.` after every tests, I think if this assert fired it exits the future.
You probably want to surround for-loop by try/catch block.
Isn't it?

**Comment by densh** [comment]
@muxanick is right, it was failing because assertion went off, which threw an exception causing it not to run to completion, nano time and corresponding test has been improved in #750

**Comment by ekrich** [comment]
Agreed, good catch.
