### ISSUE TITLE
Add support for x86 architecture

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#727]
At the moment Scala Native only supports 64-bit architectures such as x86_64 and AArch64 and this is unlikely to change in the near future.

@LeeTibbert tried running Scala Native on x86 and found a number of issues listed below. This issue is meant to be a summary of the current reports in one place:

- [X86: Multiple test failures after PR #520 (Memory layout, etc.)](https://github.com/scala-native/scala-native/issues/527)
- [X86: compensating for libunwind](https://github.com/scala-native/scala-native/issues/491)
- [X86: SizeofSuite.scala test of pointer size fails](https://github.com/scala-native/scala-native/issues/478)
- [CSize and Int literal direct comparison fails on X86](https://github.com/scala-native/scala-native/issues/455)
- [fromCstring() appears to truncate very large strings](https://github.com/scala-native/scala-native/issues/454)
- [X86: fwrite fails to output, fprintf & fputs succeed.](https://github.com/scala-native/scala-native/issues/451)
- [scala-native javalib strings appear with 2 initial NULs?](https://github.com/scala-native/scala-native/issues/441)
- [Scala-native scala println appears broken/no-op/not-yet-implemented/black-hole-sink](https://github.com/scala-native/scala-native/issues/426)

**Comment by armanbilge** [comment]
I think this is closable.
- https://github.com/scala-native/scala-native/pull/1571
