### ISSUE TITLE
Optimize zone allocation for speed

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#735]
https://github.com/scala-native/scala-native/pull/734 introduces initial support for zone allocation. 

1. Unlike [scala-offheap](http://github.com/densh/scala-offheap) we don't do anything remotely smart to improve the performance of the zone allocator yet. Performance of both `alloc` and `close` can be substantially improved by using a memory-pool of pages with bump allocation. The core memory pool management can be ported from [scala-offheap](http://github.com/densh/scala-offheap) with minimal changes.

2. We should optimize away closure allocation that demarcates the start and end of the zone.

**Comment by muxanick** [comment]
```
StackZone(1024) {
   ....
  //   allocate stuff
}
```
if allocations exceed given 1024 bytes then we use usual Zone memory pool (aggregated inside StackZone)
It seems like very small addition to algorithm, but it helped me many times
