### ISSUE TITLE
Append replacement in regex is nondeterministically broken

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#739]
This problem wasn't surfacing before, when regex was doing raw gc
allocations, but zone allocator isn't as forgiving. At first glance
group handling in (at least) appendReplacement seems to be very much
broken at the moment.

**Comment by muxanick** [comment]
I fixed that in #691 , see https://github.com/scala-native/scala-native/pull/691/files#diff-ef6e5cb9d8056c08c6441a0d16a64425 file
