### ISSUE TITLE
please offer AutoPlugin compatible alternative to nativeSettings

### ISSUE THREAD

**Issue by fommil** [scala-native/scala-native#742]
I'd like to be able to inject settings into native-enabled projects via an autoplugin, but this is making it impossible:

```
    def nativeSettings(ss: Def.SettingsDefinition*): CrossProject =
      nativeConfigure(_.settings(ss: _*))
```

Please offer something more canonical, e.g. settings attached to a scope.

**Comment by sjrd** [comment]
The `AutoPlugin` is [`ScalaNativePlugin`](https://github.com/scala-native/scala-native/blob/master/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePlugin.scala). It already exists.

The line you're referring to is a method of `CrossProject` that adds additional settings to the native part of the `CrossProject`. That project already has the plugin `ScalaNativePlugin`. `.nativeSettings` is similar to `.jsSettings` and `.jvmSettings` of Scala.js.

**Comment by fommil** [comment]
but I can't use my own AutoPlugin to add settings, because it seems that you need things to be set via `nativeSettings`, which I cannot call.

There is a similar problem with this:

```
  def settings(ss: Def.SettingsDefinition*): CrossProject =
    copy(jvm.settings(ss: _*), js.settings(ss: _*))
```

which means that calling `.settings(...)` is not the same as filling out the `projectSettings` in an `AutoPlugin`. Doesn't this mean you're ignoring everything that's been set via an autoplugin? Or do you have magic to deal with this?

**Comment by fommil** [comment]
ok, I've read a little more of the sources. So if I understand correctly, the hacky `.settings`, `.jsSettings`, `.nativeSettings` and `.jvmSettings` are all conveniences for people who don't understand how AutoPlugins work ... but I can just depend on the correct plugin and use settings as normal?

**Comment by sjrd** [comment]
Do you really think I would put in Scala.js "a hacky method for those who don't understand `AutoPlugin`s"?

`.nativeSettings` is exactly like `.settings`. It's meant to be called from end user's build, when they have settings to apply only to the native part of a cross project. Remember that a `CrossProject` is not a `Project`. It is a set of `Project`s.

In that set of projects, one of them is a JVM project, and another is a native project (and possibly others, such as a JS project). The latter has `enablePlugins(ScalaNativePlugin)`, the former doesn't.

As a plugin author, if you want your plugin to trigger for native projects, just make it trigger on `ScalaNativePlugin`. It will affect the native part of cross projects, as well as non-cross, only native projects.

Try and approach the problem by assuming we did the right thing. It's a proven design that has worked for Scala.js for 3 years, and people have been writing normal `AutoPlugin`s depending on `ScalaJSPlugin` without trouble for years.

**Comment by ekrich** [comment]
@sjrd Thanks for explaining this. I for one didn't have a clear picture on how this works for `CrossProject` as this adds a whole different dimension to the build. `sbt` is a tad complex to begin with.

**Comment by fommil** [comment]
Thanks for the explanation. It is certainly a very unique way of solving the problem. Idiomatically, I would have expected you to use scopes rather than separate projects, but it sounds like you needed to workaround sbt limitations and hence duplicated the Projects. That's what I call a hack, there is no shame in having to workaround sbt limitations.

**Comment by sjrd** [comment]
Choosing projects instead of scopes was an intentional design decision, not a hack working around scopes. We wanted the JVM and JS declinations to have `compile`, `test`, `it` and possibly other configurations, just as normal. That composes better with sbt plugins adding their own configurations, and is also the clean thing to do when publishing on Maven.

**Comment by fommil** [comment]
Ok good to know. It's clear that we make totally different design decisions, so I don't feel I can make any assumptions about what I consider "right" or "wrong", so I will try to understand explicitly what the plugin is doing.

**Comment by fommil** [comment]
sorry I meant to close this.
