### ISSUE TITLE
how to disable native projects with sbt-doge

### ISSUE THREAD

**Issue by fommil** [scala-native/scala-native#749]
This is perhaps the wrong place to ask this, but this with sbt-doge doesn't seem to work (i.e. an `sbt ++2.12.2 compile` will attempt to compile the native project with 2.12)

```
import sbt._
import sbt.Keys._
import scala.scalanative.sbtplugin.ScalaNativePlugin

object NativeWorkarounds extends AutoPlugin {
  override def requires = ScalaNativePlugin
  override def trigger = allRequirements
  override def projectSettings = Seq(
    crossScalaVersions := Seq("2.11.11")
  )
}
```

is there an idiomatic way to restrict the native projects to only build on specific scala versions?

**Comment by tindzk** [comment]
Setting the version with `++` bypasses `scalaVersion` and `crossScalaVersions`. I encountered [a similar problem](https://github.com/scala-native/sbt-crossproject/issues/36) in sbt-crossproject.
