### ISSUE TITLE
Add caching for artifacts downloaded from llvm.org in CI

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#757]
http://lists.llvm.org/pipermail/llvm-dev/2017-May/113269.html

We're partly responsible for this. There is no caching in our travis build for artifacts downloaded from `apt.llvm.org` and it only got worse recently with new matrix builds over GC implementation.

**Comment by jonas** [comment]
I have a fix for this in https://github.com/jonas/scala-native/commit/a9ab6f9ecaa1e9a58e404002ad1c18111cf40224 that I never got around to polishing. With the new build matrix it will require some rework.

**Comment by jonas** [comment]
I can submit a PR tomorrow during the spree.

**Comment by densh** [comment]
@jonas Cool, looking forward to the PR! 😀

**Comment by jonas** [comment]
I have two additional ideas to try out:

- Use Ubuntu Trusty and clang-3.8 included in it
- Download the prebuilt binaries packages as a tarball and cache it

**Comment by densh** [comment]
> Use Ubuntu Trusty and clang-3.8 included in it

This sounds like a possible solution. Did travis recently add support for trusty?

**Comment by jonas** [comment]
It is in beta since 2015-10-14: https://docs.travis-ci.com/user/trusty-ci-environment/
