### ISSUE TITLE
Find differences between Scala JVM and Scala Native

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#763]
This is a meta ticket for the Scala spree. The goal is to find code that behaves differently on Scala JVM and Scala Native. There are a few rules:

 - **[Read the contributing guidelines](https://github.com/scala-native/scala-native/blob/master/docs/contrib/contributing.rst#contributing-guidelines). It contains very important information about licenses and copyrights.**
 - The code must link
 - The behaviour must be different (crash on the JVM, but runs fine on Native or vice-versa, crash for different reasons, different results, etc.)

If you find such code, please open a PR with a test for Scala Native! Note that, at the moment, Scala Native cannot be used with usual test frameworks like scalatest, utest, etc. You'll need to use [our super simple test framework](https://github.com/scala-native/scala-native/blob/master/unit-tests/src/main/scala/tests/Suite.scala#L10). Here's [an example of test](https://github.com/scala-native/scala-native/blob/master/unit-tests/src/main/scala/java/io/BufferedInputStreamSuite.scala#L5-L14).

To run the tests, simply type `tests/run` in your sbt shell. If you want to run a single test suite, you can enter its name. For example: `test/run FilesSuite`

**Comment by densh** [comment]
Given that the spree is over, I'm closing the issue as it's not actionable any longer.
