### ISSUE TITLE
List of Scala Native libraries/bindings

### ISSUE THREAD

**Issue by tindzk** [scala-native/scala-native#764]
Having a curated list of Scala Native libraries and bindings could facilitate adoption. For example, [Scala.js](https://www.scala-js.org/libraries/libs.html) has such a list on their website.

Scala Native currently only has a manual, so I am not sure whether it is the best place for this. There are two alternatives that come to my mind:

- Create a wiki page in this repository
- Create a separate Git repository in the `scala-native` organisation and create a `README.md` similar to an [Awesome list](https://github.com/sindresorhus/awesome)

I am happy to contribute a preliminary list of libraries I could track down using GitHub searches. On a similar note, we should also encourage libraries authors to use the [`scala-native` topic](https://github.com/search?utf8=%E2%9C%93&q=topic%3Ascala-native&type=Repositories) to make it easier to find their projects.

**Comment by xuwei-k** [comment]
- http://mvnrepository.org/artifact/org.scala-native/scalalib_native0.2_2.11/0.2.1/usages
- https://index.scala-lang.org/search?q=&targetTypes=NATIVE

**Comment by tindzk** [comment]
Great, thanks! I wasn't aware of Scaladex's ability to search by platform. However, it seems to only consider libraries with published artifacts.

**Comment by tindzk** [comment]
I compiled an initial list of Scala Native resources and libraries [here](https://github.com/tindzk/scala-native-resources). Let me know your thoughts.

**Comment by densh** [comment]
@tindzk Looks good!

**Comment by tindzk** [comment]
Thanks. I will close the issue for now.
