### ISSUE TITLE
Finalize binary representation of NIR

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#77]
Once Scala Native is released, all libraries will need to have NIR published for them. We need to review the binary format to make sure it's easy to extend it in binary-compatible manner as the project evolves. 

- [ ] Include magic number in binary representation
- [ ] Include NIR version in binary representation
- [ ] Stabilise serialization tags

**Comment by sirinath** [comment]
Before finalising format make sure the format gives best performance on OMR JIT and Truffle. This way it can serve a dual purpose of being and higher abstraction before LLVM IR and also being able to run faster than JVM ByteCode on JIT mode.

**Comment by densh** [comment]
As I replied in [the other thread](https://github.com/scala-native/scala-native/issues/83#issuecomment-219403841), JIT compilation is out of scope for the project.

**Comment by sirinath** [comment]
Without doing this you will not know if the SN implementation is optimised enough. The JVM implementation alone would be a poor benchmark and the JVM is optimised for Java. Also benchmarking against other languages like http://benchmarksgame.alioth.debian.org/ is also a poor choise as the coparisons are on toy program. OMR JIT and Truffle targeting will make you push for more performance for SN. Also give the advantage of having alternative. At the LLVM IR level if it does not beat Sulong after warm up there is a big issue on performance which is the main or only reason you would want to use SN. So best is to have alternatives to compete or benchmark against each other will definitely be the most healthy choice. So I would request you to reconsider. This need not be a high priority issue but as I feel needs to be around for the project to mature and polished.

**Comment by densh** [comment]
I've just moved non-blocker parts of this issue to https://github.com/scala-native/scala-native/issues/132

**Comment by sjrd** [comment]
Add positions.

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/134
