### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#775]
Since this is not 100% compatible with Java perhaps this can be moved into another package. `scalanative.util.regex` instead of `java.util.regex`.

Is the future perhaps the differences can be closed in `java.util.regex` while not breaking code using `scalanative.util.regex` 

Maybe you can place non  Java or Mainline Scala compatible implementations in `scalanative` until they confirm.

**Comment by sirinath** [comment]
Maybe you can place non  Java or Mainline Scala compatible implementations in `scalanative` until they confirm.

**Comment by densh** [comment]
We already have a ticket for this: #620 

Difference in behavior is expected and might improve in the future. We do not intend to provide a separate regex API, other than java.util.regex.

**Comment by sirinath** [comment]
If you are including it under ` java.util.regex` please keep it compatible. Otherwise have it in another experimental namespace until it becomes compatible. Otherwise what happens is when people start using the current implementation and make it more compatible their code will break. Also i you want to maintain compatibility with mainline Scala then again there will be issues.

**Comment by densh** [comment]
We'll happily accept a more compatible implementation of `java.util.regex` as a contribution from the community. Current implementation seems to work well enough for most people and is huge step up from not having any regular expressions at all. We're interested in improving it but that's not the priority at the moment.
