### ISSUE TITLE
!vec Syntax

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#776]
`!vec._1` is awkward to use. How does this interact with logical not operator?

```
@stack
val vec = stackalloc[Vec]
```

might be a better way to signal stack allocation without introducing new syntax for this.

I do not think even `stackalloc` is needed.

Simply

```
@stack
val vec = new Vec
```

Should be able to achieve the same with more compatibility with main line Scala

For pointers you can have a special field. E.g. `vec.$address` but for this to be used perhaps it needs to be annotated with `@pointer`. Also pointer to pointers should also be considered.

This means SN constructs can be easily mocked away to keep same code base with mainline Scala.

**Comment by densh** [comment]
Difference between managed and unmanaged types is by design. Managed and unmanaged types have completely different semantics and expectations in terms of safety and performance. We do not intend to blur the line between the two in the foreseeable future.

**Comment by sirinath** [comment]
Can you do this while keeping parity with mainline Scala so you can use one code base on both but also get the best out of SN?

**Comment by densh** [comment]
You don't have to use any of the interop features to write efficient Scala code on Native. Interop-free code already has close to 1-to-1 feature parity with JVM (with minor semantic differences in exceptional cases.) We're investing heavily in making sure that regular high-level Scala doesn't incur any major performance penalty over lower-level code.
