### ISSUE TITLE
Pass by Value & Pass by Reference in Function & Closures

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#777]
It would be useful to have pass by value and pass by reference. Perhaps this can be implemented as `@ref` and `@val`. These should be available for function parameters and closures. In closures locally defined variables can have these annotation to hint if they are captured as value or references.

Also `@ref` and `@val` should be easily mocked away in mainline Scala.

**Comment by densh** [comment]
We do not intend provide any new language features that go beyond the interoperability with C code. Scala Native is an implementation of the Scala language, and the work we are doing is focused around getting the best implementation of the language, not in experimenting with new user-facing language features.

**Comment by sirinath** [comment]
C++ has both pass by value and pass by reference. Also C++ closures has them.

Also what I am requesting it to keep parity with mainline Scala. E.g. `!` operator breaks this. So support full C/C++ interop while also maintaining compatibility with mainline Scala where you can have one code base to run on both which using additional features of SN when compiled on it.

**Comment by densh** [comment]
We're not a C++ implementation, we're Scala implementation. Scala language doesn't have pass by value and pass by reference, if you want this to change you first need this to happen on the reference implementation on top of the JVM first. Interop layer is there purely for calling C code, you are not expected to use in typical idiomatic Scala code.

**Comment by sirinath** [comment]
I think to have proper C++ interop you will need it.
