### ISSUE TITLE
toCString will not compile

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#779]
The following code will not compile:
```
package example

import scalanative.native._
import stdio._

object ToCString {
  def main(args: Array[String]): Unit = {
    printf(c"%s\n", toCString("foo"))
  }
}
```
Error:
```
[error] /Users/eric/workspace/scala-native-hello/src/main/scala/HelloWorld.scala:35: 
could not find implicit value for parameter a: scala.scalanative.native.Alloc
[error]     printf(c"\n%s\n", toCString("foo"))
```

**Comment by jonas** [comment]
#733 changed the signature of `toCString` to take an allocator.

```
package example

import scalanative.native._
import stdio._

object ToCString {
  def main(args: Array[String]): Unit = Zone { implicit z =>
    printf(c"%s\n", toCString("foo"))
  }
}
```

**Comment by ekrich** [comment]
I wanted to add  `implicit private[this] val alloc = Alloc.system` to `scalanative.native.package.scala` to satisfy `toCString` but that doesn't look like that will work after chatting with @jonas and @Duhemm. I guess the user needs to manage the memory so maybe some documentation for the user is what we need. Maybe an Allocator that allows using stack memory would be helpful as well.
