### ISSUE TITLE
Consider integrating with Eclipse OMR 

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#78]
https://github.com/eclipse/omr

The project provides an implementation of many of the runtime pieces we currently missing. Even if we can't use those directly, it should serve as reasonable foundation for own implementation.

**Comment by densh** [comment]
License compatibility needs to be investigated too, it's not clear if BSD is compatible with EPL.

**Comment by david-t-daniel** [comment]
Thank you for taking the time to look into this.  I believe it is apache licensed as well APL v2

**Comment by sirinath** [comment]
OMR is dual licensed under EPL 1.0 and ASL 2.0. Use ASL 2.0 license.

**Comment by sirinath** [comment]
Also consider cooperative JIT using OMR JIT to further optimise code on the runtime for which you cannot generate the most optimal native code statically to  squeeze out the last bit of performance.

**Comment by densh** [comment]
I'm closing this issue as we have a bigger ideas thread in https://github.com/scala-native/scala-native/issues/128
