### ISSUE TITLE
Add support for stripping the compiled binary from the sbt plugin

### ISSUE THREAD

**Issue by DarkDimius** [scala-native/scala-native#789]
`Hello world` currently takes 2MB.
It can be automatically stripped to 1.4MB. 
Afaik scala-native does not support any kind of runtime linking\etc.
If I'm not mistaking, you won't loose anything by stripping.

**Comment by densh** [comment]
Sounds like a good idea, we might want to do it by default for release builds.

**Comment by LeeTibbert** [comment]
@WojciechMazur I believe this can be closed.  I believe that there is currently (like for last three or four
years) a documented way to set the options used by the linker.  At least on ubuntu, one of those
linker options (-s?) says to strip the symbols from the generated binary.

So the request specified in this issue has been available for a number of years, albeit that it is
not trivial to figure out.
