### ISSUE TITLE
Add support for calling Scala code from C

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#79]
Currently `@extern` objects provide one-way interop between Scala and C. We need to extend it to support calls the other way around too. It used to be enabled before, but we disabled it due to some weird interactions with link-time dead code elimination. It should become much more predictable once we have https://github.com/scala-native/scala-native/issues/156.

**Comment by sirinath** [comment]
When SN code is compiled in library mode you should be able to generate target [ABIs](Application_binary_interface)

**Comment by densh** [comment]
@sirinath I've opened a #155 for that.

**Comment by densh** [comment]
Lets focus on #155 for efforts on this front.
