### ISSUE TITLE
Signature of Arrays.asList is wrong

### ISSUE THREAD

**Issue by hewie** [scala-native/scala-native#794]
```
import java.util.Arrays

object Test {

  def main(args: Array[String]): Unit = {
    println(Arrays.asList(Array[String]("asdfsd")))
    println(Arrays.asList(new Array[String](2)))
  }
}
```

This code works in plain scala & inside the javalib subproject.
But in a standalone scala native projects it can't be linked.

```
[error] cannot link: @java.util.Arrays$::asList_scala.scalanative.runtime.ObjectArray_java.util.List
[error] unable to link
[error] (sandbox/compile:nativeLinkNIR) unable to link
``` 

If the `asList` function inside javalib is modified so that the argument is `Array[String]` instead of `Array[T]` the function can be linked and the code in this use case is executed properly.

`def asList[T](a: Array[T]): List[T]`

So i assume that the Linker has a Bug regarding generic Arrays.

**Comment by sjrd** [comment]
No it's the signature of `asList` which is wrong. It should have `T <: AnyRef`. I guess that code was taken from Scala.js before we fixed it in https://github.com/scala-js/scala-js/commit/f63f3fbdab908f79f166284619b0ca770e9cf328
