### ISSUE TITLE
Allow Nothing as a member of a case class

### ISSUE THREAD

**Issue by matil019** [scala-native/scala-native#802]
The nir phase fails to compile the following code:

```scala
case class Foo(a: Nothing)
```

Yes, it's nonsense. But nonetheless, the ordinary Scala compiles it fine.

I sometimes use `Nothing` in this way as a placeholder when I'm sure certain member(s) are needed, but haven't decided their types yet.

**Comment by densh** [comment]
Thanks for the report!

**Comment by WojciechMazur** [comment]
This issue is no longer observed. It's possible to use `Nothing` in case class.
