### ISSUE TITLE
Some methods accepting charset as String should throw UnsupportedEncodingException

### ISSUE THREAD

**Issue by matil019** [scala-native/scala-native#816]
`Charset.forName` throws Unsupported _Charset_ Exception. However, some (older?) methods/constructors are specified to throw Unsupported _Encoding_ Exception, which is an entirely unrelated exception class.

**UPDATE** According to the JDK Javadoc, the following constructors/methods throw `UnsupportedEncodingException`.

The following methods exist in Scala Native, and are affected by this bug:

* `java.io.ByteArrayOutputStream.toString(String)`
* `java.io.InputStreamReader(InputStream, String)`
* `java.io.OutputStreamWriter(OutputStream, String)`
* `java.io.PrintStream(OutputStream, Boolean, String)`
* `java.io.PrintStream(String, String)`
* `java.io.PrintStream(File, String)`
* `java.io.PrintWriter(String, String)`
* `java.io.PrintWriter(File, String)`
* `java.lang.String(Array[Byte], Int, Int, String)`
* `java.lang.String(Array[Byte], String)`

The following method was already fixed:

* `java.lang.String.getBytes(String)`

The following methods don't exist in Scala Native:

* `java.awt.datatransfer.DataFlavor.getReaderForText(Transferable)`
* `java.net.URLDecoder.decode(String, String)`
* `java.net.URLEncoder.encode(String, String)`
* `java.util.Formatter(String, String)`
* `java.util.Formatter(String, String, Locale)`
* `java.util.Formatter(File, String)`
* `java.util.Formatter(File, String, Locale)`
* `java.util.Formatter(OutputStream, String)`
* `java.util.Formatter(OutputStream, String, Locale)`
* `java.util.Properties.loadFromXML(InputStream)`
* `java.util.Properties.storeToXML(OutputStream, String, String)`
* `java.util.logging.Handler.setEncoding(String)`
* `java.util.logging.StreamHandler.setEncoding(String)`
* `javax.xml.bind.helpers.AbstractMarshallerImpl.getJavaEncoding(String)`

They are found by grepping UnsupportedEncodingException in Java SE Development Kit 8 Documentation (http://www.oracle.com/technetwork/java/javase/documentation/jdk8-doc-downloads-2133158.html)

At first I was only aware of `OutputStreamWriter` which causes some tests in Formatter (#804) to fail.

**Comment by sjrd** [comment]
Scala.js probably suffers from the same bug(s).

**Comment by LeeTibbert** [comment]
My recent work with Double & Float output formats took me to FormatterSuite.scala,
which took me here. I am looking at the items kindly listed in this issue.

So far: Looks like #1263 fixed String.getBytes() exception type.

**Comment by matil019** [comment]
@LeeTibbert Nice to meet you, and thank you for the ping. I updated the list.
