### ISSUE TITLE
Pattern.scala potentially leaks a native memory

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#817]
There is a class Pattern:
`scala-native/javalib/src/main/scala/java/util/regex/Pattern.scala`
and there is a method:
```
override protected def finalize(): Unit = {
    super.finalize()
    cre2.delete(_regex)
  }
```
You can search `cre2.delete` over codebase, there is no other place where it called. Seems like memory for native part of regex never released.

There are 4 more places where finalize method is declared:
```
scala-native/javalib/src/main/scala/java/io/FileInputStream.scala
scala-native/javalib/src/main/scala/java/io/FileOutputStream.scala
scala-native/javalib/src/main/scala/niocharset/ISO_8859_1_And_US_ASCII_Common.scala
scala-native/javalib/src/main/scala/niocharset/UTF_8.scala
```

**Comment by densh** [comment]
That indeed looks like a bug given that finalizers are not supported at the moment.

**Comment by densh** [comment]
Superseded by #873, to be fixed by #894

**Comment by matil019** [comment]
I think this is a sign of need for finalizers. There are no ways to tell when to `cre2.delete` without the knowledge of the lifetime of `Pattern`, and the API of `Pattern` cannot be changed to have `close` etc.

For this particular case, the implementation of `Pattern` (i.e. RE2) can be replaced to remove the need of `delete`-ing. Not every SN project may be able to do that, however, especially when they are designed as drop-in replacements for (possibly legacy) JVM libraries.

How about providing a subset of finalizers? For example, a class gets a member of type `Zone` or `Scope` and its `close()` called on finalization? The idea is to embed a lifetime of `Zone`/`Scope` into that of an object. Limiting the use of finalizers may help simplify its implementation.

**Comment by densh** [comment]
Finalizers are conceptually broken as they can modify the reachability of objects during garbage collection. This complicates the GC and gives users way more power than they actually need. We've decided that we are not going to support them. 

Finding a good replacement for finalizers is a hard problem without a definitive solution. Lets continue the discussion on gitter and keep the github issues for actionable tasks.

**Comment by matil019** [comment]
On the other finalize functions:

```
scala-native/javalib/src/main/scala/java/io/FileInputStream.scala
scala-native/javalib/src/main/scala/java/io/FileOutputStream.scala
```

Both of their definitions are:

```
override protected def finalize(): Unit = close()
```

This is just a failsafe. They can be removed assuming that client code calls the `close` methods properly.

```
scala-native/javalib/src/main/scala/niocharset/ISO_8859_1_And_US_ASCII_Common.scala
scala-native/javalib/src/main/scala/niocharset/UTF_8.scala
```

It's confusing but they are *local functions* coincidentally named `finalize`. They are not at all related to the usual "finalization".
