### ISSUE TITLE
Compatibility with Mainline Scala and Dotty

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#82]
It is possible to ensure that a valid Mainline Scala and Dotty programs are valid SN programs and vise versa perhaps adding these features to Scala Off Heap

E.g.

@extern can be replicated through https://github.com/bytedeco/javacpp, https://github.com/java-native-access/jna, https://github.com/jnr/jnr-ffi

Also stack access perhaps maybe replicated through JVMCI (https://bugs.openjdk.java.net/browse/JDK-8062493) and can be ignoged in some vertions. Ignoring should make the results of the program different other than speed of execution. Some example perhaps you can have a look at: https://github.com/graalvm

**Comment by RomanHargrave** [comment]
Do you mean to suggest the ability to compile SN directly to the JVM? I may be misinterpreting your suggestion, but I like the direction SN is currently going in (e.g. not trying to be JVM compatible in favour of better native compatibility).

**Comment by sirinath** [comment]
I do not see why main line Scala cannot have the same features through Scala Off Head abite being less performant.

**Comment by densh** [comment]
If I understand correctly @sirinath wants Scala Native's language extensions compile to something semantically equivalent on JVM. Possibility of something like this happening is slim as we don't have time for implementing this right now (therefore the `Backlog` milestone) but we'll keep the idea in mind.

**Comment by densh** [comment]
Supporting an implementation of Scala Native extensions outside of Scala Native platform is out of scope for the project.
