### ISSUE TITLE
Truffle Runner for NIR

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#83]
In case a Truffle implementation of NIR would outperform the pure JVM implementation with the safety of the JVM perhaps NIR can be make to run on Truffle (https://github.com/graalvm/truffle). NIR also may need tuning to get  the best performance.

The SN LLVM IR can be tested on Sulong (https://github.com/graalvm/sulong) for perfomance comparison also.

As a performance test ideally SN should be able to reasonably run faster than when run on Truffle and Sulong and code running on Truffle and Sulong should be faster than running ByteCode. Running on  Truffle and Sulong maybe useful when security and safety is a concern and also there is existing JVM infrastructure.

**Comment by densh** [comment]
First of all, Scala Native is an ahead-of-time compiler, not a just-in-time compiler. We already have great JITs in JVMs from numerous vendors, that's not what we are aiming at.  

Second of all, NIR was explicitly designed as an intermediate stage between Scala's typed ASTs and LLVM's IR. It's definitely possible to compile it other targets, interpret it or even stage it. None of that is the goal of Scala Native. We're LLVM-based compiler project at the core, and that's not going to change in foreseeable future.

**Comment by sirinath** [comment]
The Java AOT Compiler Oracle is working on I believe has JITing also. One introduction to it is in: https://www.youtube.com/watch?feature=player_embedded&v=Xybzyv8qbOc. Also I believe IBM has JIT optimisations in their AOT compiler Java: http://www.ibm.com/support/knowledgecenter/SSYKE2_7.0.0/com.ibm.java.win.71.doc/diag/understanding/aot.html

There are many instances where part of a program where JIT will outperform AOT and AOT will outperform JIT. So to get the best performance you need both working hand in hand to with AOT and JIT fall back where it matters.
