### ISSUE TITLE
Improve javalib docs on supported/unsupported classes

### ISSUE THREAD

**Issue by asoltysik** [scala-native/scala-native#839]
As we support more and more classes from javalib, maybe it would be more useful to change this list: https://scala-native.readthedocs.io/en/v0.3.0/lib/javalib.html#supported-classes
to unsupported classes/packages? We could also mention our priorities there and classes which are probably never going to be implemented (SecurityManager?). Potential contributors could also find it useful to find areas to work on. What do you think about that?

**Comment by densh** [comment]
Currently javalib classes are just auto-generated. In the future it would definitely be nice to show some kind of completeness/maturity rating for the classes we have.

**Comment by densh** [comment]
But going all the way to listing unsupported first might be a bit too far as we don't have a goal of implementing everything.

**Comment by densh** [comment]
We're slowly converging towards the number of classes that we want to have and the current list seems to work for this well enough.
