### ISSUE TITLE
Cannot run unit tests

### ISSUE THREAD

**Issue by mccartney** [scala-native/scala-native#847]
## Steps to reproduce
```sbt tests/run```

## Observed
```
[...]
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 9 Scala sources to /redacted/scala-native/unit-tests/target/scala-2.11/classes...
[error] No main class detected.
[error] (tests/compile:nativeConfig) No main class detected.
[error] Total time: 0 s, completed 16-Jun-2017 20:52:11
```

**Comment by ekrich** [comment]
@mccartney Please try `tests/test` at the sbt prompt. We have changed to a new test framework. We also have a gitter channel. https://gitter.im/scala-native/scala-native

**Comment by mccartney** [comment]
Ah. Perfect! That worked. Thanks.

I think it deserves a mention somewhere. I am not sure where, but one of the two places come to my mind: `README.md` (top-level or within `unit-tests`) or the "Contributor’s Guide" on the webpage.
Would you be able to suggest something where to contribute a short line similar to "run tests/test in sbt"?

**Comment by ekrich** [comment]
You can do a PR to the contributors guide if you find a good place. They code is in the `docs` directory. There is a plan for a `0.3.1` release soon.

**Comment by densh** [comment]
@mccartney Contributors's guide is probably a reasonable place for this.

**Comment by ekrich** [comment]
I think we can close this one when this is merged since we will have a basic example. https://github.com/scala-native/scala-native/pull/1117

**Comment by densh** [comment]
@ekrich Agreed.
