### ISSUE TITLE
FileWriter fails to create a new file

### ISSUE THREAD

**Issue by mccartney** [scala-native/scala-native#848]
As observed by @Duhemm in #772, when you ask the `FileWriter` to create a new file, it fails:

### Steps to reproduce 
```
       val fw = new FileWriter("/tmp/new.file")
       fw.write("something")
       fw.close()
```

**Comment by mccartney** [comment]
Moreover. It's not enough to specify {{O_CREAT}} flag. As per documentation for `open`:
>  mode  specifies  the  mode to use in case a new file is created.  This argument must be supplied when O_CREAT or O_TMPFILE is specified in flags;

**Comment by matil019** [comment]
I think there is already a working piece of code in `FileOutputStream`. Perhaps delegating the implementation of `FileWriter` to `FileOutputStream` is a good idea.
