### ISSUE TITLE
Random without a seed is deterministic

### ISSUE THREAD

**Issue by mccartney** [scala-native/scala-native#849]
### Steps to reproduce
Run the following program several times:
```
     val r= new java.util.Random()
     println(r.nextInt)
```

### Observed
I keep getting the same results.
Obviously, I might be totally (un)lucky.

```1206531168``` the whole time

### Expected
Different results each time I call it as per [Random() constructor javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#Random--):
> This constructor sets the seed of the random number generator to a value very likely to be distinct from any other invocation of this constructor.

**Comment by mccartney** [comment]
Which begs for a reference to: [https://xkcd.com/221/](https://xkcd.com/221/)

**Comment by mccartney** [comment]
When I looked at it. the `stdlib.rand` yields the same results for me every time I call it:
```
println(scala.scalanative.native.stdlib.rand)
```
And there I am not fully sure how to troubleshoot further.

**Comment by ekrich** [comment]
When running this bit of code:
```
for (i <- 1 to 10) println(scala.scalanative.native.stdlib.rand)
```
I get the following:
```
16807
282475249
1622650073
984943658
1144108930
470211272
101027544
1457850878
1458777923
2007237709
```

**Comment by ekrich** [comment]
Looking at the default `Random` ctor. The seed should probably be the time in Millis or something?

**Comment by densh** [comment]
Keep filing those, @mccartney ! 👍

**Comment by ekrich** [comment]
We should initialize srand first before calling rand. See https://www.tutorialspoint.com/c_standard_library/c_function_srand.htm
