### ISSUE TITLE
ArrayList should throw exception with negative initial capacity

### ISSUE THREAD

**Issue by mccartney** [scala-native/scala-native#850]
A minor issue, yet a violation from Java spec.

### Steps to reproduce
```new java.util.ArrayList(-1)```

### Observed
works, creates a list with size = 0

### Expected
>IllegalArgumentException - if the specified initial capacity is negative
as per [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#ArrayList-int-)

**Comment by mccartney** [comment]
```
  testFails("should throw an error with negative initial capacity", 850) {
    assertThrows[IllegalArgumentException] {
      new ArrayList(-1)
    }
  }
```

**Comment by densh** [comment]
Thanks!
