### ISSUE TITLE
AbstractList.addAll doesn't work

### ISSUE THREAD

**Issue by mccartney** [scala-native/scala-native#851]
### Steps to reproduce
- due to #375 add "dummy forwarders" to `ArrayList`, e.g.
```
  override def addAll(c: Collection[_ <: E]): Boolean =>super.addAll(c)
  override def addAll(index: Int, c: Collection[_ <: E]): Boolean = super.addAll(index, c)
```
- call `addAll` on an `ArrayList` (or any `AbstractList` descendant), e.g.
```
        val l = new java.util.ArrayList[String]()
        l.add("First")
        l.add("Second")
        println(l)
        
        val l2 = new java.util.ArrayList[String]()
        l2.addAll(0, l)
        println(l2)
```

### Observed
- the outputs of both printlns differ

### Expected
- they should be the same
- i.e. all elements of `l` should be added to `l2`

**Comment by mccartney** [comment]
I think the bug is in the implementation of `AbstractList.addAll` which seems to ignore the collection argument totally, and iterates over `this` instead.
So to put it differently - `addAll` rather works as doubling itself.

**Comment by densh** [comment]
Nice find, thanks @mccartney !
