### ISSUE TITLE
Add support for checked casts in debug mode

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#858]
The following code compiles fine, but its behavior is different on the JVM and on Native:

```scala
object Main {
  def main(args: Array[String]): Unit = {
    println(0.asInstanceOf[String]) // Prints `0`, should throw `ClassCastException`
    println("" + 0.asInstanceOf[String]) // Prints ``, should throw `ClassCastException`
  }
}
```

On Native, the first `println` will print `0`, but it should throw an exception.
The second `println` will print an empty line, but it should throw an exception too.

**Comment by densh** [comment]
Casts are unchecked on purpose in release mode. We wanted to make them checked in debug for a while now, but there was no issue for it.

**Comment by densh** [comment]
Superseded by #1140
