### ISSUE TITLE
Doco error - getting started

### ISSUE THREAD

**Issue by huntc** [scala-native/scala-native#859]
`sbt new sbt new scala-native/scala-native.g8` has one too many `sbt new`s in it http://www.scala-native.org/en/v0.3.0/user/sbt.html#sbt

**Comment by huntc** [comment]
Maybe also recommend upgrading sbt - 0.13.13 is required.

**Comment by xuwei-k** [comment]
https://github.com/scala-native/scala-native/pull/824

**Comment by ekrich** [comment]
@huntc I would recommend getting 0.13.15 and make sure you download or reinstall `sbt` as the launcher has changed.

**Comment by huntc** [comment]
Well, brew for sbt is only on 0.13.13. However that did allow things to work for me.

**Comment by ekrich** [comment]
I show the following but if it is working all is good.
```
Erics-MBP:docker eric$ brew list sbt
/usr/local/Cellar/sbt/0.13.15/bin/sbt
```
