### ISSUE TITLE
Performance regression in 0.3.0

### ISSUE THREAD

**Issue by scf37** [scala-native/scala-native#870]
Below code snippet shows 2.5 times performance regression on 0.3.0 in comparison with 0.2.0.

By the way, scala-native is 3-10 times slower than Java8. Is that intended?

build.sbt:
    enablePlugins(ScalaNativePlugin)
    scalaVersion := "2.11.11"
    nativeMode := "release"

Code:

    object Main {
      def main(args: Array[String]): Unit = {
        println("Hello, world!")
        println(Seq(1, 2, 3))
        var t = System.nanoTime
        var n = 0
        var k = 0
        while (true) {
          val seq = Seq(1, 2, 3)
          seq.foreach(k += _)
          n += 1
          if (System.nanoTime - t > 1000 * 1e6) {
            println(n)
            n = 0
            t = System.nanoTime
          }
        }
      }
    }

**Comment by matil019** [comment]
Bisecting revealed that the regression is introduced at `d1255a5`, but it only touches `sbt-scala-native` and `scripted-tests`. Can anyone confirm this?

**Comment by matil019** [comment]
I'm not sure which phase it is, but one of the phases should pass `-O2` to `clang++` but it doesn't.

sbt output:

```
> ; debug; sandbox/nativeLink
...
[info] Optimizing (945 ms)
[info] Generating intermediate code (228 ms)
[info] Produced 1 files
[debug] running
[debug] /usr/bin/clang++
[debug]         -c
[debug]         /home/.../src/scala-native/scala-native/sandbox/target/scala-2.11/native/out.ll
[debug]         -o
[debug]         /home/.../src/scala-native/scala-native/sandbox/target/scala-2.11/native/out.ll.o
[debug]         -I/usr/local/include
[debug]         -Qunused-arguments
[debug]         -O0
[info] Compiling to native code (882 ms)
...
```

**Comment by densh** [comment]
> Below code snippet shows 2.5 times performance regression on 0.3.0 in comparison with 0.2.0.

That's a performance regression, thanks for the report! 👍 

> By the way, scala-native is 3-10 times slower than Java8. Is that intended?

At the moment can be much slower on code that heavily uses virtual dispatch because we miss optimizations. This includes some idiomatic uses of Scala collections. Follow #745 to get progress updates on this front. 

Generally anything more than 2x slower with Immix GC is a performance bug on our side. With Boehm GC it can easily get slower than that on code that allocates a lot.
