### ISSUE TITLE
tests/test doesn't work sometimes

### ISSUE THREAD

**Issue by muxanick** [scala-native/scala-native#890]
```
[info] Starting process '/home/mike/scala/scala-native/unit-tests/target/scala-2.11/tests-out' on port '38573'.
[error] bind: Address already in use
[error] The test program never connected to sbt.
[error] (tests/nativetest:executeTests) The test program never connected to sbt.
[error] Total time: 84 s, completed Jul 1, 2017 1:48:39 PM
```
On Ubuntu 14.04.5

**Comment by asoltysik** [comment]
@Duhemm My initial guess would be that when the test runner fails unexpectedly it doesn't close the file descriptor.

**Comment by densh** [comment]
@muxanick Can you provide any more information to reproduce this issue?

**Comment by ekrich** [comment]
@muxanick Are you still having this issue and was this prior to the new test fixture? It may have been fixed via https://github.com/scala-native/scala-native/pull/874 which refers to this issue: https://github.com/scala-native/scala-native/issues/863

**Comment by muxanick** [comment]
I just tested this on latest code, doesn't repro.
I'm closing this issue
