### ISSUE TITLE
Stack, structures, external objects, etc. need representation in type system through trait tagging and in the future as effects

### ISSUE THREAD

**Issue by sirinath** [scala-native/scala-native#90]
Perhaps you can have trait tagging some of these constructs so they are represented in the type system also. In the future when Dotty gets effects you these can be also represented and affects.

E.g. Stack variable perhaps can extend `Stack[Obj]`, similarly for structs `Struct[Obj]`, etc.

Perhaps this can be extended to Scala Off Heap.

**Comment by densh** [comment]
This change is out of scope. We don't aim at complicating Scala type system any further.

**Comment by sirinath** [comment]
This does not affect Scala side of thing. This is using the Scala type system for additional protection in SN fro the new concepts introduced in SN like e.g. on the stack variable or structure, which are not found in mainline Scala. You need some way to distinguish between if what you are dealing with or some function is specific to what has been introduced in SN. Say I want to define a generic function which can operate only on a stack variable or structure or any other SN specific data type or format then there should be a way to specify or restrict that a function operates only in these types and you cannot pass just any other type. So IMO any type which is not a main Scala type should have a way to distinguish from main scala types to build safer APIs so you do not invariantly pass around data to which the receiving API is not designed to handle.
