### ISSUE TITLE
where comes the hello-native in README.md

### ISSUE THREAD

**Issue by rustup** [scala-native/scala-native#91]
hi 
I have two questions.

1> Where comes the hello-native in README.md

2> The BOEHM in develop.md does what for scala-native?  Why should this be installed?

**Comment by densh** [comment]
1. It's not in the repo atm, you can replicate it by having following code in sandbox:

```scala
import scalanative.native._
import scalanative.libc.stdlib._

object Test {
  def main(args: Array[String]): Unit =
    fprintf(__stdoutp, c"hello, world")
}
```

2. We use Boehm GC as our garbage collector at the moment.

Please use gitter or stackoverflow for this kind of questions in the future.

**Comment by frgomes** [comment]
Have a look at http://github.com/scala-native/scala-native-example
