### ISSUE TITLE
Upgrade plugins to support sbt 1.0.0

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#915]
Sbt has added support in 0.13.16 to allow compiling plugins for sbt 1.0.0 to allow easier migration. Getting the plugins ready could smooth the transition to sbt 1.0 and Scala 2.12 usage in plugins.

Release notes:
https://github.com/sbt/sbt/releases/tag/v0.13.16-RC1

Some APIs used in plugins may be private in sbt 1.0. Here is one such solution recommended by the sbt maintainers.
https://github.com/sbt/sbt-release/pull/207/commits/314a2b6bdf9993e65d93424f4ccb444cf13b9638

**Comment by sjrd** [comment]
For reference, the PR in Scala.js: https://github.com/scala-js/scala-js/pull/3075

**Comment by densh** [comment]
This one fits nicely with 2.12 support being one of the key issues for 0.4.

**Comment by densh** [comment]
Bumped to 0.3.4 due to requests.

**Comment by MasseGuillaume** [comment]
I'm on this.
