### ISSUE TITLE
Difference in regex behaviour compared to JVM

### ISSUE THREAD

**Issue by mb720** [scala-native/scala-native#921]
Hi and thanks for your amazing work!

Consider the following program:

    object Main {
      def main(args: Array[String]): Unit = {
        val greetings = "Gruesze"
        
        val greetingsWithUmlaut = greetings.replaceAll("ue", "ü")
        println(s"Greetings with umlaut: $greetingsWithUmlaut")

        val greetingsWithUmlautAndSharpS = greetingsWithUmlaut.replaceAll("sz", "ß")
        println(s"Greetings with sharp s: $greetingsWithUmlautAndSharpS")
      }
    }

When executing this on the JVM, the output is how I expect it to be:

> Greetings with umlaut: Grüsze
> Greetings with sharp s: Grüße

Yet when I compile it using Scala Native, this is what I get:

> Greetings with umlaut: Gr�sze
> Greetings with sharp s: Gr�s

I don't know whether this is an issue with Scala Native or RE2.

This issue might be related to [this one](https://github.com/scala-native/scala-native/issues/700).

---
My system: 

`uname -a`:
> Linux marathon 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux

`clang --version`:
> clang version 4.0.1 (tags/RELEASE_401/final)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin

`scalaVersion := "2.11.11"`

`addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.1")`

**Comment by densh** [comment]
Thanks for the bug report!
