### ISSUE TITLE
java.nio.HeapByteBuffer NotImplementedError

### ISSUE THREAD

**Issue by olafurpg** [scala-native/scala-native#925]
While porting fastparse to native using 0.3.2 I hit on ??? errors in HeapByteBuffer
https://github.com/scala-native/scala-native/blob/9a22d3069e388f8b96a68ddb797b1e27779606ed/javalib/src/main/scala/java/nio/HeapByteBuffer.scala#L65-L94 in the fastparseByte module

```
[info]     endianness		Success
[info]         short		Failure('scala.NotImplementedError: an implementation is missing')
[info]         int		Failure('scala.NotImplementedError: an implementation is missing')
[info]         long		Failure('scala.NotImplementedError: an implementation is missing')
[info]         float		Failure('scala.NotImplementedError: an implementation is missing')
[info]         double		Failure('scala.NotImplementedError: an implementation is missing')
```

To reproduce https://github.com/lihaoyi/fastparse/pull/160 at https://github.com/lihaoyi/fastparse/commit/72fd55275aecb7af4a4d1e3a2140b7e6c955fce1

**Comment by densh** [comment]
Thanks for the bug report, this looks like a porting oversight!

**Comment by asoltysik** [comment]
I have a ported (rather copy-pasted) it from Scala.js, I just need to port the tests and I will submit a PR with this.

**Comment by 2m** [comment]
This is required for full functionalty of https://github.com/scodec/scodec-bits on scala-native (https://github.com/scodec/scodec-bits/blob/3a56b960c517d640501b4b60268b8bf94843e37b/core/shared/src/main/scala/scodec/bits/BitVector.scala#L1389)

**Comment by 2m** [comment]
Has there been a discussion on cross-compiling javalib project from scala.js to scala native?

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/1080 by @asoltysik

**Comment by olafurpg** [comment]
🎉
