### ISSUE TITLE
Blocking sockets support

### ISSUE THREAD

**Issue by asoltysik** [scala-native/scala-native#967]
- [ ] Implement `java.net.DatagramSocket`
- [x] Implement `java.net.Socket` #914 
    - [ ] Support deprecated nonstreaming mode (delegate work to DatagramSocket)
    - [ ] Support out of band data
    - [ ] Support sockets through `java.net.Proxy` and SOCKS
- [x] Implement `java.net.ServerSocket` #917

**Comment by LeeTibbert** [comment]
@RustedBones @WojciechMazur 

A bit of housekeeping:

If you both concur, I believe this Issue can be closed.  

* DatagramSocket has been implemented.

* spending limited devo time to implemented a feature (non-streaming TCP) which was
   nonsensical to begin with and which has been deprecated for probably a decade or more
   makes should not happen. Now, Lee, tell me how you really feel about it.

* somebody must still be using "java.net.Proxy and SOCKS" but it probably does not
   have as large a user base as competing work, such as network channels.

* there may be a reason to implement out-of-band data but it has an exceedingly
   small, probably single digit, user base.

Thoughts?

**Comment by LeeTibbert** [comment]
@asoltysik  In closing this, I do not mean to disregard the work you did in 2017.  It has served its
purpose.
