### ISSUE TITLE
Consider adding support for java.net.URL

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#970]

**Comment by sjrd** [comment]
`java.net.URL` is a nightmare. Its `equals(Any)` method is specified to do a blocking network request to resolve hostnames. If at all possible, don't support `java.net.URL`.

**Comment by densh** [comment]
> Its equals(Any) method is specified to do a blocking network request to resolve hostnames.

:scream:

**Comment by ekrich** [comment]
We have a special `javalib-ext-dummies` to test for example `uri.toURL` and the `URL` constructors are also deprecated in Java 20 recommending using `URI` for parsing.

See https://github.com/scala-native/scala-native/pull/2788
