### ISSUE TITLE
Don't link stubs by default

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#971]
Add a special annotation `@stub` that would be used for planned but not yet implemented parts of JDK APIs. Those methods would not link by default, but only under a flag that allows stubs.

**Comment by matil019** [comment]
How about an extra option that allows auto-generation of `???` for non-existent methods (even without `@stub`)? Such a permissive feature would be helpful for development/experimental projects.

**Comment by densh** [comment]
@matil019 It would be _really_ cool if we could automatically generate stubs, but unfortunately we don't have enough information at link-time for this to happen at the moment. Adding more information to the NIR so that we can generate those automatically might be another solution for this.

**Comment by matil019** [comment]
@densh All right, it is just a nice-to-have idea. `@stub` itself will be really helpful already, I'm looking forward to it!
