### ISSUE TITLE
Cannot build if a parent directory is called `gc`

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#977]
Scala Native will fail to link all `.o` files if sbt is run from a directory that is named `gc` or has a directory named `gc` as parent.

In `nativeCompileLib`, we select what are the `.c` and `.cpp` files that need to be compiled using `def include(path: Path): Boolean`:
https://github.com/scala-native/scala-native/blob/7ac1b4afab79a6e01f95d1c94d9ab457a6f44fa8/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala#L235-L249

The issue is that we'll exclude sources that do not belong to the implementation of the gc (because the  ALL the paths contain `sep + gc + sep`. Therefore, we'll exclude almost everything from the nativelib, and we'll fail during linking.

Potential solution:
 - Set `val prefix = crossTarget.value + sep + "native" + sep + "lib"`
 - Check if the path starts with `prefix + "gc"`.
 - Do the same for the other comparisons in that function

@densh Any better idea?

**Comment by densh** [comment]
That's indeed a bug, good find!
