### ISSUE TITLE
Test `java.lang.StackTraceElementSuite.getMethodName` fails on MacOS

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#979]
We didn't catch it until now because the CI is disabled for MacOS.

This is the failing assertion:
https://github.com/scala-native/scala-native/blob/dd9aa215368338e76e099bb24599a061f56c120a/unit-tests/src/test/scala/java/lang/StackTraceElementSuite.scala#L29

We have `dummy2.getMethodName == "dummy1"`.

This was certainly caused by #963.

**Comment by densh** [comment]
This is a regression that blocks 0.3.3
