### ISSUE TITLE
`java.util.regex.Matcher.region` is missing

### ISSUE THREAD

**Issue by Duhemm** [scala-native/scala-native#986]
The method is not implemented. Once we support it, the corresponding test in `MatcherSuite` should be uncommented:
https://github.com/scala-native/scala-native/pull/972/files#diff-d85024596ae129a0cf5ccad03239b0fdR241

**Comment by LeeTibbert** [comment]
From current `j.u.r.Matcher` code.
```
 def region(start: Int, end: Int): Matcher = {
    underlying.region(start, end)
    this
  }
```

I believe I fixed this at some point in time, perhaps Summer 2022, and this Issue never
got closed.
