### ISSUE TITLE
Support for scala.util.Properties

### ISSUE THREAD

**Issue by mb720** [scala-native/scala-native#998]
Hi!

This works when executed on the JVM:

    object Main {
      def main(args: Array[String]): Unit = {
        scala.util.Properties.envOrNone("HOME")
          .foreach(homeDir => println(s"Home is: $homeDir"))
      }
    }

But when run via Scala Native I get

>[error] cannot link: @java.lang.Class::getResourceAsStream_java.lang.String_java.io.InputStream
>[error] cannot link: @java.util.jar.Attributes$Name
>[error] cannot link: @java.util.jar.Attributes$Name::init_java.lang.String
>[error] unable to link
>[error] (compile:nativeLinkNIR) unable to link

To get around this issue, I use `System.getenv("HOME")` instead, which works just fine.

---

    addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.2")

    scalaVersion := "2.11.11"

    sbt.version = 0.13.16

**Comment by densh** [comment]
Hi @mb720, this is a duplicate #867 and the fix is going to ship as part of 0.3.4.

**Comment by Duhemm** [comment]
@mb720 I think @densh meant 0.3.3 (the next release)

**Comment by densh** [comment]
@Duhemm You're right, it's 0.3.3, not 0.3.4.

**Comment by mb720** [comment]
Thanks for the heads up and sorry for having overlooked #867.
