### ISSUE TITLE
Support for java.time

### ISSUE THREAD

**Issue by mb720** [scala-native/scala-native#999]
Hi!

I'm curious on whether there are plans to support `java.time`.

This runs on the JVM but yields a linker error with Scala Native:

    def main(args: Array[String]): Unit = {

      import java.time.ZonedDateTime
      import java.time.format.DateTimeFormatter

      val currentDateAndTimeFormatted = ZonedDateTime.now().format(DateTimeFormatter.ISO_OFFSET_DATE_TIME)

      println(s"Current date and time: $currentDateAndTimeFormatted")
    }

>[error] cannot link: @java.time.ZonedDateTime
>[error] cannot link: @java.time.ZonedDateTime$
>[error] cannot link: @java.time.ZonedDateTime$::now_java.time.ZonedDateTime
>[error] cannot link: @java.time.ZonedDateTime::format_java.time.format.DateTimeFormatter_java.lang.String
>[error] cannot link: @java.time.format.DateTimeFormatter
>[error] cannot link: @java.time.format.DateTimeFormatter$
>[error] cannot link: @java.time.format.DateTimeFormatter$::ISO$underscore$OFFSET$underscore$DATE$underscore$TIME_java.time.format.DateTimeFormatter
>[error] unable to link
>[error] (compile:nativeLinkNIR) unable to link

---

    addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.2")

    scalaVersion := "2.11.11"

    sbt.version = 0.13.16

**Comment by daniil-timofeev** [comment]
There are scala implementation of `java.time` at https://github.com/cquiroz/scala-java-time 
Maybe it can be useful for this issue.

**Comment by asoltysik** [comment]
Calling @cquiroz

**Comment by cquiroz** [comment]
it would be very natural to use `scala-java-time` with scala-native. I was planning to work on that and other related issues in the next 2 weeks. I need to first make `scala-java-locales` work on scala-native

**Comment by asoltysik** [comment]
Is it possible to have this inside Scala Native library as 'java.time' or
only as an external library? I am not too familiar with license issues.

13.09.2017 2:16 PM "Carlos Quiroz" <notifications@github.com> napisał(a):

**Comment by mkotsbak** [comment]
See https://github.com/cquiroz/scala-java-time/issues/45

**Comment by WojciechMazur** [comment]
java.time package was removed in #2087. It's recommened to use third-party implementation instead
